### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by curious1me** [miguelgrinberg/Flask-SocketIO#1022]
System Details:
Ubuntu 16.06
Python 3.5
flask_socketio Version: 4.1.0
```
from flask import Flask, render_template
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@app.route('/')
def index():
    return render_template('index.html')

@socketio.on('my event')
def test_message(message):
    emit('my response', {'data': 'got it!'})

if __name__ == '__main__':
    PORT = 4000
    print('server starting at port : ',PORT)
    socketio.run(app,host="0.0.0.0",port=PORT)
```
The above program is throwing the following exception:
```
Traceback (most recent call last):
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/engineio/server.py", line 520, in _trigger_event
    return self.handlers[event](*args)
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/socketio/server.py", line 691, in _handle_eio_message
    pkt = packet.Packet(encoded_packet=data)
  File "/home/virtualenvs/basic/lib/python3.5/site-packages/socketio/packet.py", line 43, in __init__
    self.attachment_count = self.decode(encoded_packet)
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/socketio/packet.py", line 113, in decode
    self.data = self.json.loads(ep)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Please help to find the root cause of the issue.

**Comment by miguelgrinberg** [comment]
Can you show me the client as well? This is caused by something the client is sending to the server.

**Comment by curious1me** [comment]
Sorry for the late response.Yes it actually was due to an error in the client side code.
