### ISSUE TITLE
It works well, but it can't broadcast, after a period of time.

### ISSUE THREAD

**Issue by 903165495** [miguelgrinberg/Flask-SocketIO#1027]
The program has just run and is working properly.After a period of time, the message can be received, but the message can not be broadcast.
![image](https://user-images.githubusercontent.com/30617738/61989320-15c39900-b060-11e9-88fc-b35be7559f8f.png)

**Comment by 903165495** [comment]
[log.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/3437821/log.txt)
This is the log file. Stop broadcasting at the last minute.

**Comment by 903165495** [comment]
82ab51b5a1e642819355f90761b4996c: Received packet MESSAGE data 2/danmu,["controlsend",{"token":"eyJjb3Vyc2VfaWQiOjI1OSwic3ViamVjdF9pZCI6NjksInVpZCI6NDl9.UxBtOz8Km5c61ARXgkZKo_W0mOY","msg":"1","page":2}]
received event "controlsend" from 82ab51b5a1e642819355f90761b4996c [/danmu]
Traceback (most recent call last):
  File "F:\venv\gevent_socketio\lib\site-packages\redis\connection.py", line 182, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "F:\venv\gevent_socketio\lib\site-packages\redis\_compat.py", line 58, in recv
    return sock.recv(*args, **kwargs)
  File "F:\venv\gevent_socketio\lib\site-packages\gevent\_socket3.py", line 378, in recv
    return _socket.socket.recv(self._sock, *args)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "F:\venv\gevent_socketio\lib\site-packages\socketio\server.py", line 640, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "F:\venv\gevent_socketio\lib\site-packages\socketio\server.py", line 669, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "F:\venv\gevent_socketio\lib\site-packages\flask_socketio\__init__.py", line 280, in _handler
    *args)
  File "F:\venv\gevent_socketio\lib\site-packages\flask_socketio\__init__.py", line 694, in _handle_event
    ret = handler(*args)
  File "E:\a开学\untitled\app\main\control.py", line 32, in controlsend
    if (control(data["subject_id"], data["uid"]) == 'True'):
  File "E:\a开学\untitled\app\libs\redisclass.py", line 21, in control
    return rc.hget(name=name, key='is_open')
  File "F:\venv\gevent_socketio\lib\site-packages\redis\client.py", line 2645, in hget
    return self.execute_command('HGET', name, key)
  File "F:\venv\gevent_socketio\lib\site-packages\redis\client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "F:\venv\gevent_socketio\lib\site-packages\redis\client.py", line 789, in parse_response
    response = connection.read_response()
  File "F:\venv\gevent_socketio\lib\site-packages\redis\connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "F:\venv\gevent_socketio\lib\site-packages\redis\connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "F:\venv\gevent_socketio\lib\site-packages\redis\connection.py", line 224, in readline
    self._read_from_socket()
  File "F:\venv\gevent_socketio\lib\site-packages\redis\connection.py", line 199, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)
2019-07-27T05:33:10Z <Thread at 0x28f67c7b748: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x0000028F67BE7748>>(<socketio.server.Server object at 0x0000028F67BE77, '82ab51b5a1e642819355f90761b4996c', ['controlsend', {'token': 'eyJjb3Vyc2VfaWQiOjI1OSw, '/danmu', None)> failed with ConnectionError

**Comment by miguelgrinberg** [comment]
The Windows error indicates that the other side (the client) has closed the connection unexpectedly. Based on experience, when using gevent or eventlet on the Windows platform sometimes these errors really point to problems in these frameworks, which are not as thoroughly tested on Windows as they are on Posix platforms.

**Comment by 903165495** [comment]
Yes, I've deployed it to the Linux system and it's working properly.
