### ISSUE TITLE
"QueuePool limit of size 10 overflow 10 reached" when using eventlet-based dev server.

### ISSUE THREAD

**Issue by lanmaster53** [miguelgrinberg/Flask-SocketIO#1040]
I've got an app that uses the eventlet-based dev server with socketio for dev/testing. I then deploy the app using gunicorn in the production environment. When using the dev server, I encounter this error when doing some lite automation against the application with a single threaded DAST. In the production environment, i encounter no such issue. The full traceback is below.

```
Traceback (most recent call last):
  File "<omitted>/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "<omitted>/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "<omitted>/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<omitted>/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "<omitted>/lib/python3.6/site-packages/flask/app.py", line 2445, in wsgi_app
    ctx.push()
  File "<omitted>/lib/python3.6/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/Users/lanmaster/Development/Repositories/pwnedhub/flask_session.py", line 109, in open_session
    saved_session = self.sql_session_model.query.filter_by(session_id=store_id).first()
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3222, in first
    ret = list(self[0:1])
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3012, in __getitem__
    return list(res)
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3324, in __iter__
    return self._execute_and_instances(context)
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3346, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3361, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3339, in _connection_from_session
    conn = self.session.connection(**kw)
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
    execution_options=execution_options,
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
    engine, execution_options
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
    conn = bind._contextual_connect()
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2226, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "<omitted>/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 131, in _do_get
    code="3o7r",
sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
```

The read of the database to retrieve the session is causing the issue, but I don't understand why it would be an issue for the dev server and not the gunicorn server. The database is configured the exact same way in both environments, so that shouldn't be the issue. Any ideas?

**Comment by miguelgrinberg** [comment]
Your SQLAlchemy is configured with a maximum of 10 active database connections, and you seem to have maxed out after 20 active connections, I assume because you are sending several concurrent requests (i.e. 20 or more).

How are you running under gunicorn? If you are also sending the same amount of traffic to the gunicorn server but that does not fail in the same way, then it is possible that your gunicorn server settings are different than your development server settings.

**Comment by lanmaster53** [comment]
That's just the thing. I am running the DAST in a single thread, so there shouldn't be any more than one database connection at a time, unless the application is creating a new connection for every request and not closing the previous connections. What could cause that for one server and not the other? I was thinking that perhaps the gunicorn server was triggering the application to close out database connections after properly closing out connections with client, while the dev server was not. I don't know enough about the underlying system to know if this even makes sense. Thoughts?

**Comment by lanmaster53** [comment]
I fixed it. It ended up being a strange bug where a 400 response raised an exception in a custom error handler by returning a None response, which resulted in a 500 response. Somewhere in that mess Flask was not given the opportunity to clean up after itself and the database connections used for that request hung. After 10 requests to the same resource, I got the QueuePool error above. Anyway. All good now. Thanks for listening! :-D

**Comment by lanmaster53** [comment]
Well, I thought I fixed it, then further testing showed that was just one source of 500 error. DASTs cause a LOT of 500 errors and it wasn't long before I got the error again. Then I found this: https://github.com/pallets/flask-sqlalchemy/issues/339. Makes complete sense! I tested the recommended solution and it indeed works. That's a serious gotcha worth noting. Thanks again for listening!
