### ISSUE TITLE
can reproduce，place help!!!

### ISSUE THREAD

**Issue by fushenghua** [miguelgrinberg/Flask-SocketIO#1069]
[2019-09-26 11:50:44 +0000] [2774] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base_async.py", line 115, in handle_request
    resp.write(item)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 333, in write
    self.send_headers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 325, in send_headers
    tosend = self.default_headers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 306, in default_headers
    elif self.should_close():
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 229, in should_close
    if self.status_code < 200 or self.status_code in (204, 304):
AttributeError: 'Response' object has no attribute 'status_code'
^C[2019-09-26 11:50:44 +0000] [2768] [INFO] Handling signal: int

**Comment by miguelgrinberg** [comment]
Are you using an old version of gunicorn by any chance? Try upgrading it.
