### ISSUE TITLE
Emit on database update

### ISSUE THREAD

**Issue by amosbastian** [miguelgrinberg/Flask-SocketIO#1074]
I am using `flask-apscheduler` to update my PostgreSQL database every X seconds. If there are any changes I want to emit the new objects to my React client. I've never used SocketIO before, so bear with me, but here is an example of my application's folder structure:

```
.
├── run.py
└── myapp
     ├── api.py
     ├── config.py
     ├── __init__.py
     ├── models.py
     ├── cars
     │   ├── __init__.py
     │   └── cars.py
     └── utilities.py
```

In `myapp/__init__.py` I have the following

```python
import os

from flask import Flask
from flask_apscheduler import APScheduler
from flask_cors import CORS
from flask_migrate import Migrate
from flask_socketio import SocketIO
from myapp.config import DevelopmentConfig, ProductionConfig
from myapp.models import db
from myapp.utilities import update_cars

migrate = Migrate()
socketio = SocketIO()


def create_app(development=True):
    app = Flask(__name__, instance_relative_config=True)
    CORS(app)
    app.config.from_object(ProductionConfig())

    # Non-relevant code omitted

    scheduler = APScheduler()
    scheduler.init_app(app)
    scheduler.start()

    socketio.init_app(app, cors_allowed_origins="*")
    return app
```

which I run with the command `python run.py`, where `run.py` just contains:

```python
from myapp import create_app, socketio

app = create_app()

if __name__ == "__main__":
    socketio.run(app)
```

Every 10 seconds the scheduler checks which cars in the database have a certain status, and reaches out to an external API to update them if needed. I want to emit the updated car to my React application and show the status updates in real-time, and found out this is possible using SocketIO. Since I already had the scheduler working (just had to refresh to see the status update) I thought I could just add an emit to it, like so:

```python
from flask_socketio import emit
from myapp.api import MyApi
from myapp.models import Car, db

myapp = MyApi()


def update_cars():
    app = db.get_app()

    # Need to use the app's context to access the cars
    with app.app_context():
        incomplete_cars = db.session.query(Car).filter(
            car.status != "completed",
            car.status != "failed").all()

    for car in incomplete_cars:
        updated_car = myapp.get_car(car.uid)
        if updated_car.get("status") != car.status:
            car.status = updated_car.get("status")
            car.description = updated_car.get(
                "description")

            db.session.add(car)
            print(updated_car)
        emit("updateCar", updated_car, broadcast=True)

    db.session.commit()
```
However, I get the following error when running it:

```
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 212-007-978
(19480) wsgi starting up on http://127.0.0.1:5000
(19480) accepted ('127.0.0.1', 42190)
127.0.0.1 - - [02/Oct/2019 18:05:20] "GET /socket.io/?EIO=3&transport=polling&t=MsDRksC HTTP/1.1" 200 401 0.002760
(19480) accepted ('127.0.0.1', 42194)
127.0.0.1 - - [02/Oct/2019 18:05:20] "GET /socket.io/?EIO=3&transport=polling&t=MsDRksz&sid=312632fb3b2441aabc67fbf9ec593a55 HTTP/1.1" 200 235 0.004945
{'order_number': 42643, 'price': 900.0, 'description': 'A sample description', 'status': 'sold', 'uid': 'c640cc54b7'}
Job "update_cars (trigger: interval[0:00:10], next run at: 2019-10-02 18:05:35 WEST)" raised an exception
Traceback (most recent call last):
  File "/home/amos/anaconda3/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/amos/Documents/test_project/backend/myapp/utilities.py", line 26, in update_cars
    emit("updateCar", updated_car, broadcast=True)
  File "/home/amos/anaconda3/lib/python3.7/site-packages/flask_socketio/__init__.py", line 752, in emit
    namespace = flask.request.namespace
  File "/home/amos/anaconda3/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/amos/anaconda3/lib/python3.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/amos/anaconda3/lib/python3.7/site-packages/flask/globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```
I had similar errors with the database context earlier, and some other stuff with setting up `flask_socketio` in the first place, but managed to find solutions to this. Unfortunately I've been stuck on this a while... I have an idea on how this *would* be fixed, but don't know how to do it. Any help is definitely appreciated!

P.S. I have tested the connection by changing `events.py` to 

```python
from flask_socketio import emit

from .. import socketio


@socketio.on('connect')
def update_car():
    print("CONNECTED!!!")
```

and emitting from my React application, and this works fine. I have tried adding `from . import socketio` to `utilities.py`, but this results in an `ImportError`.

**Comment by miguelgrinberg** [comment]
Try:

    emit("updateCar", updated_car, broadcast=True, namespace='/')

Any of the optional arguments that you omit will be obtained from the request context. Since in your case there is no request context, you have to provide all the arguments in the emit call.

**Comment by amosbastian** [comment]
I ended up using server-sent events in place of it (since I only need to send from the server to the client anyway), which seems to work fine. Sorry for the inconvenience!
