### ISSUE TITLE
Problem using SocketIOTestClient with Flask-Testing

### ISSUE THREAD

**Issue by m-flak** [miguelgrinberg/Flask-SocketIO#1075]
I am having problems setting the flask_test_client for the SocketIOTestClient class. I am passing a proper test client, for Flask-Testing comes equipped with one:
```
self.client = self.app.test_client()
```

If I attempt to pass ```self.client``` from a Flask-Testing TestCase instance to the SocketIOTestClient's ```flask_test_client``` parameter, I get the following error:

```
======================================================================
ERROR: test_sockets_working (flfm.tests.test_sockets.SocketsWorkingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Matthew\flfm\flfm\tests\test_sockets.py", line 39, in test_sockets_working
    None, self.client) as sockclient:
  File "C:\Users\Matthew\flfm\flfm\tests\test_sockets.py", line 11, in __init__
    flask_test_client)
  File "C:\Users\Matthew\Envs\flfm\lib\site-packages\flask_socketio\test_client.py", line 69, in __init__
    headers=headers)
  File "C:\Users\Matthew\Envs\flfm\lib\site-packages\flask_socketio\test_client.py", line 98, in connect
    environ = EnvironBuilder(url, headers=headers).get_environ()
  File "C:\Users\Matthew\Envs\flfm\lib\site-packages\werkzeug\test.py", line 383, in __init__
    headers = Headers(headers)
  File "C:\Users\Matthew\Envs\flfm\lib\site-packages\werkzeug\datastructures.py", line 958, in __init__
    self.extend(defaults)
  File "C:\Users\Matthew\Envs\flfm\lib\site-packages\werkzeug\datastructures.py", line 1090, in extend
    for key, value in iterable:
TypeError: 'FlaskClient' object is not iterable
```

**I'd rather not be forced to pass _None_ to the _flask\_test\_client_ parameter. Is this a bug or something I'm doing wrong?**

**Comment by miguelgrinberg** [comment]
I suggest you pass the argument as a keyword argument just in case (i.e. `flask_test_client=self.client`). I think the test client is incorrectly being mapped to the headers argument.

**Comment by m-flak** [comment]
Okay.

 I will give that a try and let you know if that works.

**Comment by m-flak** [comment]
**It appears _it was_ an error on my part.**

I accidently passed ```self.client``` to the headers parameter.

Miscounted all those parameters. Oops. 🤦‍♂️
