### ISSUE TITLE
Running dev server wit Rabbit (remote)

### ISSUE THREAD

**Issue by NotSoShaby** [miguelgrinberg/Flask-SocketIO#1090]
**Your question**
We are currently moving from Redis to RabbitMQ as a broker and want to use it for websockets cache as well. I managed to make this work on the server but not locally. 

When we defined Redis it worked on both.

I realised this has to do with the gunicorn run in prod VS the socketio\Flask run when i run in dev mode. 
I proved that by running the production command locally and have it work with a remote rabbit, I then ran the same command with the dev environment (still with remote Rabbit) which made the websockets break.

How do I make sure that the dev server works as it works in remote environment?

initializing socketio:

`SocketIO(app, message_queue='<connection string to remote vhost>')`

running dev command (not working):

`socketio.run(app, host="0.0.0.0", port=1337, debug=True)`
also tried: 
`app.run(host="0.0.0.0", port=1337, debug=True)`

running on remote (works as expected):

`gunicorn --bind 0.0.0.0:1337 --worker-class eventlet --no-sendfile --timeout 300 -w 4 server:app --config gunicorn_conf.py`

*note: no logs as it simply fails to connect.

**Comment by NotSoShaby** [comment]
yes

**Comment by miguelgrinberg** [comment]
Monkey patching should be done always, it's not a production setting only. Any time you use eventlet or gevent and your application or any dependencies make blocking calls you need the monkey patching to be done.

**Comment by NotSoShaby** [comment]
I see. Thanks so much for the quick response. 
I now tried to run the same way in prod and in dev by enabbling gevents on pycharm and trying to debug and faced this issue:

```
[2019-10-31 12:42:12 +0200] [13053] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/refael/.local/share/virtualenvs/romee-dkO78zKu/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/refael/.local/share/virtualenvs/romee-dkO78zKu/lib/python3.6/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
    super(EventletWorker, self).init_process()
  File "/Users/refael/.local/share/virtualenvs/romee-dkO78zKu/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/Users/refael/.local/share/virtualenvs/romee-dkO78zKu/lib/python3.6/site-packages/gunicorn/workers/geventlet.py", line 135, in run
    eventlet.sleep(1.0)
  File "/Users/refael/.local/share/virtualenvs/romee-dkO78zKu/lib/python3.6/site-packages/eventlet/greenthread.py", line 35, in sleep
    hub.switch()
  File "/Users/refael/.local/share/virtualenvs/romee-dkO78zKu/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 295, in switch
    return self.greenlet.switch()
  File "/Users/refael/.local/share/virtualenvs/romee-dkO78zKu/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 347, in run
    self.wait(sleep_time)
  File "/Users/refael/.local/share/virtualenvs/romee-dkO78zKu/lib/python3.6/site-packages/eventlet/hubs/kqueue.py", line 100, in wait
    result = self._control([], self.MAX_EVENTS, seconds)
  File "/Users/refael/.local/share/virtualenvs/romee-dkO78zKu/lib/python3.6/site-packages/eventlet/hubs/kqueue.py", line 41, in _control
    return self.kqueue.control(events, max_events, timeout)
OSError: [Errno 9] Bad file descriptor
```

Im not sure if this is related to socketio. but cant find many similar issues online.

**Comment by miguelgrinberg** [comment]
Can you try this outside of PyCharm?

**Comment by NotSoShaby** [comment]
might be a stupid question, but how can i reproduce debug mode out of pycharm\any IDE

**Comment by miguelgrinberg** [comment]
I don't understand the question. You must have configured PyCharm to run a command that starts the server, correct? You can type that same command in a console.
