### ISSUE TITLE
Heroku external Redis as message queue

### ISSUE THREAD

**Issue by MariusVB** [miguelgrinberg/Flask-SocketIO#1093]
**Describe the bug**
I'm trying to deploy my flask app with Heroku where I'm using an external redis-server, found in my environment as "redis_url". However, when I pass this address in to the "message_queue" argument of socketio, my app doesn't seem to work. How do I make it work with an external redis-server?

**To Reproduce**
Create a flask app and a socketio instance with an external redis message queue.
My message queue looks like this: "redis://localhost:6379" or "redis://some_aws_server"
Seems like Flask-SocketIO, defaults to a Kombu backend, because it doesn't understand the Redis_url I'm passing to it.

**Expected behavior**
The message queue should work as expected with any redis url.

**Logs**
ad8abe7915a740ababc3c4769e07f1fb: Sending packet OPEN data {'sid': 'ad8abe7915a740ababc3c4769e07f1fb', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
2019-11-06T19:37:56.454439+00:00 app[web.1]: kombu backend initialized.
2019-11-06T19:37:56.454639+00:00 app[web.1]: ad8abe7915a740ababc3c4769e07f1fb: Sending packet MESSAGE data 0
2019-11-06T19:37:56.455167+00:00 app[web.1]: 137.59.253.206,10.11.161.2 - - [06/Nov/2019 19:37:56] "GET /socket.io/?EIO=3&transport=polling&t=Mv2EJR_ HTTP/1.1" 200 344 0.026584
2019-11-06T19:37:56.458785+00:00 app[web.1]: (26) accepted ('10.9.163.168', 23297)
2019-11-06T19:37:56.467393+00:00 app[web.1]: 137.59.253.206,10.9.163.168 - - [06/Nov/2019 19:37:56] "GET /logged_in HTTP/1.1" 200 186 0.007772
2019-11-06T19:37:56.489890+00:00 app[web.1]: Sleeping 2.0s
2019-11-06T19:37:56.489894+00:00 app[web.1]: Traceback (most recent call last):
2019-11-06T19:37:56.489896+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/amqp/transport.py", line 137, in _connect
2019-11-06T19:37:56.489898+00:00 app[web.1]:     host, port, family, socket.SOCK_STREAM, SOL_TCP)
2019-11-06T19:37:56.489899+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/eventlet/support/greendns.py", line 537, in getaddrinfo
2019-11-06T19:37:56.489901+00:00 app[web.1]:     raise socket.gaierror(socket.EAI_NONAME, 'No address found')
2019-11-06T19:37:56.489902+00:00 app[web.1]: socket.gaierror: [Errno -2] No address found
2019-11-06T19:37:56.489903+00:00 app[web.1]: 
2019-11-06T19:37:56.489904+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2019-11-06T19:37:56.489906+00:00 app[web.1]: 
2019-11-06T19:37:56.489907+00:00 app[web.1]: Traceback (most recent call last):
2019-11-06T19:37:56.489909+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/kombu/utils/functional.py", line 343, in retry_over_time
2019-11-06T19:37:56.489910+00:00 app[web.1]:     return fun(*args, **kwargs)
2019-11-06T19:37:56.489911+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/kombu/connection.py", line 283, in connect
2019-11-06T19:37:56.489913+00:00 app[web.1]:     return self.connection
2019-11-06T19:37:56.489914+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/kombu/connection.py", line 837, in connection
2019-11-06T19:37:56.489915+00:00 app[web.1]:     self._connection = self._establish_connection()
2019-11-06T19:37:56.489917+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/kombu/connection.py", line 792, in _establish_connection
2019-11-06T19:37:56.489918+00:00 app[web.1]:     conn = self.transport.establish_connection()
2019-11-06T19:37:56.489919+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
2019-11-06T19:37:56.489920+00:00 app[web.1]:     conn.connect()
2019-11-06T19:37:56.489922+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/amqp/connection.py", line 311, in connect
2019-11-06T19:37:56.489923+00:00 app[web.1]:     self.transport.connect()
2019-11-06T19:37:56.489925+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/amqp/transport.py", line 77, in connect
2019-11-06T19:37:56.489926+00:00 app[web.1]:     self._connect(self.host, self.port, self.connect_timeout)
2019-11-06T19:37:56.489927+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/amqp/transport.py", line 148, in _connect
2019-11-06T19:37:56.489929+00:00 app[web.1]:     "failed to resolve broker hostname"))
2019-11-06T19:37:56.489935+00:00 app[web.1]: OSError: failed to resolve broker hostname

**Comment by miguelgrinberg** [comment]
Can you share the bit of code you use to initialize the `SocketIO` object? As you can see in [this line of code](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L203), URLs that start with `redis://` or `rediss://` are handled by the redis backend. The logs in your case suggest the message queue URL was not recognized, so it was assigned to the default backend which is Kombu.

**Comment by MariusVB** [comment]
Wow - I was using the wrong env variable for the queue... Thank you for the quick reply though.

I got the app deployed and websockets connected, however when using https i get the error: 
"https://my_domain.com" is not an accepted origin.

I'm initializing socketIO like this in both my flask app and my worker process:

        socketio = SocketIO(app, cors_allowed_origins=None, message_queue=environ.get('REDIS_URL'))

**Comment by MariusVB** [comment]
I tried adding flask_cors to my app, but I'm still getting the error.
#722 seems to have the same issue, however I'm only using a single dyno on Heroku and it seems my issue is with SocketIO not accepting the origin.

Looking into which requests get rejected from the browser, it seems like all the ones with url argument "&sid=some_id" gets rejected, both polling and websocket requests. However, the client still receives the emits. 
Any idea how to get socketIO to accept the origin when using https?

**Comment by miguelgrinberg** [comment]
`cors_allowed_origins='*'` allows any clients to connect. it is insecure. You should set it to the domain your client will be connecting from.

**Comment by MariusVB** [comment]
I fixed it by setting the `cors_allowed_origins` equal to my domain, both with and without https.
