### ISSUE TITLE
BadNamespaceError in Windows operating system

### ISSUE THREAD

**Issue by pwr617** [miguelgrinberg/Flask-SocketIO#1118]
Hello, the following code has bad BadNamespaceError  error in Windows system, but it works normally in Ubuntu system. I can't find similar problems. I need your help. Thank you!

server.py
```
# coding:utf-8

import socketio
import uvicorn

sio = socketio.AsyncServer(async_mode='asgi', ping_travler=10, ping_timeout=300)
app = socketio.ASGIApp(sio)

@sio.event
def disconnect(sid):
    print('disconnect:', sid)


@sio.event
def connect(sid, environ):
    print("connect ", sid)


@sio.on('message', namespace='/server_rece')
async def receive_message(sid, data):
    print("get a message")

uvicorn.run(app, host="127.0.0.1", port=5000)
```

client.py
```
#!/usr/bin/env python3
import asyncio
import json
from multiprocessing import Process

from flask_socketio import socketio

sio = socketio.AsyncClient(logger=False, engineio_logger=False)

@sio.event
def connect():
    sio.start_background_task(target=send_message)

@sio.event
def disconnect():
    print('client disconnected')

async def send_message():
    while True:
        await sio.sleep(0.5)
        await sio.send(json.dumps("123"), namespace='/server_rece')
        print("send a message")

async def start_sio_server(ip, port):
    addr = 'http://' + ip + ':' + str(port)
    await sio.connect(addr)


def main(ip, port):
    LOOP = asyncio.get_event_loop()
    LOOP.run_until_complete(start_sio_server(ip, port))
    LOOP.run_forever()


if __name__ == '__main__':
    p1 = Process(target=main, args=("127.0.0.1", 5000))  # 启动客户端进程
    p1.start()

```
```
Task exception was never retrieved
future: <Task finished coro=<send_message() done, defined at G:\未命名文件夹\c.py:18> exception=BadNamespaceError('/server_rece is not a connected namespace.')>
Traceback (most recent call last):
  File "G:\未命名文件夹\c.py", line 21, in send_message
    await sio.send(json.dumps("123"), namespace='/server_rece')
  File "E:\conda\envs\pytorch\lib\site-packages\socketio\asyncio_client.py", line 190, in send
    callback=callback)
  File "E:\conda\envs\pytorch\lib\site-packages\socketio\asyncio_client.py", line 147, in emit
    namespace + ' is not a connected namespace.')
socketio.exceptions.BadNamespaceError: /server_rece is not a connected namespace.
```

**Comment by pwr617** [comment]
I found some differences between the two versions of the socketio/asyncio_client.py

In windows：flask-socketio 4.2.1
```
async def emit(self, event, data=None, namespace=None, callback=None):
...
namespace = namespace or '/'
        if namespace != '/' and namespace not in self.namespaces:
            raise exceptions.BadNamespaceError(
                namespace + ' is not a connected namespace.')
        self.logger.info('Emitting event "%s" [%s]', event, namespace)
...
```
In ubuntu：flask-socketio 4.2.0
```
async def emit(self, event, data=None, namespace=None, callback=None):
...
        namespace = namespace or '/'
        self.logger.info('Emitting event "%s" [%s]', event, namespace)
...
```
After I commented out the if statement in the Windows source code, the program worked fine，Is the if statement redundant here? How do I download the correct source code, or is there any other way to solve my problem。

**Comment by miguelgrinberg** [comment]
You need to specify which namespace(s) you want to connect:

    await sio.connect(addr, namespaces=['/server_rece'])

**Comment by pwr617** [comment]
ok, Thank you
