### ISSUE TITLE
How to handle message from client ?

### ISSUE THREAD

**Issue by Kogam22** [miguelgrinberg/Flask-SocketIO#1121]
**Your question**
I was trying to get flask-socketIO  working by checking if server connected to client and sending a simple message. The python console shows something like `TypeError: handle_message() takes 1 positional argument but 2 were given`. I don't know how to handle this. As we can see, the message is recieved(in logs, not printed from function), but it throws a new error and the continues server to run. Any insights on this ? Thanks.

Client uses HTML + Javascript SocketIO and Server uses Flask-SocketIO,

Workflow:
* Server is running. 
* Client connects to server.
* Server responds to client "Connected to server successfully"
* Client responds to server "Connected to client successfully"
```bash
 * Debugger is active!
 * Debugger PIN: 238-995-173
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

127.0.0.1 - - [10/Dec/2019 15:12:25] "GET / HTTP/1.1" 200 -
f7ebed933faf4a0bb1b38377c9c3262b: Sending packet OPEN data {'sid': 'f7ebed933faf4a0bb1b38377c9c3262b', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
emitting event "message" to f7ebed933faf4a0bb1b38377c9c3262b [/]
f7ebed933faf4a0bb1b38377c9c3262b: Sending packet MESSAGE data 2["message",{"data":"Connected to server successfully"}]
f7ebed933faf4a0bb1b38377c9c3262b: Sending packet MESSAGE data 0
127.0.0.1 - - [10/Dec/2019 15:12:25] "GET /socket.io/?EIO=3&transport=polling&t=MxlC3iO HTTP/1.1" 200 -
f7ebed933faf4a0bb1b38377c9c3262b: Received packet MESSAGE data 2["message","message",{"data":"Connected to client successfully"}]
received event "message" from f7ebed933faf4a0bb1b38377c9c3262b [/]
127.0.0.1 - - [10/Dec/2019 15:12:25] "POST /socket.io/?EIO=3&transport=polling&t=MxlC3kN&sid=f7ebed933faf4a0bb1b38377c9c3262b HTTP/1.1" 200 -
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\HOME\code\MagikMoments\env\lib\site-packages\socketio\server.py", line 651, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\HOME\code\MagikMoments\env\lib\site-packages\socketio\server.py", line 680, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\HOME\code\MagikMoments\env\lib\site-packages\flask_socketio\__init__.py", line 284, in _handler
    *args)
  File "C:\Users\HOME\code\MagikMoments\env\lib\site-packages\flask_socketio\__init__.py", line 698, in _handle_event
    ret = handler(*args)
TypeError: handle_message() takes 1 positional argument but 2 were given
```

If I remove message argument, it shows

```bash
127.0.0.1 - - [10/Dec/2019 15:19:19] "GET / HTTP/1.1" 200 -
e5706b09d47349e38ae8225ed1d028e9: Sending packet OPEN data {'sid': 'e5706b09d47349e38ae8225ed1d028e9', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
emitting event "message" to e5706b09d47349e38ae8225ed1d028e9 [/]
e5706b09d47349e38ae8225ed1d028e9: Sending packet MESSAGE data 2["message",{"data":"Connected to server successfully"}]
e5706b09d47349e38ae8225ed1d028e9: Sending packet MESSAGE data 0
127.0.0.1 - - [10/Dec/2019 15:19:19] "GET /socket.io/?EIO=3&transport=polling&t=MxlDej6 HTTP/1.1" 200 -
e5706b09d47349e38ae8225ed1d028e9: Received packet MESSAGE data 2["message","message",{"data":"Connected to client successfully"}]
received event "message" from e5706b09d47349e38ae8225ed1d028e9 [/]
127.0.0.1 - - [10/Dec/2019 15:19:19] "POST /socket.io/?EIO=3&transport=polling&t=MxlDek8&sid=e5706b09d47349e38ae8225ed1d028e9 HTTP/1.1" 200 -
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\HOME\code\MagikMoments\env\lib\site-packages\socketio\server.py", line 651, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\HOME\code\MagikMoments\env\lib\site-packages\socketio\server.py", line 680, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\HOME\code\MagikMoments\env\lib\site-packages\flask_socketio\__init__.py", line 284, in _handler
    *args)
  File "C:\Users\HOME\code\MagikMoments\env\lib\site-packages\flask_socketio\__init__.py", line 698, in _handle_event
    ret = handler(*args)
TypeError: handle_message() takes 0 positional arguments but 2 were given
```

## The Code : 

`server.py`
```python3
from flask import Flask, render_template, Response
from flask_socketio import SocketIO, emit

app = Flask(__name__)
socketio = SocketIO(app, logger=True, engineio_logger=True)

@app.route('/')
def index():
    return render_template('index.html')

@socketio.on('connect')
def test_connect():
    emit('message', {'data': 'Connected to server successfully'})

@socketio.on('message')
def handle_message(message): # Should it take an argument ?
    print("Message recieved" + message)

if __name__ == '__main__':
    socketio.run(app, debug=True)
```
<br/>

`index.html`
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Display Webcam Stream</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"></script>
</head>

<body>
    <script>
        $(document).ready(function () {
            var video = document.querySelector("#videoElement");
            var socket = io.connect('http://localhost:5000');

            socket.on('connect', ()=> {
                // alert("Connection established successfully");
                socket.send('message', { data: "Connected to client successfully"});
            })

            socket.on('message', msg => {
                alert("Message recieved = " + msg.data)
            })
        });
    </script>
</body>

</html>
```

**Comment by Kogam22** [comment]
the python socket.io, and flask-socket.io official documentation shows this way of receiving messages:
```python3
@socketio.on('message')
def handle_message(message):
    print('received message: ' + message)
```
which i copy pasted only to receive an error.

**Comment by Kogam22** [comment]
I figured out the problem. The problem was with the data sent from client. after changing it to
```javascript
socket.send("Connected to client successfully");
```
from
```javascript
socket.send('message', { data: "Connected to client successfully"});
```
its working properly.
