### ISSUE TITLE
NameError: name 'socketio' is not defined

### ISSUE THREAD

**Issue by Helveg** [miguelgrinberg/Flask-SocketIO#1178]
**Describe the bug**
When I run app.py, I get the following error:

```
Traceback (most recent call last):
  File "/home/robin/.pyenv/versions/3.7.6/bin/arbor-gui", line 11, in <module>
    load_entry_point('arbor-gui', 'console_scripts', 'arbor-gui')()
  File "/home/robin/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/robin/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/robin/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/robin/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/robin/arbor-gui/dist/arbor_gui/app.py", line 33, in <module>
    @socketio.on('message')
NameError: name 'socketio' is not defined

```

**To Reproduce**
1. I copied the code in this guide https://flask-socketio.readthedocs.io/en/latest/
2. Run this script:

``` python
from flask import Flask, send_from_directory, render_template
from flask_socketio import SocketIO
from flask_cors import CORS
import webbrowser, threading, os, random

app = Flask(__name__)
CORS(app, origins="localhost")


@app.route('/<path:path>', methods=['GET'])
def static_proxy(path):
  options = {}
  if path.endswith(".js"):
    options["mimetype"] = "application/javascript"
  return send_from_directory('./', path, **options)


@app.route('/')
def serve_angular():
  return send_from_directory('./', 'index.html')


@app.errorhandler(404)
def http_error_handler(error):
  return serve_angular()


@app.errorhandler(500)
def server_error(e):
  return 'An internal error occurred [main.py] %s' % e, 500


@socketio.on('message')
def handle_message(message):
    print('received message: ' + message)


@socketio.on('json')
def handle_json(json):
    print('received json: ' + str(json))


@socketio.on('my event')
def handle_my_custom_event(json):
    print('received json: ' + str(json))


def run_app():
  port = random.randint(5000, 5999)
  path = os.path.dirname(__file__)
  threading.Timer(0.75, lambda: webbrowser.open('http://localhost:' + str(port))).start()
  socketio = SocketIO(app)
  socketio.run(app, host='localhost', port=port)
```

## Additional context
There doesn't seem to be an import for `socketio`, if I change the decorator to `@SocketIO.on('message')` I get the error that it's missing 1 required argument 'message'

**Comment by miguelgrinberg** [comment]
You have defined `socketio` as a local variable in your `run_app()` function. Move it to a global variable above all the decorator usages and you should be fine.

**Comment by Helveg** [comment]
Duh :disappointed: I looked the file up and down 20 times for `socketio`. Thanks!
