### ISSUE TITLE
How to safely disconnect the client from server when using celery, flasksocketio and docker-compose 

### ISSUE THREAD

**Issue by upliftertom** [miguelgrinberg/Flask-SocketIO#1212]
Hi Miguel,

I've been getting a strange error recently, which is causing some performance issues in the rest of my app.  I hope you can help, I love your work :)

I've been using a flask app as an API backend for website I've been working, using flask for the http stuff, and flask-socketio when we need web sockets.

One section of the site has a long running function that we needed to serve, so I installed celery as a task queue, using redis as the message queue & flask socketio sends updates to the frontend as the function returns data.  These are started together and linked using a docker-compose file.  

It's necessary for us to open one socket per client, so that communications are private.  We do this by broadcasting to a room using the user id that we set for a user when they sign up so there is only one person in the room.  Then when the long running call has finished, disconnecting the client from the room.

This has been working great so far, but recently we've been seeing this in the logs:

```bash
celery_1         | [2020-03-19 09:29:10,953: INFO/ForkPoolWorker-1] Task uplifter.audit.events.gen_audit_report[13917f67-9e16-4bd2-af04-3f6b2c921d8d] succeeded in 12.080543429008685s: None
website_1        | 493aa102ff634604b740dbae83cec4db: Received packet MESSAGE data 2/audit,["close",{"room":"fd0de1d4-999b-4fb6-8930-e034bf8dc2e9"}]
website_1        | received event "close" from 493aa102ff634604b740dbae83cec4db [/audit]
website_1        | room closed
website_1        | {'room': 'fd0de1d4-999b-4fb6-8930-e034bf8dc2e9'}
website_1        | room fd0de1d4-999b-4fb6-8930-e034bf8dc2e9 is closing [/audit]
website_1        | pubsub message: close_room
website_1        | 493aa102ff634604b740dbae83cec4db: Received packet PING data None
website_1        | 493aa102ff634604b740dbae83cec4db: Sending packet PONG data None
website_1        | Client disconnected
website_1        | pubsub message: disconnect
website_1        | Disconnecting 493aa102ff634604b740dbae83cec4db [/audit]
website_1        | 493aa102ff634604b740dbae83cec4db: Sending packet MESSAGE data 1/audit
website_1        | Client disconnected
website_1        | Traceback (most recent call last):
website_1        |   File "/usr/local/lib/python3.6/site-packages/eventlet/wsgi.py", line 599, in handle_one_response
website_1        |     write(b'')
website_1        |   File "/usr/local/lib/python3.6/site-packages/eventlet/wsgi.py", line 491, in write
website_1        |     raise AssertionError("write() before start_response()")
website_1        | AssertionError: write() before start_response()
website_1        |
website_1        | 192.168.0.1 - - [19/Mar/2020 09:29:45] "GET /socket.io/?EIO=3&transport=websocket&sid=493aa102ff634604b740dbae83cec4db HTTP/1.1" 500 0 46.591553
website_1        | pubsub message: disconnect
website_1        | pubsub message: disconnect
website_1        | Disconnecting 493aa102ff634604b740dbae83cec4db [/]
website_1        | Cannot send to sid 493aa102ff634604b740dbae83cec4db
website_1        | pubsub message: disconnect
website_1        | pubsub message: disconnect
website_1        | pubsub message: disconnect
website_1        | pubsub message: disconnect
website_1        | pubsub message: disconnect
website_1        | pubsub message: disconnect
```

And then the ```website_1        | pubsub message: disconnect``` keeps repeating infinitely, causing performance issues.

My docker compose script starts a python file with a socketio server->

```python
# run.py
"""Runs a production ready eventlet server"""
from uplifter import create_app, socketio

app = create_app()

if __name__ == "__main__":
    socketio.run(
         app,
         host= "0.0.0.0",
         port= "80",
         log_output = True,
         use_reloader = True,
        )    
```

where create_app() is a factory function - in the uplifter file we create the celery connection and the socketio server

```python
# __init__.py (uplifter.py)

celery = Celery(__name__,
    backend= 'redis://uplifterRedis:6379',
    broker= 'redis://uplifterRedis:6379/1',
    port = 6379,
    broker_use_ssl = True
)
socketio = SocketIO()

def make_extensions(app):
    """Register 0 or more extensions (mutates the app passed in)
    
    Arguments:
        app {Flask} -- Flask application instance
    """
    
    app.wsgi_app = ProxyFix(app.wsgi_app)
    CORS(app)

    socketio.init_app(
        app = app,
        message_queue = 'redis://uplifterRedis:6379',
        engineio_logger = True,
        logger = True,
        cors_allowed_origins = "*"
     )
    return None

def create_app():
    """Creates the flask application using the app factory pattern.
    
    Keyword Arguments:
        settings_override {dict} -- for use with mutating the application context (default: {None})
    
    Returns:
        app -- Flask app.
    """
    ... register blueprints  and config ...
    make_extensions(app)
    return app
```

The celery worker is just ->

```python
# celery_worker.py
from uplifter import celery, create_app

app = create_app()
app.app_context().push()

```

Then, in the events.py file where I handle all the celery tasks and socketio functions

```python
# events.py
from uplifter import socketio, celery

########################################################
# SOCKETIO

@socketio.on('connect', namespace="/audit")
def test_connect():
    emit('my response', {'data': 'Connected'})

@socketio.on('join', namespace="/audit")
def joinRoom(message):
    join_room(message["uid"])
    emit("joined", {"data": "Joined"}, room = message["uid"])


@socketio.on("runAudit", namespace="/audit")
def test_start(message):
    token = message["token"]
    

    ###################
    #  Celery task

    task = gen_audit_report.delay(
        required args
    )

@socketio.on('disconnect', namespace = "/audit")
def test_disconnect():
    print('Client disconnected')
    disconnect()

@socketio.on_error(namespace="/audit")
def socketError(e):
    print("socket error:", str(e))

@celery.task(bind=True)
def gen_audit_report(self,  -other variables for the function - ):
    """Runs the audit report queries
    """

    socketioWorker = SocketIO(message_queue = 'redis://uplifterRedis:6379')
    
    responseData = {}

    responseData.update(
        view_data_tests(...,
         { key: v for key, v in rowData.items() if key in ["test4", "test7", "test22", "test32"] })
     ) 
    # There's about 20 of these tests, they call and parse 
    # the response from an API using the requests module
    
    socketioWorker.emit(
        'testResult',
        {
            "numTestsRun" : numTestsRun,
            "percentageComplete" : round((1/totalTests) * 100),
            "totalTests": len(rowData) - 1,
            "status" : "INPROGRESS",
            "testResult" : responseData
        },
        namespace = "/audit",
        room = room
    )
    return {"status" : "COMPLETE", "testResult": responseData}

```

Then when the client calls disconnect() or closes their browser window, we get flooded with the ```website_1        | pubsub message: disconnect``` message.

**Comment by miguelgrinberg** [comment]
Please downgrade the python-socketio package to 4.4.0. The repeated disconnect message is a bug in version 4.5.0. It is fixed in the master branch, a fixed release will be available within 1-2 days.

**Comment by upliftertom** [comment]
Ah, yes that fixed the issue, many thanks

**Comment by ranihorev** [comment]
I'm seeing the same issue even after downgrading to python-socketio to 4.4.0. It happens when I refresh my page, probably on socket disconnect. 
I'm running a flask-socketio with gevent. It happens with and without the monkey patch. 

The traceback:
```
Traceback (most recent call last):
  File ".../venv/lib/python3.8/site-packages/eventlet/wsgi.py", line 606, in handle_one_response
    write(b'')
  File ".../venv/lib/python3.8/site-packages/eventlet/wsgi.py", line 491, in write
    raise AssertionError("write() before start_response()")
AssertionError: write() before start_response()

127.0.0.1 - - [15/Oct/2020 21:32:31] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 500 0 14.205794
```

Any ideas?
Thanks!

**Comment by ranihorev** [comment]
Looks like there is a fix here:
https://github.com/Hardtack/eventlet

It's been waiting for a year to get merged into eventlet...
