### ISSUE TITLE
Random key error in self.server.environ[sid]

### ISSUE THREAD

**Issue by gabriel2029** [miguelgrinberg/Flask-SocketIO#1213]
Hello, I use: Python 3.8.1, Flask 1.1.1, Flask-SocketIO 4.2.1 and Redis (with flask-redis 0.4.0) for a message queue in combination with Celery 4.4.2. 

Sometimes anywhere in the usage of SocketIO the following error occurs:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/socketio/pubsub_manager.py", line 174, in _thread
    self._handle_disconnect(data)
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/socketio/pubsub_manager.py", line 142, in _handle_disconnect
    self.server.disconnect(sid=message.get('sid'),
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/socketio/server.py", line 526, in disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/socketio/server.py", line 703, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/flask_socketio/__init__.py", line 283, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/flask_socketio/__init__.py", line 679, in _handle_event
    if 'saved_session' not in self.server.environ[sid]:
KeyError: 'ce81274328a44a6d9cbe9d1bf4f5b842'
```
After that, the server only receives messages, but doesn't send messages to the client (I tested it with the usage of `localStorage.debug = '*';` in the browser debug console). I didn't notice any clear pattern when this behavior happens.

**Comment by miguelgrinberg** [comment]
Please enable Socket.IO logs and provide a section of longs long enough to show all the references to the `sid` that ends up giving you the KeyError.

**Comment by gabriel2029** [comment]
Which logs do you exactly mean? Client or server logs?

**Comment by miguelgrinberg** [comment]
Server logs for the Socket.IO server. Please enable all the logging options.

**Comment by gabriel2029** [comment]
```
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
b7e3507c2c2d4c70a7024f313a4db538 is leaving room user 2 [/]
pubsub message: disconnect
pubsub message: disconnect
b7e3507c2c2d4c70a7024f313a4db538 is leaving room user 2 [/]
pubsub message: disconnect
Disconnecting b7e3507c2c2d4c70a7024f313a4db538 [/]
127.0.0.1 - - [22/Mar/2020 21:24:18] "GET /socket.io/?EIO=3&transport=websocket&sid=b7e3507c2c2d4c70a7024f313a4db538 HTTP/1.1" 200 0 22.140030
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/socketio/pubsub_manager.py", line 174, in _thread
    self._handle_disconnect(data)
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/socketio/pubsub_manager.py", line 142, in _handle_disconnect
    self.server.disconnect(sid=message.get('sid'),
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/socketio/server.py", line 526, in disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/socketio/server.py", line 703, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/flask_socketio/__init__.py", line 283, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/home/gabriel/AtomProjects/<Project>/env/lib/python3.8/site-packages/flask_socketio/__init__.py", line 679, in _handle_event
    if 'saved_session' not in self.server.environ[sid]:
KeyError: 'b7e3507c2c2d4c70a7024f313a4db538'
```
The line `pubsub message: disconnect` appears much more often than I printed it here.

**Comment by miguelgrinberg** [comment]
Do you get the same error if you install the master branch of the python-socketio repository? The repeating disconnect issue is fixed there. A new release with this fix is coming up soon.

**Comment by gabriel2029** [comment]
The errors occur on manjaro, I have also tested the same version of my software (also same package version installed by pip) on Debian 10 and didn't manage to reproduce the error on this system. I will inform you if I find out more information about this. 

I will try using the version on the master branch in the coming days.
