### ISSUE TITLE
Unable to use eventlet/upgrade to websocket for socketio

### ISSUE THREAD

**Issue by nullbaka** [miguelgrinberg/Flask-SocketIO#1296]
Server-side error-
```
72d76888484c40138f26d7fa5f7ce9dd: Received request to upgrade to websocket
127.0.0.1 - - [05/Jun/2020 23:38:00] "GET /socket.io/?EIO=3&transport=websocket&sid=72d76888484c40138f26d7fa5f7ce9dd HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/uttaran/.environments/quickplay/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/uttaran/.environments/quickplay/lib/python3.8/site-packages/flask_socketio/__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/Users/uttaran/.environments/quickplay/lib/python3.8/site-packages/engineio/middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/Users/uttaran/.environments/quickplay/lib/python3.8/site-packages/socketio/server.py", line 560, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/Users/uttaran/.environments/quickplay/lib/python3.8/site-packages/engineio/server.py", line 376, in handle_request
    packets = socket.handle_get_request(
  File "/Users/uttaran/.environments/quickplay/lib/python3.8/site-packages/engineio/socket.py", line 107, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/Users/uttaran/.environments/quickplay/lib/python3.8/site-packages/engineio/socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "/Users/uttaran/.environments/quickplay/lib/python3.8/site-packages/engineio/async_drivers/eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
```

Client-side error-
```
index.js:83 WebSocket connection to 'ws://127.0.0.1:5000/socket.io/?EIO=3&transport=websocket&sid=72d76888484c40138f26d7fa5f7ce9dd' failed: Error during WebSocket handshake: Unexpected response code: 500
```

My init code-
```
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import os
import eventlet
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_socketio import SocketIO
from config import Config

eventlet.monkey_patch()

app = Flask(__name__,static_url_path='', 
            static_folder='static')
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)
login.login_view = 'login'
socketio = SocketIO(app, engineio_logger=True, async_mode='eventlet')

from app import routes, models, io

if __name__ == '__main__':
    socketio.run(app)
```

io-routes-
```
from flask import request
from flask_login import current_user
from app import socketio
from flask_socketio import disconnect, emit, send

session_ids = {}

@socketio.on('connect')
def on_connect():
    if current_user.is_authenticated:
        current_user_sid = request.sid
        session_ids[current_user.name] = current_user_sid
        info_a = {'event': 'online', 'name': current_user.name}
        for friend in current_user.friends:
            if friend.name in session_ids:
                emit('user_connection', info_a, room=session_ids[friend.name])
                info_b = {'event': 'online', 'name': friend.name}
            else:
                info_b = {'event': 'offline', 'name': friend.name}
            emit('user_connection', info_b, room=current_user_sid)

    else:
        disconnect()
```

Uses long-polling instead of using websockets. When I added eventlet, I get RuntimeError: You need to use the eventlet server. At wits end because socketio.run(app) should fix it.

**Comment by miguelgrinberg** [comment]
How are you running your application? As the error says, you have to use the eventlet server, you appear to be using some other server, maybe the Flask dev server?

**Comment by nullbaka** [comment]
Hi Miguel, thank you for the push.
```
gunicorn --worker-class eventlet -w 1 app:app --bind 127.0.0.1:5000
```
This solved the issue. I was under the impression that `socketio.run(app)` automatically starts a non-dev server. Figured that `flask run` IS a dev server.

**Comment by miguelgrinberg** [comment]
> I was under the impression that socketio.run(app) automatically starts a non-dev server.

Don't think in terms of dev and non-dev servers, that confuses things. The `flask run` command runs the Werkzeug server. The `socketio.run(app)` command try to start eventlet if it finds it installed, next it tries gevent, and finally runs Werkzeug. When you use Gunicorn you select which server you run with the `-k` or `--worker-class` command.

Out of all these servers, the only one that is not ready for production is Werkzeug. All others are good to use for production.
