### ISSUE TITLE
Communication between synchronous script and Flask-socketIO web server

### ISSUE THREAD

**Issue by mitpre** [miguelgrinberg/Flask-SocketIO#1298]
Hi,

I am trying to find a good way for getting two python scripts to communicate between themselves. First script is written in a fully synchronous way, it is checking inputs from part of Raspberry Pi GPIO pins and based on some logic controls the other part of Raspberry Pi GPIO pins that are set as outputs.  A MWE of the first script can be seen bellow. `bckg` thread is running time based checks on inputs, and if something of interest happens it messages the `main` thread that does something with the info in the `else` part of the code.
```
import time
import queue
import random
import logging
import threading

logging.basicConfig(level=logging.DEBUG, format="%(asctime)s|%(name)-10s|%(threadName)-20s|%(levelname)-8s|%(message)s")

def bckg(queue, threshold=0.9):
    logger = logging.getLogger(__name__)
    while True:
        rnd = random.random()
        logger.debug("%.2f", rnd)
        if rnd > threshold:
            logger.warning("new result %.2f", rnd)
            queue.put(rnd)
        time.sleep(1)
        
        
logger = logging.getLogger(__name__)

q = queue.Queue(100)
thr = threading.Thread(target=bckg, args=(q, ), name="bckg", daemon=True)
thr.start()

while True:
    empty = False

    try:
        result = q.get(timeout=0.1)
        logger.info("task started; input queue: %r", result)

    except queue.Empty:
        empty = True
        continue

    except KeyboardInterrupt:
        logger.info("main finished")
        empty = True
        break

    else:
        # DO SOME STUFF
                  
    finally:
        if not empty:
            q.task_done()
            logger.debug("task done")
```

The second script is going to be a web server based on Flask Socket-IO, which has to get information when something is changed in the first script and also has to have an ability to send information to the first script based on user input through a web page. For this I do not yet have an example as I am stuck with finding a way to establish communication. My "lame" approach would be to write a `socketserver` for the first script and have it running in a parallel thread. Then have a background thread in Flask part with an `async socket client` constantly (~.1 second) polling for news, and a similar client implemented in `@socketio.on('newReq', namespace='')` to send user input. But I guess there are better ways that do not generate that much overhead? Can someone suggest one? Possibly with a small example?

**Comment by miguelgrinberg** [comment]
Given than your second script is a web server, can't the first script send a web request to the 2nd script when something happened?

**Comment by mitpre** [comment]
As I am completely new to web programming I did not even think of this :D So you would have the first script send updates to the second one via `request` library? What about the other direction?

Thank you very much!

**Comment by miguelgrinberg** [comment]
If you need the 2nd script to notify the 1st at random times instead of just as a response of the 1st script indicating that something changed, then it may be more convenient to use Socket.IO for this communication. Your 2nd script will have a Socket.IO server, and the 1st can use the Socket.IO client from the python-socketio package. Once the connection is made, any side can send an event to the other at any time.

**Comment by mitpre** [comment]
Could you maybe give a pointer how would you implement a Socket.IO client into the code that was posted in the original question?
I thought that python-socketio is asynchronous and that it would not mix nicely with a synchronous stuff.

**Comment by miguelgrinberg** [comment]
There are sync and async clients. Here is a sync example: https://github.com/miguelgrinberg/python-socketio/blob/master/examples/client/threads/latency_client.py.

**Comment by mitpre** [comment]
So the reason why I rewrote the whole thing, so that I have a separate script for GPIO checkups (first script) and web server (second script) is because if I had the whole GPIO part in the background thread of the web server I never managed to do a nice clean exit with a cleanup on GPIO settings. Therefore, I fear this is going to be the case again if I add the socketio client to it. For instance, just stopping the `latency_client.py` produces a traceback for `KeyboardInterrupt`
```
Traceback (most recent call last):
  File "latency_client.py", line 32, in <module>
    sio.wait()
  File "/Users/mitja/matej-pi/v4/venv/lib/python3.7/site-packages/socketio/client.py", line 292, in wait
    self.eio.wait()
  File "/Users/mitja/matej-pi/v4/venv/lib/python3.7/site-packages/engineio/client.py", line 199, in wait
    self.read_loop_task.join()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/Users/mitja/matej-pi/v4/venv/lib/python3.7/site-packages/engineio/client.py", line 43, in signal_handler
    return original_signal_handler(sig, frame)
  File "/Users/mitja/matej-pi/v4/venv/lib/python3.7/site-packages/socketio/client.py", line 26, in signal_handler
    return original_signal_handler(sig, frame)
```

And somehow I don't like this, especially because I do not understand in the slightest how it works :( Is there no other, more basic way to get the data from the web server (without polling every few milliseconds)?

**Comment by miguelgrinberg** [comment]
> Is there no other, more basic way to get the data from the web server (without polling every few milliseconds)?

Can't think of any other way that would require less work than this option. At least I don't have any to suggest.

**Comment by mitpre** [comment]
So in the end the story would go somewhat in this direction ...

Script 1 (GPIO controlling script):
```
import time
import queue
import random
import logging
import socketio
import threading
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s|%(name)-20s|%(threadName)-10s|%(levelname)-8s|%(message)s")

class sioclient(object):
    def __init__(self, queue):
        self.log = logging.getLogger(__name__)
        self.queue = queue
        self.sio = socketio.Client()
        logging.getLogger('socketio').setLevel(logging.ERROR)
        logging.getLogger('engineio').setLevel(logging.ERROR)

        @self.sio.event
        def connect():
            self.log.info('connected to server; sid %r', self.sio.sid)

        @self.sio.event
        def connect_error(message):
            self.log.info('connection failed: %r', message)

        @self.sio.event
        def disconnect():
            self.log.info('disconnected from server')

        @self.sio.event
        def www(data):
            self.log.debug("www event: %r", data)
            self.queue.put(data)

    def connect(self):
        self.sio.connect('http://localhost:5000')
        self.sio.wait()


def bckg(queue, stop):
    log = logging.getLogger(__name__)
    while not stop.isSet():
        data = {"origin": "bckg", "val": random.random()}
        log.debug("bckg event: %r", data)
        queue.put(data)
        time.sleep(3)
        
log = logging.getLogger(__name__)
if __name__ == '__main__':
    q = queue.Queue(100)
    log.info("starting bckg thread")
    stop   = threading.Event()
    bckg_t = threading.Thread(target=bckg, args=(q, stop), name="bckg")
    bckg_t.start()

    log.info("starting socketio client thread")
    sio = sioclient(q)
    sio_t = threading.Thread(target=sio.connect)
    sio_t.start()

    log.info("starting main thread")
    while True:
        empty = False

        try:
            result = q.get(timeout=0.1)
            log.debug("task started; input queue: %r", result)

        except queue.Empty:
            empty = True
            continue

        except KeyboardInterrupt:
            log.info("keyboard interrupt")
            empty = True
            break

        else:
            thr = 0.7
            if result["val"] > thr:
                log.info("new %.2f was set by %s", result["val"], result["origin"])
            # DO SOME STUFF
                      
        finally:
            if not empty:
                q.task_done()
                log.debug("task done")
    log.info("main thread done")

    sio.sio.disconnect()
    log.info("socketio client disconnected")

    sio_t.join()
    log.info("socketio client thread done")
    stop.set()
    bckg_t.join()
    log.info("bckg thread done")
    log.info("exit")
```

Script 2 (web server):
```
from flask import Flask, render_template
import socketio
import random

sio = socketio.Server()
app = Flask(__name__)
app.wsgi_app = socketio.WSGIApp(sio, app.wsgi_app)

def background_thread():
    """Example of how to send server generated events to clients."""
    while True:
        sio.sleep(3)
        sio.emit('www', {'origin': 'www', 'val': random.random()})
thread = sio.start_background_task(background_thread)

if __name__ == '__main__':
    app.run(threaded=True)
```
In the final thing there won't be any background thread, but for the simulation is OK. Do you foresee any problems in going this direction? Is `sio.disconnect()` the normal way to disconnect the client and stop its `running forever` loop?

I believe there are many problems that I do not see at this point, but one I already noticed ... if the www server crashes after the client is already connected, the client tries to reconnect.  Perfect. But if the www server is not yet running when the client tries to reach it I get the following:
```
2020-06-09 19:34:53,886|__main__            |Thread-1  |INFO    |connection failed: 'Connection refused by the server'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "latency_client_2.py", line 37, in connect
    self.sio.connect('http://localhost:5000')
  File "/Users/mitja/matej-pi/v4/venv/lib/python3.7/site-packages/socketio/client.py", line 282, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Connection refused by the server
```
How could I achieve the same behaviour as in dropped connection?

**Comment by miguelgrinberg** [comment]
> Is sio.disconnect() the normal way to disconnect the client and stop its running forever loop?

Yes, looks okay to me. Since you don't have the client in the main thread, you may want to add an interrupt handler to clean everything up when the process is killed or Ctrl-C'd. If the client is started on the main thread it does set up its own signal handler to clean up.

> How could I achieve the same behaviour as in dropped connection?

When I implemented the reconnect feature I thought it should not activate on the initial connection, so this is actually working as I designed it. You are not the first to suggest the reconnects should work even when the initial connection fails, but at this point the only option you have is to write a retry loop on your side.

**Comment by mitpre** [comment]
> Yes, looks okay to me. Since you don't have the client in the main thread, you may want to add an interrupt handler to clean everything up when the process is killed or Ctrl-C'd. If the client is started on the main thread it does set up its own signal handler to clean up.
What is there to clean? The references to socketio.Client() so that garbage collector can do its job? Anything else?

> When I implemented the reconnect feature I thought it should not activate on the initial connection, so this is actually working as I designed it. You are not the first to suggest the reconnects should work even when the initial connection fails, but at this point the only option you have is to write a retry loop on your side.
Will do so. Thank you.
