### ISSUE TITLE
Local testing leads to 401 Unauthorized error while trying to connect

### ISSUE THREAD

**Issue by abshkbh** [miguelgrinberg/Flask-SocketIO#1312]
Here is my basic server - https://pastebin.com/1YJPy38u
Here is my basic React client - https://pastebin.com/gE6AvQuT

1. I am just trying to test out connecting to the server over websocket and printing a success message. I get an 401 Unauthorized message.

2. I see transport=polling in the URL sent. This shouldn't be right ?

Attaching a screenshot of my  console log here - https://imgur.com/a/IHHuMRz

Any idea what I'm missing. I definitely needed the cors_allowed_origins args to get past another error before.

**Comment by miguelgrinberg** [comment]
I'm going to have time to look at this later today, but I suspect this was caused by a recent change I've made. Try changing the `return True` to `return None` and let me know if that helps.

**Comment by abshkbh** [comment]
return None didn't help

In your example here you don't return anything from the handlers -
https://blog.miguelgrinberg.com/post/easy-websockets-with-flask-and-gevent

**Comment by abshkbh** [comment]
Also, see this stack on the server, not necessarily tied to a connect event coming in but randomly happens -

connect handler error
Traceback (most recent call last):
  File "/home/abhishekbh/projects/flask-debugging/backend/venv/lib/python3.5/site-packages/engineio/server.py", line 546, in _trigger_event
    return self.handlers[event](*args)
  File "/home/abhishekbh/projects/flask-debugging/backend/venv/lib/python3.5/site-packages/socketio/server.py", line 724, in _handle_eio_connect
    return self._handle_connect(sid, '/')
  File "/home/abhishekbh/projects/flask-debugging/backend/venv/lib/python3.5/site-packages/socketio/server.py", line 628, in _handle_connect
    self.environ[sid])
  File "/home/abhishekbh/projects/flask-debugging/backend/venv/lib/python3.5/site-packages/socketio/server.py", line 711, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/abhishekbh/projects/flask-debugging/backend/venv/lib/python3.5/site-packages/flask_socketio/__init__.py", line 283, in _handler
    *args)
  File "/home/abhishekbh/projects/flask-debugging/backend/venv/lib/python3.5/site-packages/flask_socketio/__init__.py", line 711, in _handle_event
    ret = handler()
  File "/home/abhishekbh/projects/flask-debugging/backend/venv/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/abhishekbh/projects/flask-debugging/backend/venv/lib/python3.5/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/abhishekbh/projects/flask-debugging/backend/venv/lib/python3.5/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.

**Comment by abshkbh** [comment]
return self._handle_connect(sid, '/') - this does seem to be related to the connect function then

**Comment by miguelgrinberg** [comment]
You may be mixing some unrelated things.

The error `The view function did not return a valid response` is from Flask, not Flask-SocketIO. You have a view function that is not returning a response. All view functions must return something. This has nothing to do with the problem you reported.

Also, note that `return None` is equivalent to not returning anything. Any Python that does not return anything is effectively returning `None`. I could have asked you to delete the `return` statement and it would have been exactly the same.

I believe the problem is in your code. You used the Flask-CORS decorator, which is intended for Flask routes in a Flask-SocketIO event handler. Remove the decorator and I think your connection will work.

**Comment by abshkbh** [comment]
Thanks, that was it.
I uploaded a minimal example for others as well -
https://github.com/abshkbh/flask-react-websocket-example

I think your example has a vanilla js client. I added a React one :)
