### ISSUE TITLE
AssertionError: The application did not call start_response() trying to use gevent

### ISSUE THREAD

**Issue by chamecall** [miguelgrinberg/Flask-SocketIO#1313]
I'm passing images from a client to the server at fixed intervals with next processing them by neural networks there and after a certain time server is disconnect a client possibly due to slow transfer provided by pooling.
So I'd like to use websockets inside of Flask Socketio for data transfer between server and client.
For that reason I installed gevent and gevent-websocket.
My flask server creation is the next:

```
app = Flask(__name__)

socketio = SocketIO(app, logger=True, engineio_logger=True)

import namespaces

def get_namespaces(namespaces):
	namespaces_list = []
	for module_name in dir(namespaces):
		required_module = namespaces.__dict__.get(module_name)
		if isinstance(namespaces.__dict__.get(module_name), type(sys)):
			for resource_name in dir(required_module):
				resource = required_module.__dict__.get(resource_name)
				if "_namespace" in dir(resource):
					namespaces_list.append({
						"namespace_instance": resource,
						"namespace_name": resource.__dict__.get("_namespace"),
					})
	return namespaces_list

if __name__ == "__main__":
	for current_namespace in get_namespaces(namespaces):
		socketio.on_namespace(current_namespace["namespace_instance"](current_namespace["namespace_name"]))
	socketio.run(app, host="0.0.0.0", debug=False)
```

On client side I use[ the Android-Socketio project](https://github.com/socketio/socket.io-client-java) with such socket initialization:
```
        String mainAddress = protocol + "://" + domain + namespaces[0];
        try {
            final IO.Options options = new IO.Options();
            options.transports = new String[] {
                    "websocket"
            };
            mainSocket = IO.socket(mainAddress, options);
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
```

And when client calls `mainSocket.connect()` method on the server side happens the following error:

```
июн 23 13:51:58 gitea bash[29434]: 1955272d35124d9e8bf3dbe8e912fb6b: Sending packet OPEN data {'sid': '1955272d35124d9e8bf3dbe8e912fb6b', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
июн 23 13:51:58 gitea bash[29434]: 13:51:58,250 engineio.server INFO 1955272d35124d9e8bf3dbe8e912fb6b: Sending packet OPEN data {'sid': '1955272d35124d9e8bf3dbe8e912fb6b', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
июн 23 13:51:58 gitea bash[29434]: 1955272d35124d9e8bf3dbe8e912fb6b: Sending packet MESSAGE data 0
июн 23 13:51:58 gitea bash[29434]: 13:51:58,251 engineio.server INFO 1955272d35124d9e8bf3dbe8e912fb6b: Sending packet MESSAGE data 0
июн 23 13:51:58 gitea bash[29434]: Traceback (most recent call last):
июн 23 13:51:58 gitea bash[29434]:   File "/var/lib/jenkins/workspace/vozera-server/venv/lib/python3.7/site-packages/gevent/pywsgi.py", line 970, in handle_one_response
июн 23 13:51:58 gitea bash[29434]:     self.run_application()
июн 23 13:51:58 gitea bash[29434]:   File "/var/lib/jenkins/workspace/vozera-server/venv/lib/python3.7/site-packages/geventwebsocket/handler.py", line 87, in run_application
июн 23 13:51:58 gitea bash[29434]:     return super(WebSocketHandler, self).run_application()
июн 23 13:51:58 gitea bash[29434]:   File "/var/lib/jenkins/workspace/vozera-server/venv/lib/python3.7/site-packages/gevent/pywsgi.py", line 918, in run_application
июн 23 13:51:58 gitea bash[29434]:     self.process_result()
июн 23 13:51:58 gitea bash[29434]:   File "/var/lib/jenkins/workspace/vozera-server/venv/lib/python3.7/site-packages/gevent/pywsgi.py", line 904, in process_result
июн 23 13:51:58 gitea bash[29434]:     self.write(data)
июн 23 13:51:58 gitea bash[29434]:   File "/var/lib/jenkins/workspace/vozera-server/venv/lib/python3.7/site-packages/gevent/pywsgi.py", line 750, in write
июн 23 13:51:58 gitea bash[29434]:     raise self.ApplicationError("The application did not call start_response()")
июн 23 13:51:58 gitea bash[29434]: AssertionError: The application did not call start_response()
июн 23 13:51:58 gitea bash[29434]: 2020-06-23T10:51:58Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '49424', 'HTTP_HOST': '127.0.0.1:5000', (hidden keys: 22)} failed with AssertionError
июн 23 13:51:58 gitea bash[29434]: 13:51:58,251 geventwebsocket.handler INFO 127.0.0.1 - - [2020-06-23 13:51:58] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.0" 500 161 0.001225

```

**Comment by chamecall** [comment]
In case I use eventlet the server output is the following:
```
июн 23 14:06:27 gitea bash[29793]: 8e96db16f53a4ca2a0961e511f98a94c: Sending packet OPEN data {'sid': '8e96db16f53a4ca2a0961e511f98a94c', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
июн 23 14:06:27 gitea bash[29793]: 8e96db16f53a4ca2a0961e511f98a94c: Sending packet MESSAGE data 0

```

**Comment by miguelgrinberg** [comment]
I have not seen that problem with gevent, but given that eventlet works well my guess is that this is an issue with that package.

**Comment by markjin1990** [comment]
Had the exact same issue. Did you figure it out?
