### ISSUE TITLE
Flask socketio SSL request

### ISSUE THREAD

**Issue by rupak78** [miguelgrinberg/Flask-SocketIO#1315]
Hello,

I am running this very simple code:
url = 'https://xxxx.com/wp-json/'

    post = {'username': 'xxxx',
        'password': 'xxxxxx'
    }
    r = requests.post(url + 'jwt-auth/v1/token', verify=False,json=post)

Python == 3.6.8
eventlet==0.25.1
Flask==1.1.1
Flask-SocketIO==4.2.1

The error message I am getting is this :

ERROR in app: Exception on /userReistration [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "covid.py", line 1607, in userReistration
    r = requests.post(url + 'jwt-auth/v1/token', verify=False,json=post)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 276, in create_urllib3_context
    context.options |= options
  File "/usr/lib64/python3.6/ssl.py", line 423, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib64/python3.6/ssl.py", line 423, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib64/python3.6/ssl.py", line 423, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 309 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

Any help will be much appreicated.

**Comment by miguelgrinberg** [comment]
This is a bug in the SSL implementation used by eventlet. Nothing I can do about it, appears to be a difficult to fix issue. Your options are to try gevent, which might work better, or else find an older version of eventlet that does not have this issue.

**Comment by rupak78** [comment]
Thanks for the clarification.

Can you please help me with a workaround, if, one is available.

**Comment by miguelgrinberg** [comment]
I gave you all the possible workarounds that I know:

> Your options are to try gevent, which might work better, or else find an older version of eventlet or a different version of Python. Some combinations of Python and eventlet versions do not have this issue.
