### ISSUE TITLE
ssl.SSLError: ('timed out',) when using redis SSL + eventlet + Monkey Patch

### ISSUE THREAD

**Issue by akrawez** [miguelgrinberg/Flask-SocketIO#1316]
**Your question**
I am using flask socketio with message_queue via redis currently in a test environment _redis://localhost:6379/0_. I would like to deploy in a azure cloud with redis which is set up with ssl encryption. When I activate ssl (change url, port and ssl=true) i receive the following error below. In order to make the code concise and debug i tried to set up an socketio independent ssl connection to redis and it fails with the same error.

I noticed that when i remove **eventlet.monkey_patch()** it works so maybe its a problem with eventlet. Set-up without ssl connection works as well.

Thanks for your help.

**Logs**
------- CODE ------
```
import eventlet
eventlet.monkey_patch()
from flask import Flask, render_template, session, request
from flask_socketio import SocketIO, send, emit, join_room, leave_room, Namespace, disconnect
import redis
from flask_session import Session
import redis
app = Flask(__name__)

Session(app)
socketio = SocketIO(app, message_queue='redis://localhost:6379/0', logger=True, engineio_logger=True, manage_session=False, cors_allowed_origins="*")
SESSION_REDIS                 = redis.StrictRedis(host=<remove_url_in_cloud_with_SSL_ONLY(azure redis)>",
                                                  port=6380,
                                                  password="<mypassword>",
                                                  db=0,
                                                  ssl=True)
try:
    SESSION_REDIS.ping()
    print('Successfully connected to redis')
except redis.exceptions.ConnectionError as r_con_error:
    print('Redis connection error')
    raise r_con_error
```
------- Stack Trace ------
```
Server initialized for eventlet.
Redis connection error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/local/lib/python3.5/dist-packages/redis/_compat.py", line 72, in recv
    return sock.recv(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/eventlet/green/ssl.py", line 231, in recv
    return self._base_recv(buflen, flags, into=False)
  File "/usr/local/lib/python3.5/dist-packages/eventlet/green/ssl.py", line 258, in _base_recv
    read = self.read(nbytes)
  File "/usr/local/lib/python3.5/dist-packages/eventlet/green/ssl.py", line 176, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/eventlet/green/ssl.py", line 156, in _call_trampolining
    timeout_exc=timeout_exc('timed out'))
  File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/__init__.py", line 159, in trampoline
    return hub.switch()
  File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/hub.py", line 298, in switch
    return self.greenlet.switch()
ssl.SSLError: ('timed out',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "messanger.py", line 35, in <module>
    raise r_con_error
  File "messanger.py", line 31, in <module>
    SESSION_REDIS.ping()
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 1203, in get_connection
    if connection.can_read():
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 231, in can_read
    raise_on_timeout=False)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 223, in _read_from_socket
    (ex.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('timed out',)
```

**Comment by miguelgrinberg** [comment]
Unfortunately eventlet has issues with SSL on some versions of Python. See https://github.com/eventlet/eventlet/issues/371. You may be able to find a combination of Python+eventlet that works. Another option you have is to try gevent and gevent-websocket instead of eventlet.

**Comment by HyperCharlie** [comment]
Just wanted to chime in that we are currently fighting this issue too. Python 3.6, eventlet 0.25.2, and flask-SocketIO 4.2.1. Mysteriously started producing this issue on 7/17/2020, after a successful deploy on 7/16/2020. Same code, new container build. Best we can tell one of the second-layer dependencies upgraded and it was not locked in our requirements.txt. We're still trying to sort it out. We did what miguelgrinberg recommended and swapped to gevent for testing purposes, and while that does not run into the issue above, there are other issues with gevent that prevent us from using this option. GEvent brings along a different WSGI server (pywsgi) which does not handle the Flask request object the same as Eventlet, notably request.stream is no longer an IOBase compatible steam but instead only a very limited version, which is not compatible with some other streams libraries we're using (Google's resumeable file uploads, notably), and has bugs when dealing with files larger than 2GiB, which we deal with regularly. These issues seem more intractable than the eventlet issue. I'll post an update when we discover the working magic formula.

**Comment by HyperCharlie** [comment]
I was able to make it work again by pulling a complete requirements.txt from the working image (Python 3.6.9). Here it is for future reference, confirmed working combination of eventlet, python, and flask-socketio:

```
absl-py==0.7.1
aioredis==1.3.1
aioredlock==0.5.2
alabaster==0.7.12
aniso8601==7.0.0
apache-libcloud==2.8.1
APScheduler==3.6.3
argh==0.26.2
asn1crypto==0.24.0
astroid==2.4.2
async-timeout==3.0.1
atomicwrites==1.4.0
attrdict==2.0.0
attrs==19.1.0
Authlib==0.14.1
backcall==0.2.0
behave==1.2.6
boto3==1.11.3
botocore==1.14.17
cachetools==2.1.0
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Click==7.0
cloudpickle==0.8.0
colorama==0.4.1
coverage==4.5.4
cryptography==2.6.1
cytoolz==0.9.0.1
decorator==4.4.0
Deprecated==1.2.7
dill==0.2.9
dnspython==1.16.0
docutils==0.15.2
ecdsa==0.13
eth-abi==1.3.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.2.1
eth-utils==1.9.0
eventemitter==0.2.0
eventlet==0.25.2
Flask==1.1.1
Flask-APScheduler==1.11.0
Flask-Cors==3.0.7
Flask-Injector==0.12.0
flask-io==1.14.2
Flask-Login==0.4.1
flask-redis==0.4.0
Flask-SocketIO==4.2.1
Flask-SQLAlchemy==2.4.1
flask-talisman==0.6.0
future==0.17.1
gast==0.2.2
google-api-core==1.16.0
google-api-python-client==1.7.6
google-auth==1.11.0
google-auth-httplib2==0.0.3
google-cloud==0.34.0
google-cloud-core==1.3.0
google-cloud-datastore==1.7.0
google-cloud-storage==1.25.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
gprof2dot==2019.11.30
graphene==2.1.8
graphene-sqlalchemy==2.2.2
graphql-core==2.2.1
graphql-relay==2.0.1
greenlet==0.4.15
grpcio==1.15.0
gunicorn==19.9.0
hexbytes==0.1.0
hiredis==1.1.0
httplib2==0.18.1
idna==2.8
importlib-metadata==1.7.0
injector==0.18.3
ipython==7.16.1
ipython-genutils==0.2.0
isort==4.3.21
itsdangerous==0.24
jedi==0.13.3
Jinja2==2.10.1
jmespath==0.10.0
jsonpickle==1.0
jsonschema==3.0.1
lazy-object-proxy==1.4.3
line-profiler==3.0.2
lru-dict==1.1.6
Mako==1.1.0
MarkupSafe==1.1.1
marshmallow==2.21.0
mccabe==0.6.1
monotonic==1.5
more-itertools==8.4.0
newrelic==5.0.2.126
oauth2client==4.1.3
objectmapper==0.0.4
packaging==20.4
parse==1.15.0
parse-type==0.5.2
parsimonious==0.8.0
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
promise==2.3
prompt-toolkit==3.0.5
protobuf==3.6.1
psutil==5.6.1
ptyprocess==0.6.0
py==1.9.0
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycodestyle==2.5.0
pycparser==2.19
pycryptodome==3.9.8
pyflakes==2.1.1
Pygments==2.3.1
pylibmc==1.6.1
pylint==2.3.1
PyMySQL==0.9.2
pyparsing==2.3.1
pyrsistent==0.14.11
pysha3==1.0.2
PySocks==1.6.8
pytest==5.0.1
pytest-asyncio==0.10.0
pytest-profiling==1.7.0
python-dateutil==2.8.0
python-dotenv==0.10.1
python-engineio==3.9.3
python-etcd==0.4.5
python-jose-cryptodome==1.3.2
python-redis-lock==3.5.0
python-socketio==4.5.1
pytictoc==1.5.0
pytz==2020.1
redis==3.3.5
requests==2.23.0
rlp==1.0.3
rq==1.1.0
rsa==4.0
Rx==1.6.1
s3transfer==0.3.3
sherlock==0.3.2
singledispatch==3.4.0.3
six==1.12.0
snowballstemmer==1.2.1
socketIO-client==0.7.2
SQLAlchemy==1.3.10
sqlalchemy-json==0.2.2
SQLAlchemy-Utils==0.33.6
stripe==2.48.0
termcolor==1.1.0
toolz==0.10.0
traitlets==4.3.3
typed-ast==1.4.1
typing==3.7.4.3
typing-extensions==3.7.4.2
tzlocal==2.1
uritemplate==3.0.0
urllib3==1.24.1
wcwidth==0.2.5
web3==4.7.2
websocket-client==0.57.0
websockets==6.0
Werkzeug==0.15.5
wrapt==1.12.1
zipp==3.1.0
```

**Comment by afexer** [comment]
I have been fighting these issues for weeks.  I finally got a working system with apache, gunicorn, and flask-socketio with load balancing on two instances of gunicorn and eventlet.  Here is the code I came up with. Hope it helps. https://github.com/afexer/apache-gunicorn-flask-socketio
