### ISSUE TITLE
getting  ValueError: read of closed file when sending a file with paramiko and flask socketio  

### ISSUE THREAD

**Issue by abderrahmaneMustapha** [miguelgrinberg/Flask-SocketIO#1351]
when try to send files using paramiko sftp to an ssh server i get   ValueError: read of closed file
note :  this work perfectly when try to do the same in an HTTP view

this is how i connect to server and send file
```python
@socketio.on('client-connect')
def client_connected(message):
    global data
    
    HOST = data["host"]
    HOSTUSERNAME = data['username']
    PASSWORD = data['password']
    PATH = data['path']
    FILE = data['file']
    if data:
        for (host, hostusername, password, path) in zip(HOST, HOSTUSERNAME, PASSWORD, PATH):

            #connect to the ssh server
            emit('server_try_connect', {'data' : str('trying to connect to server '+host)})
            client = Connection(host=host, username=hostusername, password=password)
            emit('server-connected', {'data' :  'client connected'})
            emit('server-connected-establish',{'data' : str('establishing connection to  '+host)})
            client.connect()
            emit('server-connected-success', {'data' :  'client connected'})
            #sending files.....
            emit('sending-files',  {'data' : "sending file"})

             ##########
             #this is the line that cause the error
            client.send_filestorage(FILE, FILE.filename, path)
         ############

            emit('files-sent', {'data' : "file sent successfully"})
            emit('files-extract',{'data' : "extrcting files"})
            emit('files-extract-success', {'data' : str(client.extract(path, file_name=FILE.filename))})
        
            #check if the file existe / and command lines
            client.excute_command("ls")
            emit('list-dir',  {'data' : str(client.check_command())})
            client.close_connection()
            emit('connection-closed', {'data' :  ('connection closed')})
 ```

this is send file fucntion
```python
 #send a storage file
    def send_filestorage(self, file_storage, file_in_server, file_path_inserver):
        sftp = self.client.open_sftp()

        # create a file path if the we have a path from the user
        if file_path_inserver:
            self.create_and_navigate_topath(sftp,file_path_inserver)
        sftp.putfo(file_storage, file_in_server)
        sftp.close()
````

this is the error
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "c:\users\icom\appdata\local\programs\python\python37\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\users\icom\appdata\local\programs\python\python37\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\icom\Envs\wisevenv\lib\site-packages\socketio\server.py", line 682, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\icom\Envs\wisevenv\lib\site-packages\socketio\server.py", line 711, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\icom\Envs\wisevenv\lib\site-packages\flask_socketio\__init__.py", line 283, in _handler
    *args)
  File "C:\Users\icom\Envs\wisevenv\lib\site-packages\flask_socketio\__init__.py", line 713, in _handle_event
    ret = handler(*args)
  File "C:\Users\icom\myProjects\share-wise\app.py", line 51, in test
    client.send_filestorage(FILE, FILE.filename, path)
  File "C:\Users\icom\myProjects\share-wise\utils.py", line 51, in send_filestorage
    sftp.putfo(file_storage, file_in_server)
  File "C:\Users\icom\Envs\wisevenv\lib\site-packages\paramiko\sftp_client.py", line 717, in putfo
    reader=fl, writer=fr, file_size=file_size, callback=callback
  File "C:\Users\icom\Envs\wisevenv\lib\site-packages\paramiko\sftp_client.py", line 678, in _transfer_with_callback
    data = reader.read(32768)
  File "C:\Users\icom\Envs\wisevenv\lib\tempfile.py", line 736, in read
    return self._file.read(*args)
  File "C:\Users\icom\Envs\wisevenv\lib\tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file
```

**Comment by miguelgrinberg** [comment]
What is `data['file']`? If you are expecting this is going to be a `FileStorage` object like you get on a file upload via normal Flask route that is not going to work. There is no file upload equivalent for Socket.IO and/or WebSocket.

**Comment by abderrahmaneMustapha** [comment]
what im doing is that
1-  i defined a global variable data = {}   
2 - after submitting a form (a post request) i add this file to the data  like this "data = {"file" : request.files['file']}
3 - from my client.js i lunch a socket io event  and this is where  the data['file'] is used

**Comment by miguelgrinberg** [comment]
Okay I understand now. The `FileStorage` object that you get in a POST request is a wrapper for a file handle from where you can read the file. This file handle is closed when the request ends, so you cannot keep a `FileStorage` object past the end of the request in which it was created. What you need to do is save the file in the POST request, and then from the socket event read the file that you saved.

**Comment by abderrahmaneMustapha** [comment]
yup, i  solved this the same way thank you  @miguelgrinberg

**Comment by jack-sparrow-123** [comment]
i cant convert my kivy app to apk using buildozer in workflows when it coming into build apk step showing this errorTraceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/buildozer", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/buildozer/__init__.py", line 1024, in run_command
    self.target.run_commands(args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/buildozer/target.py", line 93, in run_commands
    func(args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/buildozer/target.py", line 103, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/buildozer/__init__.py", line 172, in prepare_for_build
    self.target.install_platform()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/buildozer/targets/android.py", line 615, in install_platform
    self._install_android_ndk()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/buildozer/targets/android.py", line 438, in _install_android_ndk
    self.buildozer.download(url,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/buildozer/__init__.py", line 658, in download
    urlretrieve(url, filename, report_hook)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/urllib/request.py", line 18[55](https://github.com/jack-sparrow-123/spider-invasion/actions/runs/14233787760/job/39889317234#step:8:56), in retrieve
    block = fp.read(bs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/tempfile.py", line 473, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file
Error: Process completed with exit code 1.
