### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by umityayla** [miguelgrinberg/Flask-SocketIO#1352]
Hello, started getting the error down below for a while now. Any idea what is the reason?

```Error handling request /socket.io/?EIO=4&transport=websocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 114, in handle_request
    resp.write(item)
File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 326, in write
  self.send_headers()
File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 318, in send_headers
  tosend = self.default_headers()
File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 299, in default_headers
  elif self.should_close():
File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 219, in should_close
  if self.status_code < 200 or self.status_code in (204, 304):
AttributeError: 'Response' object has no attribute 'status_code'```

**Comment by miguelgrinberg** [comment]
I believe this was an old issue with Gunicorn. Are you using an old version by any chance? Try upgrading it.

**Comment by umityayla** [comment]
Our gunicorn version is 20.0.2

**Comment by umityayla** [comment]
Our Gunicorn version was 20.0.2, upgrading to 20.0.4; will post more if the error continues.

**Comment by umityayla** [comment]
Started getting dozens of critical worker timeouts, rolled back to 20.0.2; don't know why.. I'll research further into that.

**Comment by miguelgrinberg** [comment]
This is all Gunicorn related problems as far as I can see, I don't have any access to that project to fix bugs.
