### ISSUE TITLE
Will not use eventlet server

### ISSUE THREAD

**Issue by boredomdenied** [miguelgrinberg/Flask-SocketIO#1375]
**Describe the bug**
In Windows environment, running a client's app does not succeed when attempting to run in production. I have toyed with this for some hours without success so far. 

1. Installed packages from requirements.txt
2. $env:FLASK_APP = "flaskAppSocket.py"
3. flask run

**Expected behavior**
I expect the websocket to not be pending and to see it using the eventlet webserver. Chrome shows long-polling activated but the websocket is "finished"

**Logs**

```
PS C:\contessa\contessaApp\Modules> flask run
 * Serving Flask app "flaskAppSocket.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Server initialized for eventlet.
eventlet
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
c33c80dc8e274274917943bc45185fca: Sending packet OPEN data {'sid': 'c33c80dc8e274274917943bc45185fca', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
c33c80dc8e274274917943bc45185fca: Sending packet MESSAGE data 0
127.0.0.1 - - [18/Sep/2020 16:58:41] "GET /socket.io/?EIO=3&transport=polling&t=1600466321455-292 HTTP/1.1" 200 -
c33c80dc8e274274917943bc45185fca: Received request to upgrade to websocket
127.0.0.1 - - [18/Sep/2020 16:58:41] "GET /socket.io/?EIO=3&transport=websocket&sid=c33c80dc8e274274917943bc45185fca HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "C:\Program Files\Python38\Lib\site-packages\werkzeug\serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files\Python38\Lib\site-packages\werkzeug\serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\flask_socketio\__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "C:\Program Files\Python38\Lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\socketio\server.py", line 534, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\engineio\server.py", line 375, in handle_request
    packets = socket.handle_get_request(
  File "C:\Program Files\Python38\Lib\site-packages\engineio\socket.py", line 106, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "C:\Program Files\Python38\Lib\site-packages\engineio\socket.py", line 147, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
c33c80dc8e274274917943bc45185fca: Received packet PING data None
c33c80dc8e274274917943bc45185fca: Sending packet PONG data None
127.0.0.1 - - [18/Sep/2020 16:59:06] "POST /socket.io/?EIO=3&transport=polling&t=1600466346473-294&sid=c33c80dc8e274274917943bc45185fca HTTP/1.1" 200 -
c33c80dc8e274274917943bc45185fca: Client is gone, closing socket
127.0.0.1 - - [18/Sep/2020 16:59:41] "GET /socket.io/?EIO=3&transport=polling&t=1600466321474-293&sid=c33c80dc8e274274917943bc45185fca HTTP/1.1" 400 -
Invalid session c33c80dc8e274274917943bc45185fca
127.0.0.1 - - [18/Sep/2020 16:59:41] "POST /socket.io/?EIO=3&transport=polling&t=1600466381495-295&sid=c33c80dc8e274274917943bc45185fca HTTP/1.1" 400 -
35fd104c038f4c4ea13bf23304c1898b: Sending packet OPEN data {'sid': '35fd104c038f4c4ea13bf23304c1898b', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
35fd104c038f4c4ea13bf23304c1898b: Sending packet MESSAGE data 0
127.0.0.1 - - [18/Sep/2020 16:59:42] "GET /socket.io/?EIO=3&transport=polling&t=1600466382083-296 HTTP/1.1" 200 -
35fd104c038f4c4ea13bf23304c1898b: Received request to upgrade to websocket
127.0.0.1 - - [18/Sep/2020 16:59:42] "GET /socket.io/?EIO=3&transport=websocket&sid=35fd104c038f4c4ea13bf23304c1898b HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "C:\Program Files\Python38\Lib\site-packages\werkzeug\serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files\Python38\Lib\site-packages\werkzeug\serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\flask_socketio\__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "C:\Program Files\Python38\Lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\socketio\server.py", line 534, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\engineio\server.py", line 375, in handle_request
    packets = socket.handle_get_request(
  File "C:\Program Files\Python38\Lib\site-packages\engineio\socket.py", line 106, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "C:\Program Files\Python38\Lib\site-packages\engineio\socket.py", line 147, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
35fd104c038f4c4ea13bf23304c1898b: Received packet PING data None
35fd104c038f4c4ea13bf23304c1898b: Sending packet PONG data None
127.0.0.1 - - [18/Sep/2020 17:00:07] "POST /socket.io/?EIO=3&transport=polling&t=1600466407452-298&sid=35fd104c038f4c4ea13bf23304c1898b HTTP/1.1" 200 -

```

Additional Information:

I have:

```
import eventlet
eventlet.monkey_patch
```

At the top of the file.

Here is the first part of my file after imports:

```
# initialize Flask
app = Flask(__name__)

socketio = SocketIO(app, async_mode="eventlet", debug=False, logger=True, engineio_logger=True)

# find which server will be loaded
print(socketio.server.eio.async_mode)
```

**Comment by miguelgrinberg** [comment]
Run the app by calling `socketio.run(app)` in your main script instead of `flask run`.

**Comment by boredomdenied** [comment]
That did the trick. Thank you!
