### ISSUE TITLE
greenlet.error: cannot switch to a different thread (introduced in 0.29.1)

### ISSUE THREAD

**Issue by rakhmerov** [miguelgrinberg/Flask-SocketIO#1397]
Hi,

eventlet 0.29.1 introduces the following issue:

Traceback (most recent call last):
  File "/home/mistral/.local/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 476, in fire_timers
    timer()
  File "/home/mistral/.local/lib/python3.6/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/home/mistral/.local/lib/python3.6/site-packages/eventlet/semaphore.py", line 147, in _do_acquire
    waiter.switch()
greenlet.error: cannot switch to a different thread

We're not sure yet how to reproduce it. It just happens at some point in eventlet.

If we rollback to version 0.29.0 it works fine.

**Comment by miguelgrinberg** [comment]
Have you reported it to them? I'm not part of the eventlet project, I can't really do much about it.

**Comment by rakhmerov** [comment]
Haaah, sorry.. I somehow misplaced it. My apologies.
