### ISSUE TITLE
What is the advantages of using gunicorn ? it doesn't help at all ! it makes the server soo lazy to accept new connections !

### ISSUE THREAD

**Issue by deounix** [miguelgrinberg/Flask-SocketIO#1415]
So what is the advantages of using gunicorn if we always set it to 1 worker due to load balancing algorithm ?
Why shouldn't we run gevent or eventlet itself with nginx ? without gunicorn !

I made simple test to check how many connections can I handle with (eventlet) + (gevent) + (eventlet + gunicorn) + (gevent + gunicorn)

And the best results I get with gevent without the help of (uwsgi or gunciron)

Here's my simple test :

Backend :

```
# coding: utf-8

""" KeyboardInterrupt Replaced with signal library. Default CTRL+C """
import signal; signal.signal(signal.SIGINT, signal.SIG_DFL)

# import eventlet; eventlet.monkey_patch()
from gevent.monkey import patch_all; patch_all()

from flask import Flask
from flask_socketio import SocketIO

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode="gevent")

connected = 0

@socketio.on('connect', namespace='/')
def test_connect():
    global connected
    connected += 1
    print('Connected: ', connected)


@socketio.on('disconnect', namespace='/')
def test_disconnect():
    global connected
    connected -= 1
    print('DisConnected: ', connected)

if __name__ == '__main__':
    socketio.run(app, debug=False)
```

Client :

```
# coding: utf-8

import signal; signal.signal(signal.SIGINT, signal.SIG_DFL)
import threading, socketio

def generator(number_of_clients):
    for x in range(number_of_clients):
        yield socketio.Client()

def threadedClient(client):
    @client.event
    def connect():
        print('Client with sid: {sid!s} connected!'.format(sid=client.sid))

    @client.event
    def disconnect():
        print('Client with sid: {sid!s} dis-connected!'.format(sid=client.sid))
    
    client.connect('http://krython.com:80')
    client.wait()

def start():
    clients = list()

    for client in generator(2500):
        t = threading.Thread(target=threadedClient, args=(client,))
        t.start()

    for client in clients:
        client.join()

if __name__ == "__main__":
    start()

```

With eventlet we must add max_size to define the max connection limit: with single node I get like 1500 connection
With gevent: I get 2500 connection

(eventlet + guncicorn) (gevent +gunicorn) : single worker (400-500) connection

What happen if I run my backend with gunicorn all new connection are refused

```
Exception in thread Thread-2484:
Traceback (most recent call last):
  File "C:\python3.6\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\python3.6\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 21, in threadedClient
    client.connect('http://krython.com:80')
  File "C:\python3.6\lib\site-packages\socketio\client.py", line 270, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Connection refused by the server
```

So my question why shouldn't I use only gevent (running on multiple ports) with nginx load balancing (ip_hash) !
And what is the advantages of using gunicorn if it make my app refusing all new connection ?

**Comment by miguelgrinberg** [comment]
I don't really think it is my job to defend gunicorn, if you don't like it or think it doesn't perform as well, then don't use it, or ask people who is familiar with the internals of that project about your performance concerns.
