### ISSUE TITLE
get clients in room error

### ISSUE THREAD

**Issue by chendongxtu** [miguelgrinberg/Flask-SocketIO#1454]
hi，miguelgrinberg：
    i want to get all of clients in a named room(when a client joined a room or a client left a room). so i used the following code:
    ```python
    log_info = {
        sid: get_user_info(sid)
        for sid, _ in socketio.server.manager.get_participants(namespace, room)
    }

    current_app.logger.info(
        "%s, active users: %d, info: %s",
        assist_info,
        len(log_info),
        json.dumps(log_info, ensure_ascii=False),
    )
  ```
 when i run the project, and let a client join a named room, or left room(when the last client left room, i know the code will remove the room if no client exists). error info as followed:

 ```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 685, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 714, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 284, in _handler
    *args)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 716, in _handle_event
    ret = handler(*args)
  File "/auction-ws-web/websocket/event/auction_event.py", line 83, in join_auction_room
    print_room_info("/auction_car", room_name, assist_info)
  File "/auction-ws-web/websocket/event/impl.py", line 60, in print_room_info
    for sid, _ in socketio.server.manager.get_participants(namespace, room)
  File "/auction-ws-web/websocket/event/impl.py", line 60, in <dictcomp>
    for sid, _ in socketio.server.manager.get_participants(namespace, room)
ValueError: too many values to unpack (expected 2)
Fri Jan  8 11:54:53 2021 <Thread at 0x7f0e6586c508: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7f0e65c132b0>>(<socketio.server.Server object at 0x7f0e65c132b0>, 'd023813013d44e2d8de169332d7185cd', ['join_auction_room', {'room_id': '19481'}], '/auction_car', None)> failed with ValueError

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 685, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 714, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 284, in _handler
    *args)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 716, in _handle_event
    ret = handler(*args)
  File "/auction-ws-web/websocket/event/auction_event.py", line 103, in leave_auction_room
    print_room_info("/auction_car", room_name, assist_info)
  File "/auction-ws-web/websocket/event/impl.py", line 60, in print_room_info
    for sid, _ in socketio.server.manager.get_participants(namespace, room)
  File "/auction-ws-web/websocket/event/impl.py", line 60, in <dictcomp>
    for sid, _ in socketio.server.manager.get_participants(namespace, room)
ValueError: too many values to unpack (expected 2)
Fri Jan  8 11:57:09 2021 <Thread at 0x7f0e6586c638: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7f0e65c132b0>>(<socketio.server.Server object at 0x7f0e65c132b0>, 'd023813013d44e2d8de169332d7185cd', ['leave_auction_room', {'room_id': '19481'}], '/auction_car', None)> failed with ValueError
```
i do not know why it tells me ValueError: too many values to unpack (expected 2). my accepted values is sid and _, just 2.
can you help me ,thanks

**Comment by miguelgrinberg** [comment]
You are accessing methods that are not public. This methods can change at any time and without notice. This particular one has changed recently, so your code may or may not work depending on the version of the python-socketio package that you are using.
