### ISSUE TITLE
Can't emit to server socket using Node.js 'socket.io-client'

### ISSUE THREAD

**Issue by arkostin** [miguelgrinberg/Flask-SocketIO#1455]
I'm running a Node.js client which uses the "socket.io-client" module to connect to a Flask server which uses flask-socketio, here's the code for both:

Client:
```
const io = require('socket.io-client');
const socket = io.connect('http://localhost:8000', { transports: ['websocket']});
socket.emit('hello');
```

Server:
```
from flask import Flask, request
from flask_cors import CORS
from flask_socketio import SocketIO

app = Flask(__name__)
CORS(app)
socketio = SocketIO(app, cors_allowed_origins="*", logger=True, engineio_logger=True)

@socketio.on("connect")
def user_connect():
    print('user connected!')

@socketio.on("hello")
def user_hello():
    print('user hello')

socketio.run(app, port=8000, host="localhost")
```

The server logs 'user connected!' but not the subsequent 'user hello'. I've followed the advice given [here](https://github.com/miguelgrinberg/python-socketio/issues/47) with the same result.

**Logs**

Server:
```
2d2fa11cbe63444dac9ffafe4aef43a6: Sending packet OPEN data {'sid': '2d2fa11cbe63444dac9ffafe4aef43a6', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
user connected!
2d2fa11cbe63444dac9ffafe4aef43a6: Sending packet MESSAGE data 0
2d2fa11cbe63444dac9ffafe4aef43a6: Received request to upgrade to websocket
2d2fa11cbe63444dac9ffafe4aef43a6: Upgrade to websocket successful
2d2fa11cbe63444dac9ffafe4aef43a6: Received packet MESSAGE data 0
user connected!
2d2fa11cbe63444dac9ffafe4aef43a6: Sending packet MESSAGE data 0
```

Client (Deleted some long data transmissions, can provide it if needed):
```
  engine.io-client:socket socket error {"type":"TransportError","description":{"target":{"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]},"_events":{},"_eventsCount":4,"_binaryType":"nodebuffer","_closeCode":1002,"_closeFrameReceived":false,"_closeFrameSent":false,"_closeMessage":"","_closeTimer":null,"_extensions":{"permessage-deflate":{"_maxPayload":104857600,"_options":{"threshold":1024},"_threshold":1024,"_isServer":false,"_deflate":null,"_inflate":{"_writeState":{"0":16282,"1":0},"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":true,"ended":false,"endEmitted":false,"reading":false,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"paused":false,"emitClose":true,"autoDestroy":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]},"_events":{},"_eventsCount":4,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":true,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"allowHalfOpen":true,"_transformState":{"needTransform":true,"transforming":false,"writecb":null,"writechunk":null,"writeencoding":"buffer"},"_hadError":false,"bytesWritten":112,"_handle":{"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]},"buffer":null,"availOutBefore":16282,"availInBefore":0,"inOff":0,"flushFlag":3},"_outBuffer":{"type":"Buffer","data":[48,123,34,  0,0,0,0,0]},"_outOffset":102,"_chunkSize":16384,"_defaultFlushFlag":0,"_finishFlushFlag":4,"_defaultFullFlushFlag":3,"_level":-1,"_strategy":0},"params":{"client_max_window_bits":15}}},"_protocol":"","_readyState":2,"_receiver":{"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":true,"emitClose":true,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]},"_events":{},"_eventsCount":6,"_binaryType":"nodebuffer","_extensions":{"permessage-deflate":{"_maxPayload":104857600,"_options":{"threshold":1024},"_threshold":1024,"_isServer":false,"_deflate":null,"_inflate":{"_writeState":{"0":16282,"1":0},"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":true,"ended":false,"endEmitted":false,"reading":false,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"paused":false,"emitClose":true,"autoDestroy":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]},"_events":{},"_eventsCount":4,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":true,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"allowHalfOpen":true,"_transformState":{"needTransform":true,"transforming":false,"writecb":null,"writechunk":null,"writeencoding":"buffer"},"_hadError":false,"bytesWritten":112,"_handle":{"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]},"buffer":null,"availOutBefore":16282,"availInBefore":0,"inOff":0,"flushFlag":3},"_outBuffer":{"type":"Buffer","data":[EXPUNGED]},"_outOffset":102,"_chunkSize":16384,"_defaultFlushFlag":0,"_finishFlushFlag":4,"_defaultFullFlushFlag":3,"_level":-1,"_strategy":0},"params":{"client_max_window_bits":15}}},"_isServer":false,"_maxPayload":104857600,"_bufferedBytes":0,"_buffers":[],"_compressed":true,"_payloadLength":21,"_fragmented":0,"_masked":false,"_fin":true,"_opcode":8,"_totalPayloadLength":0,"_messageLength":0,"_fragments":[],"_state":4,"_loop":false},"_sender":{"_extensions":{"permessage-deflate":{"_maxPayload":104857600,"_options":{"threshold":1024},"_threshold":1024,"_isServer":false,"_deflate":null,"_inflate":{"_writeState":{"0":16282,"1":0},"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":true,"ended":false,"endEmitted":false,"reading":false,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"paused":false,"emitClose":true,"autoDestroy":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]},"_events":{},"_eventsCount":4,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":true,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"allowHalfOpen":true,"_transformState":{"needTransform":true,"transforming":false,"writecb":null,"writechunk":null,"writeencoding":"buffer"},"_hadError":false,"bytesWritten":112,"_handle":{"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]},"buffer":null,"availOutBefore":16282,"availInBefore":0,"inOff":0,"flushFlag":3},"_outBuffer":{"type":"Buffer","data":[EXPUNGED]},"_outOffset":102,"_chunkSize":16384,"_defaultFlushFlag":0,"_finishFlushFlag":4,"_defaultFullFlushFlag":3,"_level":-1,"_strategy":0},"params":{"client_max_window_bits":15}}},"_socket":{"connecting":false,"_hadError":false,"_handle":{"reading":true,"onconnection":null,"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]}},"_parent":null,"_host":"localhost","_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":true,"ended":false,"endEmitted":false,"reading":false,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"paused":false,"emitClose":false,"autoDestroy":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]},"_events":{"end":[null,null]},"_eventsCount":3,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":{"next":null,"entry":null},"entry":null}},"writable":true,"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null,"parser":null,"_httpMessage":null,"timeout":0},"_firstFragment":true,"_compress":false,"_bufferedBytes":0,"_deflating":false,"_queue":[]},"_socket":{"connecting":false,"_hadError":false,"_handle":{"reading":true,"onconnection":null,"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]}},"_parent":null,"_host":"localhost","_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":true,"ended":false,"endEmitted":false,"reading":false,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"paused":false,"emitClose":false,"autoDestroy":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":{"domain":null,"_events":{},"_eventsCount":3,"members":[]},"_events":{"end":[null,null]},"_eventsCount":3,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":{"next":null,"entry":null},"entry":null}},"writable":true,"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null,"parser":null,"_httpMessage":null,"timeout":0},"_bufferedAmount":0,"_isServer":false,"_redirects":0,"_url":"ws://localhost:8000/socket.io/?EIO=4&transport=websocket","_req":null},"type":"error","message":"Invalid WebSocket frame: invalid status code 25342","error":{}}} +1m
  socket.io-client:manager error { Error: websocket error
    at WS.onError (/home/arkostin/Projects/talk-to-me/talk-to-me-frontend/node_modules/engine.io-client/lib/transport.js:28:17)
    at WebSocket.ws.onerror (/home/arkostin/Projects/talk-to-me/talk-to-me-frontend/node_modules/engine.io-client/lib/transports/websocket.js:111:12)
    at WebSocket.onError (/home/arkostin/Projects/talk-to-me/talk-to-me-frontend/node_modules/ws/lib/event-target.js:140:16)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.EventEmitter.emit (domain.js:448:20)
    at Receiver.receiverOnError (/home/arkostin/Projects/talk-to-me/talk-to-me-frontend/node_modules/ws/lib/websocket.js:805:13)
    at Receiver.emit (events.js:198:13)
    at Receiver.EventEmitter.emit (domain.js:448:20)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
  type: 'TransportError',
  description:
   ErrorEvent {
     target:
      WebSocket {
        domain: [Domain],
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _binaryType: 'nodebuffer',
        _closeCode: 1002,
        _closeFrameReceived: false,
        _closeFrameSent: false,
        _closeMessage: '',
        _closeTimer: null,
        _extensions: [Object],
        _protocol: '',
        _readyState: 2,
        _receiver: [Receiver],
        _sender: [Sender],
        _socket: [Socket],
        _bufferedAmount: 0,
        _isServer: false,
        _redirects: 0,
        _url: 'ws://localhost:8000/socket.io/?EIO=4&transport=websocket',
        _req: null },
     type: 'error',
     message: 'Invalid WebSocket frame: invalid status code 25342',
     error:
      { RangeError: Invalid WebSocket frame: invalid status code 25342
          at Receiver.controlMessage (/home/arkostin/Projects/talk-to-me/talk-to-me-frontend/node_modules/ws/lib/receiver.js:464:18)
          at Receiver.getData (/home/arkostin/Projects/talk-to-me/talk-to-me-frontend/node_modules/ws/lib/receiver.js:350:42)
          at Receiver.startLoop (/home/arkostin/Projects/talk-to-me/talk-to-me-frontend/node_modules/ws/lib/receiver.js:143:22)
          at Receiver._write (/home/arkostin/Projects/talk-to-me/talk-to-me-frontend/node_modules/ws/lib/receiver.js:78:10)
          at doWrite (_stream_writable.js:415:12)
          at writeOrBuffer (_stream_writable.js:399:5)
          at Receiver.Writable.write (_stream_writable.js:299:11)
          at Socket.socketOnData (/home/arkostin/Projects/talk-to-me/talk-to-me-frontend/node_modules/ws/lib/websocket.js:900:35)
          at Socket.emit (events.js:198:13)
          at Socket.EventEmitter.emit (domain.js:466:23) [Symbol(status-code)]: 1002 } } } +1m
  engine.io-client:socket socket close with reason: "transport error" +45ms
  socket.io-client:manager onclose +1ms
  socket.io-client:manager cleanup +0ms
  socket.io-client:socket close (transport error) +1m
  socket.io-client:manager will wait 664ms before reconnect attempt +0ms
  socket.io-client:manager attempting reconnect +666ms
  socket.io-client:manager readyState closed +0ms
  socket.io-client:manager opening http://localhost:8000 +0ms
  engine.io-client:socket creating transport "websocket" +666ms
  engine.io-client:socket options: {"path":"/socket.io/","agent":false,"withCredentials":false,"upgrade":true,"jsonp":true,"timestampParam":"t","rememberUpgrade":false,"rejectUnauthorized":true,"perMessageDeflate":{"threshold":1024},"transportOptions":{},"transports":["websocket"],"hostname":"localhost","secure":false,"port":"8000","query":{"EIO":4,"transport":"websocket"},"socket":{"secure":false,"hostname":"localhost","port":"8000","transports":["websocket"],"readyState":"opening","writeBuffer":[],"prevBufferLen":0,"opts":{"path":"/socket.io/","agent":false,"withCredentials":false,"upgrade":true,"jsonp":true,"timestampParam":"t","rememberUpgrade":false,"rejectUnauthorized":true,"perMessageDeflate":{"threshold":1024},"transportOptions":{},"transports":["websocket"],"hostname":"localhost","secure":false,"port":"8000"},"id":null,"upgrades":null,"pingInterval":null,"pingTimeout":null,"pingTimeoutTimer":null}} +0ms
  engine.io-client:socket setting transport websocket +0ms
  socket.io-client:manager connect attempt will timeout after 20000 +0ms
  engine.io-client:socket socket receive: type "open", data "{"sid":"5c78d6c9fe6745a7a9f8dacee3c3aed4","upgrades":[],"pingTimeout":60000,"pingInterval":25000}" +2ms
  engine.io-client:socket socket open +0ms
  socket.io-client:manager open +2ms
  socket.io-client:manager cleanup +0ms
  socket.io-client:socket transport is open - connecting +668ms
  socket.io-client:manager writing packet {"type":0,"nsp":"/"} +0ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +1m
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +0ms
  engine.io-client:socket flushing 1 packets in socket +0ms
  socket.io-client:manager reconnect success +0ms
  engine.io-client:socket socket receive: type "message", data "0" +0ms
  socket.io-parser decoded 0 as {"type":0,"nsp":"/"} +0ms
  engine.io-client:socket socket receive: type "message", data "0" +0ms
  socket.io-parser decoded 0 as {"type":0,"nsp":"/"} +1ms
```

Any ideas or suggestions on how to debug this?

**Comment by miguelgrinberg** [comment]
Check the version compatibility table in the docs and make sure the versions of client and server that you are using are compatible.

**Comment by arkostin** [comment]
Thank you for the tip, I was using socket.io-client v3.0.5, which was incompatible with flask.socketio v4.3.1. Switched socket.io-client to v2.4.0, and it worked like a charm!

**Comment by JAckZ97** [comment]
> Thank you for the tip, I was using socket.io-client v3.0.5, which was incompatible with flask.socketio v4.3.1. Switched socket.io-client to v2.4.0, and it worked like a charm!

You save my life bro, bravo!!!
