### ISSUE TITLE
Can't fix error “RuntimeError: You need to use the gevent-websocket server.” and “OSError: write error”

### ISSUE THREAD

**Issue by Yasha261998** [miguelgrinberg/Flask-SocketIO#1487]
**Your question**
I am writing a website for Flask. I use a bunch of uWSGI + NGINX + Flask-Socketio. I use gevent as an asynchronous module. 

**How can I fix the error in the logs?**

I tried different configurations and also removed the async_mode='gevent' from the socketio initialization.  
wsgi.py file:

```
from webapp import app, socketio

if __name__ == '__main__':
    socketio.run(app, use_reloader=False, debug=True, log_output=True)
```

project.ini:

```
[uwsgi]
module = wsgi:app
master = true
gevent = 1024
gevent-monkey-patch = true
buffer-size=32768 # optionally
socket = /home/sammy/projectnew/projectnew.sock
socket-timeout = 240
chmod-socket = 664
vacuum = true
die-on-term = true

```

webapp/__init__.py for application app:

```
from gevent import monkey

monkey.patch_all()
import grpc.experimental.gevent

grpc.experimental.gevent.init_gevent()

from flask import Flask, session, request
from config import DevelopConfig, MqttConfig, MailConfig, ProductionConfig
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_mail import Mail
from flask_script import Manager
from flask_socketio import SocketIO
# from flask_mqtt import Mqtt
from flask_login import LoginManager
from flask_babel import Babel
from flask_babel_js import BabelJS
from flask_babel import lazy_gettext as _l
from apscheduler.schedulers.gevent import GeventScheduler
# from celery import Celery


app = Flask(__name__)
app.config.from_object(ProductionConfig)     
app.config.from_object(MqttConfig)        
app.config.from_object(MailConfig)         
db = SQLAlchemy(app)
migrate = Migrate(app, db)
mail = Mail(app)
manager = Manager(app, db)
login_manager = LoginManager(app)
login_manager.login_view = 'auth'    
login_manager.login_message = _l("Необходимо авторизоваться для доступа к закрытой странице")
login_manager.login_message_category = "error"
# celery = Celery(app.name, broker=Config.CELERY_BROKER_URL)
# celery.conf.update(app.config)
scheduler = GeventScheduler()
# socketio = SocketIO(app) - Production Version
socketio = SocketIO(app, async_mode='gevent')
babel = Babel(app)
babeljs = BabelJS(app=app, view_path='/translations/')
import webapp.views


@babel.localeselector
def get_locale():
    # if the user has set up the language manually it will be stored in the session,
    # so we use the locale from the user settings
    try:
        language = session['language']
    except KeyError:
        language = None
    if language is not None:
        print(language)
        return language
    return request.accept_languages.best_match(app.config['LANGUAGES'].keys())


from webapp import models

if __name__ == "__main__":
    manager.run()
```
**Logs**

Errors occur during operation:

```
 Traceback (most recent call last):
Feb 23 13:46:07 toaa uwsgi[558436]:   File "/home/sammy/projectnew/projectenv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
Feb 23 13:46:07 toaa uwsgi[558436]:     return self.wsgi_app(environ, start_response)
Feb 23 13:46:07 toaa uwsgi[558436]:   File "/home/sammy/projectnew/projectenv/lib/python3.8/site-packages/flask_socketio/__init__.py", line 45, in __cal>
Feb 23 13:46:07 toaa uwsgi[558436]:     return super(_SocketIOMiddleware, self).__call__(environ,
Feb 23 13:46:07 toaa uwsgi[558436]:   File "/home/sammy/projectnew/projectenv/lib/python3.8/site-packages/engineio/middleware.py", line 60, in __call__
Feb 23 13:46:07 toaa uwsgi[558436]:     return self.engineio_app.handle_request(environ, start_response)
Feb 23 13:46:07 toaa uwsgi[558436]:   File "/home/sammy/projectnew/projectenv/lib/python3.8/site-packages/socketio/server.py", line 571, in handle_reque>
Feb 23 13:46:07 toaa uwsgi[558436]:     return self.eio.handle_request(environ, start_response)
Feb 23 13:46:07 toaa uwsgi[558436]:   File "/home/sammy/projectnew/projectenv/lib/python3.8/site-packages/engineio/server.py", line 392, in handle_reque>
Feb 23 13:46:07 toaa uwsgi[558436]:     packets = socket.handle_get_request(
Feb 23 13:46:07 toaa uwsgi[558436]:   File "/home/sammy/projectnew/projectenv/lib/python3.8/site-packages/engineio/socket.py", line 103, in handle_get_r>
Feb 23 13:46:07 toaa uwsgi[558436]:     return getattr(self, '_upgrade_' + transport)(environ,
Feb 23 13:46:07 toaa uwsgi[558436]:   File "/home/sammy/projectnew/projectenv/lib/python3.8/site-packages/engineio/socket.py", line 158, in _upgrade_web>
Feb 23 13:46:07 toaa uwsgi[558436]:     return ws(environ, start_response)
Feb 23 13:46:07 toaa uwsgi[558436]:   File "/home/sammy/projectnew/projectenv/lib/python3.8/site-packages/engineio/async_drivers/gevent.py", line 35, in>
Feb 23 13:46:07 toaa uwsgi[558436]:     raise RuntimeError('You need to use the gevent-websocket server. '
Feb 23 13:46:07 toaa uwsgi[558436]: RuntimeError: You need to use the gevent-websocket server. See the Deployment section of the documentation for more >
Feb 23 13:46:07 toaa uwsgi[558436]: [pid: 558436|app: 0|req: 500/499] 176.105.207.105 () {52 vars in 1274 bytes} [Tue Feb 23 13:46:07 2021] GET /socket.>
Feb 23 13:46:07 toaa uwsgi[558436]: [pid: 558436|app: 0|req: 501/500] 176.105.207.105 () {44 vars in 1100 bytes} [Tue Feb 23 13:46:07 2021] GET /socket.>
Feb 23 13:46:09 toaa uwsgi[558436]: [pid: 558436|app: 0|req: 502/501] 176.105.207.105 () {44 vars in 1100 bytes} [Tue Feb 23 13:46:07 2021] GET /socket.>
Feb 23 13:46:10 toaa uwsgi[558436]: load user
Feb 23 13:46:10 toaa uwsgi[558436]: [pid: 558436|app: 0|req: 504/502] 176.105.207.105 () {46 vars in 1085 bytes} [Tue Feb 23 13:46:10 2021] GET /static/>
Feb 23 13:46:11 toaa uwsgi[558436]: Tue Feb 23 13:46:11 2021 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during >
Feb 23 13:46:11 toaa uwsgi[558436]: OSError: write error
```

**Comment by miguelgrinberg** [comment]
You specified gevent as your async mode, but you are using uwsgi, which has its own flavor of gevent. Either remove the `async_mode` argument, or set it to the correct value which is `gevent_uwsgi`.

**Comment by Yasha261998** [comment]
Thank`s! It works.
