### ISSUE TITLE
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers. when socketio is imported

### ISSUE THREAD

**Issue by yananet** [miguelgrinberg/Flask-SocketIO#1491]
**Describe the bug**
Unable to import socketio.

**To Reproduce**
1. install Arch Linux
2. Install python
3. Install virtualenv
4. create venv
5. pip install flask-socketio
6. enable virtualenv
7. import socketio

**Expected behavior**
It should be imported without any error.

**Logs**
```
(venv) [yananet@vmarch]: ~/venv>$ python
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask_socketio import SocketIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yananet/venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "/home/yananet/venv/lib/python3.9/site-packages/socketio/__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "/home/yananet/venv/lib/python3.9/site-packages/socketio/zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "/home/yananet/venv/lib/python3.9/site-packages/eventlet/__init__.py", line 10, in <module>
    from eventlet import convenience
  File "/home/yananet/venv/lib/python3.9/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/home/yananet/venv/lib/python3.9/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/home/yananet/venv/lib/python3.9/site-packages/eventlet/support/greendns.py", line 399, in <module>
    resolver = ResolverProxy(hosts_resolver=HostsResolver())
  File "/home/yananet/venv/lib/python3.9/site-packages/eventlet/support/greendns.py", line 313, in __init__
    self.clear()
  File "/home/yananet/venv/lib/python3.9/site-packages/eventlet/support/greendns.py", line 316, in clear
    self._resolver = dns.resolver.Resolver(filename=self._filename)
  File "/home/yananet/venv/lib/python3.9/site-packages/dns/resolver.py", line 734, in __init__
    self.read_resolv_conf(filename)
  File "/home/yananet/venv/lib/python3.9/site-packages/dns/resolver.py", line 826, in read_resolv_conf
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
>>> 

```

**Additional context**
requirements.txt
```
flask==0.12.*
redis==2.10.*
python-socketio==5.0.*
requests==2.18.*
eventlet==0.25.*
Flask-SocketIO==5.0
```

**Comment by yananet** [comment]
Sorry, let me close this.
This is because of the old dependencies.
Fixed with below.
```
redis==3.5.*
requests==2.25.*
eventlet==0.30.*
Flask-SocketIO==5.0.*
```
