### ISSUE TITLE
SocketIO fails to start in a thread (ValueError: signal only works in main thread)

### ISSUE THREAD

**Issue by wsw70** [miguelgrinberg/Flask-SocketIO#1494]
**Describe the bug**

SocketIO fails to start in a thread with error `ValueError: signal only works in main thread`

**To Reproduce**

```
import threading
import flask
import flask_socketio

class Web:

    def websocket(self):
        ws = flask.Flask('web')
        ws.config['SECRET_KEY'] = 'aaa'
        socketio = flask_socketio.SocketIO(ws)
        self.log.info("starting websocket server")
        socketio.run(ws, port=6543, debug=True)

    @flask_socketio.SocketIO.event
    def on_message(self, data):
        print(f"event: {data}")

if __name__ == "__main__":
    web = Web()
    # start the websocket
    threading.Thread(target=web.websocket).run()
```

**Expected behavior**

The websocket server starts on port `6543` and handles incoming messages via `on_message`

**Logs**

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:/Nextcloud/dev-perso/note/note_web.py", line 34, in websocket
    socketio.run(ws, port=6543, debug=True)
  File "C:\Python38\lib\site-packages\flask_socketio\__init__.py", line 619, in run
    run_with_reloader(run_server, extra_files=extra_files)
  File "C:\Python38\lib\site-packages\werkzeug\serving.py", line 1060, in run_with_reloader
    return run_with_reloader(*args, **kwargs)
  File "C:\Python38\lib\site-packages\werkzeug\_reloader.py", line 330, in run_with_reloader
    signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
  File "C:\Python38\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

```

**Comment by miguelgrinberg** [comment]
This is a Flask and Werkzeug error, nothing to do with this project. Try running your server with `debug=False`, or at least with the reloader disabled.

**Comment by wsw70** [comment]
Thank you and sorry for the disturbance.
I will try your suggestion.
