### ISSUE TITLE
KeyError: 'Session is disconnected'

### ISSUE THREAD

**Issue by tsoernes** [miguelgrinberg/Flask-SocketIO#1522]
I have an API where socketio is initialized as such:
```
socketio = SocketIO(
    app,
    cors_allowed_origins="*",
    async_mode="threading",
    logger=True,
    engineio_logger=True,
    message_queue="redis://",
    async_handlers=True,
)
```
And the workers, in separate processes, are initialized as such:
```
            self.socketio = SocketIO(
                cors_allowed_origins="*",
                logger=False,
                engineio_logger=False,
                message_queue="redis://",
                async_handlers=True,
            )
```
After a while, with only 1 client, I get:
```
Traceback (most recent call last):
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/flask_socketio/__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/engineio/middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/socketio/server.py", line 571, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/engineio/server.py", line 410, in handle_request
    socket = self._get_socket(sid)
  File "/home/torstein/anaconda3/lib/python3.8/site-packages/engineio/server.py", line 612, in _get_socket
    raise KeyError('Session is disconnected')

```

Log:
https://gist.github.com/tsoernes/5733f4f8a8fac746fcad69123c87153c

Versions:
```
pip install --upgrade --upgrade-strategy eager flask flask-socketio python-socketio python-engineio flask-cors
Requirement already satisfied: flask in /home/torstein/anaconda3/lib/python3.8/site-packages (1.1.2)
^[Requirement already satisfied: flask-socketio in /home/torstein/anaconda3/lib/python3.8/site-packages (5.0.1)
Requirement already satisfied: python-socketio in /home/torstein/anaconda3/lib/python3.8/site-packages (5.1.0)
Requirement already satisfied: python-engineio in /home/torstein/anaconda3/lib/python3.8/site-packages (4.0.1)
Requirement already satisfied: flask-cors in /home/torstein/anaconda3/lib/python3.8/site-packages (3.0.10)
Requirement already satisfied: Werkzeug>=0.15 in /home/torstein/anaconda3/lib/python3.8/site-packages (from flask) (1.0.1)
Requirement already satisfied: Jinja2>=2.10.1 in /home/torstein/anaconda3/lib/python3.8/site-packages (from flask) (2.11.3)
Requirement already satisfied: click>=5.1 in /home/torstein/anaconda3/lib/python3.8/site-packages (from flask) (7.1.2)
Requirement already satisfied: itsdangerous>=0.24 in /home/torstein/anaconda3/lib/python3.8/site-packages (from flask) (1.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/torstein/anaconda3/lib/python3.8/site-packages (from Jinja2>=2.10.1->flask) (1.1.1)
Requirement already satisfied: Six in /home/torstein/anaconda3/lib/python3.8/site-packages (from flask-cors) (1.15.0)
Requirement already satisfied: bidict>=0.21.0 in /home/torstein/anaconda3/lib/python3.8/site-packages (from python-socketio) (0.21.2)
```

**Comment by miguelgrinberg** [comment]
Your client does not appear to be communicating promptly. The server sends a periodic PING packet to each client. You can find these in the log:

```
R9rBKCfZLgUsddWLAAAC: Sending packet PING data None
```

Note how the last PING packet wasn't answered by the server. So the server decided the client wasn't responsive and ended it:

```
R9rBKCfZLgUsddWLAAAC: Client is gone, closing socket
```

And then shortly after the client tried to continue the connection as if nothing happened. This is when the session is disconnected error is logged. You need to figure out why the client is not responsive to PINGs.

**Comment by tsoernes** [comment]
Thank you for that information.

I have enabled debugging in the SocketIO webclient, by setting `localStorage.debug = '*';` and then refreshing the page, but nothing is reported from the SocketIO library. 

The API is pretty simple - a query is sent to the server, which then replies, multiple times, over the course of minutes, with results. When the server has sent all its replies, it emits `results_finished` and the client moves on to the next query. I have no idea what would make the client not respond.

The client code is just a minimum viable demo, https://gist.github.com/tsoernes/4d94870865a3080026b1ef98b4fc35bc

**Comment by miguelgrinberg** [comment]
If the client is a standard JS client then I think it is unlikely that this is a client problem. There is another possibility, which is that the client did respond to the PING packet, but the server was blocked or too busy doing something else and was unable to process the PONG response in time.

You may want to try setting the `pingTimeout` option in the server to something longer than 5 seconds. The reference JS server changed this value from 5 to 20 just a few days ago, so I was going to make the same change. Try that and see if that helps.

**Comment by tsoernes** [comment]
That worked! thank you.
