### ISSUE TITLE
Worker not receiving an acknowledgement from client via redis although it's received by backend and published to redis

### ISSUE THREAD

**Issue by antoinert** [miguelgrinberg/Flask-SocketIO#1533]
Hello!

In my setup I have
- flask backend
- flask worker via Redis MQ with flask-RQ2
- javascript client

I'm attempting to halt my worker until it receives an acknowledgement from the client. However, for some reason the acknowledgement does not get back to the worker. From logs I can see that client receives the event and sends an ack back and then backend publishes it to redis but worker does not notice it. Eventually the `call()` in worker times out.

Each job emits events to a client via a room where the client joins. 

Any tips? Below you can find sample code and logs.

Backend code
```python
socketio = SocketIO(
    app,
    cors_allowed_origins=app.config['CORS_ORIGINS'],
    message_queue='redis://redis',
    logger=app.logger,
    engineio_logger=app.logger,
)

@socketio.on('connect')
def on_connect():
    job_id = request.args.get('job')
    join_room(job_id)
    socketio.emit('backend', {'data': f'Connected to room {job_id}'})
```
Worker code
```python
socketio = SocketIO(
    message_queue='redis://redis',
    logger=logger,
    engineio_logger=logger
)

@rq.job
def job(...):
    # do stuff

    # problem is that this call times out even though client acks it
    socketio.server.call('hello', timeout=5, to=job_id)

    # do stuff...
```
Client
```js
client.on('hello', (callback: (data: string) => void) => {
    callback('ACK');
});
```
**Logs**
```
backend_1  | INFO:app:P021wWvox66xcrjYAABq: Sending packet OPEN data {'sid': 'P021wWvox66xcrjYAABq', 'upgrades': [], 'pingTimeout': 20000, 'pingInterval': 25000}
backend_1  | INFO:app:P021wWvox66xcrjYAABq: Received packet MESSAGE data 0
backend_1  | INFO:app:YIcViNvSyeiKZP5wAABr is entering room 119eb333-ecc0-4323-8d4b-2e4ac3e9bb31 [/]
backend_1  | INFO:app:emitting event "backend" to all [/]
backend_1  | INFO:app:pubsub message: emit
backend_1  | INFO:app:P021wWvox66xcrjYAABq: Sending packet MESSAGE data 2["backend",{"data":"Connected to room 119eb333-ecc0-4323-8d4b-2e4ac3e9bb31"}]
backend_1  | INFO:app:P021wWvox66xcrjYAABq: Sending packet MESSAGE data 0{"sid":"YIcViNvSyeiKZP5wAABr"}
worker_1  | 17:50:29 Server initialized for eventlet.
worker_1  | 17:50:30 emitting event "hello" to 119eb333-ecc0-4323-8d4b-2e4ac3e9bb31 [/]
backend_1  | INFO:app:pubsub message: emit
backend_1  | INFO:app:P021wWvox66xcrjYAABq: Sending packet MESSAGE data 21["hello"]
backend_1  | INFO:app:P021wWvox66xcrjYAABq: Received packet MESSAGE data 31["ACK"]
backend_1  | INFO:app:received ack from YIcViNvSyeiKZP5wAABr [/]
backend_1  | INFO:app:pubsub message: callback
worker_1  | 17:50:35 Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.9/site-packages/rq/worker.py", line 1008, in perform_job
worker_1  |     rv = job.perform()
worker_1  |   File "/usr/local/lib/python3.9/site-packages/rq/job.py", line 706, in perform
worker_1  |     self._result = self._execute()
worker_1  |   File "/usr/local/lib/python3.9/site-packages/rq/job.py", line 729, in _execute
worker_1  |     result = self.func(*self.args, **self.kwargs)
worker_1  |   File "./worker.py", line 68, in run_card
worker_1  |     socketio.server.call('hello', timeout=5, to=job_id)
worker_1  |   File "/usr/local/lib/python3.9/site-packages/socketio/server.py", line 384, in call
worker_1  |     raise exceptions.TimeoutError()
worker_1  | socketio.exceptions.TimeoutError
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.9/site-packages/rq/worker.py", line 1008, in perform_job
worker_1  |     rv = job.perform()
worker_1  |   File "/usr/local/lib/python3.9/site-packages/rq/job.py", line 706, in perform
worker_1  |     self._result = self._execute()
worker_1  |   File "/usr/local/lib/python3.9/site-packages/rq/job.py", line 729, in _execute
worker_1  |     result = self.func(*self.args, **self.kwargs)
worker_1  |   File "./worker.py", line 68, in run_card
worker_1  |     socketio.server.call('hello', timeout=5, to=job_id)
worker_1  |   File "/usr/local/lib/python3.9/site-packages/socketio/server.py", line 384, in call
worker_1  |     raise exceptions.TimeoutError()
worker_1  | socketio.exceptions.TimeoutError
```

**Comment by miguelgrinberg** [comment]
You are calling `socketio.server.call()` in your worker. Where does that come from? I doubt that will work, you are calling a method that was designed to run on the server. The `call()` method was never implemented in Flask-SocketIO. It might work on the server, but not on an auxiliary process. I suggest you switch to use `emit()` with callback.

**Comment by antoinert** [comment]
Thanks for the quick reply!

Even if I use `emit()`, the ack doesn't seem to reach the worker.
Worker
```python
socketio = SocketIO(
    message_queue='redis://redis',
    logger=logger,
    engineio_logger=logger
)

@rq.job
def job(...):
    # do stuff

    # ack callback is never executed
    def cb():
        logger.info("ACK")

    socketio.emit("hello", callback=cb, room=job_id)

    # do stuff...
```
Logs
```
backend_1  | INFO:app:Vp3YgzvXh0H0Kv9iAAAa: Sending packet OPEN data {'sid': 'Vp3YgzvXh0H0Kv9iAAAa', 'upgrades': [], 'pingTimeout': 20000, 'pingInterval': 25000}
backend_1  | INFO:app:Vp3YgzvXh0H0Kv9iAAAa: Received packet MESSAGE data 0
backend_1  | INFO:app:5-zaQgpy6zhnc6pWAAAb is entering room 8b194a10-e593-49da-90c4-fc73f4bef367 [/]
backend_1  | INFO:app:emitting event "backend" to all [/]
backend_1  | INFO:app:Vp3YgzvXh0H0Kv9iAAAa: Sending packet MESSAGE data 0{"sid":"5-zaQgpy6zhnc6pWAAAb"}
backend_1  | INFO:app:pubsub message: emit
backend_1  | INFO:app:Vp3YgzvXh0H0Kv9iAAAa: Sending packet MESSAGE data 2["backend",{"data":"Connected to room 8b194a10-e593-49da-90c4-fc73f4bef367"}]
worker_1  | 10:57:12 Server initialized for eventlet.
worker_1  | 10:57:14 emitting event "hello" to 8b194a10-e593-49da-90c4-fc73f4bef367 [/]
backend_1  | INFO:app:pubsub message: emit
backend_1  | INFO:app:Vp3YgzvXh0H0Kv9iAAAa: Sending packet MESSAGE data 21["hello"]
backend_1  | INFO:app:Vp3YgzvXh0H0Kv9iAAAa: Received packet MESSAGE data 31["ACK"]
backend_1  | INFO:app:received ack from 5-zaQgpy6zhnc6pWAAAb [/]
backend_1  | INFO:app:pubsub message: callback
worker_1  | 10:57:14 emitting event "output" to 8b194a10-e593-49da-90c4-fc73f4bef367 [/]
backend_1  | INFO:app:pubsub message: emit
backend_1  | INFO:app:Vp3YgzvXh0H0Kv9iAAAa: Sending packet MESSAGE data 2["output",{"data":"\n"}]
worker_1  | 10:57:14 emitting event "end_output" to 8b194a10-e593-49da-90c4-fc73f4bef367 [/]
worker_1  | 10:57:14 run successful
backend_1  | INFO:app:pubsub message: emit
backend_1  | INFO:app:Vp3YgzvXh0H0Kv9iAAAa: Sending packet MESSAGE data 2["end_output"]
worker_1  | 10:57:14 default: Job OK (8b194a10-e593-49da-90c4-fc73f4bef367)
worker_1  | 10:57:14 Result is kept for 500 seconds
backend_1  | INFO:app:Vp3YgzvXh0H0Kv9iAAAa: Received packet MESSAGE data 1
backend_1  | INFO:app:Vp3YgzvXh0H0Kv9iAAAa: Received packet CLOSE data 
```

I also tried looping a while to wait for the ack but it doesn't seem to arrive.

Now I guess my main question is that should the acks work through a message queue in a normal situation?

**Comment by miguelgrinberg** [comment]
Okay, after reviewing the implementation one more time I now recall that the workers have a limited participation in the message queue dialog, they only write to it, so yes, the callback does get to the server, but there is currently no mechanism for the callback to make it to the worker, which is not reading the queue.

I'll think about this. In the short term it is likely that this is going to be noted in the documentation as a limitation. The use of an external worker made sense long ago when there was no Python client, but now that the client exists you can get a lot of the same functionality and more by connecting your worker as a client.

**Comment by antoinert** [comment]
@miguelgrinberg thanks for the confirmation 🙂 

I have for now resolved this another way so all good here.
