### ISSUE TITLE
NameError: name 'has_key' is not defined

### ISSUE THREAD

**Issue by Falcn8** [miguelgrinberg/Flask-SocketIO#1541]
**My question**
I don't know why it's returning this error...

**My Code**
`app.py`
```python
from flask import Flask, render_template
from flask_socketio import SocketIO, emit
    
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@app.route('/')
def index():
    return render_template('index.html')

@socketio.on('connect')
def app_connect():
    print('A client connected')

@socketio.on('disconnect')
def app_disconnect():
    print('A client disconnected')

if __name__ == '__main__':
    socketio.run(app, port=1234)
``` 

`index.html`
```html
<html>
    <body>
        <h1>index it is</h1>
    </body>
</html>
``` 

**Logs**
```Traceback (most recent call last):
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\curses\__init__.py", line 54, in <module>
    has_key
NameError: name 'has_key' is not defined
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "c:\Users\e\Desktop\Programming\PyExample\flasksocketio\app.py", line 2, in <module>
    from flask_socketio import SocketIO, emit
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_socketio\__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\socketio\__init__.py", line 3, in <module>
    from .client import Client
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\socketio\client.py", line 7, in <module>
    import engineio
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\engineio\__init__.py", line 11, in <module>
    from .async_drivers.tornado import get_tornado_handler
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\engineio\async_drivers\tornado.py", line 6, in <module>
    import tornado.web
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\web.py", line 84, in <module>
    from tornado.concurrent import Future, future_set_result_unless_cancelled
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\concurrent.py", line 34, in <module>
    from tornado.log import app_log
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\log.py", line 43, in <module>
    import curses
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\curses\__init__.py", line 56, in <module>
    from .has_key import has_key
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\curses\has_key.py", line 11, in <module>
    curses.KEY_A1: 'ka1',
AttributeError: partially initialized module 'curses' has no attribute 'KEY_A1' (most likely due to a circular import)
```

**Comment by miguelgrinberg** [comment]
This is unrelated to Socket.IO. You seem to have a problem between Tornado and the curses package of the standard library.

**Comment by miguelgrinberg** [comment]
I don't really know, sorry. Try regenerating your virtualenv from scratch, maybe that'll help.

**Comment by Falcn8** [comment]
I commented out lines `53`, `54`, `55`, and `56` in `C:\Users\e\AppData\Local\Programs\Python\Python38\Lib\curses\__init__.py` and the error doesn't pop out now. But I feel like I broke something... 
And the socket.io isn't working now.
