### ISSUE TITLE
request.namespace; 'str' object has no attribute 'socket'

### ISSUE THREAD

**Issue by njdart** [miguelgrinberg/Flask-SocketIO#165]
Following this gist https://gist.github.com/ericremoreynolds/dbea9361a97179379f3b, i am trying to save a list of connected clients, however I am getting the following exception when using request.namespace.socket...

    Traceback (most recent call last):
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
        self.run_application()
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/geventwebsocket/handler.py", line 88, in run_application
        return super(WebSocketHandler, self).run_application()
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
        self.result = self.application(self.environ, self.start_response)
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
        return self.engineio_app.handle_request(environ, start_response)
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/socketio/server.py", line 301, in handle_request
        return self.eio.handle_request(environ, start_response)
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/engineio/server.py", line 238, in handle_request
        socket.handle_post_request(environ)
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/engineio/socket.py", line 92, in handle_post_request
        self.receive(pkt)
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/engineio/socket.py", line 45, in receive
        self.server._trigger_event('message', self.sid, pkt.data)
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/engineio/server.py", line 302, in _trigger_event
        return self.handlers[event](*args)
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/socketio/server.py", line 418, in _handle_eio_message
        self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/socketio/server.py", line 359, in _handle_event
        r = self._trigger_event(data[0], namespace, sid, *data[1:])
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/socketio/server.py", line 386, in _trigger_event
        return self.handlers[namespace][event](*args)
      File "/home/nic/testing/pySockets/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 120, in _handler
        ret = handler(*args)
      File "test.py", line 15, in connected
        print "%s connected" % (request.namespace.socket.sessid)
    AttributeError: 'str' object has no attribute 'socket'
    {'CONTENT_LENGTH': '18',
     'CONTENT_TYPE': 'text/plain;charset=UTF-8',
     'GATEWAY_INTERFACE': 'CGI/1.1',
     'HTTP_ACCEPT': '*/*',
     'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
     'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,en-GB;q=0.6,cy;q=0.4',
     'HTTP_CONNECTION': 'keep-alive',
     'HTTP_COOKIE': 'io=35c767380188441d9a3e6f95b7d74034',
     'HTTP_HOST': '127.0.0.1:5000',
     'HTTP_ORIGIN': 'http://127.0.0.1:5000',
     'HTTP_REFERER': 'http://127.0.0.1:5000/',
     'HTTP_USER_AGENT': 'Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53',
     'HTTP_X_FIREPHP_VERSION': '0.0.6',
     'PATH_INFO': '/socket.io/',
     'QUERY_STRING': 'EIO=3&transport=polling&t=1445939061044-337&sid=35c767380188441d9a3e6f95b7d74034',
     'REMOTE_ADDR': '127.0.0.1',
     'REMOTE_PORT': '37404',
     'REQUEST_METHOD': 'POST',
     'SCRIPT_NAME': '',
     'SERVER_NAME': 'localhost.localdomain',
     'SERVER_PORT': '5000',
     'SERVER_PROTOCOL': 'HTTP/1.1',
     'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
     'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f190043e1e0>,
     'wsgi.input': <gevent.pywsgi.Input object at 0x7f18f9b40b50>,
     'wsgi.multiprocess': False,
     'wsgi.multithread': False,
     'wsgi.run_once': False,
     'wsgi.url_scheme': 'http',
     'wsgi.version': (1, 0)} failed with AttributeError

And printing request.socket simply yields ``/``
Is this feature no longer available, or am I missing something?

Thanks

**Comment by miguelgrinberg** [comment]
@njdart this code you are using was written for Flask-SocketIO v0.6. I'm guessing you are using it with one of the v1.0 beta versions, correct?

The 1.0 release changes some things. See the [documentation](https://github.com/miguelgrinberg/Flask-SocketIO/blob/v1.0/docs/index.rst#upgrading-to-flask-socketio-1x-from-older-releases) as a reference. In particular, any use of internal structures of project gevent-socketio do not work in the 1.x releases, since this project has been dropped and replaced as a dependency.

**Comment by njdart** [comment]
@miguelgrinberg  Thanks for the speedy reply, the documentation says that ``request.namespace.rooms`` be replaced with a call to ``rooms()``, is there a similar replacement for ``request.namespace.socket``.

Failing that. I recall a client is automatically put into a room of it's sid, can then broadcast to that room to target the specific client on an event from another client?

Thanks

**Comment by miguelgrinberg** [comment]
@njdart It's not `socket` that this example uses, it's `socket.sessid`, the session identifier. In the 1.x releases you can get the session id as `request.sid`.

You will also need to change how the `clients` array is generated. You can put the session id in the array, as there is no equivalent to the `request.namespace` object in 1.x. Then in [this line](https://gist.github.com/ericremoreynolds/dbea9361a97179379f3b#file-server-py-L29) you can use `socket.emit()`, and add the argument `room=session_id` to address the message to a specific client.

**Comment by njdart** [comment]
Excellent, that's working. Thanks
