### ISSUE TITLE
gevent_uwsgi import/support bug

### ISSUE THREAD

**Issue by johaven** [miguelgrinberg/Flask-SocketIO#1681]
**Versions**
- python
Flask-SocketIO      5.1.1
python-socketio     5.4.0
python-engineio     4.2.1
- js
socket.io-client@4.2.0

From documentation gevent_uwsgi can be used as async_mode but:

```python
raceback (most recent call last):
  File "/Web/./webapp/__init__.py", line 34, in <module>
    socketio = SocketIO(app, async_mode='gevent_uwsgi', client_manager=client_manager, json=json, cookie=None, logger=True, engineio_logger=False)
  File "/Web/venv/lib/python3.8/site-packages/flask_socketio/__init__.py", line 187, in __init__
    self.init_app(app, **kwargs)
  File "/Web/venv/lib/python3.8/site-packages/flask_socketio/__init__.py", line 243, in init_app
    self.server = socketio.Server(**self.server_options)
  File "/Web/venv/lib/python3.8/site-packages/socketio/server.py", line 127, in __init__
    self.eio = self._engineio_server_class()(**engineio_options)
  File "/Web/venv/lib/python3.8/site-packages/engineio/server.py", line 145, in __init__
    raise ValueError('Invalid async_mode specified')
ValueError: Invalid async_mode specified
```

**Comment by johaven** [comment]
I use uWSGI and gevent but it's the 'gevent' async driver which is selected -> "**Server initialized for gevent.**"

```python
uWSGI http bound on :5000 fd 6
uwsgi socket 0 bound to TCP address 127.0.0.1:51896 (port auto-assigned) fd 4
Python version: 3.8.11 (default, Jun 29 2021, 03:08:07)  [Clang 12.0.5 (clang-1205.0.22.9)]
Python main interpreter initialized at 0x7fe1aac061b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 10 seconds
mapped 36068428 bytes (35223 KB) for 250 cores
*** Operational MODE: async ***
Server initialized for gevent.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7fe1aac061b0 pid: 4111 (default app)
gracefully (RE)spawned uWSGI master process (pid: 4111)
spawned uWSGI worker 1 (pid: 4133, cores: 250)
cache sweeper thread enabled
spawned uWSGI mule 1 (pid: 4134)
spawned uWSGI http 1 (pid: 4135)
spawned 8 offload threads for uWSGI worker 1
*** running gevent loop engine [addr:0x10c210750] ***
Python auto-reloader enabled
```

**Comment by johaven** [comment]
```python
a = importlib.import_module('engineio.async_drivers.' + 'gevent_uwsgi')._async
```
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Web/venv/lib/python3.8/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 4, in <module>
    from gevent import selectors
ImportError: cannot import name 'selectors' from 'gevent' (/Web/venv/lib/python3.8/site-packages/gevent/__init__.py)
```

**Comment by miguelgrinberg** [comment]
Gevent does have a `selectors` module though. Any chance you have an old version of gevent, from before this module was added?

**Comment by johaven** [comment]
I think it's the problem, i use gevent 1.4.0 / 1.5.0, i tried the 21.x.x build and it's seem to be ok but ...

uWSGI documentation recommends 1.x.x releases (https://uwsgi-docs.readthedocs.io/en/latest/Gevent.html)
I am testing with 21.x.x, in this case the import is ok. I will check the uWSGI behavior in production.

A warning (during import) or one line in documentation about the required version should be cool :)

**Comment by miguelgrinberg** [comment]
@johaven where did you see that uWSGI recommends 1.x releases? All I can see is that a claim that 1.0.0 is required. That means that you cannot use any versions before 1.0. I can't find anything regarding not using the current versions of gevent.

**Comment by johaven** [comment]
@miguelgrinberg I haven't read any claim that it works with versions above 1.x.x, surely a question of interpretation but a warning about the gevent versions could be nice instead to ignore import errors.
