### ISSUE TITLE
use the gevent-websocket server. See the Deployment section of the documentation for more information.

### ISSUE THREAD

**Issue by shivarajalagond** [miguelgrinberg/Flask-SocketIO#1798]
Hi, I am running the app with gunicorn and I get this error whenever I restart the docker container or do deployment and there are stale tabs open of the app in the browser
It gives error for all users that had tabs open. Can you guide on this?

```
RuntimeError: You need to use the gevent-websocket server. See the Deployment section of the documentation for more information.
[2022-03-03 17:42:38 -0500] [9] [ERROR] Error handling request /socket.io/?username=USER&EIO=3&transport=websocket&sid=5879be715cf14b33acb95d4db9a50f46
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 46, in __call__
    start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 560, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 377, in handle_request
    environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 108, in handle_get_request
    start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/async_drivers/gevent.py", line 35, in __call__
    raise RuntimeError('You need to use the gevent-websocket server. '</div>
```

**Comment by miguelgrinberg** [comment]
Why would you write an issue and a discussion? What do you expect will be better when you duplicate your question?

Please don't write issues on this package if you only have a question. The discussion board is for that.

**Comment by miguelgrinberg** [comment]
It's not what I think. The issues board is for bug reports or enhancement requests. You just don't know how to use this package. Have you not seen the instructions when you wrote the bug?
