### ISSUE TITLE
When using redis, a JSON serialization error can prevent other events from being emitted by the server until it is restarted

### ISSUE THREAD

**Issue by mgd722** [miguelgrinberg/Flask-SocketIO#1808]
**Describe the bug**
If you pass something that cannot be JSON serialized to an `emit` call and are using redis as your message queue, it will cause an error that will prevent all future events from being emitted. The app will not recover on its own and it seems the only remedy is to restart the server. This affects all clients connected to the running process, not just the client that caused the error.

**To Reproduce**
1. Clone my fork of your chat app and checkout the [`error-breaks-all-future-emits` branch](https://github.com/mgd722/Flask-SocketIO-Chat/tree/error-breaks-all-future-emits). I have updated that app to run 5.1.1 and all modern packages.
2. Install packages, start redis, and then run `python chat_using_redis.py` to start the app using redis as a message queue.
3. Run `redis-cli monitor` in a separate terminal window to keep an eye on redis logs.
4. Send a few things in the chat and you should see them appear in the chat and pass through the redis logs as expected.
5. Send the string `non-breaking error`. It will raise a `ZeroDivisionError` in your flask console and appear in neither your chat nor your redis logs.
6. Send another random string. It will appear in the chat and pass through the redis logs as expected. The app has recovered from the `ZeroDivisionError` on its own and continues to function.
7. Send the string `breaking error`. It will raise a `TypeError` in your flask console and again appears neither in your chat nor in redis.
8. Send additional random strings. They will now appear only in the redis/debug logs and not in your chat. All clients connected to this server will no longer receive events, even though it does seem that they're still passing through redis. 

**Expected behavior**
I expect behavior consistent with how the app runs when not using redis. If there's an error with an emit, that event should fail and not affect future events nor other unrelated users connected to the server. For convenience, I have left the chat app's original `chat.py` file in the repo to allow easy toggling between using redis and using the built-in server.
1. Run `python chat.py` to start the app using the built in server.
2. You can send the strings `non-breaking error` or `breaking error` and, while those events will fail with a traceback in the console, the app as a whole keeps running and future emits work. No other connected clients are affected.

**Logs**
Following the repro steps above, here is the log:
```
(venv) ➜  Flask-SocketIO-Chat git:(error-breaks-all-future-emits) ✗ python chat_using_redis.py
monkey patching python for websockets...
Server initialized for eventlet.
 * Restarting with stat
monkey patching python for websockets...
Server initialized for eventlet.
 * Debugger is active!
 * Debugger PIN: 633-793-174
(13448) wsgi starting up on http://127.0.0.1:5000
(13448) accepted ('127.0.0.1', 50775)
127.0.0.1 - - [28/Mar/2022 01:05:01] "GET /chat HTTP/1.1" 200 2112 0.011333
Ubs9o1bE6ThkM0KMAAAA: Sending packet OPEN data {'sid': 'Ubs9o1bE6ThkM0KMAAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
redis backend initialized.
127.0.0.1 - - [28/Mar/2022 01:05:01] "GET /socket.io/?EIO=4&transport=polling&t=N_FLwGc HTTP/1.1" 200 278 0.001067
Ubs9o1bE6ThkM0KMAAAA: Received packet MESSAGE data 0/chat,
Ubs9o1bE6ThkM0KMAAAA: Sending packet MESSAGE data 0/chat,{"sid":"CWHE-OY4mIAmAy-xAAAB"}
127.0.0.1 - - [28/Mar/2022 01:05:01] "POST /socket.io/?EIO=4&transport=polling&t=N_FLwJ1&sid=Ubs9o1bE6ThkM0KMAAAA HTTP/1.1" 200 219 0.000433
(13448) accepted ('127.0.0.1', 50784)
(13448) accepted ('127.0.0.1', 50786)
Ubs9o1bE6ThkM0KMAAAA: Received request to upgrade to websocket
127.0.0.1 - - [28/Mar/2022 01:05:01] "GET /socket.io/?EIO=4&transport=polling&t=N_FLwJ2&sid=Ubs9o1bE6ThkM0KMAAAA HTTP/1.1" 200 181 0.000062
127.0.0.1 - - [28/Mar/2022 01:05:01] "GET /socket.io/?EIO=4&transport=polling&t=N_FLwJq&sid=Ubs9o1bE6ThkM0KMAAAA HTTP/1.1" 200 181 0.000088
Ubs9o1bE6ThkM0KMAAAA: Upgrade to websocket successful
Ubs9o1bE6ThkM0KMAAAA: Received packet MESSAGE data 2/chat,["joined",{}]
received event "joined" from CWHE-OY4mIAmAy-xAAAB [/chat]
CWHE-OY4mIAmAy-xAAAB is entering room 343 [/chat]
emitting event "status" to 343 [/chat]
pubsub message: emit
Ubs9o1bE6ThkM0KMAAAA: Sending packet MESSAGE data 2/chat,["status",{"msg":"Michael Davlantes has entered the room."}]
Ubs9o1bE6ThkM0KMAAAA: Received packet MESSAGE data 2/chat,["text",{"msg":"hello world?"}]
received event "text" from CWHE-OY4mIAmAy-xAAAB [/chat]
emitting event "message" to 343 [/chat]
pubsub message: emit
Ubs9o1bE6ThkM0KMAAAA: Sending packet MESSAGE data 2/chat,["message",{"msg":"Michael Davlantes:hello world?"}]
Ubs9o1bE6ThkM0KMAAAA: Sending packet PING data None
Ubs9o1bE6ThkM0KMAAAA: Received packet PONG data
Ubs9o1bE6ThkM0KMAAAA: Received packet MESSAGE data 2/chat,["text",{"msg":"non-breaking error"}]
received event "text" from CWHE-OY4mIAmAy-xAAAB [/chat]
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/socketio/server.py", line 720, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/opt/homebrew/lib/python3.9/site-packages/socketio/server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/opt/homebrew/lib/python3.9/site-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/opt/homebrew/lib/python3.9/site-packages/flask_socketio/__init__.py", line 766, in _handle_event
    ret = handler(*args)
  File "/Users/mike/Desktop/Work/Flask-SocketIO-Chat/app/main/events.py", line 28, in text
    emit('message', {'msg': session.get('name') + ':' + message['msg'], 'break': 5/0}, room=room)
ZeroDivisionError: division by zero
Ubs9o1bE6ThkM0KMAAAA: Received packet MESSAGE data 2/chat,["text",{"msg":"we were able to power through that one"}]
received event "text" from CWHE-OY4mIAmAy-xAAAB [/chat]
emitting event "message" to 343 [/chat]
pubsub message: emit
Ubs9o1bE6ThkM0KMAAAA: Sending packet MESSAGE data 2/chat,["message",{"msg":"Michael Davlantes:we were able to power through that one"}]
Ubs9o1bE6ThkM0KMAAAA: Sending packet PING data None
Ubs9o1bE6ThkM0KMAAAA: Received packet PONG data
Ubs9o1bE6ThkM0KMAAAA: Received packet MESSAGE data 2/chat,["text",{"msg":"breaking error"}]
received event "text" from CWHE-OY4mIAmAy-xAAAB [/chat]
emitting event "message" to 343 [/chat]
pubsub message: emit
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/socketio/pubsub_manager.py", line 168, in _thread
    self._handle_emit(data)
  File "/opt/homebrew/lib/python3.9/site-packages/socketio/pubsub_manager.py", line 116, in _handle_emit
    super(PubSubManager, self).emit(message['event'], message['data'],
  File "/opt/homebrew/lib/python3.9/site-packages/socketio/base_manager.py", line 171, in emit
    self.server._emit_internal(eio_sid, event, data, namespace, id)
  File "/opt/homebrew/lib/python3.9/site-packages/socketio/server.py", line 636, in _emit_internal
    self._send_packet(eio_sid, self.packet_class(
  File "/opt/homebrew/lib/python3.9/site-packages/socketio/server.py", line 641, in _send_packet
    encoded_packet = pkt.encode()
  File "/opt/homebrew/lib/python3.9/site-packages/socketio/packet.py", line 64, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BytesIO is not JSON serializable
Ubs9o1bE6ThkM0KMAAAA: Sending packet PING data None
Ubs9o1bE6ThkM0KMAAAA: Received packet PONG data
Ubs9o1bE6ThkM0KMAAAA: Received packet MESSAGE data 2/chat,["text",{"msg":"not so lucky that time"}]
received event "text" from CWHE-OY4mIAmAy-xAAAB [/chat]
emitting event "message" to 343 [/chat]
Ubs9o1bE6ThkM0KMAAAA: Received packet MESSAGE data 2/chat,["text",{"msg":"now these messages aren't getting through"}]
received event "text" from CWHE-OY4mIAmAy-xAAAB [/chat]
emitting event "message" to 343 [/chat]
Ubs9o1bE6ThkM0KMAAAA: Sending packet PING data None
Ubs9o1bE6ThkM0KMAAAA: Received packet PONG data
```

**Additional context**
I'm running python 3.9 for this demo. In production, I run python 3.6 and an nginx server that shares the load between 3 eventlet nodes using `ip_hash` as you've written in the docs and suggested in #1471. When this bug occurred, it only affected one third of my users so it seems that it's limited to the eventlet node and does not affect redis. Restarting that node got the events working again. This bug seems related to some stuff reported at the bottom of #1250.

**Comment by miguelgrinberg** [comment]
Can I ask you to install python-socketio's main branch and let me know if the problem goes away? I believe this has been reported already and there is a fix in place (not released officially yet).

**Comment by mgd722** [comment]
Yes, when I `pip install git+https://github.com/miguelgrinberg/python-socketio.git@main` and run it, the steps above no longer break future emits. You're already on top of it so I'll close this issue! Thank you!
