### ISSUE TITLE
 RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by qxwei** [miguelgrinberg/Flask-SocketIO#1842]
nginx config：

	location /socket.io {
	
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://0.0.0.0:5002/socket.io;
    }

exception information:

message handler error
Traceback (most recent call last):
  File "/opt/code/env/lib/python3.6/site-packages/engineio/server.py", line 622, in _trigger_event
    return self.handlers[event](*args)
  File "/opt/code/env/lib/python3.6/site-packages/socketio/server.py", line 781, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/opt/code/env/lib/python3.6/site-packages/socketio/server.py", line 654, in _handle_connect
    sid = self.manager.connect(eio_sid, namespace)
  File "/opt/code/env/lib/python3.6/site-packages/socketio/base_manager.py", line 55, in connect
    self.enter_room(sid, namespace, None, eio_sid=eio_sid)
  File "/opt/code/env/lib/python3.6/site-packages/socketio/base_manager.py", line 122, in enter_room
    self.rooms[namespace][room] = bidict()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 105, in __init__
    self._init_inv()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 113, in _init_inv
    self._inv = inv = self._inv_cls.__new__(self._inv_cls)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1227, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1196, in _generic_new
    obj.__init__(*args, **kwds)
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 105, in __init__
    self._init_inv()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 113, in _init_inv
    self._inv = inv = self._inv_cls.__new__(self._inv_cls)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1227, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1196, in _generic_new
    obj.__init__(*args, **kwds)
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 105, in __init__
    self._init_inv()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 113, in _init_inv
    self._inv = inv = self._inv_cls.__new__(self._inv_cls)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1227, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1196, in _generic_new
    obj.__init__(*args, **kwds)
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 105, in __init__
    self._init_inv()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 113, in _init_inv
    self._inv = inv = self._inv_cls.__new__(self._inv_cls)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1227, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1196, in _generic_new
    obj.__init__(*args, **kwds)
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 105, in __init__
    self._init_inv()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 113, in _init_inv
    self._inv = inv = self._inv_cls.__new__(self._inv_cls)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1227, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1196, in _generic_new
    obj.__init__(*args, **kwds)
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 105, in __init__
    self._init_inv()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 113, in _init_inv
    self._inv = inv = self._inv_cls.__new__(self._inv_cls)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1227, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1196, in _generic_new
    obj.__init__(*args, **kwds)
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 105, in __init__
    self._init_inv()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 113, in _init_inv
    self._inv = inv = self._inv_cls.__new__(self._inv_cls)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1227, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1196, in _generic_new
    obj.__init__(*args, **kwds)
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 105, in __init__
    self._init_inv()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 113, in _init_inv
    self._inv = inv = self._inv_cls.__new__(self._inv_cls)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1227, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1196, in _generic_new
    obj.__init__(*args, **kwds)
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 105, in __init__
    self._init_inv()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 113, in _init_inv
    self._inv = inv = self._inv_cls.__new__(self._inv_cls)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1227, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1196, in _generic_new
    obj.__init__(*args, **kwds)
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 105, in __init__
    self._init_inv()
  File "/opt/code/env/lib/python3.6/site-packages/bidict/_base.py", line 113, in _init_inv
    self._inv = inv = self._inv_cls.__new__(self._inv_cls)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1227, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/usr/local/python3/lib/python3.6/typing.py", line 1196, in _generic_new

**Comment by miguelgrinberg** [comment]
Can you show the code that you have in your connect handler?

**Comment by qxwei** [comment]
thanks for your response. below is my code：
`@socketio.on('connect')
def socket_connect():
    print("connect")
    session['sid'] = request.sid
    #if 'user' in session:
     #   user = session['user']
    #    User.query.filter_by(UserID=user['UserID']).update({'sid': request.sid})
    #    db.session.commit()
     #   r.setex(user['UserID'], 5 * 60, request.sid)
    emit('command', {'data': 'Connected'}, room=request.sid)


@socketio.on('disconnect')
def socket_disconnect():
  #  if 'user' in session:
   #     user = session['user']
   #     User.query.filter_by(UserID=user['UserID']).update({'sid': None})
   #     r.hdel("hash1", user['UserID'])
   #     db.session.commit()
    print('Client disconnected')`

**Comment by qxwei** [comment]
thanks for your response. below is my code：
`@socketio.on('connect')
def socket_connect():
    print("connect")
    session['sid'] = request.sid
    #if 'user' in session:
     #   user = session['user']
    #    User.query.filter_by(UserID=user['UserID']).update({'sid': request.sid})
    #    db.session.commit()
     #   r.setex(user['UserID'], 5 * 60, request.sid)
    emit('command', {'data': 'Connected'}, room=request.sid)`

**Comment by qxwei** [comment]
thanks for your response. below is my code：

`@socketio.on('connect')
def socket_connect():
    print("connect")
    session['sid'] = request.sid
    #if 'user' in session:
     #   user = session['user']
    #    User.query.filter_by(UserID=user['UserID']).update({'sid': request.sid})
    #    db.session.commit()
     #   r.setex(user['UserID'], 5 * 60, request.sid)
    emit('command', {'data': 'Connected'}, room=request.sid)`

**Comment by qxwei** [comment]
@socketio.on('connect')
def socket_connect():
    print("connect")
    session['sid'] = request.sid
    #if 'user' in session:
     #   user = session['user']
    #    User.query.filter_by(UserID=user['UserID']).update({'sid': request.sid})
    #    db.session.commit()
     #   r.setex(user['UserID'], 5 * 60, request.sid)
    emit('command', {'data': 'Connected'}, room=request.sid)
