### ISSUE TITLE
Can't import in python 3.10.5

### ISSUE THREAD

**Issue by chhongzh** [miguelgrinberg/Flask-SocketIO#1879]
Describe the bug:
I'm trying import this module, but raise error.
```Traceback (most recent call last):
  File "server.py", line 8, in <module>
    from flask_socketio import SocketIO
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask_socketio/__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/socketio/client.py", line 7, in <module>
    import engineio
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/engineio/__init__.py", line 11, in <module>
    from .async_drivers.tornado import get_tornado_handler
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/engineio/async_drivers/tornado.py", line 6, in <module>
    import tornado.web
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/web.py", line 88, in <module>
    from tornado import httputil
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/httputil.py", line 107, in <module>
    class HTTPHeaders(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```
In python 3.10, the attribute MutableMapping from the module collections have been removed.

**Comment by miguelgrinberg** [comment]
If you review the stack trace, you will see that it is tornado having this problem, not this package. If there is no fixed release from them, then you have to report the issue to tornado.

**Comment by mhanuel26** [comment]
Hi @chhongzh ,

If you using anaconda for your 3.10 python environment you can fix it by doing the following,

open the file

`~/miniconda3/envs/YOURENVHERE/lib/python3.10/site-packages/tornado/httputil.py `

and replace the line that has

`class HTTPHeaders(collections.MutableMapping):`

with

`class HTTPHeaders(collections.abc.MutableMapping):`

If you are not anaconda look for the similar folder within your environment. Hope this helps.

**Comment by miguelgrinberg** [comment]
@mhanuel26 modifying the code in your virtualenv is a really bad practice. I don't recommend it. Get a fix from Tornado instead.

**Comment by mhanuel26** [comment]
Hi @miguelgrinberg ,

Yes I know, we should avoid it, but this might get you off the ground in no time.

Cheers,

**Comment by chhongzh** [comment]
Ok, I solved this problem

The version of Tornado is too old, so this error occurs
Try upgrading Tornado to solve this problem

Thanks,
