### ISSUE TITLE
Unable to connect to namespaces other than the main namespace

### ISSUE THREAD

**Issue by wbb12** [miguelgrinberg/Flask-SocketIO#1983]
I upgrade the Python virtual environment because of the version change of Python. The current pip list is listed below.  The Flask-SocketIO is pulled from this repository. The test server is a modification of the sample in README.md. The client Python script is tested in the terminal. During the test, the output of the server log and the exception of the client are also listed below.

The communication in the default "\\" namespaces are normal, but the client cannot connect to other namespaces. In the JS socketio, the console just returns the info "Unable to connect". 

```
(venv) user@webctrl:~/Webctrl/socketio_server$ pip list
Package            Version
------------------ ----------
bidict             0.22.1
blinker            1.6.2
certifi            2022.12.7
charset-normalizer 3.1.0
click              8.1.3
dnspython          2.3.0
eventlet           0.33.3
Flask              2.3.1
Flask-SocketIO     5.3.4.dev0
greenlet           2.0.2
idna               3.4
itsdangerous       2.1.2
Jinja2             3.1.2
MarkupSafe         2.1.2
pip                22.0.2
python-engineio    4.4.1
python-socketio    5.8.0
requests           2.29.0
setuptools         59.6.0
six                1.16.0
urllib3            1.26.15
websocket-client   1.5.1
Werkzeug           2.3.2
```
test-server.py
```
from flask import Flask, render_template
from flask_socketio import SocketIO, emit
    
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app,logger=True, engineio_logger=True)

@app.route('/')
def index():
    return render_template('index.html')

@socketio.on("heartbeat")
def my_event(message):
    emit('heartbeat_test', message, namespace='/test',broadcast=True)
    emit('heartbeat_default', message, namespace='/',broadcast=True)

if __name__ == '__main__':
    print("Start the server!")
    socketio.run(app,host='localhost',port=9000)
    
```
test-client.py
```
import socketio
import time 

def on_message_default(*args):
	print("heartbeat_default:{}".format(args[0]))


def on_message_test(*args):
	print("heartbeat_test:{}".format(args[0]))

sio = socketio.Client()

sio.connect('http://localhost:9000',namespaces=['/test'])
sio.on('heartbeat_test', on_message_test,namespace='/test')

sio.connect('http://localhost:9000',namespaces=["/"])
sio.on('heartbeat_default', on_message_default,namespace='/')
sio.emit('heartbeat',{'time':time.time()},namespace='/')
```
Server log:
```
(venv) user@webctrl:~/Webctrl/socketio_server$ python test_server.py 
Server initialized for eventlet.
Start the server!
mvpQ9wGek6qH5HkNAAAA: Sending packet OPEN data {'sid': 'mvpQ9wGek6qH5HkNAAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
mvpQ9wGek6qH5HkNAAAA: Received request to upgrade to websocket
mvpQ9wGek6qH5HkNAAAA: Upgrade to websocket successful
mvpQ9wGek6qH5HkNAAAA: Received packet MESSAGE data 0/test,{}
mvpQ9wGek6qH5HkNAAAA: Sending packet MESSAGE data 4/test,"Unable to connect"
Cmghrn-Pn85y8XM_AAAB: Sending packet OPEN data {'sid': 'Cmghrn-Pn85y8XM_AAAB', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
Cmghrn-Pn85y8XM_AAAB: Received request to upgrade to websocket
Cmghrn-Pn85y8XM_AAAB: Upgrade to websocket successful
Cmghrn-Pn85y8XM_AAAB: Received packet MESSAGE data 0{}
Cmghrn-Pn85y8XM_AAAB: Sending packet MESSAGE data 0{"sid":"gjSZ2sNhnxmCiuBQAAAC"}
Cmghrn-Pn85y8XM_AAAB: Received packet MESSAGE data 2["heartbeat",{"time":1682866233.2246695}]
received event "heartbeat" from gjSZ2sNhnxmCiuBQAAAC [/]
emitting event "heartbeat_test" to all [/test]
emitting event "heartbeat_default" to all [/]
Cmghrn-Pn85y8XM_AAAB: Sending packet MESSAGE data 2["heartbeat_default",{"time":1682866233.2246695}]
Cmghrn-Pn85y8XM_AAAB: Received packet MESSAGE data 2["heartbeat",{"time":1682866234.9000273}]
received event "heartbeat" from gjSZ2sNhnxmCiuBQAAAC [/]
emitting event "heartbeat_test" to all [/test]
emitting event "heartbeat_default" to all [/]
Cmghrn-Pn85y8XM_AAAB: Sending packet MESSAGE data 2["heartbeat_default",{"time":1682866234.9000273}]
Cmghrn-Pn85y8XM_AAAB: Sending packet PING data None
Cmghrn-Pn85y8XM_AAAB: Received packet PONG data 
```
client test in the terminal
```
(venv) user@webctrl:~/Webctrl/socketio_server$ python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socketio
>>> import time 
>>> def on_message_default(*args):
...     print("heartbeat_default:{}".format(args[0]))
... 
>>> def on_message_test(*args):
...     print("heartbeat_test:{}".format(args[0]))
... 
>>> sio = socketio.Client()
>>> 
>>> sio.connect('http://localhost:9000',namespaces=['/test'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Webctrl/socketio_server/venv/lib/python3.10/site-packages/socketio/client.py", line 347, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect
>>> 
>>> sio.connect('http://localhost:9000',namespaces=["/"])
>>> 
>>> sio.on('heartbeat_default', on_message_default,namespace='/')
>>> 
>>> sio.emit('heartbeat',{'time':time.time()},namespace='/')
>>> heartbeat_default:{'time': 1682866233.2246695}

>>> sio.emit('heartbeat',{'time':time.time()},namespace='/')
>>> heartbeat_default:{'time': 1682866234.9000273}

>>> exit()
```

**Comment by miguelgrinberg** [comment]
Flask-SocketIO will not allow a connection to an unknown namespace. Try adding a handler for the namespace in your server, then the namespace will be known and the connection should work.
