### ISSUE TITLE
OSError observed in logs with example using latest version of socket.io library.

### ISSUE THREAD

**Issue by jgerry2002** [miguelgrinberg/Flask-SocketIO#2017]
**Describe the bug**
Using the latest version of socket.io javascript libraries in template we are seeing a client disconnect error similar to https://github.com/miguelgrinberg/Flask-SocketIO/issues/377

**To Reproduce**
1. Go to example
2. Open index.html template
3. Replace socket.io 3.0.4 with 4.7.2
4. OSError observed in logs

**Expected behavior**
A clean disconnect without raising an OSErorr

**Logs**
Client disconnected FP-tnyVJscQNJp0LAAAC
Traceback (most recent call last):
  File "/opt/miguel-env/lib64/python3.9/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/miguel-env/lib64/python3.9/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/opt/miguel-env/lib64/python3.9/site-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/opt/miguel-env/lib64/python3.9/site-packages/socketio/server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/opt/miguel-env/lib64/python3.9/site-packages/engineio/server.py", line 321, in handle_request
    start_response(r['status'], r['headers'] + cors_headers)
OSError: headers already sent

**Additional context**
use default suggested uwsgi configuration:  uwsgi --http :3031 --gevent 1000 --http-websockets --master --wsgi-file app.py --callable app

**Comment by johaven** [comment]
+1

**Comment by miguelgrinberg** [comment]
Possibly related to https://github.com/miguelgrinberg/python-engineio/issues/332

**Comment by pipozzz** [comment]
Hi, I have the same problem, with headers already sent OSError, what is the workaround here pls ?
