### ISSUE TITLE
gracefull error handling for missing arguments from client

### ISSUE THREAD

**Issue by mr-pj** [miguelgrinberg/Flask-SocketIO#21]
Flask-socketio raises a TypeError when a method has a required parameter and the client does not provide it:

for example:
```
@socketio.on('login', namespace='/test')
def login(message):
....
```

will fail with TypeError when the client only sends 'login' without a second parameter / message

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/socketio/virtsocket.py", line 403, in _receiver_loop
    retval = pkt_ns.process_packet(pkt)
  File "/usr/local/lib/python2.7/dist-packages/socketio/namespace.py", line 155, in process_packet
    return self.process_event(packet)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 53, in process_event
    return self.socketio._dispatch_message(app, self, message, args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 122, in _dispatch_message
    ret = self.messages[namespace.ns_name][message](*args)
TypeError: login() takes exactly 1 argument (0 given)
<Greenlet at 0x2672230: <bound method Socket._receiver_loop of <socketio.virtsocket.Socket object at 0x2775290>>> failed with TypeError
```

**Comment by miguelgrinberg** [comment]
Error handling is now supported. Closing.
