### ISSUE TITLE
Update 5.3.6 to 5.4.1 - test failed

### ISSUE THREAD

**Issue by coogor** [miguelgrinberg/Flask-SocketIO#2100]
Hello,
I'm trying to upgrade from 5.3.6 to 5.4.1 for openSUSE Tumbleweed (Rolling Release) and run into a test error:

[code]
```
[    9s] + python3.10 -m unittest -v test_socketio.py
[   10s] Traceback (most recent call last):
[   10s]   File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
[   10s]     return _run_code(code, main_globals, None,
[   10s]   File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
[   10s]     exec(code, run_globals)
[   10s]   File "/usr/lib64/python3.10/unittest/__main__.py", line 18, in <module>
[   10s]     main(module=None)
[   10s]   File "/usr/lib64/python3.10/unittest/main.py", line 100, in __init__
[   10s]     self.parseArgs(argv)
[   10s]   File "/usr/lib64/python3.10/unittest/main.py", line 147, in parseArgs
[   10s]     self.createTests()
[   10s]   File "/usr/lib64/python3.10/unittest/main.py", line 158, in createTests
[   10s]     self.test = self.testLoader.loadTestsFromNames(self.testNames,
[   10s]   File "/usr/lib64/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
[   10s]     suites = [self.loadTestsFromName(name, module) for name in names]
[   10s]   File "/usr/lib64/python3.10/unittest/loader.py", line 220, in <listcomp>
[   10s]     suites = [self.loadTestsFromName(name, module) for name in names]
[   10s]   File "/usr/lib64/python3.10/unittest/loader.py", line 154, in loadTestsFromName
[   10s]     module = __import__(module_name)
[   10s]   File "/home/abuild/rpmbuild/BUILD/flask_socketio-5.4.1/test_socketio.py", line 11, in <module>
[   10s]     socketio = SocketIO(app)
[   10s]   File "/home/abuild/rpmbuild/BUILDROOT/python-Flask-SocketIO-5.4.1-0.x86_64/usr/lib/python3.10/site-packages/flask_socketio/__init__.py", line 187, in __init__
[   10s]     self.init_app(app, **kwargs)
[   10s]   File "/home/abuild/rpmbuild/BUILDROOT/python-Flask-SocketIO-5.4.1-0.x86_64/usr/lib/python3.10/site-packages/flask_socketio/__init__.py", line 243, in init_app
[   10s]     self.server = socketio.Server(**self.server_options)
[   10s]   File "/usr/lib/python3.10/site-packages/socketio/base_server.py", line 31, in __init__
[   10s]     self.eio = self._engineio_server_class()(**engineio_options)
[   10s]   File "/usr/lib/python3.10/site-packages/engineio/base_server.py", line 81, in __init__
[   10s]     raise ValueError('Invalid async_mode specified')
[   10s] ValueError: Invalid async_mode specified
[   10s] error: Bad exit status from /var/tmp/rpm-tmp.vl0P2D (%check)
```
[/code]

Any idea?
Thanks

**Comment by miguelgrinberg** [comment]
I don't know what to suggest, as the tests pass on my CI. My guess is that this isn't related to the update but to some other condition in your environment, like maybe the dependencies that you have installed or any changes or patches you may have applied to the code.

**Comment by coogor** [comment]
On what system are you working?
My best guess is that one dependency got updated to a newer release, which is obviously incompatible. 
On a rolling release one sees these issues quite quickly. Since one week the current 5.3.6 version fails in Tumbleweed as well. I'm currently trying to find out which new python-packages have arrived by then

**Comment by danigm** [comment]
I've found that the problem was in a missing dependency for package python-python-engineio. I've just fixed the issue there, so it should build as soon as this update lands Tumbleweed.

https://build.opensuse.org/request/show/1222660

**Comment by coogor** [comment]
Am Freitag, 8. November 2024, 08:53:18 Mitteleuropäische Normalzeit schrieb danigm:
> 
> I&#39;ve found that the problem was in a missing dependency for package python-python-engineio. I&#39;ve just fixed the issue there, so it should build as soon as this update lands Tumbleweed.
> 
> https://build.opensuse.org/request/show/1222660
> 
> 
Thank you!
