### ISSUE TITLE
Callback error prevents future events from being emitted

### ISSUE THREAD

**Issue by chialol** [miguelgrinberg/Flask-SocketIO#2101]
**Describe the bug**
When I get an exception in my emit callback, subsequent emits will no longer work. I have a frontend application connecting to the FlaskSocket backend, with message_queue powered by redis. I emit messages like
```
def callback():
    raise Exception("boom")

socketio.emit('game_engine', 
            payload,
            room = 'someRoom',
            callback=callback,
            namespace = 'somenamespace')
```
Obviously I should fix my callback exception, but when exceptions do happen, and I refresh my frontend application, what used to be able to receive emit events do not receive anything. 

**To Reproduce**
python-engineio==4.0.0
python-socketio==5.0.4
Flask==1.1.2
Flask-Cors==3.0.8
Flask-SocketIO==5.0.1

Python version 3.8.1

Backend setup
```python
socketio = SocketIO(logger=True, engineio_logger=True)
socketio.init_app(app, cors_allowed_origins="*", message_queue=f'redis://{redis_url}')

"""
Where exceptions could happen
"""
def callback():
    raise Exception("boom")

socketio.emit('game_engine', 
            payload,
            room = 'someRoom',
            callback=callback,
            namespace = 'somenamespace')

"""
What the frontend calls
"""
@socketio.on('join_public_socket', namespace=namespace)
def join_public_socket(data):
    join_room(room_id, namespace=namespace)
    socketio.emit('joined_public_socket', 
        {
            'room_id': room_id
        },
        room = room_id,
        namespace = namespace)
```

My frontend application calls join_public_socket and listens to `joined_public_socket`. The listening works correctly prior to the exception happening. 
Once the exception in a callback happens, and when I refresh the frontend application, the listening no longer receives anything from the backend, and it appears that the backend is not emitting properly.

**Expected behavior**
I expect an exception to have no implications on future/other connections.

**Logs**
In the logs below, I noticed that prior to the exceptions happening, I see `pubsub message: emit` in the logs. Afterwards, I don't see it. Perhaps that might be related to why the backend didn't appear to be emitting anything?

```
2024-10-06 13:59:36 jT7EaUCMta9KccN8AAAS: Received packet CLOSE data 
2024-10-06 13:59:36 -FIjlShsJ4tWWxrvAAAq: Sending packet OPEN data {'sid': '-FIjlShsJ4tWWxrvAAAq', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
2024-10-06 13:59:37 -FIjlShsJ4tWWxrvAAAq: Received packet MESSAGE data 0/game_controller,
2024-10-06 13:59:37 -FIjlShsJ4tWWxrvAAAq: Sending packet MESSAGE data 0/game_controller,{"sid":"jtMy0-X15VPUnfPhAAAr"}
2024-10-06 13:59:37 -FIjlShsJ4tWWxrvAAAq: Received packet MESSAGE data 2/game_controller,["join_public_socket",{"room_id":"5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3"}]
2024-10-06 13:59:37 received event "join_public_socket" from jtMy0-X15VPUnfPhAAAr [/game_controller]
2024-10-06 13:59:37 jtMy0-X15VPUnfPhAAAr is entering room 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3 [/game_controller]
2024-10-06 13:59:37 emitting event "joined_public_socket" to 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3 [/game_controller]
2024-10-06 13:59:37 pubsub message: emit
2024-10-06 13:59:37 -FIjlShsJ4tWWxrvAAAq: Sending packet MESSAGE data 2/game_controller,["joined_public_socket",{"room_id":"5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3","instance":"900dd079-29f8-4360-bc69-a72caf4e36f5"}]
2024-10-06 13:59:37 join_public_socket {'jtMy0-X15VPUnfPhAAAr'} 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3
2024-10-06 13:59:37 -FIjlShsJ4tWWxrvAAAq: Received packet MESSAGE data 2/game_controller,["join_public_socket",{"room_id":"5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3"}]
2024-10-06 13:59:37 received event "join_public_socket" from jtMy0-X15VPUnfPhAAAr [/game_controller]
2024-10-06 13:59:37 jtMy0-X15VPUnfPhAAAr is entering room 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3 [/game_controller]
2024-10-06 13:59:37 -FIjlShsJ4tWWxrvAAAq: Received packet MESSAGE data 2/game_controller,["join_public_socket",{"room_id":"5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3"}]
2024-10-06 13:59:37 received event "join_public_socket" from jtMy0-X15VPUnfPhAAAr [/game_controller]
2024-10-06 13:59:37 emitting event "joined_public_socket" to 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3 [/game_controller]
2024-10-06 13:59:37 pubsub message: emit
2024-10-06 13:59:37 -FIjlShsJ4tWWxrvAAAq: Sending packet MESSAGE data 2/game_controller,["joined_public_socket",{"room_id":"5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3","instance":"900dd079-29f8-4360-bc69-a72caf4e36f5"}]
2024-10-06 13:59:37 jtMy0-X15VPUnfPhAAAr is entering room 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3 [/game_controller]
2024-10-06 13:59:37 -FIjlShsJ4tWWxrvAAAq: Received packet MESSAGE data 2/game_controller,["join_public_socket",{"room_id":"5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3"}]
2024-10-06 13:59:37 join_public_socket {'jtMy0-X15VPUnfPhAAAr'} 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3
2024-10-06 13:59:37 received event "join_public_socket" from jtMy0-X15VPUnfPhAAAr [/game_controller]
2024-10-06 13:59:37 emitting event "joined_public_socket" to 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3 [/game_controller]
2024-10-06 13:59:37 jtMy0-X15VPUnfPhAAAr is entering room 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3 [/game_controller]
2024-10-06 13:59:37 emitting event "joined_public_socket" to 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3 [/game_controller]
2024-10-06 13:59:37 pubsub message: emit
2024-10-06 13:59:37 -FIjlShsJ4tWWxrvAAAq: Sending packet MESSAGE data 2/game_controller,["joined_public_socket",{"room_id":"5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3","instance":"900dd079-29f8-4360-bc69-a72caf4e36f5"}]
2024-10-06 13:59:37 pubsub message: emit
2024-10-06 13:59:37 -FIjlShsJ4tWWxrvAAAq: Sending packet MESSAGE data 2/game_controller,["joined_public_socket",{"room_id":"5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3","instance":"900dd079-29f8-4360-bc69-a72caf4e36f5"}]
2024-10-06 13:59:37 join_public_socket {'jtMy0-X15VPUnfPhAAAr'} 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3
2024-10-06 13:59:37 join_public_socket {'jtMy0-X15VPUnfPhAAAr'} 5bfb01b3-1699-49d6-a1ec-4ec1a58d30f3
2024-10-06 13:59:43 emitting event "test_case" to clientId [/game_controller]
2024-10-06 13:59:43 pubsub message: emit
2024-10-06 13:59:43 YZluYXRhZQNO_fTtAAAW: Sending packet MESSAGE data 2/game_controller,1["test_case",{}]\n"}]
2024-10-06 13:59:44 received ack from JIFmqFCNedNfbaZCAAAX [/game_controller]
2024-10-06 13:59:44 pubsub message: callback
2024-10-06 13:59:44 emitting event "game_engine" to clientId [/game_controller]
2024-10-06 13:59:44 pubsub message: emit
2024-10-06 13:59:44 -FIjlShsJ4tWWxrvAAAq: Sending packet MESSAGE data 2/game_controller,["message",{}]
2024-10-06 13:59:44 pubsub message: emit
2024-10-06 13:59:44 YZluYXRhZQNO_fTtAAAW: Sending packet MESSAGE data 2/game_controller,2["game_engine",{}]
2024-10-06 13:59:44 YZluYXRhZQNO_fTtAAAW: Received packet MESSAGE data 3/game_controller,2[{}]
2024-10-06 13:59:44 received ack from JIFmqFCNedNfbaZCAAAX [/game_controller]
2024-10-06 13:59:44 pubsub message: callback
2024-10-06 13:59:44 Exception in thread Thread-4:
2024-10-06 13:59:44 Traceback (most recent call last):
2024-10-06 13:59:44   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
2024-10-06 13:59:44     self.run()
2024-10-06 13:59:44   File "/usr/lib/python3.6/threading.py", line 864, in run
2024-10-06 13:59:44     self._target(*self._args, **self._kwargs)
2024-10-06 13:59:44   File "/usr/local/lib/python3.6/dist-packages/socketio/pubsub_manager.py", line 166, in _thread
2024-10-06 13:59:44     self._handle_callback(data)
2024-10-06 13:59:44   File "/usr/local/lib/python3.6/dist-packages/socketio/pubsub_manager.py", line 126, in _handle_callback
2024-10-06 13:59:44     self.trigger_callback(sid, id, args)
2024-10-06 13:59:44   File "/usr/local/lib/python3.6/dist-packages/socketio/base_manager.py", line 171, in trigger_callback
2024-10-06 13:59:44     callback(*data)
2024-10-06 13:59:44   File "/app/games/services/....py", line 283, in callback
2024-10-06 13:59:44 AttributeError: 'str' object has no attribute 'get'
2024-10-06 13:59:44 
2024-10-06 13:59:49 SquFa7Fr09T_SFshAAAA: Sending packet PING data None
2024-10-06 13:59:49 SquFa7Fr09T_SFshAAAA: Received packet PONG data 
2024-10-06 13:59:49 4GEVk5nc5BDJXpZFAAAC: Sending packet PING data None
2024-10-06 13:59:49 4GEVk5nc5BDJXpZFAAAC: Received packet PONG data 
2024-10-06 13:59:49 abj124Pzdp0h8l--AAAE: Sending packet PING data None
2024-10-06 13:59:49 lVaABC1cda9oVqVJAAAH: Sending packet PING data None


Here I refresh the frontend page
2024-10-06 13:59:51 h3Yha5t3tyOWwQNVAAAs: Sending packet OPEN data {'sid': 'h3Yha5t3tyOWwQNVAAAs', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
2024-10-06 13:59:51 h3Yha5t3tyOWwQNVAAAs: Received packet MESSAGE data 0/game_controller,
2024-10-06 13:59:51 h3Yha5t3tyOWwQNVAAAs: Sending packet MESSAGE data 0/game_controller,{"sid":"Sr8l_HqzQ_rDB5kZAAAt"}
2024-10-06 13:59:51 h3Yha5t3tyOWwQNVAAAs: Received packet MESSAGE data 2/game_controller,["join_public_socket",{"room_id":"637c3722-a64d-457a-aae7-5a38b54d6adf"}]
2024-10-06 13:59:51 received event "join_public_socket" from Sr8l_HqzQ_rDB5kZAAAt [/game_controller]
2024-10-06 13:59:51 Sr8l_HqzQ_rDB5kZAAAt is entering room 637c3722-a64d-457a-aae7-5a38b54d6adf [/game_controller]
2024-10-06 13:59:51 emitting event "joined_public_socket" to 637c3722-a64d-457a-aae7-5a38b54d6adf [/game_controller]
2024-10-06 13:59:51 join_public_socket {'Sr8l_HqzQ_rDB5kZAAAt'} 637c3722-a64d-457a-aae7-5a38b54d6adf
2024-10-06 13:59:51 h3Yha5t3tyOWwQNVAAAs: Received packet MESSAGE data 2/game_controller,["join_public_socket",{"room_id":"637c3722-a64d-457a-aae7-5a38b54d6adf"}]
2024-10-06 13:59:51 received event "join_public_socket" from Sr8l_HqzQ_rDB5kZAAAt [/game_controller]
2024-10-06 13:59:51 Sr8l_HqzQ_rDB5kZAAAt is entering room 637c3722-a64d-457a-aae7-5a38b54d6adf [/game_controller]
2024-10-06 13:59:51 h3Yha5t3tyOWwQNVAAAs: Received packet MESSAGE data 2/game_controller,["join_public_socket",{"room_id":"637c3722-a64d-457a-aae7-5a38b54d6adf"}]
2024-10-06 13:59:51 emitting event "joined_public_socket" to 637c3722-a64d-457a-aae7-5a38b54d6adf [/game_controller]
2024-10-06 13:59:51 received event "join_public_socket" from Sr8l_HqzQ_rDB5kZAAAt [/game_controller]
2024-10-06 13:59:51 Sr8l_HqzQ_rDB5kZAAAt is entering room 637c3722-a64d-457a-aae7-5a38b54d6adf [/game_controller]
2024-10-06 13:59:51 h3Yha5t3tyOWwQNVAAAs: Received packet MESSAGE data 2/game_controller,["join_public_socket",{"room_id":"637c3722-a64d-457a-aae7-5a38b54d6adf"}]
2024-10-06 13:59:51 emitting event "joined_public_socket" to 637c3722-a64d-457a-aae7-5a38b54d6adf [/game_controller]
2024-10-06 13:59:51 received event "join_public_socket" from Sr8l_HqzQ_rDB5kZAAAt [/game_controller]
2024-10-06 13:59:51 Sr8l_HqzQ_rDB5kZAAAt is entering room 637c3722-a64d-457a-aae7-5a38b54d6adf [/game_controller]
2024-10-06 13:59:51 emitting event "joined_public_socket" to 637c3722-a64d-457a-aae7-5a38b54d6adf [/game_controller]
2024-10-06 13:59:51 join_public_socket {'Sr8l_HqzQ_rDB5kZAAAt'} 637c3722-a64d-457a-aae7-5a38b54d6adf
2024-10-06 13:59:51 join_public_socket {'Sr8l_HqzQ_rDB5kZAAAt'} 637c3722-a64d-457a-aae7-5a38b54d6adf
2024-10-06 13:59:51 join_public_socket {'Sr8l_HqzQ_rDB5kZAAAt'} 637c3722-a64d-457a-aae7-5a38b54d6adf
2024-10-06 13:59:52 hqHDOlQ_AOkd_1JCAAAi: Sending packet PING data None
2024-10-06 13:59:52 hqHDOlQ_AOkd_1JCAAAi: Received packet PONG data 
```

**Comment by miguelgrinberg** [comment]
I'm unable to reproduce this with the latest versions of Flask-Socketio, python-socketio and python-engineio. I suggest you upgrade these three packages to the latest versions and retest. If you continue to see this issue, could you please create a small complete example that I can use to reproduce the issue? Thanks.

**Comment by chialol** [comment]
Looks like it may be because I was running Flask server. 

I upgraded all these versions, and the flask server warned me about not using it in production. Adjusted my code to work with Gunicorn + gevent and re-running the original problematic code just resolved itself. 

My particular issue is resolved, so not sure if you want to continue looking into the Flask specific issue. Thanks!

**Comment by miguelgrinberg** [comment]
I was actually unable to reproduce the issue on the latest versions of everything, even with the Flask development web server. I'll close for now, if you discover any related issues now that you are upgraded feel free to reopen.
