### ISSUE TITLE
celery with eventlet workers shows error "working outside of request context"

### ISSUE THREAD

**Issue by flexlee** [miguelgrinberg/Flask-SocketIO#211]
I implemented both celery and flask-socketIO in my app. The celery implementation is done as https://github.com/miguelgrinberg/flasky-with-celery, and I use eventlet as flask-socketIO async mode. With this, I have to change the celery run command to 
`celery worker --app=celery_worker.celery --loglevel=info -P eventlet`.

 However, celery is giving me 'RuntimeError: working outside of application context'. Is there a way I can pass application context to celery with eventlet workers? Thanks.

**Comment by miguelgrinberg** [comment]
@flexlee you do not need to run the celery workers with eventlet. Did you try running celery the normal way and only having the main server running with eventlet?

**Comment by flexlee** [comment]
@miguel thanks for getting back. I tried the normal way but celery hangs without reporting any errors.

**Comment by miguelgrinberg** [comment]
Do you have any eventlet specific code in your application that celery might be hitting? It would be good to find out where it hangs.

**Comment by flexlee** [comment]
If I comment out the eventlet monkeypatch line in app/__init__.py, celery
runs fine in the normal way. But then the main server won't run.

**Comment by miguelgrinberg** [comment]
Right. You need to monkey patch for the main app, but not for celery. So monkey patch in manage.py, but not in celery_worker.py (assuming you are using my style of starter scripts).

Alternatively, you can run celery under eventlet. That would make sense if you needed to launch many concurrent jobs, that is what eventlet and gevent are great at. For small number of jobs it does not hurt to use eventlet, but it does not help either. The error that you get can probably be addressed, maybe if you show me the stack trace I can help.

**Comment by flexlee** [comment]
@miguelgrinberg, I moved the monkey patch out of `app/__init__.py` to `manage.py`. The normal way of running celery seems to work. Glad it's not issue with Flask-SocketIO.

However, if I run celery with eventlet workers, it still gives me `working outside of application context` error. I posted the stack trace below. Celery is run under your flasky-with-celery project.  Thanks for your help. 

18:44 $ celery worker --app=celery_worker.celery --loglevel=info -P eventlet
[2016-01-21 18:48:19,638: WARNING/MainProcess] /Users/keli/Dropbox/GitHub/flasky-with-celery/venv/lib/python3.5/site-packages/celery/apps/worker.py:161: CDeprecationWarning:
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

 -------------- celery@Kes-iMac.local v3.1.19 (Cipater)
---- **** -----
--- * ***  * -- Darwin-15.0.0-x86_64-i386-64bit
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         app:0x1047d4278
- ** ---------- .> transport:   redis://192.168.99.105:32769/0
- ** ---------- .> results:     redis://192.168.99.105:32769/0
- *** --- * --- .> concurrency: 4 (eventlet)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[tasks]
  . app.email.send_async_email

[2016-01-21 18:48:19,660: INFO/MainProcess] Connected to redis://192.168.99.105:32769/0
[2016-01-21 18:48:19,667: INFO/MainProcess] mingle: searching for neighbors
[2016-01-21 18:48:20,676: INFO/MainProcess] mingle: all alone
[2016-01-21 18:48:20,688: INFO/MainProcess] pidbox: Connected to redis://192.168.99.105:32769/0.
[2016-01-21 18:48:20,692: WARNING/MainProcess] celery@Kes-iMac.local ready.
[2016-01-21 18:48:45,167: INFO/MainProcess] Received task: app.email.send_async_email[e94f75e4-ac43-4239-a219-c4bf69bbbbde]
[2016-01-21 18:48:45,180: ERROR/MainProcess] Task app.email.send_async_email[e94f75e4-ac43-4239-a219-c4bf69bbbbde] raised unexpected: RuntimeError('working outside of application context',)
Traceback (most recent call last):
  File "/Users/keli/Dropbox/GitHub/flasky-with-celery/venv/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/keli/Dropbox/GitHub/flasky-with-celery/venv/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/keli/Dropbox/GitHub/flasky-with-celery/app/email.py", line 8, in send_async_email
    mail.send(msg)
  File "/Users/keli/Dropbox/GitHub/flasky-with-celery/venv/lib/python3.5/site-packages/flask_mail.py", line 415, in send
    with self.connect() as connection:
  File "/Users/keli/Dropbox/GitHub/flasky-with-celery/venv/lib/python3.5/site-packages/flask_mail.py", line 432, in connect
    return Connection(app.extensions['mail'])
  File "/Users/keli/Dropbox/GitHub/flasky-with-celery/venv/lib/python3.5/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/keli/Dropbox/GitHub/flasky-with-celery/venv/lib/python3.5/site-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/Users/keli/Dropbox/GitHub/flasky-with-celery/venv/lib/python3.5/site-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context

**Comment by miguelgrinberg** [comment]
Do you have this in your celery_worker.py file?

    app.app_context().push()

**Comment by flexlee** [comment]
yes.

**Comment by miguelgrinberg** [comment]
Sorry, yes, I see now that with eventlet threads the push that you do in celery_worker would not translate into the greenlets.

What you are going to need is to run that same thing right before you send the email.  So remove the `app` lines in celery_worker.py, and instead, change your send_email function to this:

    def send_email(to, subject, template, **kwargs):
        app = create_app(os.getenv('FLASK_CONFIG') or 'default')
        with app.app_context():
            msg = Message(app.config['FLASKY_MAIL_SUBJECT_PREFIX'] + ' ' + subject,
                          sender=app.config['FLASKY_MAIL_SENDER'], recipients=[to])
            msg.body = render_template(template + '.txt', **kwargs)
            msg.html = render_template(template + '.html', **kwargs)
            send_async_email.delay(msg)

**Comment by flexlee** [comment]
Thanks @miguelgrinberg .

Rather than changing `send_email` function, I found out changing the `send_async_email` function worked,

    @celery.task
    def send_async_email(msg):
        app = create_app(os.getenv('FLASK_CONFIG') or 'default')
        with app.app_context():
            mail.send(msg)

**Comment by miguelgrinberg** [comment]
You can also import the app created in the celery worker script instead of
making a new one every time.
