### ISSUE TITLE
Multiple wrapped listeners on connect breaks

### ISSUE THREAD

**Issue by PierrePaul** [miguelgrinberg/Flask-SocketIO#216]
This used to work in 0.6 : 

``` python
@sio.on('connect', namespace='/namespace1')
@sio.on('connect', namespace='/namespace2')
def on_connect:
     print('hi Miguel!')
```

In flask-socketio 2.0 it gives this error and breaks the connection : 

```
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 465, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/home/vagrant/venv/src/python-engineio/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/socketio/server.py", line 303, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/vagrant/venv/src/python-engineio/engineio/server.py", line 241, in handle_request
    socket.handle_post_request(environ)
  File "/home/vagrant/venv/src/python-engineio/engineio/socket.py", line 92, in handle_post_request
    self.receive(pkt)
  File "/home/vagrant/venv/src/python-engineio/engineio/socket.py", line 45, in receive
    self.server._trigger_event('message', self.sid, pkt.data)
  File "/home/vagrant/venv/src/python-engineio/engineio/server.py", line 327, in _trigger_event
    return self.handlers[event](*args)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/socketio/server.py", line 425, in _handle_eio_message
    self._handle_connect(sid, pkt.namespace)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/socketio/server.py", line 340, in _handle_connect
    self.environ[sid]) is False:
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/socketio/server.py", line 397, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 186, in _handler
    ret = handler()
TypeError: _handler() takes at least 1 argument (0 given)
```

In this exemple I'm using eventlet, but it affects gevent also.

I'm not sure it's a bug. Maybe this should have never been allowed. If it's the case though, we should put a note in the Upgrade docs. What do you think?

**Comment by miguelgrinberg** [comment]
I really never tried to make multiple chained decorators work, but I will look into it to see if that can be supported. Or else, as you said, document that it isn't.

**Comment by PierrePaul** [comment]
I can work on it and send a pull request. Just wanted your opinion before starting.

**Comment by miguelgrinberg** [comment]
Sure, if you want to give it a try, then happy to review it and merge it when you are done. Thanks!

**Comment by miguelgrinberg** [comment]
Multiple decorators chained works okay with current release. Closing.
