### ISSUE TITLE
python socketio client and flask-socketio server

### ISSUE THREAD

**Issue by gaozhidf** [miguelgrinberg/Flask-SocketIO#218]
File "", line 2237, in _find_and_load
File "", line 2222, in _find_and_load_unlocked
File "", line 2155, in _find_spec
TypeError: 'NoneType' object is not iterable

It shows TypeError. Because it returns b'OK' not b'ok'

Solution:

For in "....\lib\site-packages\socketIO_client\transports.py", line 97,
current:
assert response.content == b'ok'

change:
assert response.content == b'ok' or response.content == b'OK'

Details:

Traceback (most recent call last):
File "F:/PycharmProjects/test/test_socketio1.py", line 25, in 
piSpace = socketIO.define(Namespace, '/test')
File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client__init__.py", line 358, in define
self.connect(path)
File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client__init__.py", line 382, in connect
with_transport_instance)
File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client__init__.py", line 26, in wrap
return f(args, *kw)
File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client__init__.py", line 206, in message
transport.send_packet(engineIO_packet_type, engineIO_packet_data)
File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\transports.py", line 99, in send_packet
assert response.content == b'ok'
AssertionError
Exception ignored in: <bound method SocketIO.__del_ of >
Traceback (most recent call last):
File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client__init__.py", line 350, in del
File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client__init__.py", line 386, in disconnect
File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client__init__.py", line 184, in _close
File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\transports.py", line 97, in send_packet
File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\transports.py", line 176, in get_response
File "F:\PycharmProjects\test\env\lib\site-packages\requests\sessions.py", line 511, in post
File "F:\PycharmProjects\test\env\lib\site-packages\requests\sessions.py", line 454, in request
File "F:\PycharmProjects\test\env\lib\site-packages\requests\sessions.py", line 369, in prepare_request
File "F:\PycharmProjects\test\env\lib\site-packages\requests\cookies.py", line 482, in merge_cookies
File "F:\PycharmProjects\test\env\lib\site-packages\requests\cookies.py", line 310, in update
File "F:\PycharmProjects\test\env\lib\copy.py", line 97, in copy
File "", line 2237, in _find_and_load
File "", line 2222, in _find_and_load_unlocked
File "", line 2155, in _find_spec
TypeError: 'NoneType' object is not iterable

**Comment by miguelgrinberg** [comment]
The Python SocketIO client is not an official client. I test my server against the official clients. If you think there's something wrong in the server implementation, please tell me what it is. All I see in your report are stack traces from the Python SocketIO client, it's unclear what you are trying to report here.

**Comment by gaozhidf** [comment]
an official client??  

When socketio connected, flask-socketio server returns b'OK, but Python SocketIO client checks response as b'ok.So I do not know b'ok or b'OK is official one.

I had reported issue to Python SocketIO client, https://github.com/socketio/socket.io-client/issues/938#issuecomment-176693150
They said that It looks this is an issue of flask-socketio. Please report this to them.

**Comment by miguelgrinberg** [comment]
You reported the issue on the repository for the official Javascript client. But you are using the Python client. Did you report this to the Python Socket.IO client project? I don't thing the "ok" vs. "OK" response matters at all, in fact the response can be whatever you want, as long as the status code is 200.

**Comment by miguelgrinberg** [comment]
Actually, it looks like the issue has already been reported: https://github.com/invisibleroads/socketIO-client/issues/99
