### ISSUE TITLE
Server error on socket.io connection, 500 with error message: KeyError: '/'

### ISSUE THREAD

**Issue by doomdagger** [miguelgrinberg/Flask-SocketIO#244]
It's so weird to me. Because this error sometimes occurs sometimes not.

When socket.io-client try to connect to the server side, it sends three polling requests and then switches to websocket. But I always stuck on the third polling request. The client side has to wait up to 60 seconds and then receives an 500 error from server side. Then the client side try to reconnect again and again (always stuck on the third polling request). Util, it takes only two polling requests to switch to websocket (which means the third request doesn't happen) and then the connection is done. See the following image for details.
![image](https://cloud.githubusercontent.com/assets/6743894/13872492/69b5aea6-ecc1-11e5-84e0-0cd7d75b0bd0.png)

Later, I notice that actually after the second polling request, it has already switched to websocket. Why does it send the third polling anyway? 
![image](https://cloud.githubusercontent.com/assets/6743894/13872572/0242ad36-ecc2-11e5-924c-db0df6ab774a.png)

I have same problems no matter use eventlet or gevent and gevent-websocket. I tested it on example code in the documentation too, same problem!

The log on server side is (didn't use gunicorn right now, just the embedded server eventlet):
```
(12280) wsgi starting up on http://0.0.0.0:5000
(12280) accepted ('127.0.0.1', 46905)
127.0.0.1 - - [18/Mar/2016 04:33:47] "GET /socket.io/?EIO=3&transport=polling&t=LE8s-k4 HTTP/1.1" 200 381 0.001240
(12280) accepted ('127.0.0.1', 46906)
127.0.0.1 - - [18/Mar/2016 04:33:47] "GET /socket.io/?EIO=3&transport=polling&t=LE8s-kU&sid=a00778ef504b41f2a545edc21bb74f11 HTTP/1.1" 200 215 0.034278
Traceback (most recent call last):
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 481, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/socketio/server.py", line 303, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/engineio/server.py", line 226, in handle_request
    environ, start_response)
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/engineio/socket.py", line 83, in handle_get_request
    self.close(wait=False)
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/engineio/socket.py", line 102, in close
    self.send(packet.Packet(packet.CLOSE))
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/engineio/socket.py", line 61, in send
    self.close(wait=False, abort=True)
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/engineio/socket.py", line 100, in close
    self.server._trigger_event('disconnect', self.sid)
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/engineio/server.py", line 330, in _trigger_event
    return self.handlers[event](*args)
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/socketio/server.py", line 444, in _handle_eio_disconnect
    self._handle_disconnect(sid, '/')
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/socketio/server.py", line 360, in _handle_disconnect
    if namespace == '/' and self.manager.is_connected(sid, namespace):
  File "/home/lihe/Developer/workspace/tweetmap2/env/local/lib/python2.7/site-packages/socketio/base_manager.py", line 38, in is_connected
    return sid in self.rooms[namespace][None] and \
KeyError: '/'

127.0.0.1 - - [18/Mar/2016 04:34:47] "GET /socket.io/?EIO=3&transport=polling&t=LE8s-l5&sid=a00778ef504b41f2a545edc21bb74f11 HTTP/1.1" 500 2726 60.006727
127.0.0.1 - - [18/Mar/2016 04:34:47] "GET /socket.io/?EIO=3&transport=websocket&sid=a00778ef504b41f2a545edc21bb74f11 HTTP/1.1" 200 0 60.064034
(12280) accepted ('127.0.0.1', 46907)
127.0.0.1 - - [18/Mar/2016 04:34:48] "GET /socket.io/?EIO=3&transport=polling&t=LE8tDZq HTTP/1.1" 200 381 0.000883
(12280) accepted ('127.0.0.1', 46908)
127.0.0.1 - - [18/Mar/2016 04:34:48] "GET /socket.io/?EIO=3&transport=polling&t=LE8tDa1&sid=a3b852f7135e4ab790fcf43ec7381bc9 HTTP/1.1" 200 215 0.043442
```
And my freezed requirements file is:
```
boto3==1.3.0
botocore==1.4.4
certifi==2016.2.28
docutils==0.12
elasticsearch==2.3.0
eventlet==0.18.4
Flask==0.10.1
Flask-SocketIO==2.2
futures==3.0.5
greenlet==0.4.9
gunicorn==18.0
itsdangerous==0.24
Jinja2==2.8
jmespath==0.9.0
langdetect==1.0.5
M2Crypto==0.23.0
MarkupSafe==0.23
nltk==3.2
oauthlib==1.0.3
python-dateutil==2.5.0
python-engineio==0.9.0
python-socketio==1.1
requests==2.9.1
requests-oauthlib==0.6.1
six==1.10.0
textblob==0.11.1
tweepy==3.5.0
urllib3==1.14
Werkzeug==0.11.4
```
Although gunicorn is in my requirements file, this error occurs without usage of gunicorn server. However, if I use gunicorn server, the error code change to 400 instead of 500. The error message reported by gunicorn is Response object has no status_code field.

**Comment by miguelgrinberg** [comment]
Can you share your client script please?

**Comment by doomdagger** [comment]
Of course.

```javascript
    var socket = io('http://' + document.domain + ':' + location.port);
    socket.on('connect', function() {
        console.log('connected');
    });
    socket.on('keywords search', function(tweets) {
        console.log(tweets);
    });
    socket.on('geo search', function(tweets) {
        console.log(tweets);
    });
    function keywords() {
        socket.emit('search keywords', { page: 0, keywords: ['job'] });
    }
    function geo() {
        socket.emit('search geo', { coordinates: [[-112, 41], [-110, 39]] });
    }
```

**Comment by christopher-abastar** [comment]
Hi Miguel,

I'm also experiencing these errors. python3.5 with latest socketio/engine version.

```sh
[2016-03-21 05:27:17 +0000] [40609] [ERROR] Error handling request /socket.io/?transport=websocket&sid=4d176d899499413c9d935e1dc
ce819ae
Traceback (most recent call last):
  File "/home/vf/env/lib/python3.5/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/vf/env/lib/python3.5/site-packages/gunicorn/workers/async.py", line 112, in handle_request
    for item in respiter:
  File "/home/vf/env/lib/python3.5/site-packages/newrelic-2.58.2.45/newrelic/api/web_transaction.py", line 717, in __iter__
    for item in self.generator:
  File "/home/vf/env/lib/python3.5/site-packages/newrelic-2.58.2.45/newrelic/api/web_transaction.py", line 1093, in __call__
    self.start_response)
  File "/home/vf/env/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 303, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 226, in handle_request
    environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/socket.py", line 79, in handle_get_request
    start_response)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/socket.py", line 118, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/async_eventlet.py", line 13, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/websocket.py", line 127, in __call__
    self.handler(ws)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/socket.py", line 183, in _websocket_handler
    self.close(wait=True, abort=True)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/socket.py", line 100, in close
    self.server._trigger_event('disconnect', self.sid)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 330, in _trigger_event
    return self.handlers[event](*args)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 444, in _handle_eio_disconnect
    self._handle_disconnect(sid, '/')
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 357, in _handle_disconnect
    if n != '/' and self.manager.is_connected(sid, n):
  File "/home/vf/env/lib/python3.5/site-packages/socketio/base_manager.py", line 38, in is_connected
    return sid in self.rooms[namespace][None] and \
KeyError
```

**Comment by miguelgrinberg** [comment]
Please upgrade python-socketio to version 1.2. I think that will address this issue.
