### ISSUE TITLE
Emit function don't flush until parent function end.

### ISSUE THREAD

**Issue by rafaelcapucho** [miguelgrinberg/Flask-SocketIO#266]
Hello,

I was trying to do something like that:

```
@socketio.on('start', namespace='/queues')
def test_connect():
    while True:
        emit('testando resposta', {'data': 'conteudo da resposta'})
        eventlet.sleep(1)
```

Because I would like to send a real time stream that will feed a time series graph, but this approach doesn't work, if I remove the `while True` the message reach the client-side Ok when it is not within the loop, then I change to a loop that ends:

```
import eventlet
eventlet.monkey_patch()

import time
import flask
from flask_socketio import SocketIO, emit

app = flask.Flask(__name__)
app.config['SECRET_KEY'] = 'ha74%ahus342'
app.config['DEBUG'] = True

socketio = SocketIO(app, async_mode='eventlet')

@socketio.on('start', namespace='/queues')
def test_connect():
    for i in range(10):
        emit('testando resposta', {'data': 'conteudo da resposta'})
        eventlet.sleep(1)
    emit('testando resposta', {'data': 'conteudo da resposta 2'})

if __name__ == '__main__':
    socketio.run(app, host='0.0.0.0', debug=True)
```

And it actually worked, after 10 seconds the client get all those 10 messages.

How is the proper design to send periodically data (1/s) without this `while True` or how can I flush the emit inside the `while True` ?

**Comment by rafaelcapucho** [comment]
I changed to `gevent` instead of `eventlet` to test, the while problem was solved, the emit messages reaches the client, but I get those messages errors:


```
Traceback (most recent call last):
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/gevent/pywsgi.py", line 884, in handle_one_response
    self.run_application()
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/geventwebsocket/handler.py", line 70, in run_application
    self.result = self.upgrade_websocket()
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/geventwebsocket/handler.py", line 129, in upgrade_websocket
    return self.upgrade_connection()
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/geventwebsocket/handler.py", line 219, in upgrade_connection
    hashlib.sha1(key + self.GUID).digest())),
TypeError: Unicode-objects must be encoded before hashing
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive, Upgrade',
 'HTTP_COOKIE': 'io=c878511b776f4dc7828410f81ed9624b; '
                'csrftoken=uZZkpcQpwG9b4tIf2OuTsCZyDLnBAUdc; '
                'chaordic_browserId=db1c75b0-b5bd-11e5-a375-e3e8f4cb241f; '
                'chaordic_anonymousUserId=anon-db1c75b0-b5bd-11e5-a375-e3e8f4cb241f; '
                '_ga=GA1.4.2057341819.1462502293; pdtb_active=performance',
 'HTTP_HOST': '127.0.0.1:5000',
 'HTTP_ORIGIN': 'http://127.0.0.1:5000',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_SEC_WEBSOCKET_EXTENSIONS': 'permessage-deflate',
 'HTTP_SEC_WEBSOCKET_KEY': '9+yiZlhNZjFVW08hXikhKQ==',
 'HTTP_SEC_WEBSOCKET_VERSION': '13',
 'HTTP_UPGRADE': 'websocket',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 '
                    'Firefox/46.0',
 'PATH_INFO': '/socket.io/',
 'QUERY_STRING': 'EIO=3&transport=websocket&sid=c878511b776f4dc7828410f81ed9624b',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '33934',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost.localdomain',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.1 Python/3.5',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7fdfb41ceca8>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0),
 'wsgi.websocket': <geventwebsocket.websocket.WebSocket object at 0x7fdfb41d0ba8>,
 'wsgi.websocket_version': '13'} failed with TypeError

Traceback (most recent call last):
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/gevent/pywsgi.py", line 1253, in handle
    handler.handle()
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/gevent/pywsgi.py", line 916, in handle_one_response
    self.log_request()
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/geventwebsocket/handler.py", line 236, in log_request
    if '101' not in self.status:
TypeError: a bytes-like object is required, not 'str'
<Greenlet at 0x7fdfb415d0e0: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with TypeError
```

My code:
```
import gevent
from gevent import monkey, sleep
monkey.patch_all()

import flask
from flask_socketio import SocketIO, emit

app = flask.Flask(__name__)
app.config['SECRET_KEY'] = 'ha74%ahus342'
app.config['DEBUG'] = True

socketio = SocketIO(app, async_mode='gevent')

@socketio.on('start', namespace='/queues')
def test_connect():
    for i in range(10):
        emit('testando resposta', {'data': 'conteudo da resposta'})
        sleep(1)
    emit('testando resposta', {'data': 'conteudo da resposta 2'})

if __name__ == '__main__':
    socketio.run(app, host='0.0.0.0', debug=True)
```

Running on Python 3.5.1

**Comment by rafaelcapucho** [comment]
Sounds like `geventwebsocket` doesn't support Py3 yet [1][2].

I just `pip uninstall gevent-websocket` and it start work with only gevent, but I still don't know will eventlet was blocking the `emit`, 

Any ideas?


-----------
[1] - http://stackoverflow.com/questions/36501932/bottle-gevent-unicode-encoding-error
[2] - https://bitbucket.org/noppo/gevent-websocket/issues/54/python-3-support

**Comment by miguelgrinberg** [comment]
You are correct on gevent-websocket not working on Python 3, that unfortunately is not an option at this time.

I'm surprised you were not able to get eventlet to work. The way to get messages to "flush" is to sleep periodically, which you are already doing.

Something I'd like to suggest is that you make your event handlers short-lived. If you need to have a constant stream of events going to the client, then the best option is to start a background thread (eventlet or gevent green thread, not real system thread) and do that while loop outside of the event handler. The idea is to keep the event handling sub-system unblocked. I'm honestly not sure switching to a background thread will make eventlet work, while in terms of design that would be better, my initial impression is that the emits should have worked anyway.

I'll set up my own test based on your while loop to see if I can reproduce the problem.

**Comment by rafaelcapucho** [comment]
@miguelgrinberg Thank you.

The `while True` start hanging after a while, it make like 80 emitions and stop responding/freeze, what makes me believe on your **short-lives** handlers.

As a quick fix I'm using Js `setInterval` to emit from JS to flask that emit back to JS each second, but sounds like 2 hits instead of 1 without being effective.

I will rework using your approach, I don't know hot to use gevent thread yet but I will research. What is the problem in use the background thread (system) approach? I need this emitions to work as broadcast actually.

Thank you

**Comment by rafaelcapucho** [comment]
```
connected = False

@socketio.on('connect', namespace='/queues')
def connect():
    global connected
    connected = True
    print('conectou')

def teste(_url):
    while True:

        global connected
        print(_url)

        if connected:
            emit('testando resposta', {'data': []})

        gevent.sleep(1)

if __name__ == '__main__':
    gevent.spawn(teste, 'site.com.br')
    socketio.run(app, host='0.0.0.0', debug=True)

```

```
(beauty_monitor_venv) [kepler@localhost beauty_monitor]$ python3 main.py 
 * Restarting with stat
site.com.br
Traceback (most recent call last):
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "main.py", line 70, in teste
    emit('testando resposta', {'data': []})
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/flask_socketio/__init__.py", line 520, in emit
    namespace = flask.request.namespace
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/flask/globals.py", line 20, in _lookup_req_object
    raise RuntimeError('working outside of request context')
RuntimeError: working outside of request context
<Greenlet at 0x7f7574027f20: teste('site.com.br')> failed with RuntimeError

 * Debugger is active!
 * Debugger pin code: 130-666-932
```

**Comment by rafaelcapucho** [comment]
Changing to:

`emit('testando resposta', {'data': []}, namespace="/queues", room=False)`

```
site.com.br
Traceback (most recent call last):
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "main.py", line 82, in teste
    emit('testando resposta', {'data': []}, namespace="/queues", room=False)
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/flask_socketio/__init__.py", line 528, in emit
    socketio = flask.current_app.extensions['socketio']
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/home/kepler/Workspace/beauty/beauty_monitor_venv/lib/python3.5/site-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context
<Greenlet at 0x7fd1c5636f20: teste('site.com.br')> failed with RuntimeError
```

**Comment by rafaelcapucho** [comment]
`socketio.emit('testando resposta', {'data': queues}, namespace="/queues")`

These solve the problem of sending from thread outside flask request context :)

**Comment by miguelgrinberg** [comment]
Correct. The `emit()` function is context-aware, can only be used inside an event handler. In a background thread you have to use `socketio.emit()`, which takes all the required information from the given arguments.

**Comment by cglacet** [comment]
Is there a clean way to "flush" nowadays? If not, what is the minimum value I should use for the sleep duration?

**Comment by miguelgrinberg** [comment]
If you don't have any specific need to sleep and are using the call just to release the CPU to other tasks, use `sleep(0)`. In fact, if I wanted to implement a `flush()` function, it would do just that.

**Comment by patarapolw** [comment]
It seems that I always have to `gevent.sleep` after `flask_socketio.send`...
