### ISSUE TITLE
Constant exceptions under Python 3.5.1 running example

### ISSUE THREAD

**Issue by ssteinerx** [miguelgrinberg/Flask-SocketIO#272]
I already had gevent/greenlet installed so that's what Flask-socketIO chose.

gevent==1.1.1
gevent-websocket==0.9.5
greenlet==0.4.10

This shows up constantly with only the address of the greenlet changing each iteration.  This seems like an issue in greenlet or gevent, but I don't have a reproducible case other than this.

I've reported it there as well; this is mostly to document that this combination doesn't work at this time.

Traceback (most recent call last):
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/pywsgi.py", line 1253, in handle
    handler.handle()
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/.virtualenvs/lib/python3.5/site-packages/gevent/pywsgi.py", line 916, in handle_one_response
    self.log_request()
  File "/.virtualenvs/lib/python3.5/site-packages/geventwebsocket/handler.py", line 236, in log_request
    if '101' not in self.status:
TypeError: a bytes-like object is required, not 'str'
<Greenlet at 0x103e139c8: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with TypeError

**Comment by miguelgrinberg** [comment]
Package gevent-websocket has not been ported to Python 3 yet. Switch to Python 2.7 if you want to use this combination of packages, or if you want to stay with Py3 then drop gevent and use eventlet instead.
