### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Govinda-Fichtner** [miguelgrinberg/Flask-SocketIO#33]
I just tried to get started with Flask-SocketIO. I cloned the repository and created a virtualenv and installed the packages from requirements.txt.

All went fine and I could start the application. It looks as if the application works from the browser, but I get the following error in the logs.
How can I make this work?

```
127.0.0.1 - - [2014-05-29 15:08:33] "GET /socket.io/?EIO=2&transport=polling&t=1401368913567-200 HTTP/1.1" 500 161 0.001329
Traceback (most recent call last):
  File "/Users/govindaf/workspace/Flask-SocketIO/example/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/Users/govindaf/workspace/Flask-SocketIO/example/venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/Users/govindaf/workspace/Flask-SocketIO/example/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 27, in __call__
    raise RuntimeError('You need to use a gevent-socketio server.')
RuntimeError: You need to use a gevent-socketio server.
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip,deflate,sdch',
 'HTTP_ACCEPT_LANGUAGE': 'de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': '127.0.0.1:5000',
 'HTTP_REFERER': 'http://127.0.0.1:5000/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36',
 'PATH_INFO': '/socket.io/',
 'QUERY_STRING': 'EIO=2&transport=polling&t=1401368919567-201',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '57512',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '1.0.0.127.in-addr.arpa',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x1054c71e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x1061bc610>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with RuntimeError
```

I am using Python 2.7.5 and  this is the output of "pip freeze":

```
Flask==0.10.1
Flask-SocketIO==0.3.7
Jinja2==2.7.2
MarkupSafe==0.18
Werkzeug==0.9.4
gevent==1.0
gevent-socketio==0.3.6
gevent-websocket==0.9.2
greenlet==0.4.2
itsdangerous==0.23
ujson==1.33
wsgiref==0.1.2
```

**Comment by djagdish** [comment]
After hours of trying to debug this by wrapping the regular Flask app in different gevent supported wsgi servers, simply changing the client library to an older version solved the issue. 

0.9.16 is available here: http://cdnjs.cloudflare.com/ajax/libs/socket.io/0.9.16/socket.io.min.js

**Comment by dan-compton** [comment]
0.9.17 also appears to cause failure
