### ISSUE TITLE
Random KeyError: 'flask.app'

### ISSUE THREAD

**Issue by KillianKemps** [miguelgrinberg/Flask-SocketIO#330]
Hello,

I began to use Flask-SocketIO today and it works quite well even though I randomly get a `KeyError: 'flask.app'`. When it happened until now, it didn't matter as my app still worked fine.

However, this time the error happened while my app was executing inside a `@retry` function so it made it retry several times until it crashed my app completely. So, now the error is really annoying.

Am I missing something while setting up `flask_socketio`?

You can see below the Traceback with some lines from my code `classroom_admin`, some from the `retrying` module and the rest from `flask_socketio`.

```
Traceback (most recent call last):
  File "./classroom_admin/views/create.py", line 231, in create_classrooms
    body)
  File "/usr/local/lib/python3.5/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.5/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.5/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "./classroom_admin/views/create.py", line 153, in exec_classroom_creation
    emit_info('Error while creating classroom: Trying again.')
  File "./classroom_admin/views/create.py", line 25, in emit_info
    socketio.emit('info', {'data': message})
  File "/usr/local/lib/python3.5/site-packages/flask_socketio/__init__.py", line 330, in emit
    callback=kwargs.get('callback'))
  File "/usr/local/lib/python3.5/site-packages/socketio/server.py", line 207, in emit
    self.manager.emit(event, data, namespace, room, skip_sid, callback)
  File "/usr/local/lib/python3.5/site-packages/socketio/base_manager.py", line 127, in emit
    self.server._emit_internal(sid, event, data, namespace, id)
  File "/usr/local/lib/python3.5/site-packages/socketio/server.py", line 377, in _emit_internal
    binary=binary))
  File "/usr/local/lib/python3.5/site-packages/socketio/server.py", line 388, in _send_packet
    self.eio.send(sid, encoded_packet, binary=False)
  File "/usr/local/lib/python3.5/site-packages/engineio/server.py", line 171, in send
    socket.send(packet.Packet(packet.MESSAGE, data=data, binary=binary))
  File "/usr/local/lib/python3.5/site-packages/engineio/socket.py", line 62, in send
    self.close(wait=False, abort=True)
  File "/usr/local/lib/python3.5/site-packages/engineio/socket.py", line 102, in close
    self.server._trigger_event('disconnect', self.sid, async=False)
  File "/usr/local/lib/python3.5/site-packages/engineio/server.py", line 357, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.5/site-packages/socketio/server.py", line 504, in _handle_eio_disconnect
    self._handle_disconnect(sid, '/')
  File "/usr/local/lib/python3.5/site-packages/socketio/server.py", line 416, in _handle_disconnect
    self._trigger_event('disconnect', '/', sid)
  File "/usr/local/lib/python3.5/site-packages/socketio/server.py", line 462, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.5/site-packages/flask_socketio/__init__.py", line 213, in _handler
    *args)
  File "/usr/local/lib/python3.5/site-packages/flask_socketio/__init__.py", line 561, in _handle_event
    app = self.server.environ[sid]['flask.app']
KeyError: 'flask.app'
```

**Comment by miguelgrinberg** [comment]
Do you have any non-standard configuration regarding WSGI middlewares in your application?

The `flask.app` entry is injected into the WSGI environment by the Flask-SocketIO middleware. From the stack trace it appears you have at least one client that appears to have bypassed this middleware when it connected to the server.

If you can think of anything that is unusual or non-standard about your app, let me know. I can easily prevent the error and I will, but not having access to the Flask instance is going to affect the application anyway, so I'd like to understand how that happened.

**Comment by KillianKemps** [comment]
I don't understand why the issue happens randomly (at least it seems). As I'm not sure if the configuration is unusual, I prefer to show the three main files:

`__init__.py`
```
from flask import Flask
from flask_assets import Environment
from flask_socketio import SocketIO

import yaml


app = Flask(__name__)
assets = Environment(app)

app.config['SECRET_KEY'] = 'somesecret!'

# This is the path to the upload directory
app.config['UPLOAD_FOLDER'] = 'uploads/'

[...]

socketio = SocketIO(app)
application = app

from .views import index, create
```

Here is the `wsgi.py` run by **UWSGI**:
(it imports `application` and `socketio` from the `__init__.py` above)

`wsgi.py`
```
import uuid

from classroom_admin import application
from classroom_admin import socketio

application.secret_key = str(uuid.uuid4())
application.debug = False

if __name__ == "__main__":
    import uuid
    application.secret_key = str(uuid.uuid4())
    application.debug = False
    socketio.run(application)
```

And when I use `flask_socketio` in my `create` view (imported from `__init__.py`):

`create.py`
```
[...]
from .. import app
from .. import socketio


# Send information about the process through websocket
def emit_info(message):
    socketio.emit('info', {'data': message})
[...]
```

**Comment by miguelgrinberg** [comment]
Are you using gevent in combination with uWSGI? That is the only supported configuration for uWSGI.

**Comment by KillianKemps** [comment]
Yes I installed `gevent`. I can even see the `101 Web Socket Handshake Protocol` in my browser network tools. 
However I see the `101` response every time I emit a message from the client. I'm not sure if that is normal. I have the feeling the connection is created with the client and immediately abandoned. 
(Note: there is always only one unique client connected to the server. The web app is not meant to be used by several people at the same time. And I already get this error locally on my computer.)

**Comment by miguelgrinberg** [comment]
Can you run the server with logging enabled? Just add `engineio_logger=True` to your `SocketIO` object constructor. That will show us if connections are constantly lost and regenerated as you suggested, which is not normal.

**Comment by KillianKemps** [comment]
Yes you can see the logs below. So, I think there is no issue of constantly regenerated connection, but you may see that some errors, like the `OSError` are weird.

```
3dcf2d65b8434b9bac3d34610da3b248: Sending packet OPEN data {'pingTimeout': 60000, 'pingInterval': 25000, 'upgrades': ['websocket'], 'sid': '3dcf2d65b8434b9bac3d34610da3b248'}
Socket: Got connected to client
3dcf2d65b8434b9bac3d34610da3b248: Sending packet MESSAGE data 0
3dcf2d65b8434b9bac3d34610da3b248: Received packet MESSAGE data 2["confirm",{"data":"I'm connected!"}]
Socket: received confirmation message: I'm connected!
[Sat Oct  8 18:21:12 2016] POST /socket.io/?EIO=3&transport=polling&t=LUbXmW5&sid=3dcf2d65b8434b9bac3d34610da3b248 => generated 2 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 117 bytes (3 switches on core 999)
3dcf2d65b8434b9bac3d34610da3b248: Received request to upgrade to websocket
3dcf2d65b8434b9bac3d34610da3b248: Sending packet NOOP data None
[Sat Oct  8 18:21:12 2016] GET /socket.io/?EIO=3&transport=polling&t=LUbXmWB&sid=3dcf2d65b8434b9bac3d34610da3b248 => generated
4 bytes in 326 msecs (HTTP/1.1 200) 3 headers in 131 bytes (3 switches on core 999)

[Here I waited and then refreshed the page]

3dcf2d65b8434b9bac3d34610da3b248: Failed websocket upgrade, expected UPGRADE packet, received None instead.
Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
  return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.5/site-packages/flask_socketio/__init__.py", line 41, in __call__
  start_response)
File "/usr/local/lib/python3.5/site-packages/engineio/middleware.py", line 47, in __call__
  return self.engineio_app.handle_request(environ, start_response)
File "/usr/local/lib/python3.5/site-packages/socketio/server.py", line 334, in handle_request
  return self.eio.handle_request(environ, start_response)
File "/usr/local/lib/python3.5/site-packages/engineio/server.py", line 277, in handle_request
  start_response(r['status'], r['headers'] + cors_headers)
OSError: headers already sent
[Sat Oct  8 18:21:12 2016] GET /socket.io/?EIO=3&transport=websocket&sid=3dcf2d65b8434b9bac3d34610da3b248 => generated 12 bytes
 in 39054 msecs (HTTP/1.1 101) 4 headers in 179 bytes (1 switches on core 998)
[Sat Oct  8 18:21:51 2016] GET / => generated 11177 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 82 bytes (3 switches on core 9
98)
7a7610c225244ede84c6fa819e4751eb: Sending packet OPEN data {'pingTimeout': 60000, 'pingInterval': 25000, 'upgrades': ['websocket'], 'sid': '7a7610c225244ede84c6fa819e4751eb'}
Socket: Got connected to client
7a7610c225244ede84c6fa819e4751eb: Sending packet MESSAGE data 0
[Sat Oct  8 18:21:52 2016] GET /socket.io/?EIO=3&transport=polling&t=LUbXwJF => generated 119 bytes in 2 msecs (HTTP/1.1 200) 4
 headers in 180 bytes (3 switches on core 997)
7a7610c225244ede84c6fa819e4751eb: Received packet MESSAGE data 2["confirm",{"data":"I'm connected!"}]
Socket: received confirmation message: I'm connected!
[Sat Oct  8 18:21:53 2016] POST /socket.io/?EIO=3&transport=polling&t=LUbXwQF&sid=7a7610c225244ede84c6fa819e4751eb => generate$
 2 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 117 bytes (3 switches on core 997)
7a7610c225244ede84c6fa819e4751eb: Received request to upgrade to websocket
7a7610c225244ede84c6fa819e4751eb: Sending packet NOOP data None
[Sat Oct  8 18:21:53 2016] GET /socket.io/?EIO=3&transport=polling&t=LUbXwQP&sid=7a7610c225244ede84c6fa819e4751eb => generated
4 bytes in 420 msecs (HTTP/1.1 200) 3 headers in 131 bytes (3 switches on core 997)
7a7610c225244ede84c6fa819e4751eb: Upgrade to websocket successful
Socket: Client disconnected
3dcf2d65b8434b9bac3d34610da3b248: Client is gone, closing socket
[Sat Oct  8 18:21:13 2016] GET /socket.io/?EIO=3&transport=polling&t=LUbXmhK&sid=3dcf2d65b8434b9bac3d34610da3b248 => generated
11 bytes in 60002 msecs (HTTP/1.1 400) 3 headers in 126 bytes (3 switches on core 999)
7a7610c225244ede84c6fa819e4751eb: Received packet PING data None
7a7610c225244ede84c6fa819e4751eb: Sending packet PONG data None
7a7610c225244ede84c6fa819e4751eb: Received packet PING data None
7a7610c225244ede84c6fa819e4751eb: Sending packet PONG data None
...
```

I realized that after having refreshed three times the page, I waited some moment each time, I get the `KeyError: 'flask.app'` error. I think, it would happen in any case, even without refreshing. I have to precise that I did nothing else than waiting and refreshing the page. Each time I refresh, a 'connect' event is triggered to check the connection and that's all.

`The error happens while a ping pong, without more context`
```
a3c22ec554c7491aa2ae29230bc79342: Received packet PING data None
a3c22ec554c7491aa2ae29230bc79342: Sending packet PONG data None
Traceback (most recent call last):
[...]
KeyError: 'flask.app'
```

**Comment by KillianKemps** [comment]
While I was searching the problem in my app, I also made tests with the example you shipped with Flask_SocketIO. I tried the example with **uWSGI** and **gevent** and I can reproduce the same error when I set `async_mode='threading'` in line 9 of `app.py`.

The command I used to run the example:
`uwsgi --http :8080 --gevent 1000 --http-websockets --master --wsgi-file app.py --callable app`

The error log I got with the example:
```
[pid: 21733|app: 0|req: 11/11] 127.0.0.1 () {40 vars in 1571 bytes} [Mon Oct 10 21:31:20 2016] GET /socket.io/?EIO=3&transport=polling&t=1476127880371-4&sid=5e73594345b943919259806bbd0cf622 => generated 71 bytes $
n 9228 msecs (HTTP/1.1 200) 3 headers in 131 bytes (3 switches on core 998)
Traceback (most recent call last):
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/flask_socketio/__init__.py", line 41, in __call__
    start_response)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/socketio/server.py", line 334, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/engineio/server.py", line 257, in handle_request
    socket.handle_post_request(environ)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/engineio/socket.py", line 97, in handle_post_request
    self.receive(pkt)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/engineio/socket.py", line 49, in receive
    async=self.server.async_handlers)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/engineio/server.py", line 357, in _trigger_event
    return self.handlers[event](*args)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/socketio/server.py", line 491, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/socketio/server.py", line 430, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/socketio/server.py", line 433, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/socketio/server.py", line 462, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/flask_socketio/__init__.py", line 213, in _handler
    *args)
  File "/home/killian/Developpement/Tutoriels/Flask-SocketIO/venv/lib/python3.5/site-packages/flask_socketio/__init__.py", line 561, in _handle_event
    app = self.server.environ[sid]['flask.app']
KeyError: 'flask.app'
```

I hoped I had a similar issue with my app, so I forced `async_mode='gevent'` on my app, but unfortunately I still get the error.

**Comment by miguelgrinberg** [comment]
The choice of async mode directly affects what web servers you can use. If you set `threading` as async mode, then you need to use the Flask development server. You cannot use gunicorn with that mode, and using uWSGI requires some custom configuration.

In most cases, it is best to leave the async mode unset, so that the best mode is determined at run time from the packages detected at runtime.

**Comment by tkisme** [comment]
change
```
SocketIO()
```
to 
```
SocketIO(message_queue='redis://')
```

can reproduce this bug
```
Traceback (most recent call last):
  File "/Users/tkisme/MEGAsync/cloud/workspace/hoho_login/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/tkisme/MEGAsync/cloud/workspace/hoho_login/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 41, in __call__
    start_response)
  File "/Users/tkisme/MEGAsync/cloud/workspace/hoho_login/venv/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/Users/tkisme/MEGAsync/cloud/workspace/hoho_login/venv/lib/python2.7/site-packages/socketio/server.py", line 334, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/Users/tkisme/MEGAsync/cloud/workspace/hoho_login/venv/lib/python2.7/site-packages/engineio/server.py", line 277, in handle_request
    start_response(r['status'], r['headers'] + cors_headers)
IOError: headers already sent

  File "/Users/tkisme/MEGAsync/cloud/workspace/hoho_login/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 561, in _handle_event
    app = self.server.environ[sid]['flask.app']
KeyError: 'flask.app'

```

**Comment by miguelgrinberg** [comment]
@tkisme when you do this:

    SocketIO(message_queue='redis://')

you are not passing the Flask application instance, which is required. Does the problem still exist if you pass the app as first argument here, or if you later call `socketio.init_app(app)`?

**Comment by Bolik** [comment]
I have the same issue with redis queue

**Comment by DirtyJerz** [comment]
I was having the same issue with uwsgi and gevent. solution was to just remove app from the socketio init. 

```python
from flask import Flask, render_template, request
from flask_socketio import SocketIO

app = Flask(__name__)
socketio = SocketIO(app)
```

changed to 

```python
from flask import Flask, render_template, request
from flask_socketio import SocketIO

app = Flask(__name__)
socketio = SocketIO()
```

**Comment by miguelgrinberg** [comment]
@Bolik can I see your code?

**Comment by miguelgrinberg** [comment]
I'm going to close this, as I have fixed the one known problem with uWSGI. Feel free to open a new issue if you still have problems.
