### ISSUE TITLE
TypeError: unhashable type: 'dict' against SID

### ISSUE THREAD

**Issue by gordol** [miguelgrinberg/Flask-SocketIO#408]
Any ideas?

```
2017-02-17 12:35:21,532 - c222819e8b8d4f77a6e4e10c0dd07157: Received packet MESSAGE data 2/analytics,["save_analytics_view",{DATAOBFUSCATED},"name":"Test"}]
2017-02-17 12:35:21,549 - received event "save_analytics_view" from c222819e8b8d4f77a6e4e10c0dd07157 [/analytics]
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/socketio/server.py", line 433, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/socketio/server.py", line 462, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask_socketio/__init__.py", line 213, in _handler
    *args)
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask_socketio/__init__.py", line 574, in _handle_event
    ret = handler(*args)
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask_socketio/__init__.py", line 213, in _handler
    *args)
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask_socketio/__init__.py", line 558, in _handle_event
    if sid not in self.server.environ:
TypeError: unhashable type: 'dict'

```

**Comment by miguelgrinberg** [comment]
Can you show me the output of `pip freeze` please?

**Comment by gordol** [comment]
Sure, no problem...

--local is okay, right?

```
» pip freeze --local
amqp==2.1.0
anyjson==0.3.3
apns==2.0.1
appy==0.9.4
attrdict==2.0.0
beautifulsoup4==4.5.1
billiard==3.5.0.1
biplist==1.0.1
blinker==1.4
boto3==1.4.3
botocore==1.4.93
CacheControl==0.11.7
cffi==1.8.2
clamd==1.0.2
click==6.6
click-plugins==1.0.3
cligj==0.4.0
closure==20160517
cssmin==0.2.0
cssutils==1.0.1
decorator==4.0.10
dill==0.2.5
docutils==0.13.1
enum34==1.1.6
eventlet==0.19.0
Flask==0.11.1
Flask-Admin==1.4.2
Flask-Assets==0.12
Flask-Bower==1.2.1
Flask-Cache==0.13.1
Flask-Cors==3.0.2
Flask-JWT==0.3.2
Flask-Login==0.3.2
Flask-Mail==0.9.1
flask-mongoengine==0.7.5
Flask-Principal==0.4.0
Flask-Script==2.0.5
Flask-Security==1.7.5
Flask-SocketIO==2.7.2
Flask-WTF==0.12
futures==3.0.5
geocoder==1.19.0
gitdb==0.6.4
GitPython==2.0.8
greenlet==0.4.10
gspread==0.4.1
gunicorn==19.6.0
htmlmin==0.1.10
httplib2==0.9.2
idna==2.1
ImageHash==2.2
inflect==0.2.5
ipaddress==1.0.17
iso3166==0.7
itsdangerous==0.24
jdcal==1.2
Jinja2==2.9.5
jmespath==0.9.0
jsmin==2.2.1
kombu==3.0.35
libipa==0.0.6
mapbox==0.10.1
markdown2==2.3.3
MarkupSafe==0.23
mongoengine==0.10.6
MonthDelta==0.9.1
natsort==5.0.1
numpy==1.11.1
oauth2client==1.5.2
pandas==0.18.1
passlib==1.6.5
Paste==2.0.3
PasteDeploy==1.5.2
Pillow==3.3.1
polyline==1.3.1
prettyprint==0.1.5
pudb==2016.2
py==1.4.32
py-dateutil==2.2
pyasn1==0.1.9
pyasn1-modules==0.0.8
pyClamd==0.3.17
pycparser==2.14
pycrypto==2.6.1
Pygments==2.1.3
PyJWT==1.4.2
pymongo==3.3.0
pyPdf==1.13
python-dateutil==2.5.3
python-engineio==1.0.3
python-magic==0.4.12
python-socketio==1.6.0
pytz==2016.6.1
PyWavelets==0.4.0
ratelim==0.1.6
redis==2.10.5
repoze.lru==0.6
requests==2.11.1
Routes==2.3.1
rsa==3.4.2
s3transfer==0.1.10
scipy==0.18.0
secretary==0.2.14
six==1.10.0
smmap==0.9.0
uritemplate==3.0.0
urwid==1.3.1
vine==1.1.2
webassets==0.12.0
WebOb==1.6.1
Werkzeug==0.11.11
WTForms==2.1
xlrd==1.0.0
XlsxWriter==0.9.6
```

**Comment by miguelgrinberg** [comment]
Thanks. That was just so that I can lookup the versions of the packages you were using.

Is there anything odd in how your `save_analytics_view` event handler is constructed? Do you have multiple `@socketio.on` decorators on that function, for example?

**Comment by gordol** [comment]
> Is there anything odd in how your save_analytics_view event handler is constructed?

Kinda? Let me give you some details... and show you some code. :)

I have a wrapper that I've built around socket.io... It's a little crazy. Basically it's holding all the connected socket clients so any spawned workers and such can be cleared when they disconnect.

When clients connect, some handlers spin up, and do some various things, like listen for pubsub messages from background workers, and it does some bootstrapping to send down previous data also... which is all based on the namespace and some IDs from our database.

Here's what my SocketWrapper class is like:


```python
def debug_print(msg):
    if app.debug:
        print(msg)


class SocketWrapper():
    def __init__(self, namespace='/'):

        self.redis = StrictRedis(db=2, **app.config['REDIS_ARGS'])
        self.sio = SocketIO(**app.config['SOCKETIO'])

        self.namespace = namespace
        self.client_listeners = {}

        self.redis_messages_key = '%s-messages' % self.namespace[1:].split('/')[0]
        self.redis_channel_key = self.namespace[1:].split('/')[0]
        self.master_channel = self.namespace[1:].split('/')[0]


    def emit(self, event, payload, room, namespace=None):
        self.sio.emit(event, payload, room=room, namespace=namespace or self.namespace)


    def connect_handler(self, request, current_user, summarize=False, inject_handlers=[]):
        debug_print(str(datetime.now()) + ' - Client %s connected to namespace: %s' % (request.sid, request.namespace))
        debug_print(str(datetime.now()) + ' - Bootstrapping...')

        for method in inject_handlers:
            sleep(0.001)
            debug_print(str(datetime.now()) + ' - Pushing injected method to worker queue: %s' % method.__name__)
            method.delay(request.namespace, request.sid, current_user.id, summarize)

        debug_print(str(datetime.now()) + ' - Connect handler on %s done for sid: %s ' % (request.namespace, request.sid))


    def kill_workers(self, sid):
        debug_print(str(datetime.now()) + ' - Broadcasting disconnect signal for sid (%s)' % sid)
        self.redis.publish('_worker_control', sid)


    def cleanup(self, recv_sid):
        debug_print(str(datetime.now()) + ' - Cleaning up client session: %s' % recv_sid)

        if recv_sid in self.client_listeners:
            session = self.client_listeners[recv_sid]
            for greenthread in session.greenthreads:
                sleep(0.001)
                debug_print(str(datetime.now()) + ' - Killing greenlet: %s' % greenthread)
                greenthread.kill()

            for local_pubsub in session.pubsub_listeners:
                sleep(0.001)
                debug_print(str(datetime.now()) + ' - Unsubscribing and closing local pubsub connection: %s' % local_pubsub)
                local_pubsub.close()

            del session
            # todo: wtf, sometimes recv_sid doesn't exist in listeners, but it did above to get to this point? race condition?
            try:
                del self.client_listeners[recv_sid]
                debug_print(str(datetime.now()) + ' - Purged client listeners for sid (%s)' % recv_sid)
            except:
                debug_print(str(datetime.now()) + ' - sid (%s) does not exist in client_listeners' % recv_sid)


    def listen_for_disconnect(self, sid):
        pubsub = self.redis.pubsub()
        pubsub.subscribe('_worker_control')

        debug_print(str(datetime.now()) + ' - Listening for client disconnect events for sid (%s)' % sid)

        failures = 0
        tries = 0

        while True:
            sleep(.5)
            tries = tries + 1
            try:
                m = pubsub.get_message()
            except:
                print('pubsub.get_message() failed for sid (%s)' % sid)
                m = False
                failures = failures + 1
                failure_rate = failures / float(tries)

                if failure_rate > 0.3:
                    print(str(datetime.now()) + ' - Pubsub get message failed too many times for sid (%s)...' % sid)
                    print(str(datetime.now()) + ' - ... tries : %s' % tries)
                    print(str(datetime.now()) + ' - ... failures: %s' % failures)
                    print(str(datetime.now()) + ' - ... failure rate: %s' % failure_rate)
                    self.cleanup(sid)
                    break

            if m and m['type'] == 'message':
                recv_sid = m['data']
                if recv_sid == sid and recv_sid in self.client_listeners:
                    self.cleanup(recv_sid)
                    break

                else:
                    debug_print(str(datetime.now()) + ' - Recieved client disconnect, but (%s) is not active in this listener' % recv_sid)

        pubsub.unsubscribe('_worker_control')
        pubsub.close()
        debug_print(str(datetime.now()) + ' - Cleaned up pubsub listeners for sid (%s) and unsubscrbed from worker control channel' % sid)


    def disconnect_handler(self, sid):
        self.kill_workers(sid)


    def flush(self, data, client=None, broadcast=False):
        queue = '%s-%s' % (self.redis_messages_key, client.id)
        channel = '%s-%s' % (self.redis_channel_key, client.id)

        json_data = json.dumps(data)

        replaced = False

        #try to update by ID
        try:
            idx = 0
            for previous_data in self.redis.lrange(queue, 0, -1):
                sleep(0.001)
                previous_data_obj = json.loads(previous_data)
                if previous_data_obj['id'] == str(data['id']):
                    replaced = True
                    self.redis.lset(queue, idx, json_data)
                    break
                idx += 1

        except KeyError:
            pass

        if not replaced:
            self.redis.rpush(queue, json_data)

        if broadcast:
            debug_print(str(datetime.now()) + ' - Publishing to channel: %s' % channel)
            self.redis.publish(channel, json_data)

```


And here's some of the spawned handlers...

```python

@delayable('socketio')
def emit_bootstrap_data(namespace, sid, user_id, summarize):
    sio = SocketWrapper(namespace=namespace)
    current_user = models.User.objects(id=user_id).get()

    bootstrap = []

    def bootstrap_client_data(client_id):
        redis_key = '%s-%s' % (sio.redis_messages_key, client_id)
        messages = sio.redis.lrange(redis_key, 0, -1)

        if len(messages):

            for message in messages:
                data = json.loads(message)

                if summarize:
                    pass #hiding our unrelated business logic that does some things to data

                bootstrap.append(data)

    if current_user.client:
        #drop in data for a single client
        bootstrap_client_data(current_user.client.id)

    else:
        #drop in data for all clients
        for client in models.Client.objects().all():
            bootstrap_client_data(client.id)

    #tell socket clients to flush so they can receive fresh data
    sio.emit('bootstrap-%s-flush' % sio.master_channel, "kersplooosh", room=sid)

    #chunk out the data to prevent client, server, and workers from choking on large messages
    for chunk in chunks(bootstrap, 2000):
        sio.emit('bootstrap-%s' % sio.master_channel, chunk, room=sid)

    debug_print(str(datetime.now()) + ' - Sent bootstrap data for channel: %s' % sio.master_channel)


@delayable('socketio')
def spawn_pubsub_greenlets(namespace, sid, user_id, summarize):
    sio = SocketWrapper(namespace=namespace)
    spawn(sio.listen_for_disconnect, sid)

    if sid not in sio.client_listeners:
        sio.client_listeners[sid] = AttrDict(pubsub_listeners=[], greenthreads=[])

    current_user = models.User.objects(id=user_id).get()

    def channel_event_listener(channel):
        socket_channel = channel

        def client_event_listener(redis_channel):
            pubsub = sio.redis.pubsub()
            pubsub.subscribe(redis_channel)
            sio.client_listeners[sid].pubsub_listeners.append(pubsub)

            debug_print(str(datetime.now()) + ' - Subscribed to redis channel: %s and emitting to socket channel: %s' % (redis_channel, socket_channel))

            while True:
                sleep(.5)
                m = pubsub.get_message()
                if m and m['type'] == 'message':
                    data = json.loads(m['data'])
                    sio.emit(socket_channel, data, room=sid)

            pubsub.close()

        if current_user.client:
            debug_print(str(datetime.now()) + ' - Spawning event listener for single client')
            #drop in data for a single client
            client_channel_key = '%s-%s' % (sio.redis_channel_key, current_user.client.id)
            sio.client_listeners[sid].greenthreads.append(spawn(client_event_listener, client_channel_key))

        else:
            debug_print(str(datetime.now()) + ' - Spawning event listener for multiple clients')
            #drop in data for all clients
            for client in models.Client.objects().all():
                client_channel_key = '%s-%s' % (sio.redis_channel_key, client.id)
                sio.client_listeners[sid].greenthreads.append(spawn(client_event_listener, client_channel_key))

    debug_print(str(datetime.now()) + ' - Spawning event listeners')
    sio.client_listeners[sid].greenthreads.append(spawn(channel_event_listener, sio.master_channel))


```



So, back in our namespace module, you can see how we use this wrapper and the handlers...

```python

sio = SocketWrapper(namespace = '/analytics')

@socketio.on('save_analytics_view', namespace='/analytics')
# @socketio.on('save_analytics_view', namespace='/analytics/summary')
@login_required
def analytics_save_analytics_view(data):

    try:
        view = models.AnalyticsView.objects(name=data['name'], client=current_user.client).get()
        view.state = data['state']
        view.save()
    except:
        view = models.AnalyticsView(name=data['name'], state=data['state'], client=current_user.client).save()

    analytics_views = [dict(name=v.name, state=v.state) for v in models.AnalyticsView.objects(client=current_user.client).all()]
    emit('analytics_views', analytics_views, broadcast=True)


@delayable('socketio')
def emit_analytics_views(namespace, sid, user_id, summarize):
    sio = SocketWrapper(namespace=namespace)
    current_user = models.User.objects(id=user_id).get()

    analytics_views = [dict(name=v.name, state=v.state) for v in models.AnalyticsView.objects(client=current_user.client).all()]
    sio.emit('analytics_views', analytics_views, room=sid)


@socketio.on('connect', namespace='/analytics/summary')
@login_required
def analytics_connect_summary():
    sio.connect_handler(request, current_user, summarize=True, inject_handlers=[emit_analytics_views, emit_bootstrap_data, spawn_pubsub_greenlets])

@socketio.on('connect', namespace='/analytics')
@login_required
def analytics_connect(summarize=False, limit_days=False):
    sio.connect_handler(request, current_user, summarize=False, inject_handlers=[emit_analytics_views, emit_bootstrap_data, spawn_pubsub_greenlets])

```


> Do you have multiple @socketio.on decorators on that function, for example?

Yep...

That's exactly what is causing it, actually. :)

I commented out the /analytics/summary decorator as seen above, and now it works...

If I add two decorators, it seems to break, both receiving, and sending of socket messages by the wrapped methods. The socket.io server receives messages from the client, but they don't get routed to the handlers, and it seems the server thinks it's sending the messages, but they are never received by the client either.

This is a trivial fix on my end, it'll just cause a little duplicated code to have one handler for each namespace. Basically, our /analytics and /analytics/summary business logic is 99% the same, but the /analytics/summary is an abbreviated dataset.

**Comment by gordol** [comment]
> # todo: wtf, sometimes recv_sid doesn't exist in listeners, but it did above to get to this point? race condition?

i forgot about this until now... i believe there are some other bugs floating around here in regards to sid being missing too... hmm.

**Comment by miguelgrinberg** [comment]
@gordol just pushed version 2.8.4. Please upgrade to that to get this bug fixed (and make sure all the dependencies are also upgraded).

**Comment by gordol** [comment]
pip handles dependency upgrades, right? just tested, works great! thanks!
