### ISSUE TITLE
Manager initialize in SocketIOTestClient fails - compatibility issue related to #406 ?

### ISSUE THREAD

**Issue by jwg4** [miguelgrinberg/Flask-SocketIO#415]
This is slightly mysterious. My unit tests are crashing with:

```
======================================================================
ERROR: test_connect (test.test_admin_event_with_response.AdminInterfaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/socket_testing.py", line 13, in setUp
    self.socket_client = socketio.test_client(self.app)
  File "/home/jack/git/flask-prismfp/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 569, in test_client
    return SocketIOTestClient(app, self, namespace)
  File "/home/jack/git/flask-prismfp/venv/lib/python2.7/site-packages/flask_socketio/test_client.py", line 51, in __init__
    socketio.server.manager.initialize(socketio.server)
TypeError: initialize() takes exactly 1 argument (2 given)

----------------------------------------------------------------------
Ran 1 test in 2.027s

FAILED (errors=1)
```

My requirements is 
```
alembic==0.6.5
appdirs==1.4.1
cairocffi==0.6
CairoSVG==1.0.9
cffi==0.8.6
cssselect==0.9.1
factory-boy==2.5.2
fake-factory==0.5.0
Flask==0.10.1
Flask-Autodoc==0.1.2
Flask-Bootstrap==3.2.0.2
flask-ldap-login==0.3.0
Flask-Login==0.2.11
Flask-Migrate==1.2.0
Flask-Moment==0.4.0
Flask-Redis==0.1.0
Flask-Restless==0.14.2
Flask-Script==2.0.5
Flask-SocketIO==2.8.1
Flask-SQLAlchemy==1.0
Flask-Triangle==0.5.4
Flask-WeasyPrint==0.4
Flask-WTF==0.10.2
gevent==1.1.2
gevent-websocket==0.9.5
greenlet==0.4.4
gunicorn==19.1.1
html5lib==0.999
inflect==0.2.4
ipdb==0.8
ipython==2.1.0
itsdangerous==0.24
Jinja2==2.7.3
jsonschema==2.4.0
lxml==3.4.1
Mako==1.0.0
MarkupSafe==0.23
mimerender==0.5.4
mock==1.0.1
packaging==16.8
passlib==1.6.5
prmutils-calendar==20150810
psycopg2==2.5.3
pycparser==2.10
pyparsing==2.1.10
pyperclip==1.5.9
Pyphen==0.9.1
python-dateutil==2.4.2
python-engineio==1.2.3
python-ldap==2.4.18
python-mimeparse==0.1.4
python-socketio==1.7.1
pytz==2014.7
redis==2.10.5
requests==2.4.3
selenium==2.51.1
six==1.10.0
sqlacodegen==1.1.4
SQLAlchemy==0.9.7
tinycss==0.3
WeasyPrint==0.23
Werkzeug==0.9.6
WTForms==2.0.1
```

Previously the tests passed with requirements
```
BeautifulSoup==3.2.1
Flask==0.10.1
Flask-Autodoc==0.1.2
Flask-Bootstrap==3.2.0.2
Flask-Login==0.2.11
Flask-Migrate==1.2.0
Flask-Moment==0.4.0
Flask-Redis==0.1.0
Flask-Restless==0.14.2
Flask-SQLAlchemy==1.0
Flask-Script==2.0.5
Flask-SocketIO==2.6.1
Flask-Triangle==0.5.4
Flask-WTF==0.10.2
Flask-WeasyPrint==0.4
Jinja2==2.7.3
Mako==1.0.0
MarkupSafe==0.23
Pyphen==0.9.1
SQLAlchemy==0.9.7
WTForms==2.0.1
WeasyPrint==0.23
Werkzeug==0.9.6
alembic==0.6.5
argparse==1.2.1
cairocffi==0.6
cffi==0.8.6
cssselect==0.9.1
factory-boy==2.5.2
fake-factory==0.5.0
flask-ldap-login==0.3.0
gevent==1.1.2
gevent-websocket==0.9.5
greenlet==0.4.4
gunicorn==19.1.1
html5lib==0.999
inflect==0.2.4
ipdb==0.8
ipython==2.1.0
itsdangerous==0.24
jsonschema==2.4.0
lxml==3.4.1
mimerender==0.5.4
mock==1.0.1
passlib==1.6.5
prmutils-calendar==20150810
psycopg2==2.5.3
pycparser==2.10
pyperclip==1.5.9
python-dateutil==2.4.2
python-engineio==0.9.2
python-ldap==2.4.18
python-mimeparse==0.1.4
python-socketio==1.4.4
pytz==2014.7
redis==2.10.5
requests==2.4.3
selenium==2.51.1
six==1.8.0
sqlacodegen==1.1.4
tinycss==0.3
wsgiref==0.1.2
```

Sorry about the re-ordering of the requirements. That's tests failing with:

```
Flask==0.10.1
Flask-SocketIO==2.8.1
python-engineio==1.2.3
python-socketio==1.7.1
```

tests passing with:

```
Flask==0.10.1
Flask-SocketIO==2.6.1
python-engineio==0.9.2
python-socketio==1.4.4
```

The failure occurs in the setUp of the unit test. The setUpClass creates a Flask app called self.app, and then

```
    def setUp(self):
        self.client = self.app.test_client()
        self.socket_client = socketio.test_client(self.app)
```

I saw https://github.com/miguelgrinberg/Flask-SocketIO/issues/406 but I can't untangle the changes in dependency, and the fact that the error in the number of arguments is the wrong way around between that error and this.

Note that I had problems with a unit test before, because I was running the socket test client but using the Redis message queue in the app. I now make sure that this doesn't happen - and I upgraded to Flask-SocketIO version 2.8.1 specifically to have the error if you try and run the test client with an external message queue.

**Comment by miguelgrinberg** [comment]
This was reported a week or so ago (see #406). Should be fixed if you upgrade Flask-SocketIO to the latest release.

**Comment by jwg4** [comment]
I saw the other report, but wasn't sure if it was exactly the same error. However upgrading seems to have fixed it, thanks.
