### ISSUE TITLE
Does flask-socketio support ArrayBuffer with WebSocket? 

### ISSUE THREAD

**Issue by crf1111** [miguelgrinberg/Flask-SocketIO#426]
the code as following:
```python
import numpy as np
....
arr = np.arange(10, dtype=np.float32)
buf = arr.tobytes()

socketio.emit('my_response', buf)

```

but it raised some errors : 
```shell
emitting event "my_response" to all [/test]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "app.py", line 43, in background_thread
    namespace='/test')
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 346, in emit
    skip_sid=skip_sid, callback=callback, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 221, in emit
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/socketio/base_manager.py", line 133, in emit
    self.server._emit_internal(sid, event, data, namespace, id)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 396, in _emit_internal
    binary=binary))
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 400, in _send_packet
    encoded_packet = pkt.encode()
  File "/usr/local/lib/python2.7/dist-packages/socketio/packet.py", line 71, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 6: invalid start byte

```

can some one give me some ideas to solve this problems?

**Comment by miguelgrinberg** [comment]
Try sending your binary data as a member inside a dictionary:

    socketio.emit('my_response', {'data': buf})

**Comment by crf1111** [comment]
hi @miguelgrinberg : 
thanks for your answer, I tried it. But it raises the some error. Can you @miguelgrinberg  give me some other ideas ?  
thanks again.

**Comment by miguelgrinberg** [comment]
Oh, sorry, just noticed you are using Python 2.7! See https://python-socketio.readthedocs.io/en/latest/#socketio.Server, if you want to support binary payloads you have to pass `binary=True` to your `SocketIO` object. Unfortunately when you do that, you then need to make sure all tests are passed as unicode, if not they'll also be sent as binary and that'll confuse your client.

My recommendation is that if you can, you switch to Python 3, where binary data is handled properly without any custom configuration.

**Comment by crf1111** [comment]
Thanks @miguelgrinberg , I fixed it by using Python3.5.2. 
thanks again.

**Comment by miguelgrinberg** [comment]
@cwhatley I think you mean Python 2, not Python 7 :)

**Comment by cwhatley** [comment]
"2.7", but yes. Thanks!
