### ISSUE TITLE
missing module socketio

### ISSUE THREAD

**Issue by cydrobolt** [miguelgrinberg/Flask-SocketIO#45]
I can't import `flask-socketio` because of a missing `socketio` package.

```
(env)[cydrobolt@new-host-2 pychattr-doge]$ python
Python 2.7.5 (default, Jun 25 2014, 10:19:55) 
[GCC 4.8.2 20131212 (Red Hat 4.8.2-7)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask import Flask, render_template
>>> from flask.ext.socketio import SocketIO, emit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cydrobolt/PyDev/pychattr-doge/env/lib/python2.7/site-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/home/cydrobolt/PyDev/pychattr-doge/env/lib/python2.7/site-packages/flask_socketio/__init__.py", line 5, in <module>
    from socketio import socketio_manage
ImportError: No module named socketio
>>> quit()
Exception KeyError: KeyError(140084549336112,) in <module 'threading' from '/usr/lib64/python2.7/threading.pyc'> ignored

```

**Comment by sreezree** [comment]
from flask_socketio import SocketIO, send
ImportError: No module named 'flask_socketio'
 can anyone help....i installed socketio using and -H.....and still i am getting this error
