### ISSUE TITLE
Unable to use eventlet. gevent works. 

### ISSUE THREAD

**Issue by ColdHeat** [miguelgrinberg/Flask-SocketIO#457]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 261, in handle_request
    environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 89, in handle_get_request
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 136, in _upgrade_websocket
    return ws(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/async_eventlet.py", line 11, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
```

If I pip install eventlet, my application refuses to run. It will work more or less with the built in server or gevent. Sessions seem to die unexpectedly but I suspect it has to do with some threading issues. I just don't understand why I can't use eventlet.

**Comment by miguelgrinberg** [comment]
How are you starting the server? This error means that you are not using an eventlet web server.

**Comment by ColdHeat** [comment]
```
from webapplication import create_app

app = create_app()
app.run(debug=True, threaded=True, port=8888)
```

```
from flask import Flask, render_template
from flask_socketio import SocketIO, emit

socketio = SocketIO()

def create_app(config='webapplication.config.Config'):
    app = Flask(__name__)
    with app.app_context():
        app.config.from_object(config)
        socketio.init_app(app)

        from views import views

        app.register_blueprint(views)

        return app
```

This is the structure.

**Comment by miguelgrinberg** [comment]
The server needs to be started in a different way, `app.run()` does not work for Socket.IO, you have to use `socketio.run()` instead. See the example: https://flask-socketio.readthedocs.io/en/latest/#initialization.

**Comment by ColdHeat** [comment]
Thanks, I got it figured out. 

https://github.com/miguelgrinberg/Flask-SocketIO/issues/279 This was useful.
