### ISSUE TITLE
websocket not working

### ISSUE THREAD

**Issue by ArunMj** [miguelgrinberg/Flask-SocketIO#458]
After upgrading dependency packages, Flask-SocketIO fails to connect via websocket and fallback to long-polling mode [ it was previously worked for me ] 

```
 * Detected change in '/usr/local/lib/python2.7/dist-packages/engineio/socket.py', reloading
('Client disconnected', 'c21c5b5e854c4ef093aec457ab9cb988')
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 158-463-196
(17360) wsgi starting up on http://127.0.0.1:5000
(17360) accepted ('127.0.0.1', 65488)
127.0.0.1 - - [09/May/2017 16:32:20] "GET /socket.io/?EIO=3&transport=polling&t=1494327740606-221 HTTP/1.1" 200 381 0.000761
(17360) accepted ('127.0.0.1', 65490)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 507, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 261, in handle_request
    environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 89, in handle_get_request
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 136, in _upgrade_websocket
    return ws(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/async_eventlet.py", line 19, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/websocket.py", line 127, in __call__
    self.handler(ws)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 142, in _websocket_handler
    if hasattr(ws, attr) and hasattr(ws.attr, 'settimeout'):
AttributeError: 'RFC6455WebSocket' object has no attribute 'attr'
127.0.0.1 - - [09/May/2017 16:32:20] "GET /socket.io/?EIO=3&transport=websocket&sid=5a8b0eacc44c4c3f985438412aae66e8 HTTP/1.1" 500 1799 0.001889
127.0.0.1 - - [09/May/2017 16:32:20] "GET /socket.io/?EIO=3&transport=polling&t=1494327740611-5 HTTP/1.1" 200 381 0.000788
(17360) accepted ('127.0.0.1', 65492)
127.0.0.1 - - [09/May/2017 16:32:20] "POST /socket.io/?EIO=3&transport=polling&t=1494327740618-222&sid=5a8b0eacc44c4c3f985438412aae66e8 HTTP/1.1" 200 219 0.002287
127.0.0.1 - - [09/May/2017 16:32:20] "GET /socket.io/?EIO=3&transport=polling&t=1494327740620-223&sid=5a8b0eacc44c4c3f985438412aae66e8 HTTP/1.1" 200 280 0.000230
(17360) accepted ('127.0.0.1', 65494)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 507, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 261, in handle_request
    environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 89, in handle_get_request
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 136, in _upgrade_websocket
    return ws(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/async_eventlet.py", line 19, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/websocket.py", line 127, in __call__
    self.handler(ws)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 142, in _websocket_handler
    if hasattr(ws, attr) and hasattr(ws.attr, 'settimeout'):
AttributeError: 'RFC6455WebSocket' object has no attribute 'attr'
127.0.0.1 - - [09/May/2017 16:32:20] "GET /socket.io/?EIO=3&transport=websocket&sid=75f0b094ac6140e9916b74c76d6c9283 HTTP/1.1" 500 1799 0.000348
127.0.0.1 - - [09/May/2017 16:32:20] "POST /socket.io/?EIO=3&transport=polling&t=1494327740631-6&sid=75f0b094ac6140e9916b74c76d6c9283 HTTP/1.1" 200 219 0.000982
127.0.0.1 - - [09/May/2017 16:32:20] "GET /socket.io/?EIO=3&transport=polling&t=1494327740635-7&sid=75f0b094ac6140e9916b74c76d6c9283 HTTP/1.1" 200 280 0.000176
127.0.0.1 - - [09/May/2017 16:32:20] "POST /socket.io/?EIO=3&transport=polling&t=1494327740635-224&sid=5a8b0eacc44c4c3f985438412aae66e8 HTTP/1.1" 200 219 0.000954
```

**Comment by kosmiciatakuja** [comment]
This is actually an issue in the python-engineio library, reported here: https://github.com/miguelgrinberg/python-engineio/issues/46
There's also a patch posted there.
