### ISSUE TITLE
Session is disconnected. Empty session on socket.io connect (current_user is Anonymous)

### ISSUE THREAD

**Issue by alexanderbladyko** [miguelgrinberg/Flask-SocketIO#477]
I'm doing HTTP post to API, which logins user. 
`login_user(user, remember=True)`
(Pdb) import flask
After login_user:
```(Pdb) flask.session
<SecureCookieSession {'_id': '938c42dd9ec74a9e69e04eaef77514533a970fe7f707dca4a8895b8c31b1ad293c2a5aa0527c1f3b17e4a1dbc1e23249a85f191c6cc94302538ed4210f3a1b98', 'remember': 'set', 'user_id': '2', '_fresh': True}>
```

```
@io.on('connect')
def ws_connect():
    import pdb; pdb.set_trace()
    if current_user.is_authenticated:
        app.logger.info(
            'User (%s, %s) connected' % (current_user.id, current_user.name)
        )
        emit('handshake', 'connected')
        ensure_user(current_user)
    else:
        return None
```

Current user is Anonymous. and session is:
```
(Pdb) import flask
(Pdb) flask.session
<SecureCookieSession {}>
```

pip freeze:
```
Flask==0.12.2
Flask-Login==0.4.0
Flask-Script==2.0.5
Flask-SocketIO==2.8.6
Flask-Testing==0.6.2
gevent==1.2.1
greenlet==0.4.12
python-engineio==1.5.4
python-slugify==1.2.4
python-socketio==1.7.5
```

Not sure, but there is trace after a while:
```
Traceback (most recent call last):
  File "/home/alex/.virtualenvs/energynet/lib/python3.5/site-packages/gevent/pywsgi.py", line 936, in handle_one_response
    self.run_application()
  File "/home/alex/.virtualenvs/energynet/lib/python3.5/site-packages/gevent/pywsgi.py", line 909, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/alex/.virtualenvs/energynet/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/alex/.virtualenvs/energynet/lib/python3.5/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/home/alex/.virtualenvs/energynet/lib/python3.5/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/alex/.virtualenvs/energynet/lib/python3.5/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/alex/.virtualenvs/energynet/lib/python3.5/site-packages/engineio/server.py", line 258, in handle_request
    socket = self._get_socket(sid)
  File "/home/alex/.virtualenvs/energynet/lib/python3.5/site-packages/engineio/server.py", line 411, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
```

**Comment by alexanderbladyko** [comment]
Looks like issue is with the nginx config. No idea how to proxy cookies to different localhost ports

**Comment by miguelgrinberg** [comment]
@alexanderbladyko do you mean that if you remove nginx the cookie appears in the socket.io connect event handler?

Does the cookie appears in other HTTP routes after you call login_user()? If the problem is with nginx, I would expect no other endpoints will see it.

**Comment by ebagdasa** [comment]
hey, what was the solution to your problem?
