### ISSUE TITLE
Polling: crashing due to too many threads

### ISSUE THREAD

**Issue by fedorbirjukov** [miguelgrinberg/Flask-SocketIO#482]
My service crashes after 24 hours or less due to SocketIO server. Any help is appreciated.

Code:
```
from   flask          import Flask, jsonify, request, abort
from   flask_socketio import SocketIO, send, emit
from   flask_cors     import CORS
app = Flask(__name__)
CORS(app)
app.config['SECRET_KEY'] = binascii.hexlify(os.urandom(24))
socketio = SocketIO(app, async_mode='threading')
if __name__ == "__main__":
	socketio.run(app, host="0.0.0.0", port=80, debug=True, use_reloader=False)

```

Log:
```
Traceback (most recent call last):
  File "orchestrator.py", line 621, in <module>
    socketio.run(app, host="0.0.0.0", port=80, debug=True, use_reloader=False)
  File "/usr/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 469, in run
    use_reloader=use_reloader, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 702, in inner
    srv.serve_forever()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 539, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib64/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 607, in process_request
    t.start()
  File "/usr/lib64/python2.7/threading.py", line 739, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
Exception in thread Thread-20189 (most likely raised during interpreter shutdown):Exception in thread Thread-20235 (most likely raised during interpreter shutdown):Exception in thread Thread-20238 (most likely raised during interpreter shutdown):Exception in thread Thread-20232 (most likely raised during interpreter shutdown):Exception in thread Thread-20201 (most likely raised during interpreter shutdown):

```

UPDATE: I was disconnecting and reconnecting my client socket a lot. I would like to be wrong but from what I've seen I think that this server is likely to crash, it's just a matter of time.

**Comment by fedorbirjukov** [comment]
By the way, socket connections are constantly switching from 'connected' to 'disconnected' and back.

I know this because I track their status
```
on('connect', function(){status='connected'})
on('disconnect', function(){status='disconnected'})
```

**Comment by miguelgrinberg** [comment]
You are using the threading mode, which uses the development web server from Flask. This isn't a production web server, you can't expect it will work 24/7 in a production environment. Try one of the other async modes with either gunicorn or uwsgi.
