### ISSUE TITLE
Sudden Issues "RuntimeError: You need to use a gevent-socketio server"

### ISSUE THREAD

**Issue by cherston** [miguelgrinberg/Flask-SocketIO#488]
Hi, 

I've been successfully using Flask-SocketIO on my site for 1.5 years, and seemingly out of the blue I'm hit with a 502 Bad Gateway error. I'm using Flask, Flask-SocketIO, Gunicorn, and NGINX to serve the site. When I try to restart Gunicorn using: 

/var/www/sonification/sonification/venv/bin/gunicorn --bind 127.0.0.1:5001 --worker-class socketio.sgunicorn.GeventSocketIOWorker <appname>:app

where <appname> is my appname, I see an error: "ImportError: No module named <appname>"

The most recent error in my log file is copied below. I would sincerely appreciate any suggestions for restoring my site. 

```
2017-05-22 15:09:01 [2183] [INFO] Booting worker with pid: 2183

Traceback (most recent call last):

  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response

    self.run_application()

  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application

    self.result = self.application(self.environ, self.start_response)

  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__

    return self.wsgi_app(environ, start_response)

  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 27, in __call__

    raise RuntimeError('You need to use a gevent-socketio server.')

RuntimeError: You need to use a gevent-socketio server.

{'GATEWAY_INTERFACE': 'CGI/1.1',

 'HTTP_ACCEPT': '*/*',

 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',

 'HTTP_ACCEPT_LANGUAGE': 'en-US',

 'HTTP_CONNECTION': 'Upgrade',

 'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0;  Trident/5.0)',

 'PATH_INFO': '/socket.io/static/flashsocket/WebSocketMain.swf',

 'QUERY_STRING': '',

 'RAW_URI': '/socket.io/static/flashsocket/WebSocketMain.swf',

 'REMOTE_ADDR': '127.0.0.1',

 'REMOTE_PORT': '47258',

 'REQUEST_METHOD': 'GET',

 'SCRIPT_NAME': '',

 'SERVER_NAME': 'localhost',

 'SERVER_PORT': '5001',

 'SERVER_PROTOCOL': 'HTTP/1.1',

 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',

 'gunicorn.sock': <socket at 0x7f2bf594fb90 fileno=11 sock=127.0.0.1:5001 peer=127.0.0.1:47258>,

 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f2bfa0a31e0>,

 'wsgi.input': <gevent.pywsgi.Input object at 0x7f2bf585ff90>,

 'wsgi.multiprocess': False,

 'wsgi.multithread': False,

 'wsgi.run_once': False,

 'wsgi.url_scheme': 'http',

 'wsgi.version': (1, 0)} failed with RuntimeError



```

**Comment by miguelgrinberg** [comment]
Did you update your Flask-SocketIO version by any chance? From your log, I suspect you were using one of the 0.x releases, and now went to a 1.x or 2.x release. There are a lot of changes that you need to make if you upgrade Flask-SocketIO from the 0.x to the 1.x or 2.x release line, which are described in the documentation: https://flask-socketio.readthedocs.io/en/latest/#upgrading-to-flask-socketio-1-x-and-2-x-from-the-0-x-releases. I recommend that you revert your project back to the 0.x release that you were using, and then make the changes necessary for the upgrade on a development server.

**Comment by cherston** [comment]
Thanks for your prompt response. I wish something would jump out at me but as far as I can tell the dependencies are in order: 

```
user@site:/var/www/sonification/sonification$ source venv/bin/activate
(venv)user@site:/var/www/sonification/sonification$ pip freeze
/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.0.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Flask==0.10.1
Flask-Bootstrap==3.3.4.1
Flask-SocketIO==0.6.0
gevent==1.0.2
gevent-socketio==0.3.6
gevent-websocket==0.9.3
greenlet==0.4.7
gunicorn==18.0
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
uWSGI==2.0.10
Werkzeug==0.10.4
wheel==0.24.0
(venv)user@site:/var/www/sonification/sonification$ gunicorn --bind 127.0.0.1:5002 --worker-class socketio.sgunicorn.GeventSocketIOWorker sonification:app
2017-06-28 14:59:45 [23115] [INFO] Starting gunicorn 18.0
2017-06-28 14:59:45 [23115] [INFO] Listening at: http://127.0.0.1:5002 (23115)
2017-06-28 14:59:45 [23115] [INFO] Using worker: socketio.sgunicorn.GeventSocketIOWorker
2017-06-28 14:59:45 [23120] [INFO] Booting worker with pid: 23120
2017-06-28 14:59:45 [23120] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
ImportError: No module named sonification
Traceback (most recent call last):
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/sonification/sonification/venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
ImportError: No module named sonification
2017-06-28 14:59:45 [23120] [INFO] Worker exiting (pid: 23120)
2017-06-28 14:59:45 [23115] [INFO] Shutting down: Master
2017-06-28 14:59:45 [23115] [INFO] Reason: Worker failed to boot.
```

**Comment by miguelgrinberg** [comment]
The gevent-socketio package needs to be uninstalled, as it is outdated and not supported anymore.
