### ISSUE TITLE
handleconnect() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by red-green** [miguelgrinberg/Flask-SocketIO#501]
SocketIO seems to think my handler function is recieving the wrong number of arguments:

```
connect handler error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/engineio/server.py", line 398, in _trigger_event
    return self.handlers[event](*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/socketio/server.py", line 494, in _handle_eio_connect
    return self._handle_connect(sid, '/')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/socketio/server.py", line 414, in _handle_connect
    self.environ[sid]) is False:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/socketio/server.py", line 481, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_socketio/__init__.py", line 236, in _handler
    *args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_socketio/__init__.py", line 616, in _handle_event
    ret = handler()
TypeError: handleconnect() takes exactly 1 argument (0 given)
```

In my python file:

```
@socketio.on('connect')
def handleconnect(msg):
	c = db.cursor()
	cookie = msg['cookie']
	c.execute("SELECT nickname FROM users WHERE cookie=?",(cookie,))
	nickname = c.fetchone()[0]
	if nickname:
		emit('joined',{'nickname':nickname})
```

In my javascript:

```
$(document).ready(function () {
	let socket = io.connect(location.protocol + "//" + document.domain + ":" + location.port);
	socket.emit("connect", {"cookie":getCookie("session_id")});
....
```

Clearly the javascript is passing an argument, so why is SocketIO not calling it with one?

**Comment by red-green** [comment]
Actually I seem to have found the issue. The `connect` event is reserved or something by the library. See this code from [__init__.py](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L614):

```
try:
  if message == 'connect':
  ret = handler()
  else:
  ret = handler(*args)
```

Perhaps this should be mentioned in the tutorial/readme/docs, unless I have missed it.

**Comment by miguelgrinberg** [comment]
Yes, `connect`, `disconnect`, `message` and `json` are all reserved names by the Socket.IO protocol. I'll look into making this more clear in the docs.
