### ISSUE TITLE
Not working with debug mode on

### ISSUE THREAD

**Issue by taseppa** [miguelgrinberg/Flask-SocketIO#508]
Here is what happens after `flask run`

 ```
* Serving Flask-SocketIO app "test"
 * Forcing debug mode on
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 292-597-800
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/cli.py", line 56, in run_server
    return run_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 438, in run_command
    use_debugger=debugger, threaded=with_threads)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 737, in run_simple
    reloader_type)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 257, in run_with_reloader
    signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
ValueError: signal only works in main thread

```

Contents of test.py:
```

from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
        return 'Hello, World2!'
```

Everything working ok without debug mode.

**Comment by taseppa** [comment]
Issue was that even though im using flask run instead of starting with python test.py I still need to have
`socketio = SocketIO(app)` even though the variable is not used anywhere in code.

**Comment by miguelgrinberg** [comment]
If your `socketio` variable is not used, then why do you need Flask-SocketIO?

**Comment by taseppa** [comment]
I was just trying to simplify the reproduction of issue, but obviously ended up simplifying too much.

**Comment by jxltom** [comment]
I think @taseppa means flask application will raise error when debugging with ```flask run```, even without using flask-socketio but with an environment with flask-socketio installed. This is because ```flask run``` command will be overided when flask-socketio is installed even it is not used in the application.

**Comment by frozflame** [comment]
I removed the 'flask_socketio' package and the problem solved.
