### ISSUE TITLE
Can not use redis as message_queue

### ISSUE THREAD

**Issue by Schnodderbalken** [miguelgrinberg/Flask-SocketIO#553]
I have an application in which I want to use redis as a message_queue for socket-io. If I try to do that I get the following stack trace:

```
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    MainClass.main()
  File "main.py", line 32, in main
    m._start_web_socket_server()
  File "main.py", line 63, in _start_web_socket_server
    from logic.websocket import socket
  File "/usr/src/app/src/logic/websocket/socket.py", line 13, in <module>
    socketio = boot_strap.setup(app)
  File "/usr/src/app/src/logic/websocket/routing/bootstrap.py", line 22, in setup
    self._socketio = SocketIO(app, message_queue='redis://redis:6379/')
  File "/root/.local/lib/python3.5/site-packages/flask_socketio/__init__.py", line 147, in __init__
    self.init_app(app, **kwargs)
  File "/root/.local/lib/python3.5/site-packages/flask_socketio/__init__.py", line 172, in init_app
    write_only=write_only)
  File "/root/.local/lib/python3.5/site-packages/socketio/redis_manager.py", line 41, in __init__
    self.redis = redis.Redis.from_url(url)
AttributeError: module 'redis' has no attribute 'Redis'
```

That seems to imply that there is a wrong redis module imported. However if I print out the imported redis module during runtime it says `<module 'redis' from '/root/.local/lib/python3.5/site-packages/redis/__init__.py'>`. If I look at the file it seems to have all the stuff including "Redis":
```

from redis.client import Redis, StrictRedis
from redis.connection import (
    BlockingConnectionPool,
    ConnectionPool,
    Connection,
    SSLConnection,
    UnixDomainSocketConnection
)
from redis.utils import from_url
from redis.exceptions import (
    AuthenticationError,
    BusyLoadingError,
    ConnectionError,
    DataError,
    InvalidResponse,
    PubSubError,
    ReadOnlyError,
    RedisError,
    ResponseError,
    TimeoutError,
    WatchError
)


__version__ = '2.10.6'
VERSION = tuple(map(int, __version__.split('.')))

__all__ = [
    'Redis', 'StrictRedis', 'ConnectionPool', 'BlockingConnectionPool',
    'Connection', 'SSLConnection', 'UnixDomainSocketConnection', 'from_url',
    'AuthenticationError', 'BusyLoadingError', 'ConnectionError', 'DataError',
    'InvalidResponse', 'PubSubError', 'ReadOnlyError', 'RedisError',
    'ResponseError', 'TimeoutError', 'WatchError'
]

```

Strangely enough `dir(redis)` shows this: `['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_compat', 'connection', 'exceptions', 'utils']`

All this happens within a docker container which means that this error is reproducible. 
The base image I derive my docker image from is `python:3.5.2` and this is what my Dockerfile looks like:

```
FROM python:3.5.2

# Setup commands, to install dependencies
RUN \
    apt-get update &&\
    apt-get upgrade -y &&\
    apt-get install -y python3 tesseract-ocr tesseract-ocr-deu nginx graphicsmagick imagemagick build-essential libsqlite3-dev poppler-utils &&\
    apt-get install -y python3-pip virtualenv

# Install dependencies
COPY ./project/config/requirements.txt /usr/src/app/install/requirements.txt
RUN cd /usr/src/app/install && virtualenv -p python3 env && bash env/bin/activate && pip install -r /usr/src/app/install/requirements.txt --user --upgrade

# install pyinstaller
RUN ln /root/.local/bin/pyinstaller /usr/local/bin/pyinstaller

# install celery
RUN ln /root/.local/bin/celery /usr/local/bin/celery
RUN export C_FORCE_ROOT="true"

# add start script
COPY ./deploy/dev/python/start.sh /etc/init.d/start.sh
RUN chmod a+x /etc/init.d/start.sh

# ports
EXPOSE 5000

# Default parameters
ENTRYPOINT ["python3.5", "/usr/src/app/src/main.py"]
```

requirements.txt looks like this:
```
dropbox==6.6.0
Flask==0.12.2
flask-socketio==2.9.2
eventlet==0.19.0
voluptuous==0.9.2
pyinstaller==3.2
redis==2.10.6
celery==4.0.2
configparser==3.5.0
flask-cors==3.0.2
```

I haven't found anything about somebody else having the same issue. This brings me to the conclusion that it has to do with the system configuration. Although there is really nothing much configured within that docker container. Also possible that I miss. Thank you in advance!

**Comment by Schnodderbalken** [comment]
Sorry. Solved by monkeypatching like it's suggested here:
https://github.com/miguelgrinberg/Flask-SocketIO/issues/531

`eventlet.monkey_patch(socket=True)`
