### ISSUE TITLE
On client reconnect, server hangs and throws timeout exception

### ISSUE THREAD

**Issue by patrislav1** [miguelgrinberg/Flask-SocketIO#557]
Hi Miguel,

my Flask-SocketIO app intermittently hangs for the duration of ping_timeout (60 seconds) and then throws a timeout exception.
It can be reproduced by just hitting F5 (reload) in the browser. Please see the log below: in the first session, everything is all right, then I hit F5 and after the client reconnects and sends a `GET /socket.io/?EIO=3&...` request, the server hangs.
I noticed that one difference between the "successful" and the "failed" session is, that in the latter case the client and server are already exchanging socketIO messages, while the negotiation about websocket upgrade is not finished yet.
I can make this error completely go away by forcing the client to use websocket with `{transports: ['websocket'], upgrade: false}`. If this a legitimate workaround, this is fine for me, since I don't need the HTTP polling fallback. Still I wonder if this is just chasing the bug away instead of solving it.

Thanks and best regards, Patrick

PS.: My example code is derived from [this site](http://www.matthieuamiguet.ch/blog/synchronize-clients-flask-application-websockets)
P.P.S: Not sure if this issue is related to [that one](https://github.com/miguelgrinberg/Flask-SocketIO/issues/459), however they don't mention exceptions there.

server log:
~~~~
$ ./run.py 
Server initialized for eventlet.
 * Restarting with stat
Server initialized for eventlet.
 * Debugger is active!
 * Debugger PIN: 158-043-969
(8582) wsgi starting up on http://0.0.0.0:5000
(8582) accepted ('127.0.0.1', 44432)
127.0.0.1 - - [26/Sep/2017 15:21:08] "GET / HTTP/1.1" 200 1288 0.004419
fe5c852f04144fd79ebc405cc66066c0: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': 'fe5c852f04144fd79ebc405cc66066c0'}
client connected!
fe5c852f04144fd79ebc405cc66066c0: Sending packet MESSAGE data 0
127.0.0.1 - - [26/Sep/2017 15:21:09] "GET /socket.io/?EIO=3&transport=polling&t=1506432068997-0 HTTP/1.1" 200 381 0.000868
(8582) accepted ('127.0.0.1', 44438)
fe5c852f04144fd79ebc405cc66066c0: Received request to upgrade to websocket
fe5c852f04144fd79ebc405cc66066c0: Sending packet NOOP data None
fe5c852f04144fd79ebc405cc66066c0: Received packet MESSAGE data 2["client_ack"]
received event "client_ack" from fe5c852f04144fd79ebc405cc66066c0 [/]
received connection acknowledge from client!
127.0.0.1 - - [26/Sep/2017 15:21:09] "POST /socket.io/?EIO=3&transport=polling&t=1506432069027-1&sid=fe5c852f04144fd79ebc405cc66066c0 HTTP/1.1" 200 199 0.001172
127.0.0.1 - - [26/Sep/2017 15:21:09] "GET /socket.io/?EIO=3&transport=polling&t=1506432069035-2&sid=fe5c852f04144fd79ebc405cc66066c0 HTTP/1.1" 200 215 0.000129
fe5c852f04144fd79ebc405cc66066c0: Upgrade to websocket successful
fe5c852f04144fd79ebc405cc66066c0: Received packet MESSAGE data 2["value changed",{"who":"slider2","data":"1"}]
received event "value changed" from fe5c852f04144fd79ebc405cc66066c0 [/]
emitting event "update value" to all [/]
fe5c852f04144fd79ebc405cc66066c0: Sending packet MESSAGE data 2["update value",{"who":"slider2","data":"1"}]

(...)

fe5c852f04144fd79ebc405cc66066c0: Received packet MESSAGE data 2["value changed",{"who":"slider2","data":"9"}]
received event "value changed" from fe5c852f04144fd79ebc405cc66066c0 [/]
emitting event "update value" to all [/]
fe5c852f04144fd79ebc405cc66066c0: Sending packet MESSAGE data 2["update value",{"who":"slider2","data":"9"}]
client disconnected!
127.0.0.1 - - [26/Sep/2017 15:21:13] "GET /socket.io/?EIO=3&transport=websocket&sid=fe5c852f04144fd79ebc405cc66066c0 HTTP/1.1" 200 0 4.518702
127.0.0.1 - - [26/Sep/2017 15:21:13] "GET / HTTP/1.1" 200 1288 0.000538
38b6969b691549fca0b4e8c4b9418b80: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': '38b6969b691549fca0b4e8c4b9418b80'}
client connected!
38b6969b691549fca0b4e8c4b9418b80: Sending packet MESSAGE data 0
127.0.0.1 - - [26/Sep/2017 15:21:13] "GET /socket.io/?EIO=3&transport=polling&t=1506432073794-0 HTTP/1.1" 200 381 0.000770
38b6969b691549fca0b4e8c4b9418b80: Received packet MESSAGE data 2["client_ack"]
received event "client_ack" from 38b6969b691549fca0b4e8c4b9418b80 [/]
received connection acknowledge from client!
127.0.0.1 - - [26/Sep/2017 15:21:13] "POST /socket.io/?EIO=3&transport=polling&t=1506432073852-1&sid=38b6969b691549fca0b4e8c4b9418b80 HTTP/1.1" 200 199 0.000644
(8582) accepted ('127.0.0.1', 44440)
(8582) accepted ('127.0.0.1', 44442)
38b6969b691549fca0b4e8c4b9418b80: Received request to upgrade to websocket
38b6969b691549fca0b4e8c4b9418b80: Sending packet NOOP data None
127.0.0.1 - - [26/Sep/2017 15:21:13] "GET /socket.io/?EIO=3&transport=polling&t=1506432073854-2&sid=38b6969b691549fca0b4e8c4b9418b80 HTTP/1.1" 200 215 0.007057
Traceback (most recent call last):
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/wsgi.py", line 507, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/engineio/server.py", line 267, in handle_request
    environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/engineio/socket.py", line 89, in handle_get_request
    start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/engineio/socket.py", line 130, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/engineio/async_eventlet.py", line 19, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/websocket.py", line 127, in __call__
    self.handler(ws)
  File "/home/patrick/.local/lib/python2.7/site-packages/engineio/socket.py", line 155, in _websocket_handler
    pkt = ws.wait()
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/websocket.py", line 633, in wait
    for i in self.iterator:
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/websocket.py", line 503, in _iter_frames
    message = self._recv_frame(message=fragmented_message)
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/websocket.py", line 526, in _recv_frame
    header = recv(2)
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/websocket.py", line 442, in _get_bytes
    d = self.socket.recv(numbytes - len(data))
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 360, in recv
    return self._recv_loop(self.fd.recv, b'', bufsize, flags)
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 354, in _recv_loop
    self._read_trampoline()
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 325, in _read_trampoline
    timeout_exc=socket_timeout('timed out'))
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 207, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 163, in trampoline
    return hub.switch()
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 295, in switch
    return self.greenlet.switch()
timeout: timed out

127.0.0.1 - - [26/Sep/2017 15:22:13] "GET /socket.io/?EIO=3&transport=websocket&sid=38b6969b691549fca0b4e8c4b9418b80 HTTP/1.1" 500 0 60.012835
client disconnected!
38b6969b691549fca0b4e8c4b9418b80: Client is gone, closing socket
Traceback (most recent call last):
  File "/home/patrick/.local/lib/python2.7/site-packages/eventlet/wsgi.py", line 507, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/engineio/server.py", line 267, in handle_request
    environ, start_response)
  File "/home/patrick/.local/lib/python2.7/site-packages/engineio/socket.py", line 94, in handle_get_request
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
~~~~

versions:
~~~~
$ pip freeze
chardet==2.3.0
click==6.7
defer==1.0.6
enum-compat==0.0.2
enum34==1.1.6
eventlet==0.21.0
Flask==0.12.2
Flask-SocketIO==2.9.2
freeopcua==0.90.3
futures==3.1.1
greenlet==0.4.12
itsdangerous==0.24
Jinja2==2.9.6
lxml==4.0.0
MarkupSafe==1.0
psutil==3.4.2
pygobject==3.20.0
pysqlite==2.7.0
python-apt==1.1.0b1
python-dateutil==2.6.1
python-debian==0.1.27
python-engineio==1.7.0
python-socketio==1.8.0
pytz==2017.2
pyxdg==0.25
PyYAML==3.12
pyzmq==16.0.2
six==1.11.0
trollius==2.1
Werkzeug==0.12.2
~~~~

run.py:
~~~~
#!/usr/bin/python

from flask import Flask, render_template
from flask_socketio import SocketIO, emit

app = Flask(__name__)
socketio = SocketIO(app, logger=True,  engineio_logger=True)

values = {
    'slider1': 25,
    'slider2': 0,
}

@app.route('/')
def index():
    return render_template('index.html', **values)

@socketio.on('connect')
def on_connect():
    print("client connected!")

@socketio.on('disconnect')
def test_disconnect():
    print("client disconnected!")

@socketio.on('value changed')
def value_changed(message):
    values[message['who']] = message['data']
    emit('update value', message, broadcast=True)

@socketio.on('client_ack')
def client_ack():
    print("received connection acknowledge from client!")

if __name__ == '__main__':
    socketio.run(app, debug=True, host='0.0.0.0', port=5000)
~~~~

index.html:
~~~~
<!DOCTYPE HTML>
<html>
<head>
    <title>Synchronized Sliders</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function(){

            var socket = io().connect();

            socket.on('connect', function() {
                socket.emit('client_ack');
            });

            $('input.sync').on('input', function(event) {
                socket.emit('value changed', {who: $(this).attr('id'), data: $(this).val()});
                return false;
            });

            socket.on('update value', function(msg) {
                $('input#'+msg.who).val(msg.data)
            });

        });
    </script>
</head>
<body>
    <h1>Synchronized Sliders!</h1>
    <input id="slider1" class="sync" type="range" min="0" max="50" value="{{slider1}}" /> <br>
    <input id="slider2" class="sync" type="range" min="0" max="50" value="{{slider2}}" />
    <input id="txt1" class="sync" type="text" />
</body>
</html>
~~~~

**Comment by miguelgrinberg** [comment]
Does this happen only with a particular browser?
Also, can you upgrade your Socket.IO JS client lib to a more recent version to see if there is any improvement?

**Comment by patrislav1** [comment]
Ok, it happens independently of the socket.io JS, I upgraded that to 2.0.3 and it happens just the same.

But after checking with different browser I noticed that it seems to happen only with Firefox.
Could reproduce the bug with: FF 55.0.2 (64-bit) on Linux, FF 55.0.3 (64-Bit) on Windows
Could NOT reproduce it with: Chrome 61.0.3163.100 on Windows, Chromium 61.0.3163.79 on Linux

**Comment by miguelgrinberg** [comment]
Hmm. Sounds like this could be https://github.com/miguelgrinberg/Flask-SocketIO/issues/186, which was reported a while ago and I was never able to reproduce locally.

**Comment by SenninSensei** [comment]
i have a problem very similar in all browsers, did u solve it ?

**Comment by miguelgrinberg** [comment]
@SenninSensei I was never able to reproduce this. If you want to debug this more in depth and try to figure out what's going on, I can help. Try by enabling logs on both sides and see if there are any interesting errors.

**Comment by ocervell** [comment]
@miguelgrinberg I'm running into a similar issue on Windows **only**:

```
127.0.0.1 - - [15/Jan/2018 16:27:58] "GET /socket.io/?EIO=3&transport=polling&t=M3wfXqh HTTP/1.1" 200 381 0.000000
127.0.0.1 - - [15/Jan/2018 16:27:58] "POST /socket.io/?EIO=3&transport=polling&t=M3wfXqz&sid=d8520e475bcb4d8e8f84868978370c32 HTTP/1.1" 200 219 0.001000
127.0.0.1 - - [15/Jan/2018 16:27:58] "GET /socket.io/?EIO=3&transport=polling&t=M3wfXr0&sid=d8520e475bcb4d8e8f84868978370c32 HTTP/1.1" 200 222 0.000000
(5212) accepted ('127.0.0.1', 64898)
127.0.0.1 - - [15/Jan/2018 16:27:58] "GET /socket.io/?EIO=3&transport=polling&t=M3wfXrB&sid=d8520e475bcb4d8e8f84868978370c32 HTTP/1.1" 200 215 0.288000
Traceback (most recent call last):
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\wsgi.py", line 539, in handle_one_response
    result = self.application(self.environ, start_response)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\flask_socketio\__init__.py", line 42, in __call__
    start_response)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\engineio\middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\socketio\server.py", line 360, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\engineio\server.py", line 274, in handle_request
    environ, start_response)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\engineio\socket.py", line 91, in handle_get_request
    start_response)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\engineio\socket.py", line 133, in _upgrade_websocket
    return ws(environ, start_response)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\engineio\async_eventlet.py", line 19, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\websocket.py", line 129, in __call__
    self.handler(ws)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\engineio\socket.py", line 158, in _websocket_handler
    pkt = ws.wait()
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\websocket.py", line 787, in wait
    for i in self.iterator:
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\websocket.py", line 642, in _iter_frames
    message = self._recv_frame(message=fragmented_message)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\websocket.py", line 668, in _recv_frame
    header = recv(2)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\websocket.py", line 577, in _get_bytes
    d = self.socket.recv(numbytes - len(data))
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\greenio\base.py", line 363, in recv
    return self._recv_loop(self.fd.recv, b'', bufsize, flags)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\greenio\base.py", line 357, in _recv_loop
    self._read_trampoline()
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\greenio\base.py", line 328, in _read_trampoline
    timeout_exc=socket_timeout('timed out'))
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\greenio\base.py", line 207, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\hubs\__init__.py", line 163, in trampoline
    return hub.switch()
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\hubs\hub.py", line 295, in switch
    return self.greenlet.switch()
timeout: timed out

127.0.0.1 - - [15/Jan/2018 16:28:58] "GET /socket.io/?EIO=3&transport=websocket&sid=d8520e475bcb4d8e8f84868978370c32 HTTP/1.1" 500 0 60.002000
Traceback (most recent call last):
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\hubs\hub.py", line 458, in fire_timers
    timer()
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\hubs\timer.py", line 58, in __call__
    cb(*args, **kw)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\hubs\__init__.py", line 155, in _timeout
    current.throw(exc)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\greenthread.py", line 218, in main
    result = function(*args, **kwargs)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\wsgi.py", line 781, in process_request
    proto.__init__(conn_state, self)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\wsgi.py", line 337, in __init__
    self.finish()
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\wsgi.py", line 695, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "c:\python27\Lib\SocketServer.py", line 713, in finish
    self.wfile.close()
  File "c:\python27\Lib\socket.py", line 283, in close
    self.flush()
  File "c:\python27\Lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\greenio\base.py", line 400, in sendall
    tail = self.send(data, flags)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\greenio\base.py", line 394, in send
    return self._send_loop(self.fd.send, data, flags)
  File "C:\Users\JahMyst\Desktop\scrapez\venv\lib\site-packages\eventlet\greenio\base.py", line 381, in _send_loop
    return send_method(data, *args)
error: [Errno 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
```

Seems that the greenlet times out and then can't connect to Redis.

**Comment by kea14** [comment]
Hi,

I had this exact same problem, that's why I hit this issue and #186 . 

I'm using Flask-SocketIO 3.0.0 and eventlet 0.23.0. This timeout issue seemed to only happen on Firefox (version: 60.0.1).

I stopped having this issue when I added `import eventlet` to my imports.py.

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Please reopen if you need more assistance.
