### ISSUE TITLE
error: [Errno 10053] always throws me this error

### ISSUE THREAD

**Issue by hackloper** [miguelgrinberg/Flask-SocketIO#600]
I have the following code
```
from flask_socketio import SocketIO,emit,send
from flask import Flask,send_from_directory
from threading import Thread
from pytube import YouTube
import time,os

app = Flask(__name__,instance_path='C:\\Users\\franciskiko\\Desktop\\projectos\\webdescarga\\protected')
socketio = SocketIO(app,manage_session=False,ping_timeout=65,ping_interval=1,async_mode='gevent')

class Test(Thread):
    def __init__(self):
        Thread.__init__(self)

    def process(self):
        for i in range(10):
            socketio.send(str(i), broadcast=True)
    def run(self):
        self.process()

class Download(Thread):
    def __init__(self,url=None):
        Thread.__init__(self)
        self.url = url
    def progress(self,receive,size,date):
        total = (receive*100) / size
        socketio.send(str(total))

    def finish(self,path):
        print(path)

    def run(self):
        print(self.url)
        yt = YouTube(self.url)
        video = yt.filter('mp4')[-1]
        path = os.path.join(app.instance_path,'downloads')
        print(path)
        video.download(path,on_progress=self.progress,on_finish=self.finish,force_overwrite=True)

@socketio.on('connect')
def connect():
    print('client connected')

@socketio.on('message')
def handlemessage(url):
    print(url)
    thread = Download(url)
    thread.start()

if __name__ == '__main__':
    socketio.run(app,port=5000)
```
and on my website

```
$(document).ready(function(){
	sock = io.connect('http://127.0.0.1:5000');

	sock.on('connect',function(){
			alert('conectado');
		});

	sock.on('message',function(data){
		$('#changeprogress').attr('aria-valuenow', data).width(data+'%');

	});

	$(document).on('click','a[data-slide="prev"]',function(){
		$('#carouselExample').carousel('prev');
	});
	$(document).on('click','a[data-slide="next"]',function(){
		$('#carouselExample').carousel('next');
	});
	$(document).on('click','#btnsend',function(){
		var _url = $('#url').val();
		sock.send(_url);
	});
});
```

> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 935, in handle_one_response
>     self.run_application()
>   File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 909, in run_application
>     self.process_result()
>   File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 895, in process_result
>     self.write(data)
>   File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 741, in write
>     self._write_with_headers(data)
>   File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 763, in _write_with_headers
>     self._write(data)
>   File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 726, in _write
>     self._sendall(data)
>   File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 701, in _sendall
>     self.socket.sendall(data)
>   File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 419, in sendall
>     timeleft = self.__send_chunk(chunk, flags, timeleft, end)
>   File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 355, in __send_chunk
>     data_sent += self.send(chunk, flags)
>   File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 323, in send
>     return sock.send(data, flags)
> error: [Errno 10053] Se ha anulado una conexi¾n establecida por el software en su equipo host
> Wed Nov 29 21:38:05 2017 {'REMOTE_PORT': '59877', 'HTTP_HOST': '127.0.0.1:5000', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 24)} failed with error

Everything works fine, but the error is displayed in the console

**Comment by hackloper** [comment]
no, the error is not shown when the browser is closed, it is displayed when the button is clicked and it enters the message event, I think the error occurs because of the thread but I do not know the reason

**Comment by miguelgrinberg** [comment]
Do you get the error if you use the default values for `ping_timeout` and `ping_interval`?

**Comment by hackloper** [comment]
this shows the same error
 ```
socketio = SocketIO(app)
```
I use python 2.7 on windows 10

**Comment by miguelgrinberg** [comment]
Well, not really sure then. The error 10053 was reported a few times already, seems to be some sort of issue in the Windows implementation of Python sockets. I suggest you try different options to see if it goes away. For example, try eventlet instead of gevent, or Python 3 instead of Python 2.

**Comment by hackloper** [comment]
With eventlet it works but the thread does not work
```
    def progress(self,receive,size,date):
        total = (receive*100) / size
        socketio.send(str(total))
```
not send data
```
socketio.send(str(total))
```

**Comment by hackloper** [comment]
Solucione el error estos son los pasos a seguir.
yo instalo python3 y despues creo el path apuntando a la carpeta script para poder ejecutar pip de python 3
**C:\python3\Scripts** Then install with pip all necessary packages
**pip install flask
pip install flasck-socketio
pip install pytube
....**
despues me muestra un error en la libreria markupsafe aunque la instalacion no dio ningun error si me lo da al ejecutar markupsafe y este motivo es por algun motivo no se installa correctamente y lo que hice fue descargar la libreria y copiar todos los archivos dentro de la carpeta markupsafe en **C:\python3\Lib\site-packages\markupsafe** 
Everything works perfect, now another question that I do not know if I should do it here, how can I detect when the client closes the tab to disconnect the connection?

**Comment by miguelgrinberg** [comment]
> how can I detect when the client closes the tab to disconnect the connection?

Add a `disconnect` handler.

```python
@socketio.on('disconnect')
def disconnect():
    print('client disconnected')
```

**Comment by hackloper** [comment]
yes, a add
```
@socketio.on('disconnect')
def disconnect():
    print('client disconnected')
```
later i reset server and close tab but not call event disconnect

**Comment by miguelgrinberg** [comment]
It may take a while, sometimes it is not immediate.

**Comment by j-o-d-o** [comment]
I also reported this issue some while ago with the Win [10053] error and the error seems to be in gevent. Switching from eventlet resolved the issue and by using eventlet also the disconnect event will be called properly when closing the tab, so @hackloper usecases should be covered and fixed by using eventlet instead of gevent.
