### ISSUE TITLE
 RuntimeError: working outside of request context 

### ISSUE THREAD

**Issue by connect2robiul** [miguelgrinberg/Flask-SocketIO#621]
```
def on_message(client, userdata, message):           
               print(session['topic_login'])
```

```
def login():
             session['topic_login'] = value
```

get error on message section

**Comment by miguelgrinberg** [comment]
Please provide the complete stack trace of the error.

**Comment by connect2robiul** [comment]
```
Connected with result code 0
192.168.1.42 - - [20/Jan/2018 12:30:25] "GET /socket.io/?EIO=3&transport=polling                                                                                                                     &t=1516429825070-135 HTTP/1.1" 200 -
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2606,                                                                                                                      in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1470,                                                                                                                      in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 995, i                                                                                                                     n loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1273,                                                                                                                      in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1838,                                                                                                                      in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2285,                                                                                                                      in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2456,                                                                                                                      in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2603,                                                                                                                      in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "app.py", line 92, in on_message
    print(session['topic_login'])
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 368, in <lambd                                                                                                                     a>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 297, in _get_c                                                                                                                     urrent_object
    return self.__local()
  File "/usr/lib/python2.7/dist-packages/flask/globals.py", line 20, in _lookup_                                                                                                                     req_object
    raise RuntimeError('working outside of request context')
RuntimeError: working outside of request context

```

**Comment by miguelgrinberg** [comment]
What does this have to do with Flask-SocketIO?

You are using the `session` variable from Flask outside of a request. The user session only exists while a request is being handled, outside of the request there is no context to know who's the user.

**Comment by connect2robiul** [comment]
I try with flask session and global variable inside the socket . both are failed. I need login information inside the socket message for my program so what is the process?

**Comment by miguelgrinberg** [comment]
What do you mean when you say "socket message". You seem to be using mqtt, but you are asking in a SocketIO issue tracker about it. Are you sure you are in the right place?

**Comment by SudeshKumarSK** [comment]
> What does this have to do with Flask-SocketIO?
> 
> You are using the `session` variable from Flask outside of a request. The user session only exists while a request is being handled, outside of the request there is no context to know who's the user.

Hey @miguelgrinberg I am using flask_session and am also using session["key"] = value in my flask app and am facing the same issue. Am also using gunicorn wsgi. Is there a workaround to solve this issue. Please help me out! Thanks in advance. My mail id : sudesh.skofficial@gmail.com

**Comment by SudeshKumarSK** [comment]
> 

Hiee Miguel!
I will explain what am exactly working on. I have Google's dialogflow having some mega agents and each agent has intents. Now what I am actually doing is using Flask framework as a restful api deployed on a Virtual Private Server to handle the requests from users by using their google accounts directly from google assistant. What happens is that the session gets overlapped and users' data like say username etc gets mismatched when multiple users login. I am using gunicorn as a wsgi.  One more thing is that When the same workflow is deployed in google cloud everything works like a pro. So I thought "session management" was the problem when I deployed in VPS. So tried changing all variables like "app.username", "app.questionName" to "session["username"] , etc etc. I am also using redis server to handle these session variables. Could you please help me out @miguelgrinberg

**Comment by miguelgrinberg** [comment]
@SudeshKumarSK I'm sorry but this is just bugs in your application. I cannot help you, you have to debug this yourself. As I said above, `session` can only be used when there is a request context.
