### ISSUE TITLE
Azure web app service python 2.7 behind IIS 

### ISSUE THREAD

**Issue by alucas1219** [miguelgrinberg/Flask-SocketIO#624]
Having an issue connecting with websockets transport for azure web app service(polling transport appears to be working). The Azure web app service exposes connecting to a WSGI application object with wfastcgi(https://pypi.python.org/pypi/wfastcgi). When trying to connect over websockets transport, receiving the following error below:

```
2018-01-27 22:23:35.373000: Python version: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
2018-01-27 22:23:35.389000: wfastcgi.py 2.1.1 initializing
2018-01-27 22:23:35.452000: Activating virtualenv with D:\home\site\wwwroot\env\Scripts\activate_this.py
2018-01-27 22:23:35.467000: Getting handler main.app
2018-01-27 22:23:41.077000: Got handler: <Flask 'app'>
2018-01-27 22:23:41.092000: wfastcgi.py will restart when files in D:\home\site\wwwroot\ are changed: .*((\.py)|(\.config))$
2018-01-27 22:23:41.108000: wfastcgi.py 2.1.1 initialized
2018-01-27 22:23:59.142000: Error occurred:

Traceback (most recent call last):
  File "D:\Python27\Scripts\wfastcgi.py", line 736, in main
    result = handler(record.params, response.start)
  File "D:\home\site\wwwroot\env\Lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\home\site\wwwroot\env\Lib\site-packages\engineio\middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "D:\home\site\wwwroot\env\Lib\site-packages\socketio\server.py", line 360, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "D:\home\site\wwwroot\env\Lib\site-packages\engineio\server.py", line 265, in handle_request
    transport, b64)
  File "D:\home\site\wwwroot\env\Lib\site-packages\engineio\server.py", line 377, in _handle_connect
    ret = s.handle_get_request(environ, start_response)
  File "D:\home\site\wwwroot\env\Lib\site-packages\engineio\socket.py", line 91, in handle_get_request
    start_response)
  File "D:\home\site\wwwroot\env\Lib\site-packages\engineio\socket.py", line 133, in _upgrade_websocket
    return ws(environ, start_response)
  File "D:\home\site\wwwroot\env\Lib\site-packages\engineio\async_eventlet.py", line 15, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information
```

Setup for flask app and flask-socket below:

```
sockets = socketio.Server()
app = Flask(__name__)
app.wsgi_app = socketio.Middleware(sockets, app.wsgi_app)
```

The Azure config for WSGI follow:

`    <add key="WSGI_ALT_VIRTUALENV_HANDLER" value="app" />`

Any suggestions for troubleshooting would be greatly appreciated

**Comment by miguelgrinberg** [comment]
Socket.IO does not work with a standard WSGI web server, simply because it needs WebSocket, and WSGI does not have support for that. I can't tell you for sure, but my guess is that the wfastcgi package that you are using is also not WebSocket friendly (in the same way mod_wsgi isn't for Apache).

I don't have much experience with the IIS webserver, but it's probably not going to work for this. I suggest you read the deployment section of the documentation, where I describe the supported deployment options.

**Comment by miguelgrinberg** [comment]
Unfortunately I don't know enough about IIS to help you with this, but I can tell you that I do not know of anyone using it with a Socket.IO application.

**Comment by jackdh** [comment]
@alucas1219 How far did you get with this? Did you manage to deploy it successfully?
