### ISSUE TITLE
Emitting events not received

### ISSUE THREAD

**Issue by Zomtorg** [miguelgrinberg/Flask-SocketIO#627]
Greetings,

I'm currently building a interactive machine learning platform.

I've a Flask service that deals with the actual machine learning and it's supposed to emit data about its progress every so often.

The problem is that after some time (varies), the events just stop being received by the Node.js service.

Here's a sample of the logs of the Flask service showing the sudden stop:
```
{"epoch":
{"batch": 512, "epoch_num": 42, "loss": 0.0024756821803748608}}
127.0.0.1 - - [29/Jan/2018 23:43:22] "GET /socket.io/?EIO=3&transport=polling&t=M54JSYL&b64=1&sid=a156c12680fb4b49ada9990b2cc29c1c HTTP/1.1" 200 -
{"epoch": {"batch": 544, "epoch_num": 42, "loss": 0.006104349624365568}}
127.0.0.1 - - [29/Jan/2018 23:43:23] "GET /socket.io/?EIO=3&transport=polling&t=M54JSYh&b64=1&sid=a156c12680fb4b49ada9990b2cc29c1c HTTP/1.1" 200 -
{"epoch": {"batch": 576, "epoch_num": 42, "loss": 0.003250140231102705}}
127.0.0.1 - - [29/Jan/2018 23:43:23] "GET /socket.io/?EIO=3&transport=polling&t=M54JSZu&b64=1&sid=a156c12680fb4b49ada9990b2cc29c1c HTTP/1.1" 200 -
{"epoch": {"batch": 608, "epoch_num": 42, "loss": 0.004642133601009846}}
127.0.0.1 - - [29/Jan/2018 23:43:23] "GET /socket.io/?EIO=3&transport=polling&t=M54JSaX&b64=1&sid=a156c12680fb4b49ada9990b2cc29c1c HTTP/1.1" 200 -
{"epoch": {"batch": 640, "epoch_num": 42, "loss": 0.0036571775563061237}}
127.0.0.1 - - [29/Jan/2018 23:43:23] "GET /socket.io/?EIO=3&transport=polling&t=M54JSbk&b64=1&sid=a156c12680fb4b49ada9990b2cc29c1c HTTP/1.1" 200 -
{"epoch": {"batch": 672, "epoch_num": 42, "loss": 0.0038731619715690613}}
127.0.0.1 - - [29/Jan/2018 23:43:23] "GET /socket.io/?EIO=3&transport=polling&t=M54JScL&b64=1&sid=a156c12680fb4b49ada9990b2cc29c1c HTTP/1.1" 200 -
{"epoch": {"batch": 704, "epoch_num": 42, "loss": 0.006970785558223724}}
{"epoch": {"batch": 736, "epoch_num": 42, "loss": 0.004532341379672289}}
{"epoch": {"batch": 0, "epoch_num": 43, "loss": 0.003477332182228565}}
{"epoch": {"batch": 32, "epoch_num": 43, "loss": 0.0037559380289167166}}
...
```
Similarly, here's the same logs from the Node.js service:
```
node_1     | Training update! 
node_1     | {"epoch": {"batch": 640, "epoch_num": 42, "loss": 0.0036571775563061237}}
node_1     | Training update!
node_1     | {"epoch": {"batch": 672, "epoch_num": 42, "loss": 0.0038731619715690613}}
node_1     | ::ffff:127.0.0.1 - - [29/Jan/2018:23:43:46 +0000] "GET /health HTTP/1.1" 200 23
node_1     | ::ffff:127.0.0.1 - - [29/Jan/2018:23:44:16 +0000] "GET /health HTTP/1.1" 200 23
....

```

There's no registered `disconnect` event. Please note that I've also edited the ping interval and ping timeout both on the Node.js service and the Flask service. 

Flask service:

```socketio = SocketIO(app, ping_interval=2000, ping_timeout=5000)```

And for the Node.js client I'm using:

```
var other_server = require("socket.io-client");
var other_socket = other_server(this.url, {'pingInterval': 2000, 'pingTimeout': 5000});```

**Comment by miguelgrinberg** [comment]
It's a really bad idea to change the timeouts to something that short. Basically the service is going to thrash catering to the ping/pong traffic. There is rarely a need to decrease the timeouts. Sometimes you want to actually increase them, to help with unreliable networks or very busy applications.

To help track down the source of this problem, I suggest you do a run with logging enabled on the server and the client, to find the exact point at which the emits start to be dropped. On the server, you can add logging by adding `logger=True, engineio_logger=True` arguments to the `SocketIO` class. I recommend that you restore the ping interval and timeout values to their defaults to decrease the amount of logging.

**Comment by Zomtorg** [comment]
Thanks for the heads up! I had this issue with the default settings as well, which led me to tweaking some of the parameters. Currently I've the settings back to default - here are the logs:

Flask logs:
```
{"epoch": {"batch": 672, "epoch_num": 17, "loss": 0.3169611990451813}}
emitting event "training_update" to all [/]
9d54e95e4fbf417e9bced276e111c22c: Sending packet MESSAGE data 2["training_update","{\"epoch\": {\"batch\": 672, \"epoch_num\": 17, \"loss\": 0.3169611990451813}}"]
127.0.0.1 - - [30/Jan/2018 01:16:24] "GET /socket.io/?EIO=3&transport=polling&t=M54ekus&b64=1&sid=9d54e95e4fbf417e9bced276e111c22c HTTP/1.1" 200 -
{"epoch": {"batch": 704, "epoch_num": 17, "loss": 0.1603725701570511}}
emitting event "training_update" to all [/]
9d54e95e4fbf417e9bced276e111c22c: Sending packet MESSAGE data 2["training_update","{\"epoch\": {\"batch\": 704, \"epoch_num\": 17, \"loss\": 0.1603725701570511}}"]
127.0.0.1 - - [30/Jan/2018 01:16:24] "GET /socket.io/?EIO=3&transport=polling&t=M54ekvZ&b64=1&sid=9d54e95e4fbf417e9bced276e111c22c HTTP/1.1" 200 -
{"epoch": {"batch": 736, "epoch_num": 17, "loss": 0.016498945653438568}}
emitting event "training_update" to all [/]
9d54e95e4fbf417e9bced276e111c22c: Sending packet MESSAGE data 2["training_update","{\"epoch\": {\"batch\": 736, \"epoch_num\": 17, \"loss\": 0.016498945653438568}}"]
{"epoch": {"batch": 0, "epoch_num": 18, "loss": 3.718496322631836}}
emitting event "training_update" to all [/]
9d54e95e4fbf417e9bced276e111c22c: Sending packet MESSAGE data 2["training_update","{\"epoch\": {\"batch\": 0, \"epoch_num\": 18, \"loss\": 3.718496322631836}}"]
emitting event "training_update" to all [/]
9d54e95e4fbf417e9bced276e111c22c: Sending packet MESSAGE data 2["training_update","{\"epoch\": {\"batch\": 32, \"epoch_num\": 18, \"loss\": 3.481973171234131}}"]
{"epoch": {"batch": 32, "epoch_num": 18, "loss": 3.481973171234131}}
emitting event "training_update" to all [/]
```

Node.js logs:
```
node_1     | Training update
node_1     | {"epoch": {"batch": 704, "epoch_num": 17, "loss": 0.1603725701570511}}
node_1     | {"epoch": {"batch": 704, "epoch_num": 17, "loss": 0.1603725701570511}}
node_1     | Tue, 30 Jan 2018 01:16:24 GMT engine.io-client:polling polling
node_1     | Tue, 30 Jan 2018 01:16:24 GMT engine.io-client:polling-xhr xhr poll
node_1     | Tue, 30 Jan 2018 01:16:24 GMT engine.io-client:polling-xhr xhr open GET: http://docker.for.mac.localhost:5000/socket.io/?EIO=3&transport=polling&t=M54ekws&b64=1&sid=9d54e95e4fbf417e9bced276e111c22c
node_1     | Tue, 30 Jan 2018 01:16:24 GMT engine.io-client:polling-xhr xhr data null
node_1     | Tue, 30 Jan 2018 01:16:43 GMT engine:ws received "2"
node_1     | Tue, 30 Jan 2018 01:16:43 GMT engine:socket packet
node_1     | Tue, 30 Jan 2018 01:16:43 GMT engine:socket got ping
node_1     | Tue, 30 Jan 2018 01:16:43 GMT engine:socket sending packet "pong" (undefined)
node_1     | Tue, 30 Jan 2018 01:16:43 GMT engine:socket flushing buffer to transport
node_1     | Tue, 30 Jan 2018 01:16:43 GMT engine:ws writing "3"
[edited healthcheck logs]
node_1     | Tue, 30 Jan 2018 01:16:47 GMT morgan log request
node_1     | Tue, 30 Jan 2018 01:16:48 GMT engine.io-client:socket writing ping packet - expecting pong within 60000ms
node_1     | Tue, 30 Jan 2018 01:16:48 GMT engine.io-client:socket flushing 1 packets in socket
node_1     | Tue, 30 Jan 2018 01:16:48 GMT engine.io-client:polling-xhr xhr open POST: http://docker.for.mac.localhost:5000/socket.io/?EIO=3&transport=polling&t=M54eqve&b64=1&sid=9d54e95e4fbf417e9bced276e111c22c
node_1     | Tue, 30 Jan 2018 01:16:48 GMT engine.io-client:polling-xhr xhr data 1:2
node_1     | Tue, 30 Jan 2018 01:16:48 GMT engine.io-client:socket socket error {"type":"TransportError","description":503}
node_1     | Tue, 30 Jan 2018 01:16:48 GMT socket.io-client:manager error { Error: xhr post error
node_1     |     at XHR.Transport.onError (/opt/node_modules/engine.io-client/lib/transport.js:64:13)
node_1     |     at Request.<anonymous> (/opt/node_modules/engine.io-client/lib/transports/polling-xhr.js:109:10)
node_1     |     at Request.Emitter.emit (/opt/node_modules/component-emitter/index.js:133:20)
node_1     |     at Request.onError (/opt/node_modules/engine.io-client/lib/transports/polling-xhr.js:310:8)
node_1     |     at Timeout._onTimeout (/opt/node_modules/engine.io-client/lib/transports/polling-xhr.js:257:18)
node_1     |     at ontimeout (timers.js:386:11)
node_1     |     at tryOnTimeout (timers.js:250:5)
node_1     |     at Timer.listOnTimeout (timers.js:214:5) type: 'TransportError', description: 503 }
node_1     | Tue, 30 Jan 2018 01:16:48 GMT engine.io-client:socket socket close with reason: "transport error"
node_1     | Tue, 30 Jan 2018 01:16:48 GMT engine.io-client:polling transport open - closing
node_1     | Tue, 30 Jan 2018 01:16:48 GMT engine.io-client:polling writing close packet
node_1     | Tue, 30 Jan 2018 01:16:48 GMT engine.io-client:polling-xhr xhr open POST: http://docker.for.mac.localhost:5000/socket.io/?EIO=3&transport=polling&t=M54eqvr&b64=1&sid=9d54e95e4fbf417e9bced276e111c22c
node_1     | Tue, 30 Jan 2018 01:16:48 GMT engine.io-client:polling-xhr xhr data 1:1
node_1     | Tue, 30 Jan 2018 01:16:48 GMT socket.io-client:manager onclose
node_1     | Tue, 30 Jan 2018 01:16:48 GMT socket.io-client:manager cleanup
node_1     | Tue, 30 Jan 2018 01:16:48 GMT socket.io-client:socket close (transport error)
node_1     | GOT DISCONNECTED
node_1     | Tue, 30 Jan 2018 01:16:48 GMT socket.io-client:manager will wait 878ms before reconnect attempt
node_1     | Tue, 30 Jan 2018 01:16:49 GMT socket.io-client:manager attempting reconnect
node_1     | Tue, 30 Jan 2018 01:16:49 GMT socket.io-client:manager readyState closed
node_1     | Tue, 30 Jan 2018 01:16:49 GMT socket.io-client:manager opening http://docker.for.mac.localhost:5000
node_1     | Tue, 30 Jan 2018 01:16:49 GMT engine.io-client:socket creating transport "polling"
node_1     | Tue, 30 Jan 2018 01:16:49 GMT engine.io-client:polling polling
node_1     | Tue, 30 Jan 2018 01:16:49 GMT engine.io-client:polling-xhr xhr poll
node_1     | Tue, 30 Jan 2018 01:16:49 GMT engine.io-client:polling-xhr xhr open GET: http://docker.for.mac.localhost:5000/socket.io/?EIO=3&transport=polling&t=M54er7f&b64=1
node_1     | Tue, 30 Jan 2018 01:16:49 GMT engine.io-client:polling-xhr xhr data null
node_1     | Tue, 30 Jan 2018 01:16:49 GMT engine.io-client:socket setting transport polling
node_1     | Tue, 30 Jan 2018 01:16:49 GMT socket.io-client:manager connect attempt will timeout after 20000
node_1     | Tue, 30 Jan 2018 01:16:49 GMT engine.io-client:socket socket error {"type":"TransportError","description":503}
node_1     | Tue, 30 Jan 2018 01:16:49 GMT socket.io-client:manager connect_error
node_1     | Tue, 30 Jan 2018 01:16:49 GMT socket.io-client:manager cleanup
node_1     | Tue, 30 Jan 2018 01:16:49 GMT socket.io-client:manager reconnect attempt error
node_1     | Tue, 30 Jan 2018 01:16:49 GMT socket.io-client:manager will wait 2166ms before reconnect attempt
node_1     | Tue, 30 Jan 2018 01:16:49 GMT engine.io-client:socket socket close with reason: "transport error"
node_1     | Tue, 30 Jan 2018 01:16:49 GMT engine.io-client:polling transport not open - deferring close
...
```

**Comment by miguelgrinberg** [comment]
Do you have the logs for the entire server session? Basically the snippet that you showed me indicates that the client stopped sending long-polling requests. A little bit later the server should have declared the client gone and called your disconnect event.

**Comment by Zomtorg** [comment]
Funnily enough I can't seem to recreate the problem after restarting my laptop. I swear my code was not working yesterday!
