### ISSUE TITLE
send audio data from server to client and vice-versa ? 

### ISSUE THREAD

**Issue by saisrinivas047** [miguelgrinberg/Flask-SocketIO#633]
hi all need your hep urgently,

send audio data from server to client and vice-versa ? 

I am using flask-socketio.

**Comment by miguelgrinberg** [comment]
See https://github.com/miguelgrinberg/socketio-examples/tree/master/audio for an example app.

**Comment by saisrinivas047** [comment]
hi thanks for the reply. I dont want to record the audio I have an audio file in my pc and want to send it to the server from the client ?

**Comment by miguelgrinberg** [comment]
You asked for an example that streams audio from one side to the other, and this example does that. If you don't want to record the audio, then change it to read it from a file, that part is not what I wanted to highlight.

**Comment by saisrinivas047** [comment]
hi @miguelgrinberg again,
I am trying to send a sample message from flask to javascript cliet, but my client is not receiving the message. here is the code i used

in flask:
@socketio.on('message')
def handle_message(json):
    emit('message', str(json))
in client:
var socket = io.connect('http://0.0.0.0:5000/');
socket.on('message', function (data) {
            console.log('message form backend ' + data);
            });

**Comment by miguelgrinberg** [comment]
If that is all your code, then the problem is that nobody is calling the `on_message()` function on the Python side. You can get the function to run if you emit from the client first. Something like this:

```javascript
var socket = io.connect('http://0.0.0.0:5000/');
socket.on('message', function (data) {
    console.log('message form backend ' + data);
});
socket.emit('message', {foo: 'bar'});
```

The emit at the bottom will trigger the `message` event on the server, so your function will run. Then in this function you can emit events to the client.

**Comment by saisrinivas047** [comment]
hi thanks for the reply , I am able to send data from server to client 'socketio.emit("message", trans)' this function is inside a loop. when I am catching this from the client sometimes I am getting this error:
Receive error
Traceback (most recent call last):
  File "/home/zemoso/.local/lib/python2.7/site-packages/engineio/socket.py", line 209, in _websocket_handler
    self.receive(pkt)
  File "/home/zemoso/.local/lib/python2.7/site-packages/engineio/socket.py", line 53, in receive
    self.send(packet.Packet(packet.PONG, pkt.data))
  File "/home/zemoso/.local/lib/python2.7/site-packages/engineio/socket.py", line 67, in send
    raise IOError('Socket is closed')
IOError: Socket is closed

Can you please help me solve it ?

**Comment by miguelgrinberg** [comment]
That indicates that the client went away or disconnected unexpectedly.

**Comment by saisrinivas047** [comment]
this is my client code, is there any way that I can modify this to erase that error
socket.on('message', function (data) {
              var trans = document.getElementById("transcript");
              $('#transcript').append($('<p>').text(data).css("display","inline"));
              console.log(data)
            });

**Comment by miguelgrinberg** [comment]
This has nothing to do with the client-side code, it is the connection that is being interrupted.

**Comment by saisrinivas047** [comment]
so is there are way to solve this problem or i have to chance my machine ?

**Comment by saisrinivas047** [comment]
hi @miguelgrinberg 
i want to send data to a specific user how can I do that. Can we have session ID's for sockets
