### ISSUE TITLE
socketio.emit is not working 

### ISSUE THREAD

**Issue by connect2robiul** [miguelgrinberg/Flask-SocketIO#672]
```
from flask_socketio import SocketIO, emit,send 
app = Flask(__name__) 
socketio = SocketIO(app)


def on_message(client, userdata, message):
    t = message.topic 
    print(t)
    x = yaml.load(message.payload)
    admin_data = [x] 

    socketio.emit('admin', admin_data)


mqc = mqttc.Client()
mqc.on_message = on_message
mqc.connect('localhost',1883,60)
mqc.loop_start()




if __name__ == '__main__':

    app.run(host='0.0.0.0', port=1212,threaded=True, debug=True)
    socketio.run(app, debug=True)





```

javascript code 

```
<script type="text/javascript" src="../../static/socket/socket.io.min.js"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io.connect('http://' + document.domain + ':' + location.port + '/realtime');

    console.log(socket);
    socket.on('connect', function() {
		socket.send('connect!');
        console.log('hello');
	});

    socket.on('admin', function(data){

        console.log(data);

    });







</script>
```

**Comment by miguelgrinberg** [comment]
Remove `app.run()` from your script. The `socketio.run()` call runs includes the functionality provided by it.

**Comment by connect2robiul** [comment]
This error will be shown when emit line run . can not solve error 


```
192.168.1.88 - - [28/Mar/2018 11:10:43] "GET /socket.io/?EIO=3&transport=polling&t=1522213819914-26&sid=eb576e5e0b054e34a786643d58b0ae07 HTTP/1.1" 200 -
[{'device': 'CO74', 'message': 'Colling'}]
192.168.1.88 - - [28/Mar/2018 11:10:43] "GET /socket.io/?EIO=3&transport=polling&t=1522213831032-3&sid=41d40553edd94c80935731d9a6e3c236 HTTP/1.1" 200 -
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2606, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1470, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 995, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1273, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1838, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2285, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2456, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2603, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "app.py", line 86, in on_message
    db.session.add(ncsdata)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.2.0b1-py2.7-linux-armv7l.egg/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.2.0b1-py2.7-linux-armv7l.egg/sqlalchemy/util/_collections.py", line 1001, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.2.0b1-py2.7-linux-armv7l.egg/sqlalchemy/orm/session.py", line 2903, in __call__
    return self.class_(**local_kw)
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 145, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 922, in engine
    return self.get_engine()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 941, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 533, in get_engine
    uri = self.get_uri()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 524, in get_uri
    return self._app.config['SQLALCHEMY_DATABASE_URI']
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/usr/lib/python2.7/dist-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context

```

**Comment by miguelgrinberg** [comment]
That has nothing to do with this package. You are trying to use the database from a mqtt event handler, so there is no application context. Create a context and you should be fine:

    with app.app_context():
        # do what you need with the database here

**Comment by connect2robiul** [comment]
now the error is solved but still, data is not coming

**Comment by miguelgrinberg** [comment]
I can't really help you with that. You need to debug your application to see why the message isn't being sent. You can enable logging for Socket.IO if that helps, see the documentation for details.
