### ISSUE TITLE
weird behavior form debug=True

### ISSUE THREAD

**Issue by habi3000** [miguelgrinberg/Flask-SocketIO#684]
hi, i am having a problem with ssl so i tried  to use debug=True with socketio.run() to figure out what is going on but instead of that it prevented the server from running at all with an error regarding address already in use when i remove it the server works great

 here is my code 
```
from gevent import monkey
monkey.patch_all()
import redis, os, time
import gevent.socket as socket
import gevent.ssl as ssl
from time import gmtime, strftime
from multiprocessing import Process
from threading import Thread
from flask import *
from flask_socketio import SocketIO


mycert = "/home/habi/PycharmProjects/untitled3/cert.pem"
mycert2 = "/home/habi/PycharmProjects/untitled3/cert2.pem"

app = Flask(__name__)
app.secret_key = '777777777'
socketio = SocketIO(app, logger=True, engineio_logger=True, async_mode='gevent')
rdb = redis.StrictRedis(host='77777777', port=16112, db=0,
                        password='7777777')
os.environ['TZ'] = 'Riyadh'
time.tzset()


class PrintExceptThread(Thread):
    def run(self):
        try:
            self._run()
        except Exception as e:
            print('{} got exception {}'.format(self.__class__.__name__, e))


class lowlevelsocket(Process):
    def run(self):
        print("lowlevelsocket")
        while True:
            print("Waiting for incoming connections...")
            tcpsock.listen(20)
            (conn, (ip, port)) = tcpsock.accept()
            newthread = ClientThread(ip, port, conn)
            newthread.start()


class ClientThread(Thread):
    def __init__(self, ip, port, conn):
        super().__init__()
        self.ip = ip
        self.port = port
        # self.conn = context.wrap_socket(conn, server_side=True)
        self.conn = conn
        print("[+] New thread started for {}: {}".format(ip, port))

    def run(self):
        while True:
            data = self.conn.recv(2048)
            if not data:
                break
            rdb.publish('carmessage', data)


def carmessageHandler(message):
    lis = str(message['data'].decode('ascii')).strip().split(',')
    if len(lis) > 2:
        link = 'https://www.google.com/maps/search/?api=1&query={},{}'.format(lis[1], lis[2])
    ltime = strftime("%a, %d %b %Y %H:%M:%S", gmtime())
    print(lis)
    if lis[0] == 'drunk':
        socketio.send("[+] " + ltime + " WARNING Drunk driver detected at <a href=" + link + " >this location</a> ")
    elif lis[0] == 'rollover':
        socketio.send("[+] " + ltime + " WARNING Roll Over detected at <a href=" + link + " >this location</a> ")
    elif lis[0] == 'airbag':
        socketio.send("[+] " + ltime + " WARNING Accident detected at <a href=" + link + " >this location</a> ")
    elif lis[0] == 'speed':
        socketio.send(
            "[+] " + ltime + " WARNING Speed Violation detected at <a href=" + link + " >this location</a> with vechile ID=" + str(
                lis[3]))
    else:
        socketio.send(ltime + " " + str(lis))


@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if request.form['password'] == 'admin' and request.form['username'] == 'admin':
            session['user'] = request.form['username']
            return redirect(url_for('carmsg'))
    return render_template('index.html')


@app.route('/carmsg/')
def carmsg():
    if g.user:
        return render_template('carmsg.html')
    return render_template('index.html')


@app.before_request
def beforeRequest():
    g.user = None
    if 'user' in session:
        g.user = session['user']


@socketio.on('message')
def handle_message(message):
    print('received message: ' + message)


context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
context.load_cert_chain(certfile=mycert, keyfile=mycert)
TCP_IP = '0.0.0.0'
TCP_PORT = 5300
BUFFER_SIZE = 1024
tcpsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
tcpsock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
tcpsock.bind((TCP_IP, TCP_PORT))
lowlevelsocketPro = lowlevelsocket()
lowlevelsocketPro.start()
p = rdb.pubsub(ignore_subscribe_messages=True)
p.subscribe(**{'carmessage': carmessageHandler})
p.run_in_thread(0.001)
#socketio.run(app, debug=True, port=5200, keyfile=mycert2, certfile=mycert2)
socketio.run(app,debug=True, port=5000)
```

**and here is the trace back**

```
/home/habi/PycharmProjects/untitled3/venv/bin/python /home/habi/PycharmProjects/untitled3/server.py
Server initialized for gevent.
lowlevelsocket
Waiting for incoming connections...
 * Restarting with stat
Server initialized for gevent.
Traceback (most recent call last):
  File "/home/habi/PycharmProjects/untitled3/server.py", line 118, in <module>
    tcpsock.bind((TCP_IP, TCP_PORT))
OSError: [Errno 98] Address already in use
```

i am running on ubuntu linux here is what is have tried so far 
1-checked that there is no process running with `lsof -i`
2-removed debug=True, it works great 
3-changed the ports for both high and low level sockets 
finally this is the error i get with ssl maybe it is related somehow 

```
/home/habi/PycharmProjects/untitled3/venv/bin/python /home/habi/PycharmProjects/untitled3/server.py
Server initialized for gevent.
lowlevelsocket
Waiting for incoming connections...
Traceback (most recent call last):
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/server.py", line 174, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 642, in wrap_socket
    ciphers=ciphers)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 232, in __init__
    raise x
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 228, in __init__
    self.do_handshake()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 545, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:777)
Sat Apr  7 13:24:27 2018 <Greenlet at 0x7f144452d800: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with SSLError

Traceback (most recent call last):
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/server.py", line 174, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 642, in wrap_socket
    ciphers=ciphers)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 232, in __init__
    raise x
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 228, in __init__
    self.do_handshake()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 545, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:777)
Sat Apr  7 13:24:28 2018 <Greenlet at 0x7f144452d800: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with SSLError

Traceback (most recent call last):
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/server.py", line 174, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 642, in wrap_socket
    ciphers=ciphers)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 232, in __init__
    raise x
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 228, in __init__
    self.do_handshake()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/gevent/_ssl3.py", line 545, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:777)
Sat Apr  7 13:24:30 2018 <Greenlet at 0x7f144452d800: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with SSLError
```
this error keeps repeating as long as the server is running.

**Comment by miguelgrinberg** [comment]
Should you be using a cert file and a key file? You are passing `cert2` as cert and key both.

**Comment by habi3000** [comment]
thanks for your response, 
as far as i understand the certificate and the key can be concatenated into one file, anyway i tried to use two files one for the key and one for the certificate, but i got the same behavior

**Comment by habi3000** [comment]
hi, i tried to use eventlet instead of gevent. with `debug=True` it gives the same error and stops the server. without it:-
1-when not using ssl every thing works correctly as gevent.
2-when passing the cert and key file as arguments to socketio.run() it produces the following error 
`/home/habi/PycharmProjects/untitled3/venv/bin/python /home/habi/PycharmProjects/untitled3/server.py
Server initialized for eventlet.
lowlevelsocket
Waiting for incoming connections...
Traceback (most recent call last):
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 458, in fire_timers
    timer()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/greenthread.py", line 218, in main
    result = function(*args, **kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 781, in process_request
    proto.__init__(conn_state, self)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 335, in __init__
    self.handle()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 368, in handle
    self.handle_one_request()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 397, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 380, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/green/ssl.py", line 204, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/green/ssl.py", line 225, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/green/ssl.py", line 139, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/green/ssl.py", line 109, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2217)
Traceback (most recent call last):
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 458, in fire_timers
    timer()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/greenthread.py", line 218, in main
    result = function(*args, **kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 781, in process_request
    proto.__init__(conn_state, self)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 335, in __init__
    self.handle()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 368, in handle
    self.handle_one_request()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 397, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 380, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/green/ssl.py", line 204, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/green/ssl.py", line 225, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/green/ssl.py", line 139, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/home/habi/PycharmProjects/untitled3/venv/lib/python3.6/site-packages/eventlet/green/ssl.py", line 109, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2217)
`

**Comment by miguelgrinberg** [comment]
The error has nothing to do with Flask-SocketIO. Something in your certificate or private key is causing SSL to throw these errors. I suggest you try to build a simpler server that uses SSL with the async framework of your choice and only when you get that working you incorporate the SocketIO portion.

**Comment by habi3000** [comment]
i think you are right.
thanks a lot.

**Comment by habi3000** [comment]
but what about the `debug=True` weird behavior ?
it outputs the error even without ssl 
`Server initialized for eventlet.
low-level-socket
Waiting for incoming connections...
 * Restarting with stat
Server initialized for eventlet.
Traceback (most recent call last):
  File "server.py", line 114, in <module>
    tcpsock.bind((TCP_IP, TCP_PORT))
OSError: [Errno 98] Address already in use
`

this is the error message, also the code works perfectly with out `debut=True`, which leads me to think that the code is correct and also  i am sure that there is no other process that is using the address

**Comment by miguelgrinberg** [comment]
Probably some sort of bad interaction with the Flask reloader, which is not fully compatible with async frameworks such as gevent or eventlet. Try running debug mode with the reloader disabled.
