### ISSUE TITLE
Greenlet Primitive Issue

### ISSUE THREAD

**Issue by yennhan96** [miguelgrinberg/Flask-SocketIO#708]
I am not sure where to have this posted, so I will post it here.
I have follow the required task for the chatroom, and the following has cause me issue that I can't understand as it is not able to produce user is connected or following.
-Two Prominent Package installed
-Gevent
-login manager

```
from flask import Flask
from flask_socketio import SocketIO
from flask_login import LoginManager
socketio = SocketIO()
login_manager = LoginManager()
async_mode = None 
def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'
    from .main import main as main_blueprint
    from .main import dash as dash_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(dash_blueprint)
    socketio.init_app(app,async_mode=async_mode)
    return app
```

Here is my code for app/__init__.py

Problem Faced. 
```
KeyboardInterrupt
2018-05-15T19:56:00Z
Traceback (most recent call last):
  File "/Users/leowyennhan/Desktop/Project-official/main.py", line 11, in <module>
    socketio.run(app)
  File "/Users/leowyennhan/Desktop/One-identity/venv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 556, in run
    self.wsgi_server.serve_forever()
  File "/Users/leowyennhan/Desktop/One-identity/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
KeyboardInterrupt
```

**Comment by yennhan96** [comment]
Here is a copy of my structure, I am stuck at this for sometimes and couple of days now, pardon my language. I am not sure what went wrong. 
[main copy.zip](https://github.com/miguelgrinberg/Flask-SocketIO/files/2006661/main.copy.zip)

**Comment by yennhan96** [comment]
Thank You for replying.

So basically what happen is when I split the socket.io into another file called event.py, it didn't work, but if I put the socket io functions into the main.py file, it works. Is there a missing blueprint I don't understand? Cheers!

**Comment by miguelgrinberg** [comment]
I need details. It does not help if you just tell me "it didn't work", I need to know what didn't work, what error(s) did you get, snippets or all your code, etc.

**Comment by yennhan96** [comment]
> 
Sorry for the miscommunication. The event.py which contain the socket.io code functions, it doesn't run, I would like to split it, but when I locate it into main_1.py, it works as following so this means that my html is working just fine. Thank You so much!
My Code Structure Goes Like This, I think its more of a code structure problem.
**Project 
.
|--app
----- |--main
------------|--''__init__.py''
------------|--Dashboard.py
------------|--event.py
------------|--forms.py
------------|--routes.py
----- |--static
------------|--JS
----- |--templates
----- |--''__init__.py''
|--main_1.py**
> 
In my init.py of app
```
from flask import Flask
from flask_login import LoginManager
from flask_socketio import SocketIO
socketio = SocketIO(manage_sesison=False)
login_manager = LoginManager()

def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'
    from .main import main as main_blueprint
    from .main import dash as dash_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(dash_blueprint)
    socketio.init_app(app)
    return app
```
In my main_1.py of app
```
from gevent import monkey
monkey.patch_all()
from app import create_app, socketio, login_manager
from flask_socketio import send,emit,disconnect
from flask_login import current_user
import functools

app = create_app(debug=True)
login_manager.init_app(app)
login_manager.login_view='login'

def authenticated_only(f):
    @functools.wraps(f)
    def wrapped(*args, **kwargs):
        if not current_user.is_authenticated:
            disconnect()
        else:
            return f(*args, **kwargs)
    return wrapped

@socketio.on('message',namespace='/dashboard_login')
def handleMessage(msg):
    print('Message'+msg)
    send(msg, broadcast=True,namespace='/dashboard_login')

@socketio.on('my event',namespace='/dashboard_login')
def test_message(message):
    emit('my response', {'data': 'got it!'})

if __name__ == '__main__':
    socketio.run(app)
```
In my __init__.py of my main folder. 
```
from flask import Blueprint

main = Blueprint('main', __name__)
dash = Blueprint('dash', __name__)

from . import routes, dashboard, event

```
In my routes.py of my main folder.
```
from flask import redirect, url_for, render_template, request
from . import main
import decimal
import boto3,json
from botocore.exceptions import ClientError
from werkzeug.security import check_password_hash
from flask_login import UserMixin, login_user,login_required,logout_user,current_user
from main1 import login_manager



dynamodb = boto3.resource('dynamodb', region_name="ap-southeast-1")
# Helper class to convert a DynamoDB item to JSON.

class DecimalEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, decimal.Decimal):
            if o % 1 > 0:
                return float(o)
            else:
                return int(o)
        return super(DecimalEncoder, self).default(o)

class User(UserMixin):
    user = dynamodb.Table('CRM-user')

    def __init__(self, user):
        self.id = user

    def __repr__(self):
        return "%d" % (self.id)

@login_manager.user_loader
def load_user(user):
    return User(user)

@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html')

@main.route('/login',methods=['GET','POST'])
def login():
    if request.method == 'POST':
        user = dynamodb.Table('CRM-user')
        email = request.form.get('email')
        password = request.form.get('password')
        try:
            response = user.get_item(
                Key={
                    'user_id': email
                }
            )
        except ClientError as e:
            return "%s" %(e.response['Error']['Message'])
        else:
            try:
               item = response['Item']
            except Exception:
                word="Invalid Username!  ..."
                return render_template('index.html',condition=word)
            else:
                if check_password_hash(item['password'],password):
                    user=User(email)
                    login_user(user)
                    return redirect(url_for('main.dashboard_login'))
                else:
                    word="Wrong Password"
                    return render_template('index.html',condition=word)


@main.route('/dashboard_login',methods=['GET','POST'])
@login_required
def dashboard_login():
    user = dynamodb.Table('CRM-user')
    response = user.get_item(
        Key={
            'user_id': current_user.id
        }
    )
    item = response['Item']
    name=item['name'][0]
    return render_template('dashboard.html',name=name,username=name)


@login_manager.unauthorized_handler
def unauthorized_handler():
    return 'Unauthorized'

@main.route("/logout")
@login_required
def logout():
    logout_user()
    print('You have been logged out.')
    return redirect(url_for('main.index'))

```
In my main file there is a dashboard.py 
```
from flask import *
from . import dash
from flask_login import current_user,login_required
import boto3

dynamodb = boto3.resource('dynamodb', region_name="ap-southeast-1")



@dash.route('/search',methods=['GET','POST'])
@login_required
def searching():
    if request.method == 'POST':
        search_item=request.form.get('searchbox')
        user_id = current_user.id
        print(search_item,user_id)
        return redirect(url_for('main.dashboard_login'))
```

**Comment by miguelgrinberg** [comment]
Please reopen and provide more information if this is still a problem, specifically what does "doesn't run" mean in this context.
