### ISSUE TITLE
KeyError: Namespace not found

### ISSUE THREAD

**Issue by YatishB** [miguelgrinberg/Flask-SocketIO#72]
All my clients connect to the server using the namespace `/test`. Upon a certain action on the client, the socket on the client is triggering a function on the server that iterates through all the connected clients using the following code segment:

    for sessid, socket in request.namespace.socket.server.sockets.items():
		print "id : %r  random: %r" % (socket['/test'].session['id'], socket['/test'].session['random'])

where each connection has an 'id' and a 'random' key assigned to it on connection.

However sometimes the server gives the following error indicating that the namespace key was not found:

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/local/lib/python2.7/dist-packages/socketio/virtsocket.py", line 403, in _receiver_loop
        retval = pkt_ns.process_packet(pkt)
      File "/usr/local/lib/python2.7/dist-packages/socketio/namespace.py", line 155, in process_packet
        return self.process_event(packet)
      File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 64, in process_event
        return self.socketio._dispatch_message(app, self, message, args)
      File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 137, in _dispatch_message
        ret = self.messages[namespace.ns_name][message](*args)
      File "/home/ubuntu/flask-app/current/py/flaskapp/main/sockets.py", line 190, in gameInitialisedByClient
        print "id : %r  random: %r" % (socket['/test'].session['id'], socket['/test'].session['random'])
      File "/usr/local/lib/python2.7/dist-packages/socketio/virtsocket.py", line 190, in __getitem__
        return self.active_ns[key]
    KeyError: '/test'
    <Greenlet at 0x7f483bc6bf50: <bound method Socket._receiver_loop of <socketio.virtsocket.Socket object at 0x7f483a5ac6d0>>> failed with KeyError

I do not understand why i get this error since all my sockets that connect to the server are connecting on the same namespace. Moreover, this error is experienced only during a fraction of the function calls. Why isn't this error consistent?

**Comment by miguelgrinberg** [comment]
@YatishB This is probably due to a race condition when a new client connects, but its connection isn't fully established yet. The server knows about the client, but hasn't completed its registration, so it does not know that it is on the `/test` namespace yet.

Can you can check if the key exists before accessing it?

**Comment by gordol** [comment]
I'm noticing this too, but it's simply from firing en emit from a connect handler....



```
Traceback (most recent call last):
  File "/Users/tinix/.virtualenvs/visual-management-system/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/tinix/.virtualenvs/visual-management-system/lib/python2.7/site-packages/socketio/virtsocket.py", line 403, in _receiver_loop
    retval = pkt_ns.process_packet(pkt)
  File "/Users/tinix/.virtualenvs/visual-management-system/lib/python2.7/site-packages/socketio/namespace.py", line 164, in process_packet
    return self.call_method_with_acl('recv_connect', packet)
  File "/Users/tinix/.virtualenvs/visual-management-system/lib/python2.7/site-packages/socketio/namespace.py", line 240, in call_method_with_acl
    return self.call_method(method_name, packet, *args)
  File "/Users/tinix/.virtualenvs/visual-management-system/lib/python2.7/site-packages/socketio/namespace.py", line 282, in call_method
    return method(*args)
  File "/Users/tinix/Development/projects/visual-management-system/lib/socketio/__init__.py", line 97, in recv_connect
    self.socketio._dispatch_message(app, self, 'connect')
  File "/Users/tinix/Development/projects/visual-management-system/lib/socketio/__init__.py", line 154, in _dispatch_message
    ret = self.messages[namespace.ns_name][message](*args)
  File "/Users/tinix/Development/projects/visual-management-system/vms/view_utils.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/Users/tinix/Development/projects/visual-management-system/vms/namespaces/lcms.py", line 264, in lcms_connect
    emit('previous_reinject_requests', lcms_get_reinject_requests(delivery), namespace='/lcms')
  File "/Users/tinix/Development/projects/visual-management-system/lib/socketio/__init__.py", line 272, in emit
    return request.namespace.emit(event, *args, **kwargs)
  File "/Users/tinix/Development/projects/visual-management-system/lib/socketio/__init__.py", line 131, in emit
    return request.namespace.socket[ns_name].base_emit(event, *args, **kwargs)
  File "/Users/tinix/.virtualenvs/visual-management-system/lib/python2.7/site-packages/socketio/virtsocket.py", line 190, in __getitem__
    return self.active_ns[key]
KeyError: '/lcms'
<Greenlet at 0x108965730: <bound method Socket._receiver_loop of <socketio.virtsocket.Socket object at 0x10de1e510>>> failed with KeyError
```

Perhaps I could simply put that emit in a loop with an exception handler so it will retry if it fails with a KeyError... but should that be necessary? Or can we consider this a bug within the library? Shouldn't the connect callback **not** fire if the client isn't fully "connected"?

**Comment by gordol** [comment]
Actually you know what, this is using an older Flask-SocketIO version... please disregard, this very well may be fixed in the newer release.
