### ISSUE TITLE
Shutting down the gevent-socketio server

### ISSUE THREAD

**Issue by jwg4** [miguelgrinberg/Flask-SocketIO#73]
In the Flask book example 15-6 shows how to shutdown the Werkzeug server, for when using it to run unit tests.

In my unit tests I am using gevent-socketio, starting it by calling 

    def run():
        socketio.run(cls.app, host='0.0.0.0', port=4999, log=None, policy_server=False)

    td = threading.Thread(target=run)
    td.start()

When I run unittests in several classes, both of which start the server like this, I get an error message when the second one runs:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jack/git/flask-prismfp/test/selenium_testing.py", line 41, in run
    socketio.run(cls.app, host='0.0.0.0', port=4999, log=None, policy_server=False)
  File "/home/jack/git/flask-prismfp/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 250, in run
    self.server.serve_forever()
  File "/home/jack/git/flask-prismfp/venv/local/lib/python2.7/site-packages/gevent/baseserver.py", line 282, in serve_forever
    self.start()
  File "/home/jack/git/flask-prismfp/venv/local/lib/python2.7/site-packages/gevent/baseserver.py", line 234, in start
    self.init_socket()
  File "/home/jack/git/flask-prismfp/venv/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 639, in init_socket
    StreamServer.init_socket(self)
  File "/home/jack/git/flask-prismfp/venv/local/lib/python2.7/site-packages/gevent/server.py", line 78, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/home/jack/git/flask-prismfp/venv/local/lib/python2.7/site-packages/gevent/server.py", line 89, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
  File "/home/jack/git/flask-prismfp/venv/local/lib/python2.7/site-packages/gevent/server.py", line 153, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
error: [Errno 98] Address already in use: ('0.0.0.0', 4999)
```

However, the unit tests still succeed.
Is there some similar way that I can close the server down when the unit test fixture completes?
It could be from within a flask view as in the book example, or in the unit test class.

**Comment by noah** [comment]
Does this `stop` behavior work in newer versions of Flask SocketIO?

**Comment by miguelgrinberg** [comment]
I thought it did, but I have an open issue #162 that I have yet to investigate.

**Comment by noah** [comment]
Some diagnosis:

```     
from flask.ext.socketio import SocketIO                                                                  
sio = SocketIO()
print sio.server                                                                                   
sio.server.stop()          sio.server.stop()          
```

Looks like the sio object is a socket.server.Server object:

```
<socketio.server.Server object at 0x7f007c553190>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "[...]remote.py", line 63, in fics_r
    sio.server.stop()
AttributeError: 'Server' object has no attribute 'stop'
```

I believe that Server is a python-socketio (https://github.com/miguelgrinberg/python-socketio) socketio.Server object which is instantiated here: https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L117

I don't see a `stop` method in this code, assuming I've traced it correctly:

https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/server.py



As an aside, the API Reference section here (toward the bottom) seems missing:

https://flask-socketio.readthedocs.org/en/latest/
