### ISSUE TITLE
Connection will be auto-closed after some hours

### ISSUE THREAD

**Issue by GitKKg** [miguelgrinberg/Flask-SocketIO#740]
Hi,Miguel
if just keep idle for some while, probably some hours, the connection will be closed,the log is shown below, broker_heartbeat of celery is already set to 0,but it seems to take no effect

ws Connected sid is 0x 021099aa317247d38c003e2d6d8a601c
<Request 'http://localhost:85/socket.io/?EIO=3&transport=polling&t=MINy8tW' [GET]>
some hours later....
Connection error while reading from queue
Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\socketio\kombu_manager.py", line 98, in _listen
    message = queue.get(block=True)
  File "c:\Python34\lib\site-packages\kombu\simple.py", line 53, in get
    timeout=timeout and remaining)
  File "c:\Python34\lib\site-packages\kombu\connection.py", line 288, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "c:\Python34\lib\site-packages\kombu\transport\pyamqp.py", line 95, in drain_events
    return connection.drain_events(**kwargs)
  File "c:\Python34\lib\site-packages\amqp\connection.py", line 303, in drain_events
    chanmap, None, timeout=timeout,
  File "c:\Python34\lib\site-packages\amqp\connection.py", line 366, in _wait_multiple
    channel, method_sig, args, content = read_timeout(timeout)
  File "c:\Python34\lib\site-packages\amqp\connection.py", line 330, in read_timeout
    return self.method_reader.read_method()
  File "c:\Python34\lib\site-packages\amqp\method_framing.py", line 189, in read_method
    raise m
  File "c:\Python34\lib\site-packages\amqp\method_framing.py", line 107, in _next_method
    frame_type, channel, payload = read_frame()
  File "c:\Python34\lib\site-packages\amqp\transport.py", line 154, in read_frame
    frame_header = read(7, True)
  File "c:\Python34\lib\site-packages\amqp\transport.py", line 283, in _read
    raise IOError('Socket closed')
OSError: Socket closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\socketio\kombu_manager.py", line 100, in _listen
    yield message.payload
  File "c:\Python34\lib\site-packages\kombu\simple.py", line 30, in __exit__
    self.close()
  File "c:\Python34\lib\site-packages\kombu\simple.py", line 82, in close
    self.consumer.cancel()
  File "c:\Python34\lib\site-packages\kombu\messaging.py", line 461, in cancel
    cancel(tag)
  File "c:\Python34\lib\site-packages\amqp\channel.py", line 1631, in basic_cancel
    self._send_method((60, 30), args)
  File "c:\Python34\lib\site-packages\amqp\abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "c:\Python34\lib\site-packages\amqp\method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "c:\Python34\lib\site-packages\amqp\transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
  File "c:\Python34\lib\site-packages\eventlet\greenio\base.py", line 400, in sendall
    tail = self.send(data, flags)
  File "c:\Python34\lib\site-packages\eventlet\greenio\base.py", line 394, in send
    return self._send_loop(self.fd.send, data, flags)
  File "c:\Python34\lib\site-packages\eventlet\greenio\base.py", line 381, in _send_loop
    return send_method(data, *args)
ConnectionResetError:

**Comment by miguelgrinberg** [comment]
This seems to be a recently discovered problem for Celery as well. Would it make sense for your application to keep the connection active by sending a dummy payload every few minutes? At least until this issue is resolved on the kombu/amqp side.

**Comment by GitKKg** [comment]
That's ok.
I will give a try on python 3.7 and its related newest modules, see if it's same too,now I work on 3.4

**Comment by GitKKg** [comment]
it seems 3.7 also gets the issue,but seems new version celery constantly send wake up already,at least seen by log,that's weird ,rabbitmq's bad?
