### ISSUE TITLE
Can't connect with "websockets" client library?

### ISSUE THREAD

**Issue by gatoatigrado** [miguelgrinberg/Flask-SocketIO#776]
I'm a bit confused about how to get this library working ... if someone could send me a simple example, I'd appreciate it. I saved the Python code from the main webpage to a file, and installed the following libraries,

```sh
pip install flask flask-socketio websockets
```

(exact library versions [here](https://pastebin.com/kLSrXsWC)), and then save the following to `/tmp/test-socketio.py`,

```python
from flask import Flask, render_template
from flask_socketio import SocketIO, emit
    
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@app.route('/')
def index():
    return render_template('index.html')

@socketio.on('my_event')
def test_message(message):
    emit('my response', {'data': 'got it!'})

if __name__ == '__main__':
    socketio.run(app)
```

I ran this, and executed the following code in a Jupyter notebook cell,

```python
import asyncio, websockets

async def run():
    async with websockets.connect('ws://localhost:5000/socket.io/') as websocket:
        pass

asyncio.ensure_future(run())
loop = asyncio.get_event_loop()
loop.run_forever()
```

Unfortunately this gives the following error,

```
Task exception was never retrieved
future: <Task finished coro=<run() done, defined at <ipython-input-35-76c0bd8a217f>:3> exception=InvalidMessage('Malformed HTTP message',)>
Traceback (most recent call last):
  File "/home/gatoatigrado/bin/venv3/lib/python3.6/site-packages/websockets/client.py", line 77, in read_http_response
    status_code, headers = yield from read_response(self.reader)
  File "/home/gatoatigrado/bin/venv3/lib/python3.6/site-packages/websockets/http.py", line 129, in read_response
    raise ValueError("Unsupported HTTP version: %r" % version)
ValueError: Unsupported HTTP version: b'HTTP/1.0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<ipython-input-35-76c0bd8a217f>", line 4, in run
    async with websockets.connect('ws://localhost:5000/socket.io') as websocket:
  File "/home/gatoatigrado/bin/venv3/lib/python3.6/site-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self
  File "/home/gatoatigrado/bin/venv3/lib/python3.6/site-packages/websockets/py35/client.py", line 19, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/home/gatoatigrado/bin/venv3/lib/python3.6/site-packages/websockets/client.py", line 260, in handshake
    status_code, response_headers = yield from self.read_http_response()
  File "/home/gatoatigrado/bin/venv3/lib/python3.6/site-packages/websockets/client.py", line 79, in read_http_response
    raise InvalidMessage("Malformed HTTP message") from exc
websockets.exceptions.InvalidMessage: Malformed HTTP message
```

The output from the server is as follows,

```
> python test-socketio.py
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Serving Flask app "test-socketio" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [03/Sep/2018 20:43:44] "GET /socket.io/ HTTP/1.1" 200 -
```

When I try this in a uwsgi+nginx container, I get an error about the status code being 200 instead of 101. If anyone has a working end-to-end example, I'd appreciate it! Maybe some integration tests could be added to this library using docker-compose?

**Comment by miguelgrinberg** [comment]
Flask-SocketIO is a Socket.IO server, not a WebSocket server. You have to use a Socket.IO client to connect to it.
