### ISSUE TITLE
room in socketio message handler error

### ISSUE THREAD

**Issue by rupesh2017** [miguelgrinberg/Flask-SocketIO#786]
import os
import requests

from flask import Flask,jsonify,render_template,request
from flask_socketio import SocketIO,emit,join_room,leave_room

from werkzeug import secure_filename

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")
socketio=SocketIO(app)

@app.route("/")
def index():
    return render_template("index.html")

    
@socketio.on('join')
def on_join(data):
    username = data['username']
    room = data['room']
    join_room(room)
    send(username + ' has entered the room.', room=room)

@socketio.on('leave')
def on_leave(data):
    username = data['username']
    room = data['room']
    leave_room(room)
    send(username + ' has left the room.', room=room)

**_127.0.0.1 - - [2018-09-08 17:19:40] "GET /socket.io/?EIO=3&transport=polling&t=1536407379432-22 HTTP/1.1" 200 345 0.000999
127.0.0.1 - - [2018-09-08 17:19:44] "GET / HTTP/1.1" 200 732 0.009974
127.0.0.1 - - [2018-09-08 17:19:44] "GET /socket.io/?EIO=3&transport=polling&t=1536407384504-0 HTTP/1.1" 200 345 0.000998
message handler error
Traceback (most recent call last):
  File "c:\users\rupesh kumar\appdata\local\programs\python\python36\lib\site-packages\engineio\server.py", line 411, in _trigger_event
    return self.handlers[event](*args)
  File "c:\users\rupesh kumar\appdata\local\programs\python\python36\lib\site-packages\socketio\server.py", line 522, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "c:\users\rupesh kumar\appdata\local\programs\python\python36\lib\site-packages\socketio\server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "c:\users\rupesh kumar\appdata\local\programs\python\python36\lib\site-packages\socketio\server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "c:\users\rupesh kumar\appdata\local\programs\python\python36\lib\site-packages\socketio\server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "c:\users\rupesh kumar\appdata\local\programs\python\python36\lib\site-packages\flask_socketio\__init__.py", line 251, in _handler
    *args)
  File "c:\users\rupesh kumar\appdata\local\programs\python\python36\lib\site-packages\flask_socketio\__init__.py", line 634, in _handle_event
    ret = handler(*args)
  File "C:\Users\Rupesh Kumar\Desktop\pop\local-storage-chat-note-app\room2\application.py", line 26, in on_join
    username = data['username']
KeyError: 'username'
127.0.0.1 - - [2018-09-08 17:19:53] "POST /socket.io/?EIO=3&transport=polling&t=1536407393645-2&sid=f1e636ca7cbf48f3bdca04f1f13fea9f HTTP/1.1" 200 195 0.007690_**

**Comment by rupesh2017** [comment]
that problem solved but where do will i get the message
  
send(username + ' has entered the room.', room=room)

i opened index.html , checked cmd but i do not see anything.

**Comment by miguelgrinberg** [comment]
If you use `send()`, on the other side you have to have an event handler for the `message` event. If you use `emit()`, you can define the name of the event. Your JavaScript needs the `message` event if you want to catch those strings that you send via `send()`.

**Comment by rupesh2017** [comment]
socket.on('chat',(data)=>{
 const li = document.createElement('li');
 li.innerHTML=`${data.username} is online`
 document.querySelector('#tasks').append(li);

});

I have used right, **chat**  client side as well **emit** so why not displaying output  
and i really need a example for difference b/w send and emit client side seem me same thing ,sorry

**Comment by miguelgrinberg** [comment]
You should always prefer `emit()`, the `send()` function is there for legacy reasons only.

I can't really tell you what's wrong. You need to debug your application to find out. There are logging options for the server and the client that you can enable to have a detailed report on what actions are being issued on each side.

For example, does your submit handler in the client run when you press the button? If yes, does the `join` handler in the server run right after?

**Comment by rupesh2017** [comment]
i don't what was the issue but it working now after i closed and started server.thanks
