### ISSUE TITLE
Misbehaving websocket client can crash server

### ISSUE THREAD

**Issue by awrichar** [miguelgrinberg/Flask-SocketIO#810]
I have an app based on Flask-SocketIO (running on eventlet), and this week was seeing frequent issues where the server would print the below trace and then stop responding to all requests.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eventlet/wsgi.py", line 547, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 360, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 282, in handle_request
    environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 103, in handle_get_request
    start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 145, in _upgrade_websocket
    return ws(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/async_eventlet.py", line 19, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 130, in __call__
    self.handler(ws)
  File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 170, in _websocket_handler
    pkt = ws.wait()
  File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 788, in wait
    for i in self.iterator:
  File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 643, in _iter_frames
    message = self._recv_frame(message=fragmented_message)
  File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 669, in _recv_frame
    header = recv(2)
  File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 578, in _get_bytes
    d = self.socket.recv(numbytes - len(data))
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 364, in recv
    return self._recv_loop(self.fd.recv, b'', bufsize, flags)
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 358, in _recv_loop
    self._read_trampoline()
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 329, in _read_trampoline
    timeout_exc=socket_timeout('timed out'))
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 208, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/usr/local/lib/python3.6/site-packages/eventlet/hubs/__init__.py", line 164, in trampoline
    return hub.switch()
  File "/usr/local/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 297, in switch
    return self.greenlet.switch()
socket.timeout: timed out
```
This looks similar to #557, but most of the debugging there seemed to center around fixing the client to avoid the error. In my case, the client is an Ember.js app. I was using Mirage for data mocking, but attempting to let websocket traffic flow using Mirage's `passthrough`. My best interpretation is that `passthrough` doesn't work with websockets, and was causing an unexpected sequence of events in the websocket exchange. I've since made some adjustments on the client side and it seems to mitigate the issue.

Regardless, if a _misbehaving_ client can lock up and crash my server, it seems like a _malicious_ client could do the same thing. No matter what the client does, the server should not lock up and crash. If a socket times out waiting on a client response, the server should just move on/drop the client/etc - anything to gracefully handle the broken flow and keep serving other requests.

**Comment by miguelgrinberg** [comment]
It seems this is a problem with eventlet's websocket implementation, not specifically with the Socket.IO server. The last operation was a weboscket `wait()` call, which is what's used to read from the stream. Do you have any idea what the client sent?

**Comment by awrichar** [comment]
Not offhand; I'll have to see if I can reproduce this in a sandbox for better analysis.

I guess there are two questions - 1) can eventlet be fixed? and 2) can Flask-SocketIO do anything to catch and work around this type of thing?

I'll let you know if I can get more info on exactly what the "bad" client was doing.

**Comment by miguelgrinberg** [comment]
This issue in the eventlet repo seems related, but does not contain too much info: https://github.com/eventlet/eventlet/issues/456.
