### ISSUE TITLE
Websockets not connecting over SSL (eventlet, self-signed cert)

### ISSUE THREAD

**Issue by theRageNT** [miguelgrinberg/Flask-SocketIO#842]
Hey! I've been trying to tackle this for a minute now.

I am currently using a self-signed cert to process SSL, and running the application through eventlet.

`socketio.run(app,
                 host="0.0.0.0",
                 debug=True,
                 keyfile=key,
                 certfile=cert)`

My client is JS inside the browser, and I can connect just fine on any desktop platform, however I noticed I was getting a lot of polling transports (and no websocket), so I decided to try and force them.

`var socket = io.connect('https://' + document.domain + ':' + location.port, {transports: ['websocket']});`

I noticed that when I do this and try to connect with a mobile client I get a significant amount of SSL Handshake errors.

`(19444) accepted ('192.168.1.117', 54027)
Traceback (most recent call last):
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\hubs\selects.py", line 55, in wait
    listeners.get(fileno, noop).cb(fileno)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\greenthread.py", line 219, in main
    result = function(*args, **kwargs)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\wsgi.py", line 789, in process_request
    proto.__init__(conn_state, self)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\wsgi.py", line 343, in __init__
    self.handle()
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\wsgi.py", line 376, in handle
    self.handle_one_request()
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\wsgi.py", line 405, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\wsgi.py", line 388, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\green\ssl.py", line 200, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\green\ssl.py", line 215, in _base_recv
    read = self.read(nbytes, buffer_)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\green\ssl.py", line 135, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\green\ssl.py", line 109, in _call_trampolining
    return func(*a, **kw)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure (_ssl.c:2281)
Removing descriptor: 1816`

This error also happens on mobile when not forcing websockets, but it seems to revert back to polling successfully and actual begin to send data.

Anything I might be missing here?

For the record, I didn't monkey-patch eventlet. When I try that i get the following:

`(17476) accepted ('127.0.0.1', 34662)
Traceback (most recent call last):
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\hubs\hub.py", line 460, in fire_timers
    timer()
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\greenthread.py", line 219, in main
    result = function(*args, **kwargs)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\wsgi.py", line 789, in process_request
    proto.__init__(conn_state, self)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\wsgi.py", line 343, in __init__
    self.handle()
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\wsgi.py", line 376, in handle
    self.handle_one_request()
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\wsgi.py", line 405, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\wsgi.py", line 388, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\green\ssl.py", line 200, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\green\ssl.py", line 215, in _base_recv
    read = self.read(nbytes, buffer_)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\green\ssl.py", line 135, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\site-packages\eventlet\green\ssl.py", line 105, in _call_trampolining
    return func(*a, **kw)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\butle\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2281)`

**Comment by miguelgrinberg** [comment]
I don't know what the problem is, but I don't see how this problem can be in this project, which has nothing to do with TLS. Sounds like this could be an issue with Eventlet's web server. You have a couple other web servers to try, Gunicorn and if that does not work, then switch to Gevent.

In any case, I think handling encrypted connections in Python is not the best solution, there are robust proxy servers out there that can handle and terminate TLS right before the Python side, and do so very efficiently. I have been using nginx for this purpose with great success.

**Comment by theRageNT** [comment]
I narrowed the behavior down to the web sockets and figured this would be a good place to start. But I will move onto eventlet and work on tracking it down. Feel free to close.

**Comment by miguelgrinberg** [comment]
You can find simple websocket examples in the eventlet repo. Also, as I said, you can run on Gunicorn to see if that makes any difference and helps narrow down the bug a bit.

**Comment by stefan-falk** [comment]
@theRageNT Have you been able to solve this? I lately ran into the same issue (even though everything worked a few weeks ago).. 

I asked the thing on stackoverflow as well: https://stackoverflow.com/questions/62444764/arraybuffer-at-index-0-is-already-detached-caused-by-ssl-sslerror-ssl-ssl-han
