### ISSUE TITLE
teardown() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by VEDA95** [miguelgrinberg/Flask-SocketIO#852]
Whenever I make a http request to a flask REST API that I have running flask-SocketIO on gunicorn the following error that occurs.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/middleware.py", line 49, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1993, in wsgi_app
    ctx.auto_pop(error)
  File "/usr/local/lib/python3.6/site-packages/flask/ctx.py", line 387, in auto_pop
    self.pop(exc)
  File "/usr/local/lib/python3.6/site-packages/flask/ctx.py", line 376, in pop
    app_ctx.pop(exc)
  File "/usr/local/lib/python3.6/site-packages/flask/ctx.py", line 189, in pop
    self.app.do_teardown_appcontext(exc)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1892, in do_teardown_appcontext
    func(exc)
TypeError: teardown() takes 0 positional arguments but 1 was given
```

How i'm currently running gunicorn:
```
gunicorn --certfile=/etc/pki/tls/certs/ssl_here.crt --keyfile=/etc/pki/tls/certs/ssl_here.key --log-level=error --access-logfile access.log --error-logfile errors.log --worker-class=gevent -w 1 -b 127.0.0.1:8025 sitebackend:app
```

I wasn't having any issues running this particular flask server when I was running from my development environment. However in my production enviroment this error always come up, whether I try opening a socketio connection or even http request to said server. For the dev environment I was running the flask server using uwsgi, where with the production server we use gunicorn (Don't know why this is. Not my server so I just go along with it).

For the current worker class for the gunicorn server i'm using gevent, I also tried runninng the server using eventlet, but I got the same errors. Which is bizarre that eventlet would pop up gevent errors.

If you have a fix, or advice for what I can do to fix this problem i'm all ears. Need the help badly and need to figure this out quick.

**Comment by VEDA95** [comment]
I do but this issues seems to be limited to gunicorn from the looks of it. I ran the same REST API with uwsgi and didn't get this error. Once I have a little more free time i'll have to investigate and see with this is.

**Comment by miguelgrinberg** [comment]
@VEDA95 As I said above, your teardown handler must have an argument. That is how Flask communicates errors to your application.

**Comment by VEDA95** [comment]
@miguelgrinberg except I also get a error when I do that. Whenever I do include a argument I usually get a error back telling me there are no arguments for the teardown handler. I've had it happen before with a couple projects i've used flask for

**Comment by miguelgrinberg** [comment]
Show me a stacktrace when you have an argument in your teardown handler please.

**Comment by VEDA95** [comment]
I will. I'll grab the stacktrace when I have a moment free. I just happened to stumble across another issue that takes a little more precedence right now
