### ISSUE TITLE
'gevent._queue.JoinableQueue' object has no attribute 'Empty'

### ISSUE THREAD

**Issue by max-l** [miguelgrinberg/Flask-SocketIO#871]
I had a settup running fine with FlaskIO 3.0.1, 
I upgraded the underlying OS (ubuntu 16.04 to 18.04) and suddently got this exception 'gevent._queue.JoinableQueue' object has no attribute 'Empty'

Python 3.6.7
Flask-SocketIO==3.0.1
gevent==1.3.6

I tried upgrading to  gevent-1.4.0 and  Flask-SocketIO-3.1.2
and the problem remains

```
127.0.0.1 - - [2019-01-10 19:13:28] "GET /socket.io/?EIO=3&transport=polling&t=1547147608950-245 HTTP/1.1" 500 161 0.015381
Traceback (most recent call last):
  File "/genap2_venv/lib/python3.6/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/genap2_venv/lib/python3.6/site-packages/gevent/pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/genap2_venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/genap2_venv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/genap2_venv/lib/python3.6/site-packages/engineio/middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/genap2_venv/lib/python3.6/site-packages/socketio/server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/genap2_venv/lib/python3.6/site-packages/engineio/server.py", line 333, in handle_request
    transport, b64)
  File "/genap2_venv/lib/python3.6/site-packages/engineio/server.py", line 454, in _handle_connect
    s = socket.Socket(self, sid)
  File "/genap2_venv/lib/python3.6/site-packages/engineio/socket.py", line 17, in __init__
    self.queue = self.server.create_queue()
  File "/genap2_venv/lib/python3.6/site-packages/engineio/server.py", line 430, in create_queue
    sys.modules[queue.__class__.__module__], 'Empty')
AttributeError: 'gevent._queue.JoinableQueue' object has no attribute 'Empty'
2019-01-10T19:13:35Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '50608', 'HTTP_HOST': 'local.genap.ca:9000', (hidden keys: 27)} failed with AttributeError

```

This is the code: 

```
import logging

from gevent import monkey

monkey.patch_all()

from flask import Flask, request
from flask_socketio import SocketIO, emit, join_room, leave_room, disconnect

async_mode = "gevent"

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode=async_mode)


@app.route('/publishMessage', methods=['POST'])
def relay():

    message = request.get_json()

    app.logger.info("will publish message {0} to folder {1}".format(message['event'], message['room']))

    emit('folder_event', message, room=message['room'], namespace='/async/appFolders')

    return "", 200


@socketio.on('join', namespace='/async/appFolders')
def join(message):

    app.logger.info("will subscribe to folder {0} ".format(message['room']))

    join_room(message['room'])

    emit('folder_event', {
        'event': 'subscribed',
        'guid': message['room']
    }, room=message['room'], namespace='/async/appFolders')


@socketio.on('leave', namespace='/async/appFolders')
def leave(message):

    app.logger.info("will unsubscribe from folder {0} ".format(message['room']))

    leave_room(message['room'])


@socketio.on('my_room_event', namespace='/async/appFolders')
def send_room_message(message):

    emit('folder_event', message, room=message['room'])


@socketio.on('disconnect_request', namespace='/async/appFolders')
def disconnect_request():

    disconnect()


@socketio.on('connect', namespace='/async/appFolders')
def test_connect():
    emit('folder_event', {'data': 'Connected'})

if __name__ == '__main__':
    socketio.run(app, debug=True, host='0.0.0.0', port=5000)

else:
    # We are running in Gunicorn
    gunicorn_logger = logging.getLogger("gunicorn.error")
    app.logger.handlers = gunicorn_logger.handlers
    app.logger.setLevel(gunicorn_logger.level)
```

**Comment by miguelgrinberg** [comment]
Yes, this was already reported. Fix coming up in a bit.

**Comment by max-l** [comment]
The problem goes away if I don't use gevent, but I get the warning: 

> WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.

how bad is the loss of performance when running without gevent ? 

or would you recommend a switch to eventlet ? 

Thanks for the quick response, and for  FlaskSocketIO  !

**Comment by miguelgrinberg** [comment]
Fixed. Please upgrade python-engineio to 3.2.2. Sorry for the mistake.

**Comment by max-l** [comment]
Works like a charm.

Thanks !
