### ISSUE TITLE
CPU is too high when connection fails

### ISSUE THREAD

**Issue by linuxvae** [miguelgrinberg/Flask-SocketIO#886]
Hello, when I use flask-socketio as my websocket server, use websocket-bench for connection testing. When using websocket-bench to enable 500-way concurrency, flask-socketio has the following error：
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 356, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 521, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
```
Then the CPU has been kept at around 80%, thank you

**Comment by miguelgrinberg** [comment]
This isn't really an error, all this is saying that a client isn't properly sending pings, so it was considered gone and later on it reappeared.

**Comment by linuxvae** [comment]
When I close all the connections, the CPU still does not fall, and the socket connection is determined to be fully managed. and When I use “pstace” to view the python process call, I find that it has been calling clock_gettime.

**Comment by miguelgrinberg** [comment]
Sorry, but don't really know what I can do with that information. If you give me a report of a problem that I can reproduce here I'm happy to look into the problem.

**Comment by wangyang02** [comment]
I come across the familiar problem. I already read the document knowing that it should have sticky sessions support, but if I set uwsgi worker more than 1 ,the client will always try to reconnect.Later cup load would be nearly 83%. I find this problem while I'm using Nginx and uwsgi，and set 'hash $remote_addr ', I suspect sticky sessions may cause this problem, so I deliberately set workers more than 1 in my test evn , it happens again~

**Comment by wangyang02** [comment]
when using uwsgi with gevent, one worker and long polling,if clients > 10 ,may cause this problem.

**Comment by miguelgrinberg** [comment]
You are only giving me vague statements that aren't really accionable. I'm going to quote myself:

> If you give me a report of a problem that I can reproduce here I'm happy to look into the problem.
