### ISSUE TITLE
Intermittent Server Error Handling Requests

### ISSUE THREAD

**Issue by srikanth-nekt** [miguelgrinberg/Flask-SocketIO#888]
Hello Miguel, thanks for the great work!
Seeing this error every once in a while recently. Server is running behind an Nginx proxy with sticky sessions and 1 gunicorn worker (using eventlets). Also Using:

eventlet==0.19.0
Flask==0.10.1
Flask-SocketIO==2.4
gunicorn==19.7.1
python-engineio==0.9.1
python-socketio==1.3

>received event "login" from e50128fb12fc4bf3b4e8ff13e32a58c6 [/]
received event "login" from 19d4b7b6ebd84c0484c4c23033621cab [/]
[2019-01-29 10:29:41 +0000] [4334] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket&sid=1c97aeffd5b64a079aa987f345cbb462
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/socketio/server.py", line 306, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/engineio/server.py", line 233, in handle_request
    r = self._ok(packets, b64=b64)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/engineio/server.py", line 356, in _ok
    'response': payload.Payload(packets=packets).encode(b64)}
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/engineio/payload.py", line 17, in encode
    encoded_packet = pkt.encode(b64=b64)
TypeError: 'b64' is an invalid keyword argument for this function
received event "login" from c4e9624b4207459fa5dfad5f68bb4ba3 [/]
received event "login" from 2ea627a8bf264b20b04e5b94795ef128 [/]
received

**Comment by miguelgrinberg** [comment]
Upgrade python-engineio and python-socketio and let me know if the problem persists.

**Comment by srikanth-nekt** [comment]
> 
> 
> Upgrade python-engineio and python-socketio and let me know if the problem persists.

Upgraded to:
Flask-SocketIO==3.2.1
python-engineio==3.3.0
python-socketio==3.1.1

I do not see the original error anymore. However, I am seeing session disconnected error sometimes. Is that expected?

> received event "login" from 8f33200a315a4adda76c1d6664fceebf [/]
received event "login" from 34d8fc8145ea4772a395445a56c3099e [/]
[2019-01-31 04:46:29 +0000] [23463] [ERROR] Error handling request /socket.io/?EIO=3&transport=polling&t=MYY5bwW&sid=8f33200a315a4adda76c1d6664fceebf
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 44, in __call__
    start_response)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/engineio/middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/socketio/server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/engineio/server.py", line 356, in handle_request
    socket = self._get_socket(sid)
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/engineio/server.py", line 521, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
received event "login" from 5b608354d8b84c2897658783b0e796bc [/]

**Comment by miguelgrinberg** [comment]
The `session is disconnected` error occurs when a client fails to send regular pings to the server, or alternatively, when the server is too busy or blocked and cannot handle those pings timely. So I'd say it might be an indication of problems, but I can't tell you exactly what kind of problem, it could be several things.

**Comment by srikanth-nekt** [comment]
The error reported originally no longer seems to occur after libs upgrade. Hence, closing.
