### ISSUE TITLE
Logger error when running a second instance of Flask-SocketIO without app initialization

### ISSUE THREAD

**Issue by dhhagan** [miguelgrinberg/Flask-SocketIO#902]
I have a flask-socketio app and am using RQ to run background jobs - ideally, once a background job finishes, it sends a notification to the user via an emit(). App format looks something like this:

<pre>
/app
    /main/events.py
    /main/...
    tasks.py
    __init__.py
    ...
</pre>

My `__init__.py` file starts the flask-socketio dev server by initializing it:

<pre>
...
socketio = SocketIO()
rq_app = RQ()

def create_app():
    ...
    socketio.init_app(app, message_queue=os.environ.get("REDIS_QUEUE"))
    rq_app.init_app(app)
    ...

...
</pre>

In my `events.py` file, where the socket events/listeners are, I have some events that are called from the front-end and launch the background jobs. My guess is there is an issue with this import from the next file which contains a new socketio instance?

<pre>
...
from app.tasks import long_job

@socketio.on("long-job")
def long_job(json):
    # perform long job here
    ...
</pre>

Finally, in `tasks.py`, I have the background jobs that are launched via RQ:

<pre>
socket = SocketIO(message_queue=os.environ.get("REDIS_URL"))

@rq_app.job("user-queue")
def download_user_data(user_id):
    # do stuff here
    ...

    socket.emit("set-user-notifications")
</pre>

It now seems that the app fails to run because it claims it cannot use logger because `app is None`. My understanding of the docs are that if I don't specify the app on initialization of the socket setup in `tasks.py`, that it would have logging disabled.

The full error:

<pre>
Traceback (most recent call last):
  File "/Users/davidhagan/.pyenv/versions/ceams_env/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/click/core.py", line 1171, in resolve_c
ommand
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/flask/cli.py", line 515, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)

  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/davidhagan/Documents/github/aerovir/ceams/ceams/manage.py", line 28, in <module>
    app = create_app(os.getenv("FLASK_CONFIG") or 'default')
  File "/Users/davidhagan/Documents/github/aerovir/ceams/ceams/app/__init__.py", line 80, in create_app
    from app.main import bp as main_bp
  File "/Users/davidhagan/Documents/github/aerovir/ceams/ceams/app/main/__init__.py", line 5, in <module>
    from app.main import routes, errors, forms, events
  File "/Users/davidhagan/Documents/github/aerovir/ceams/ceams/app/main/events.py", line 12, in <module>
    from app.tasks import download_instrument_data
  File "/Users/davidhagan/Documents/github/aerovir/ceams/ceams/app/tasks.py", line 20, in <module>
    socket = SocketIO(message_queue=os.environ.get("REDIS_URL"))
  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/flask_socketio/__init__.py", line 163,
in __init__
    self.init_app(app, **kwargs)
  File "/Users/davidhagan/.pyenv/versions/3.6.5/envs/ceams_env/lib/python3.6/site-packages/flask_socketio/__init__.py", line 216,
in init_app
    app.logger.warning(
AttributeError: 'NoneType' object has no attribute 'logger'
</pre>

Am I missing something here? Or is there a reason it has a problem with app being None..?

**Comment by miguelgrinberg** [comment]
I don't think you are missing anything. I'm probably the one who missed one possible way in which the system can be used.

I assume this error appears when you start your RQ worker? Are you starting the worker using a `flask` custom command?

In any case, I will remove this error and make a new release in a bit.

**Comment by dhhagan** [comment]
Indeed - I'm using `flask rq worker` to start them.

**Comment by miguelgrinberg** [comment]
This should not be a problem anymore, please upgrade flask-socketio and retest.
