### ISSUE TITLE
I get a AttributeError in SocketIOHandler,when I use the tool:ngrok and use IE11. Chrome is OK.

### ISSUE THREAD

**Issue by zhangwen9229** [miguelgrinberg/Flask-SocketIO#91]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "D:\tlvflask0.1\env\lib\site-packages\socketio\transports.py", line 312, in chunk
    self.write_packed(payload)
  File "D:\tlvflask0.1\env\lib\site-packages\socketio\transports.py", line 283, in write_packed
    self.write("<script>_('%s');</script>" % data)
  File "D:\tlvflask0.1\env\lib\site-packages\socketio\transports.py", line 287, in write
    super(HTMLFileTransport, self).write("%d\r\n%s%s\r\n" % (l, data, " " * (l - len(data))))
  File "D:\tlvflask0.1\env\lib\site-packages\socketio\transports.py", line 41, in write
    self.handler.write_smart(data)
  File "D:\tlvflask0.1\env\lib\site-packages\socketio\handler.py", line 83, in write_smart
    args = urlparse.parse_qs(self.environ.get("QUERY_STRING"))
AttributeError: 'SocketIOHandler' object has no attribute 'environ'
<Greenlet at 0x4886638L: chunk> failed with AttributeError

Please help me to resolve it

**Comment by miguelgrinberg** [comment]
Does everything work when you run the server normally i.e. without ngrok) and use IE11?

**Comment by zhangwen9229** [comment]
Yes. without ngrok.   IE11 is normal。  Thank you for your reply。
But why, I also don't know about ngrok used
