### ISSUE TITLE
Flask-SocketIO import error on RHEL7.4

### ISSUE THREAD

**Issue by Andy-SJQ** [miguelgrinberg/Flask-SocketIO#910]
I have installed flask_socketio successful, but when I import it into my script and run:
```
[root@eosdlab47 map]# python app-socket.py 
Traceback (most recent call last):
  File "app-socket.py", line 11, in <module>
    from flask_socketio import SocketIO,emit
  File "/usr/lib64/python2.7/site-packages/flask_socketio/__init__.py", line 21, in <module>
    from werkzeug.debug import DebuggedApplication
  File "/usr/lib/python2.7/site-packages/werkzeug/debug/__init__.py", line 24, in <module>
    from werkzeug.debug.tbtools import get_current_traceback, render_console_html
  File "/usr/lib/python2.7/site-packages/werkzeug/debug/tbtools.py", line 22, in <module>
    from werkzeug.debug.console import Console
  File "/usr/lib/python2.7/site-packages/werkzeug/debug/console.py", line 12, in <module>
    import code
  File "/home/flask/map/code.py", line 8, in <module>
    from flask_socketio import emit
ImportError: cannot import name emit
```
```
[root@eosdlab47 map]# pip freeze
backports.ssl-match-hostname==3.4.0.2
chardet==2.2.1
Click==7.0
configobj==4.7.2
decorator==3.4.0
ethtool==0.8
Flask==1.0.2
Flask-SocketIO==3.3.1
iniparse==0.4
itsdangerous==1.1.0
Jinja2==2.10
jsonify==0.5
kitchen==1.1.1
langtable==0.0.31
lxml==3.2.1
M2Crypto==0.21.1
Magic-file-extensions==0.2
MarkupSafe==1.1.1
pciutils==1.7.3
perf==0.1
psutil==5.5.1
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pyOpenSSL==0.13.1
python-augeas==0.5.0
python-dateutil==1.5
python-dmidecode==3.10.13
python-engineio==3.4.3
python-linux-procfs==0.4.9
python-socketio==3.1.2
pyudev==0.15
pyxattr==0.5.1
redhat-access-insights==1.0.13
requests==2.6.0
rhnlib==2.5.65
rhsm==1.19.10
schedutils==0.4
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
subscription-manager==1.19.23
urlgrabber==3.10
urllib3==1.10.2
virtualenv==16.4.1
Werkzeug==0.14.1
yum-langpacks==0.4.2
yum-metadata-parser==1.1.4
```
Would you please help to advice what went wrong? thank you very much.

**Comment by miguelgrinberg** [comment]
Your `code.py` module is shadowing the `code` module from the standard library, and this causes a circular dependency. Rename this module to some other name to address this problem.

**Comment by Andy-SJQ** [comment]
Resolved， thanks for your help!
