### ISSUE TITLE
Can't use eventlet websoket mode; fallsback to polling

### ISSUE THREAD

**Issue by rbwilcoxon11** [miguelgrinberg/Flask-SocketIO#912]
I am trying to get a basic dev server going running eventlet. Currently, I keep getting the following output whenever I try to conect to the websocket, and it falls back to polling:

```
Error on request:
Traceback (most recent call last):
  File "D:\Polis\Sign\web-server\venv\lib\site-packages\werkzeug\serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "D:\Polis\Sign\web-server\venv\lib\site-packages\werkzeug\serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "D:\Polis\Sign\web-server\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\Polis\Sign\web-server\venv\lib\site-packages\flask_socketio\__init__.py", line 44, in __call__
    start_response)
  File "D:\Polis\Sign\web-server\venv\lib\site-packages\engineio\middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "D:\Polis\Sign\web-server\venv\lib\site-packages\socketio\server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "D:\Polis\Sign\web-server\venv\lib\site-packages\engineio\server.py", line 340, in handle_request
    environ, start_response)
  File "D:\Polis\Sign\web-server\venv\lib\site-packages\engineio\socket.py", line 106, in handle_get_request
    start_response)
  File "D:\Polis\Sign\web-server\venv\lib\site-packages\engineio\socket.py", line 146, in _upgrade_websocket
    return ws(environ, start_response)
  File "D:\Polis\Sign\web-server\venv\lib\site-packages\engineio\async_drivers\eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
```

Here is my app.py:
```
from flask import Flask, send_from_directory
from flask_socketio import SocketIO, emit

import os

import eventlet
eventlet.monkey_patch()

root_dir = os.path.dirname(os.getcwd())
static_path = os.path.join(root_dir, 'web-server', 'static')

app = Flask(__name__)
socketio = SocketIO(app, async_mode="eventlet")


@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def catch_all(path):
    return send_from_directory(static_path, 'index.html')


@socketio.on('my event', namespace='/client-socket')
def test_message(message):
    emit('my response', {'data': message['data']})


@socketio.on('my broadcast event', namespace='/client-socket')
def test_message(message):
    emit('my response', {'data': message['data']}, broadcast=True)


@socketio.on('connect', namespace='/client-socket')
def test_connect():
    emit('my response', {'data': 'Connected'})


@socketio.on('disconnect', namespace='/client-socket')
def test_disconnect():
    print('Client disconnected')


if __name__ == '__main__':
    socketio.run(app)
```

And here is my requirements.txt
```
cffi==1.12.2
Click==7.0
dnspython==1.16.0
eventlet==0.24.1
Flask==1.0.2
Flask-SocketIO==3.3.1
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.1
monotonic==1.5
pycparser==2.19
python-engineio==3.4.3
python-socketio==3.1.2
six==1.12.0
Werkzeug==0.14.1
```

Python version is 3.7.2, using a virtualenv set up through pycharm.

**Comment by miguelgrinberg** [comment]
You need to run your server using `socketio.run(app)`, as indicated in the documentation, as that will enable the eventlet web server. My guess is that you are using `flask run`, which runs the Flask development server.

**Comment by rbwilcoxon11** [comment]
You are correct. Apparently PyCharm defaults to running through "flask run" instead of just running the main. Now it is working as expected, I appreciate the help!
