### ISSUE TITLE
Connections closed

### ISSUE THREAD

**Issue by trendsensor** [miguelgrinberg/Flask-SocketIO#926]
```
[2019-03-20 14:41:34 +0900] [4512] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket&sid=dda59f19840b4dcfabe803b268ab1153
Traceback (most recent call last):
File "/usr/local/pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/pyenv/versions/3.6.3/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/pyenv/versions/3.6.3/lib/python3.6/site-packages/flask_socketio/__init__.py", line 44, in __call__
    start_response)
  File "/usr/local/pyenv/versions/3.6.3/lib/python3.6/site-packages/engineio/middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/pyenv/versions/3.6.3/lib/python3.6/site-packages/socketio/server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/pyenv/versions/3.6.3/lib/python3.6/site-packages/engineio/server.py", line 342, in handle_request
    r = self._ok(packets, b64=b64)
  File "/usr/local/pyenv/versions/3.6.3/lib/python3.6/site-packages/engineio/server.py", line 535, in _ok
    'response': payload.Payload(packets=packets).encode(b64)}
  File "/usr/local/pyenv/versions/3.6.3/lib/python3.6/site-packages/engineio/payload.py", line 17, in encode
    encoded_packet = pkt.encode(b64=b64)
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by miguelgrinberg** [comment]
Can I see your code please?
