### ISSUE TITLE
Gunicorn error : AttributeError: 'socket' object has no attribute 'cfg_addr'

### ISSUE THREAD

**Issue by yoyoprs** [miguelgrinberg/Flask-SocketIO#93]
__Configuration__:
Flask==0.10.1
Flask-HTTPAuth==2.3.0
Flask-Login==0.2.11
Flask-SocketIO==0.5.0
Flask-SQLAlchemy==2.0
Flask-Triangle==0.5.4
Flask-WTF==0.11
gevent==1.0.1
gevent-socketio==0.3.6
gevent-websocket==0.9.3
greenlet==0.4.5
gunicorn==19.2.1
itsdangerous==0.24
Werkzeug==0.10.1

__run.py__:
from webapp import app, socketio
if __main__ == 'name':
    socketio.run(app)

__Command__:gunicorn --worker-class socketio.sgunicorn.GeventSocketIOWorker  run:app

__TraceBack__:
[2015-02-04 20:16:03 +0000] [1425] [INFO] Starting gunicorn 19.2.1
[2015-02-04 20:16:03 +0000] [1425] [INFO] Listening at: http://127.0.0.1:8000 (1425)
[2015-02-04 20:16:03 +0000] [1425] [INFO] Using worker: socketio.sgunicorn.GeventSocketIOWorker
[2015-02-04 20:16:03 +0000] [1430] [INFO] Booting worker with pid: 1430
[2015-02-04 20:16:03 +0000] [1430] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.run()
  File "/usr/lib/python2.7/site-packages/socketio/sgunicorn.py", line 80, in run
    **ssl_args
  File "/usr/lib/python2.7/site-packages/socketio/server.py", line 72, in __init__
    address = args[0].cfg_addr[0]
AttributeError: 'socket' object has no attribute 'cfg_addr'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.run()
  File "/usr/lib/python2.7/site-packages/socketio/sgunicorn.py", line 80, in run
    **ssl_args
  File "/usr/lib/python2.7/site-packages/socketio/server.py", line 72, in __init__
    address = args[0].cfg_addr[0]
AttributeError: 'socket' object has no attribute 'cfg_addr'

**Comment by yoyoprs** [comment]
gunicorn==0.16.1 resolves that issue but it would be interesting to specify compatible Version

**Comment by miguelgrinberg** [comment]
Did you test any releases between 19.x and 16.1? I'm pretty sure I used v18 at some point and had no problems with it. Release 19.2.1 has been released today, and 19.2.0 was released just a few days ago. I guess there is a chance they introduced a regression.

**Comment by yoyoprs** [comment]
16, 17, 18 are ok
From the 19 it no longer works

**Comment by jaredmcqueen** [comment]
@yoyoprs that worked great.

pip uninstall gunicorn
pip install gunicorn==18.0

**Comment by miguelgrinberg** [comment]
Closing this as it is outdated with the 1.0 release. I have tested gunicorn 19 and it seems to work fine now.
