### ISSUE TITLE
Error handling socket session

### ISSUE THREAD

**Issue by jsbroks** [miguelgrinberg/Flask-SocketIO#936]
Getting an error in the logs not sure whats causes it, or what information to provide you with

I'm running the flask server behind gunicorn with eventlet.

```
flask_1     | [2019-03-29 15:02:12 +0000] [9] [ERROR] Error handling request /socket.io/?EIO=3&transport=polling&t=Md9zMgu&sid=0978d950f22b46e393098866c06a4075
flask_1     | Traceback (most recent call last):
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
flask_1     |     self.handle_request(listener_name, req, client, addr)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
flask_1     |     respiter = self.wsgi(environ, resp.start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
flask_1     |     return self.wsgi_app(environ, start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 44, in __call__
flask_1     |     start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/engineio/middleware.py", line 59, in __call__
flask_1     |     return self.engineio_app.handle_request(environ, start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 428, in handle_request
flask_1     |     return self.eio.handle_request(environ, start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 337, in handle_request
flask_1     |     socket = self._get_socket(sid)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 521, in _get_socket
flask_1     |     raise KeyError('Session is disconnected')
flask_1     | KeyError: 'Session is disconnected'
```

**Comment by miguelgrinberg** [comment]
This means that a client timed out and was considered gone, but later it came back. There are a few different potential causes for this, but the two most likely are 1. that your client isn't sending PING packets at the appropriate times, or 2. that the server is too busy or blocked and can't process those PING packets in a timely manner.

**Comment by jsbroks** [comment]
Probably 2. I dont think I'm handling my long tasks properly.
