### ISSUE TITLE
Socket error processing request, greenlet timeout

### ISSUE THREAD

**Issue by jsbroks** [miguelgrinberg/Flask-SocketIO#937]
Not sure if this is related to flask-socket-io or whats causes this to happen:

I'm running the flask server behind gunicorn with eventlet.

```
flask_1     | [2019-03-29 15:02:11 +0000] [9] [ERROR] Socket error processing request.
flask_1     | Traceback (most recent call last):
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 66, in handle
flask_1     |     six.reraise(*sys.exc_info())
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/six.py", line 625, in reraise
flask_1     |     raise value
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
flask_1     |     self.handle_request(listener_name, req, client, addr)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 129, in handle_request
flask_1     |     six.reraise(*sys.exc_info())
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/six.py", line 625, in reraise
flask_1     |     raise value
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
flask_1     |     respiter = self.wsgi(environ, resp.start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
flask_1     |     return self.wsgi_app(environ, start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 44, in __call__
flask_1     |     start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/engineio/middleware.py", line 59, in __call__
flask_1     |     return self.engineio_app.handle_request(environ, start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 428, in handle_request
flask_1     |     return self.eio.handle_request(environ, start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 340, in handle_request
flask_1     |     environ, start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 106, in handle_get_request
flask_1     |     start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 146, in _upgrade_websocket
flask_1     |     return ws(environ, start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/engineio/async_drivers/eventlet.py", line 20, in __call__
flask_1     |     return super(WebSocketWSGI, self).__call__(environ, start_response)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 130, in __call__
flask_1     |     self.handler(ws)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 171, in _websocket_handler
flask_1     |     pkt = ws.wait()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 788, in wait
flask_1     |     for i in self.iterator:
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 643, in _iter_frames
flask_1     |     message = self._recv_frame(message=fragmented_message)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 669, in _recv_frame
flask_1     |     header = recv(2)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/websocket.py", line 578, in _get_bytes
flask_1     |     d = self.socket.recv(numbytes - len(data))
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 364, in recv
flask_1     |     return self._recv_loop(self.fd.recv, b'', bufsize, flags)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 358, in _recv_loop
flask_1     |     self._read_trampoline()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 329, in _read_trampoline
flask_1     |     timeout_exc=socket_timeout('timed out'))
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 208, in _trampoline
flask_1     |     mark_as_closed=self._mark_as_closed)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/hubs/__init__.py", line 164, in trampoline
flask_1     |     return hub.switch()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 297, in switch
flask_1     |     return self.greenlet.switch()
flask_1     | socket.timeout: timed out
```

**Comment by miguelgrinberg** [comment]
Your server might be blocking for too long. An eventlet server cannot block.
