### ISSUE TITLE
Emit does not work when using threading.timer

### ISSUE THREAD

**Issue by Prateek327** [miguelgrinberg/Flask-SocketIO#938]
Hello , recently i am working on having a timer in the server which will execute a function periodically .

```
def timer_check():
            time_req = time.time() - c.timeout_mode*60
            print(time_req)
            print(type(time_req))
            requests = chatreqs.find({"alloc_time": {"$lt": time_req}})
            for req in list(requests):
                agent_id = req['agent_id']
                id = req["id"]
                if redis.hexists('online_agents',agent_id):
                    print('reached')
                    recipient = redis.hget('online_agents',agent_id).decode('utf-8')
                    socketio.emit('cancel',{'id':id},room=recipient,namespace='/private')
                browser_id = req["browser_id"]
                name = req['client_name']
                timestamp = req['timestamp']
                skill_pref = req['skill_pref']
                lang_pref = req['lang_pref']
                skill = req['skill']
                language = req['language']
                print(id,browser_id,name,timestamp,skill_pref,lang_pref,skill,language)
                message = sendinround(skill,language,skill_pref,lang_pref,name,timestamp,id,browser_id)
            threading.Timer(WAIT_SECONDS, timer_check).start()

if c.mode == 'round_robin':
    timer_check()
```
As you can see this timer executes this function every 10 seconds as i have defined wait_seconds in configuration file. So when condition is true , it sends a 'cancel' event to the front end . In the logs I can see that it is actually emitting the event to the desired socket id but I cannot see the desired result in the front end . I tried console.log on the event listener in the frontend but even that is not executing that means it never received the event on front end . So I wanted to ask is there any problem emitting this way .

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent? I'm not sure if `Timer` is compatible with green threads, that could the problem. A simple test you can do is to run your application in the "threading" async_mode, which uses standard threads.

**Comment by Prateek327** [comment]
I am using 'eventlet' currently as async_mode .

**Comment by Prateek327** [comment]
Okay I give it a try .

**Comment by miguelgrinberg** [comment]
Did you do the monkey patching under eventlet? That would be another thing to test if you haven't done that yet.

**Comment by Prateek327** [comment]
Yes so what I can see is it is working in " threading" async mode . Yes while using 'Eventlet', I did monkey patched it . 
I had added the following lines on top of my code to monkey patch it . 
`import eventlet

eventlet.monkey_patch()`

So currently it is working on 'threading' but not on 'eventlet' but i need eventlet for websocket support . what should i do ?

**Comment by miguelgrinberg** [comment]
Looks like eventlet has its own `Timer` implementation:

    from eventlet.hubs.timer import Timer

Maybe that works as a replacement for `threading.Timer`?

**Comment by Prateek327** [comment]
Ok thank you , I am implementing it and let you know  if I still have this issue .

**Comment by Prateek327** [comment]
Hello , I made the this function by using eventlet timer . 
Reference : [https://github.com/eventlet/eventlet/blob/master/eventlet/hubs/timer.py](url)
```
def timer_check():
            time_req = time.time() - c.timeout_mode*60
            print(time_req)
            print(type(time_req))
            requests = chatreqs.find({"alloc_time": {"$lt": time_req}})
            for req in list(requests):
                agent_id = req['agent_id']
                id = req["id"]
                if redis.hexists('online_agents',agent_id):
                    print('reached')
                    recipient = redis.hget('online_agents',agent_id).decode('utf-8')
                    socketio.emit('cancel',{'id':id},room=recipient,namespace='/private')
                browser_id = req["browser_id"]
                name = req['client_name']
                timestamp = req['timestamp']
                skill_pref = req['skill_pref']
                lang_pref = req['lang_pref']
                skill = req['skill']
                language = req['language']
                print(id,browser_id,name,timestamp,skill_pref,lang_pref,skill,language)
                message = sendinround(skill,language,skill_pref,lang_pref,name,timestamp,id,browser_id)
            new_timer = Timer(WAIT_SECONDS,timer_check)
            new_timer.schedule()

if c.mode == 'round_robin':
    timer_check()
```

I am getting this error : 

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/eventlet/hubs/hub.py", line 460, in fire_timers
    timer()
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "app.py", line 730, in timer_check
    for req in list(requests):
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/cursor.py", line 1104, in _refresh
    self.__send_message(q)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/cursor.py", line 931, in __send_message
    operation, exhaust=self.__exhaust, address=self.__address)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1145, in _send_mes$
age_with_response
    exhaust)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1156, in _reset_on$
error
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/server.py", line 85, in send_message_with$
response
    with self.get_socket(all_credentials, exhaust) as sock_info:
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/pool.py", line 1004, in get_socket
    sock_info = self._get_socket_no_auth()
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/pool.py", line 1044, in _get_socket_no_au$
h
    sock_info = self._check(sock_info)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/pool.py", line 1095, in _check
    return self.connect()
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/pool.py", line 968, in connect
    sock = _configured_socket(self.address, self.opts)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/pool.py", line 843, in _configured_socket
    sock = _create_connection(address, options)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/pymongo/pool.py", line 817, in _create_connection
    sock.connect(sa)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/eventlet/greenio/base.py", line 261, in connect
    self._trampoline(fd, write=True, timeout=timeout, timeout_exc=_timeout_exc)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/eventlet/greenio/base.py", line 208, in _trampoli$
e
    mark_as_closed=self._mark_as_closed)
  File "/home/ubuntu/miniconda3/envs/handoff/lib/python3.7/site-packages/eventlet/hubs/__init__.py", line 146, in trampolin
e
    assert hub.greenlet is not current, 'do not call blocking functions from the mainloop'
AssertionError: do not call blocking functions from the mainloop
```
Can you help me with this . Thanks

**Comment by miguelgrinberg** [comment]
Something you are doing with pymongo appears to upset eventlet. Are you sure you are fully monkey patched? Pymongo will not work on eventlet without monkey patching.

**Comment by Prateek327** [comment]
I just did normal pymongo query , I am quite sure it is fine . Yes i fully monkey patched the eventlet .

**Comment by Prateek327** [comment]
As I saw in eventlet docs I hope I only need to add this two lines on the top of my code for fully monkey patching it .
```
import eventlet
eventlet.monkey_patch()
```
Is it anything more I have to do to make it fully compatible?

**Comment by miguelgrinberg** [comment]
The monkey patching should be fine if you are doing it above all other imports. Unfortunately I can't really tell you what the problem is with the information that you provided. There is obviously something there that is conflicting with eventlet's scheduling.

**Comment by Prateek327** [comment]
Hello sir , I used this threading module which is almost similar to the original ones and is friendly to green threads 
`from eventlet.green import threading`
But it seems the timer is not working in this case also . As of now i made a api out of this function and kept a scheduler at another tmux to send http request to this api at regular intervals . Not a very nice approach but it is working for me as of now . Thanks for your time . I am closing this issue.
