### ISSUE TITLE
Cant start socketio.run with debug=True or use_reloader=True

### ISSUE THREAD

**Issue by iceone-ninja** [miguelgrinberg/Flask-SocketIO#949]
Hello! I'm new to flask and flask-socketio. Here is my code:

I create app as fabric:

**scriptappmain/__init__.py:**

```python
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_socketio import SocketIO
from .database import db

bootstrap = Bootstrap()
socketio = SocketIO()

def create_app():
    
    app = Flask(__name__)

    # Initialize flask extensions
    db.init_app(app)
    bootstrap.init_app(app)
    socketio.init_app(app, async_mode='eventlet')


    # # Register web application routes
    from .routes import main_router as main_router_blueprint
    app.register_blueprint(main_router_blueprint)

    return app
```

**manage.py**
```python
import eventlet
eventlet.monkey_patch()
from flask import Flask
from scriptappmain import create_app, db, socketio


app = create_app()


if __name__ == '__main__':
    socketio.run(app, host='10.40.200.10',port=5050, log_output=True)
```

In that case, eventlet server starts fine:

```
(scriptapp-venv) user@0600tddouscactips:/var/www/html/flask/scriptapp$ python manage.py
/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
(24393) wsgi starting up on http://10.40.200.10:5050
```

But, if I add an atribute debug=True or use_reloader=True, I have this exception ( example for
**`socketio.run(app, host='10.40.200.10',port=5050, debug=True)`**):

```
(scriptapp-venv) user@0600tddouscactips:/var/www/html/flask/scriptapp$ python manage.py
/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Serving Flask app "scriptappmain" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://10.40.200.10:5050/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    socketio.run(app, host='10.40.200.10',port=5050, debug=True)
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 504, in run
    use_reloader=use_reloader, **kwargs)
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/eventlet/green/subprocess.py", line 58, in __init__
    subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/var/www/html/flask/scriptapp/manage.py'
```
I've tried to use `eventlet.monkey_patch()`, but it didn't solve the problem.
I also tried to reinstall my virtualenv (with python 3.5, 3.6 , 3.7), Flask, flasksocketio ..etc  - nothing happend.

My pip freeze log:

```
(scriptapp-venv) user@0600tddouscactips:/var/www/html/flask/scriptapp$ pip freeze
Click==7.0
dnspython==1.16.0
dominate==2.3.5
eventlet==0.24.1
Flask==1.0.2
Flask-Bootstrap==3.3.7.1
Flask-SocketIO==3.3.2
Flask-SQLAlchemy==2.3.2
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
monotonic==1.5
pkg-resources==0.0.0
python-engineio==3.5.1
python-socketio==3.1.2
six==1.12.0
SQLAlchemy==1.3.3
visitor==0.1.3
Werkzeug==0.15.2

**Python version - 3.6**
```

Hope for your help. Thanks

**Comment by miguelgrinberg** [comment]
@iceone-ninja not sure what the problem is exactly, but you can probably workaround it if you make your `manage.py` file a proper unix executable. The problem is that the reloader is trying to run your app as `manage.py` instead of as `python manage.py`.

**Comment by iceone-ninja** [comment]
@miguelgrinberg thanx a lot for the reply. I made some changes:
1. added shebang` #!/var/www/html/flask/scriptapp/scriptapp-venv/bin python3` (path to virtualenv python) to the top of manage.py
2. `chmod +x manage.py`

Now I have Permission Denied error:

```
(scriptapp-venv) user@0600tddouscactips:/var/www/html/flask/scriptapp$ python manage.py
/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
 * Restarting with stat
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    socketio.run(app, host='10.40.200.10',port=5050, debug=True)
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 532, in run
    run_with_reloader(run_server, extra_files=extra_files)
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 998, in run_with_reloader
    return run_with_reloader(*args, **kwargs)
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/var/www/html/flask/scriptapp/scriptapp-venv/lib/python3.6/site-packages/eventlet/green/subprocess.py", line 58, in __init__
    subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
**PermissionError: [Errno 13] Permission denied: '/var/www/html/flask/scriptapp/manage.py'**
```

**Comment by miguelgrinberg** [comment]
the shebang line should be:

    #!/var/www/html/flask/scriptapp/scriptapp-venv/bin/python3

**Comment by iceone-ninja** [comment]
@miguelgrinberg big thanks for help! debbuger and reloader started successfully.
