### ISSUE TITLE
Occasional slow requests

### ISSUE THREAD

**Issue by toshima** [miguelgrinberg/Flask-SocketIO#979]
Hello

I'm running into a problem where the server occasionally takes 30s - 60s to respond to a request from a JS client. It seems to happen about 1 in 10 times. This error also seems to only occur when running the server remotely.

Here's a minimal code example:

```python
import eventlet
eventlet.monkey_patch()

from flask import Flask
app = Flask(__name__)

from flask_socketio import SocketIO
socketio = SocketIO(app, engineio_logger=True, logger=True)


src = """
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"></script>
<script>
const socket = io();
socket.on('connect', function(){
  console.log('Connected');
  setTimeout(function() {socket.emit('msg', 2);}, 1000);
});
</script>
"""


@app.route('/')
def index():
    return src


@socketio.on('msg')
def msg(param):
    print('msg', param)


if __name__ == '__main__':
    socketio.run(app, host='0.0.0.0', port=80, log_output=True)

```

The code was meant to emit the message 1s after connecting but this time took 40s:

![Screenshot 2019-05-21 at 22 27 37](https://user-images.githubusercontent.com/1486015/58133173-29dfba00-7c1b-11e9-8cee-19ec2751bf76.jpg)

From the server logs, it looks like it was blocked for 40s after receiving the request to upgrade to websockets:

```
109.145.183.11 - - [21/May/2019 21:20:03] "GET / HTTP/1.1" 200 396 0.000357
109.145.183.11 - - [21/May/2019 21:20:03] "GET /socket.io/?EIO=3&transport=websocket&sid=06dd201cc7d24ab39ee2f70b1725fc09 HTTP/1.1" 200 0 131.856901
73c085c8b62b4af6ba3cc20c0c494839: Sending packet OPEN data {'sid': '73c085c8b62b4af6ba3cc20c0c494839', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
73c085c8b62b4af6ba3cc20c0c494839: Sending packet MESSAGE data 0
109.145.183.11 - - [21/May/2019 21:20:03] "GET /socket.io/?EIO=3&transport=polling&t=MhSG_d8 HTTP/1.1" 200 381 0.000477
(6806) accepted ('109.145.183.11', 64793)
73c085c8b62b4af6ba3cc20c0c494839: Received request to upgrade to websocket
109.145.183.11 - - [21/May/2019 21:20:03] "GET /favicon.ico HTTP/1.1" 404 365 0.000340
109.145.183.11 - - [21/May/2019 21:20:03] "GET /socket.io/?EIO=3&transport=polling&t=MhSG_ed&sid=73c085c8b62b4af6ba3cc20c0c494839 HTTP/1.1" 200 215 0.058273
73c085c8b62b4af6ba3cc20c0c494839: Client is gone, closing socket
73c085c8b62b4af6ba3cc20c0c494839: Client is gone, closing socket
109.145.183.11 - - [21/May/2019 21:20:43] "GET /socket.io/?EIO=3&transport=polling&t=MhSG_fv&sid=73c085c8b62b4af6ba3cc20c0c494839 HTTP/1.1" 200 211 39.551286
73c085c8b62b4af6ba3cc20c0c494839: Upgrade to websocket successful
73c085c8b62b4af6ba3cc20c0c494839: Received packet MESSAGE data 2["msg",2]
received event "msg" from 73c085c8b62b4af6ba3cc20c0c494839 [/]
73c085c8b62b4af6ba3cc20c0c494839: Received packet PING data None
Receive error -- socket is closed
109.145.183.11 - - [21/May/2019 21:20:43] "GET /socket.io/?EIO=3&transport=websocket&sid=73c085c8b62b4af6ba3cc20c0c494839 HTTP/1.1" 200 0 39.866910
b75a6750c2584ec489ac620473ce85f6: Sending packet OPEN data {'sid': 'b75a6750c2584ec489ac620473ce85f6', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
b75a6750c2584ec489ac620473ce85f6: Sending packet MESSAGE data 0
109.145.183.11 - - [21/May/2019 21:20:45] "GET /socket.io/?EIO=3&transport=polling&t=MhSH9uR HTTP/1.1" 200 381 0.000492
(6806) accepted ('109.145.183.11', 64965)
b75a6750c2584ec489ac620473ce85f6: Received request to upgrade to websocket
109.145.183.11 - - [21/May/2019 21:20:45] "GET /socket.io/?EIO=3&transport=polling&t=MhSH9u-&sid=b75a6750c2584ec489ac620473ce85f6 HTTP/1.1" 200 215 0.040526
b75a6750c2584ec489ac620473ce85f6: Upgrade to websocket successful
b75a6750c2584ec489ac620473ce85f6: Received packet MESSAGE data 2["msg",2]
received event "msg" from b75a6750c2584ec489ac620473ce85f6 [/]
msg 2
```

I'm new to socket.io so any help or pointers would be greatly appreciated. Thank you in advance

**Comment by miguelgrinberg** [comment]
Not sure what is the problem here. Does the browser console show any useful messages?

**Comment by toshima** [comment]
Thanks for the quick response Miguel! When I tried again now, something different actually happened.

There was a ```socket.timeout: timed out``` error in the server logs after 60s and a ```Received a broken close frame containing invalid UTF-8.``` error in the browser logs when it got the 400 response.

This behaviour of the request timing out still seems to happen about 10% of the time. Do you know what might be causing it?


Browser logs:

```
(index):6 Connected
index.js:83 engine.io-client:polling polling +10ms
index.js:83 engine.io-client:polling-xhr xhr poll +92ms
index.js:83 engine.io-client:polling-xhr xhr open GET: http://mydomain.com/socket.io/?EIO=3&transport=polling&t=MhSi16t&sid=6153b3b2b8f84304952090ed093d919c +0ms
index.js:83 engine.io-client:polling-xhr xhr data null +1ms
index.js:83 engine.io-client:socket probe transport "websocket" opened +48ms
index.js:83 engine.io-client:polling polling got data ArrayBuffer(4) +61ms
index.js:83 engine.io-client:socket socket receive: type "noop", data "undefined" +17ms
index.js:83 engine.io-client:polling polling +3ms
index.js:83 engine.io-client:polling-xhr xhr poll +64ms
index.js:83 engine.io-client:polling-xhr xhr open GET: http://mydomain.com/socket.io/?EIO=3&transport=polling&t=MhSi17w&sid=6153b3b2b8f84304952090ed093d919c +2ms
index.js:83 engine.io-client:polling-xhr xhr data null +1ms
index.js:83 engine.io-client:socket probe transport "websocket" pong +8ms
index.js:83 engine.io-client:socket pausing current transport "polling" +0ms
index.js:83 engine.io-client:polling we are currently polling - waiting to pause +7ms
favicon.ico:1 GET http://mydomain.com/favicon.ico 404 (NOT FOUND)
index.js:83 socket.io-client:manager writing packet {"type":2,"data":["msg",2],"options":{"compress":true},"nsp":"/"} +1s
index.js:83 socket.io-parser encoding packet {"type":2,"data":["msg",2],"options":{"compress":true},"nsp":"/"} +1s
index.js:83 socket.io-parser encoded {"type":2,"data":["msg",2],"options":{"compress":true},"nsp":"/"} as 2["msg",2] +1ms
index.js:83 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
index.js:83 WebSocket connection to 'ws://mydomain.com/socket.io/?EIO=3&transport=websocket&sid=6153b3b2b8f84304952090ed093d919c' failed: Received a broken close frame containing invalid UTF-8.
index.js:83 engine.io-client:socket probe transport "websocket" failed because of error: Error: websocket error    at r.onError (https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js:7:8176)    at WebSocket.ws.onerror (https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js:8:6573) +35s
index.js:83 GET http://mydomain.com/socket.io/?EIO=3&transport=polling&t=MhSi17w&sid=6153b3b2b8f84304952090ed093d919c 400 (BAD REQUEST)
index.js:83 engine.io-client:socket socket error {"type":"TransportError","description":400} +12ms
index.js:83 socket.io-client:manager error +59s Error: xhr poll error
    at o.r.onError (index.js:83)
    at i.<anonymous> (index.js:83)
    at i.r.emit (index.js:83)
    at i.onError (index.js:83)
    at index.js:83
index.js:83 engine.io-client:socket socket close with reason: "transport error" +2ms
index.js:83 socket.io-client:manager onclose +1ms
index.js:83 socket.io-client:manager cleanup +1ms
index.js:83 socket.io-client:socket close (transport error) +1m
```

**Comment by miguelgrinberg** [comment]
The client received a 400 error from the server. Now we need to see the server logs around the time of this error.

**Comment by toshima** [comment]
There's an error in the server logs that the socket timed out:

```

82.163.196.42 - - [22/May/2019 13:10:21] "GET / HTTP/1.1" 200 396 0.000284
82.163.196.42 - - [22/May/2019 13:10:21] "GET /socket.io/?EIO=3&transport=websocket&sid=b47657ac01ee488ea7dcd25919130f46 HTTP/1.1" 200 0 1.062366
8df9aec4106e4a27b8b71328a5991821: Sending packet OPEN data {'sid': '8df9aec4106e4a27b8b71328a5991821', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
8df9aec4106e4a27b8b71328a5991821: Sending packet MESSAGE data 0
82.163.196.42 - - [22/May/2019 13:10:21] "GET /socket.io/?EIO=3&transport=polling&t=MhVgVzk HTTP/1.1" 200 381 0.000460
(8456) accepted ('82.163.196.42', 48690)
8df9aec4106e4a27b8b71328a5991821: Received request to upgrade to websocket
82.163.196.42 - - [22/May/2019 13:10:21] "GET /socket.io/?EIO=3&transport=polling&t=MhVgV-C&sid=8df9aec4106e4a27b8b71328a5991821 HTTP/1.1" 200 215 0.039745
8df9aec4106e4a27b8b71328a5991821: Upgrade to websocket successful
82.163.196.42 - - [22/May/2019 13:10:21] "GET / HTTP/1.1" 200 396 0.000322
82.163.196.42 - - [22/May/2019 13:10:21] "GET /socket.io/?EIO=3&transport=websocket&sid=8df9aec4106e4a27b8b71328a5991821 HTTP/1.1" 200 0 0.442900
cf27bffca30c4200a9091ce51788fdad: Sending packet OPEN data {'sid': 'cf27bffca30c4200a9091ce51788fdad', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
cf27bffca30c4200a9091ce51788fdad: Sending packet MESSAGE data 0
82.163.196.42 - - [22/May/2019 13:10:21] "GET /socket.io/?EIO=3&transport=polling&t=MhVgW5_ HTTP/1.1" 200 381 0.000443
(8456) accepted ('82.163.196.42', 55210)
cf27bffca30c4200a9091ce51788fdad: Received request to upgrade to websocket
82.163.196.42 - - [22/May/2019 13:10:21] "GET /socket.io/?EIO=3&transport=polling&t=MhVgW6O&sid=cf27bffca30c4200a9091ce51788fdad HTTP/1.1" 200 215 0.071684
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/wsgi.py", line 547, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/flask_socketio/__init__.py", line 44, in __call__
    start_response)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/engineio/middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/socketio/server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/engineio/server.py", line 340, in handle_request
    environ, start_response)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/engineio/socket.py", line 106, in handle_get_request
    start_response)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/engineio/socket.py", line 146, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/engineio/async_drivers/eventlet.py", line 20, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/websocket.py", line 130, in __call__
    self.handler(ws)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/engineio/socket.py", line 171, in _websocket_handler
    pkt = ws.wait()
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/websocket.py", line 788, in wait
    for i in self.iterator:
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/websocket.py", line 643, in _iter_frames
    message = self._recv_frame(message=fragmented_message)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/websocket.py", line 669, in _recv_frame
    header = recv(2)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/websocket.py", line 578, in _get_bytes
    d = self.socket.recv(numbytes - len(data))
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/greenio/base.py", line 364, in recv
    return self._recv_loop(self.fd.recv, b'', bufsize, flags)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/greenio/base.py", line 358, in _recv_loop
    self._read_trampoline()
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/greenio/base.py", line 329, in _read_trampoline
    timeout_exc=socket_timeout('timed out'))
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/greenio/base.py", line 208, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/hubs/__init__.py", line 164, in trampoline
    return hub.switch()
  File "/home/ubuntu/venv/lib/python3.7/site-packages/eventlet/hubs/hub.py", line 297, in switch
    return self.greenlet.switch()
socket.timeout: timed out

82.163.196.42 - - [22/May/2019 13:11:21] "GET /socket.io/?EIO=3&transport=websocket&sid=cf27bffca30c4200a9091ce51788fdad HTTP/1.1" 500 0 60.018876
cf27bffca30c4200a9091ce51788fdad: Client is gone, closing socket
82.163.196.42 - - [22/May/2019 13:11:21] "GET /socket.io/?EIO=3&transport=polling&t=MhVgW7m&sid=cf27bffca30c4200a9091ce51788fdad HTTP/1.1" 400 218 60.001220
120847e96e6c454583a44f284fa7d886: Sending packet OPEN data {'sid': '120847e96e6c454583a44f284fa7d886', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
120847e96e6c454583a44f284fa7d886: Sending packet MESSAGE data 0
82.163.196.42 - - [22/May/2019 13:11:23] "GET /socket.io/?EIO=3&transport=polling&t=MhVgl4U HTTP/1.1" 200 381 0.000489
(8456) accepted ('82.163.196.42', 61625)
120847e96e6c454583a44f284fa7d886: Received request to upgrade to websocket
82.163.196.42 - - [22/May/2019 13:11:23] "GET /socket.io/?EIO=3&transport=polling&t=MhVgl4n&sid=120847e96e6c454583a44f284fa7d886 HTTP/1.1" 200 215 0.032301
120847e96e6c454583a44f284fa7d886: Upgrade to websocket successful
120847e96e6c454583a44f284fa7d886: Received packet MESSAGE data 2["msg",2]
received event "msg" from 120847e96e6c454583a44f284fa7d886 [/]
msg 2
```

**Comment by miguelgrinberg** [comment]
Your code examples works fine here. Are you sure you didn't simplify the example too much? How often does it fail for you?

**Comment by valentin-ballester** [comment]
i have this problem, from time to time i get a socket.timeout error.
