### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by migeek** [miguelgrinberg/Flask-SocketIO#981]
Similar to issue #926 which was closed since no source was provided, I am getting an "AttributeError: 'NoneType' object has no attribute 'encode'" error when using Flask Socketio.  This happens specifically when I am disconnecting and I try to emit a message in disconnect().  I have cut my code down to just a simple flask app including flask-socketio.  When I comment out the emit() in my disconnect the error goes away.  See line 27 in the attached appSocketIO.py.  

The specific error:

Traceback (most recent call last):
  File "C:\Users\hms\Dropbox (HuSmith)\PythonCode\chattest\vtest\lib\site-packages\eventlet\wsgi.py", line 547, in handle_one_response
    result = self.application(self.environ, start_response)
  File "C:\Users\hms\Dropbox (HuSmith)\PythonCode\chattest\vtest\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\hms\Dropbox (HuSmith)\PythonCode\chattest\vtest\lib\site-packages\flask_socketio\__init__.py", line 44, in __call__
    start_response)
  File "C:\Users\hms\Dropbox (HuSmith)\PythonCode\chattest\vtest\lib\site-packages\engineio\middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\hms\Dropbox (HuSmith)\PythonCode\chattest\vtest\lib\site-packages\socketio\server.py", line 485, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\hms\Dropbox (HuSmith)\PythonCode\chattest\vtest\lib\site-packages\engineio\server.py", line 342, in handle_request
    r = self._ok(packets, b64=b64)
  File "C:\Users\hms\Dropbox (HuSmith)\PythonCode\chattest\vtest\lib\site-packages\engineio\server.py", line 535, in _ok
    'response': payload.Payload(packets=packets).encode(b64)}
  File "C:\Users\hms\Dropbox (HuSmith)\PythonCode\chattest\vtest\lib\site-packages\engineio\payload.py", line 17, in encode
    encoded_packet = pkt.encode(b64=b64)
AttributeError: 'NoneType' object has no attribute 'encode'

[chattest.zip](https://github.com/miguelgrinberg/Flask-SocketIO/files/3215065/chattest.zip)
[requirements.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/3214891/requirements.txt)

**Comment by migeek** [comment]
So I solved my own problem.  It appears that the issue is the emit() in my disconnect() is also being sent to the client that is actually disconnecting and this causes the error.  The default in flask_socketio file: __init__.py is to set the 'include_self' option to true.  For a disconnecting connection, this causes a problem.  The solution was to set the "include_self" option to false in my emit() call.  Not sure how portable this will be over time but it works for now.

So my disconnect() now looks like (see the include_self option on the emit()):

@socketio.on('disconnect')
def disconnect():
    print(f'In disconnect: {request.sid}')
    socketio.emit('toRobot', {'text' : "robot disconnecting"}, include_self=False)
