### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by mayJJ** [miguelgrinberg/Flask-SocketIO#982]
when send tens of thousands message, alway raise this error

```
2019-05-27 09:39:04,733 [pid:777] [MainThread:4434306008] [handler:37] [INFO]- <sub from redis queue> : {'skip_sid': None, 'event': 'broadcast-comment', 'room': 'private-comment-1', 'data': {'id': 12920, 'who': 'test', 'content': 'the messages 12916 send ~', 'task_id': 'ydvs2Vk9n7Zf'}, 'namespace': '/comment'}
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/connection.py", line 600, in send_packed_command
    self._sock.sendall(item)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/eventlet/greenio/base.py", line 401, in sendall
    tail = self.send(data, flags)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/eventlet/greenio/base.py", line 395, in send
    return self._send_loop(self.fd.send, data, flags)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/eventlet/greenio/base.py", line 382, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/kombu/connection.py", line 431, in _reraise_as_library_errors
    yield
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/app/base.py", line 755, in send_task
    self.backend.on_task_call(P, task_id)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 294, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 136, in consume_from
    self._consume_from(task_id)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 142, in _consume_from
    self._pubsub.subscribe(key)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/client.py", line 3096, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/client.py", line 3009, in execute_command
    self._execute(connection, connection.send_command, *args)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/connection.py", line 620, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/connection.py", line 613, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 32 while writing to socket. Broken pipe.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yaomeijun/project/real-time-push/server/subscribers/redis_queue_subscriber.py", line 34, in loop_pop
    result = callback(qname, val)
  File "/Users/yaomeijun/project/real-time-push/server/handlers.py", line 85, in handle_subscribe
    return super(RedisQueueHandle, self).handle_subscribe(msg, retry, qname)
  File "/Users/yaomeijun/project/real-time-push/server/handlers.py", line 39, in handle_subscribe
    result = io_task.delay(**msg)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/app/task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/app/base.py", line 756, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/kombu/connection.py", line 436, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/kombu/connection.py", line 431, in _reraise_as_library_errors
    yield
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/app/base.py", line 755, in send_task
    self.backend.on_task_call(P, task_id)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 294, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 136, in consume_from
    self._consume_from(task_id)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 142, in _consume_from
    self._pubsub.subscribe(key)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/client.py", line 3096, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/client.py", line 3009, in execute_command
    self._execute(connection, connection.send_command, *args)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/connection.py", line 620, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yaomeijun/project/real-time-push/venv/lib/python3.6/site-packages/redis/connection.py", line 613, in send_packed_command
    (errno, errmsg))
kombu.exceptions.OperationalError: Error 32 while writing to socket. Broken pipe.
```

**Comment by miguelgrinberg** [comment]
@mayJJ looks like this is an issue with Kombu. See https://github.com/celery/kombu/issues/1018.

**Comment by mayJJ** [comment]
hello, everyone. I find the solution few days. Other developer face the same problems. I find some solution like:
1. **kombu version error.**   (#https://github.com/celery/kombu/issues/1018 I was previously on kombu 4.3.0 and redis 2.10.6, and after upgrading to kombu 4.4.0 and redis 3.2.0 (manually cf issue #1016 ) )
> my environment: Kombu 4.5.0 and redis 3.2.1, through I try to downgrade kombu 4.3.0, redis 2.10.6, face other problem, brpop is not work.

2. **redis list oversize or over length** (#https://github.com/andymccurdy/redis-py/issues/997  [redis list datatype]#https://redis.io/topics/data-types)
> I try to monitor my redis server, the list size is not oversize or over length

3. **redis is not thread-safety** , there is the explain:
    1. These errors hint that sometime redis client closes connection, but also tries to use it from another thread. (#https://github.com/miguelgrinberg/Flask-SocketIO/issues/982)
    2. So, I try to find where are not thread-safety. First, I look up redis document(#https://github.com/andymccurdy/redis-py#thread-safety). We can see `Redis client instances can safely be shared between threads`, but `It is not safe to pass PubSub or Pipeline objects between threads.` Yeah , I use pipeline for less the network loss time. So I change pipe operator to native.
> But it's also not work.......
4. **Alternative PythonParser with Hiredis**, also not work.
5. Finally , I just try except, When the BrokenPipeError, reconnect redis, brpop the same queue name ...

environment:
- macos
- python 3.6
- kombu: 4.5.0 redis: 3.2.1 celery 4.3
